window.MEETING_ACADEMY_UI=(()=>{
  const A=window.MEETING_ACADEMY,D=window.MEETING_ACADEMIC_CONTENT,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let stage='master',scenario='regular';
  try{const c=JSON.parse(localStorage.getItem('meeting-survival-academic-menu'));stage=c?.stage||stage;scenario=c?.scenario||scenario;}catch{}
  const menuConfig=()=>({studyStage:A.stages.some(s=>s.id===stage)?stage:'master',scenario:A.scenarios.some(s=>s.id===scenario)?scenario:'regular'});
  function landing(){if(document.querySelector('#academic-setup'))return;const anchor=document.querySelector('.mentor-setup');if(!anchor)return;const el=document.createElement('section');el.id='academic-setup';el.className='academy-setup';el.innerHTML='<div class="section-line"><h2>选一段生涯，再选一种开局。</h2><span class="tag">阶段目标提前公布</span></div><div class="academy-stage-options">'+D.stages.map(d=>'<button data-stage="'+d.id+'" class="academy-card '+(d.id===stage?'selected':'')+'" aria-pressed="'+(d.id===stage)+'"><strong>'+esc(d.icon||'🎓')+' '+esc(d.name)+'</strong><p>'+esc(d.desc)+'</p><small>'+ (d.id==='free'?'持续生活与年度目标':(d.id==='master'?'约三学年':'约四学年')+' · 可补救和延期')+'</small></button>').join('')+'</div><details class="academy-fold"><summary>🎲 特殊挑战剧本 · '+esc(D.scenarios.find(s=>s.id===scenario)?.name)+'</summary><div class="academy-scenario-options">'+D.scenarios.map(d=>'<button data-scenario="'+d.id+'" class="academy-card '+(d.id===scenario?'selected':'')+'" aria-pressed="'+(d.id===scenario)+'"><strong>'+esc(d.name)+'</strong><p>'+esc(d.desc)+'</p></button>').join('')+'</div></details>';anchor.before(el);el.querySelectorAll('[data-stage],[data-scenario]').forEach(b=>b.onclick=()=>{if(b.dataset.stage)stage=b.dataset.stage;else scenario=b.dataset.scenario;localStorage.setItem('meeting-survival-academic-menu',JSON.stringify({stage,scenario}));window.MEETING_SAVES?.schedule();window.MEETING_APP.landing();});}
  function personTime(n){const text=(n.studyStage==='doctor'?'博士阶段':'硕士阶段')+' · '+(n.rank==='senior'?'入局时已在高年级':'第 '+n.born+' 周入组')+' · 第 '+n.graduationWeek+' 周起安排学位收尾';return window.MEETING_NARRATIVE_WORLD.pair(text,()=> (n.studyStage==='doctor'?'Doctoral stage':'Master’s stage')+' · '+(n.rank==='senior'?'Already in a later year at entry':'Joined in week '+n.born)+' · Degree wrap-up from week '+n.graduationWeek);}
  const btn=(type,text,target='',disabled=false)=>'<button class="secondary" data-academic="'+type+'" data-target="'+esc(target)+'" '+(disabled?'disabled':'')+'>'+esc(text)+'</button>';
  const fold=(title,body,open=false)=>'<details class="academy-fold" '+(open?'open':'')+'><summary>'+title+'</summary>'+body+'</details>';
  function decorate(w,render,save){const a=w.academy;if(!a)return;const ready=A.available(w),m=A.milestone(w),p=w.world.artifact,k=A.kind(w),j=a.resource.active,co=a.collab.active,r=a.recovery.active;
    const card=document.createElement('section');card.className='academy-stage-panel';card.id='academy-stage';const req=A.requirements(w,m);card.innerHTML='<div class="academy-heading"><div><small>第 '+a.term.cycle+' 段生涯 · '+esc(D.scenarios.find(d=>d.id===a.scenario)?.name)+'</small><h3>🎓 '+esc(D.stages.find(d=>d.id===a.term.stage)?.name)+' · '+(a.term.graduated?'阶段检查已完成':m?esc(D.phases[m.id]):'本阶段目标已完成')+'</h3></div><span class="tag">'+(m?'第 '+m.due+' 周检查':'阶段留档')+'</span></div>'+fold('阶段日历与实际要求','<div class="academy-timeline">'+a.term.milestones.map(t=>'<div class="'+(t.status==='passed'?'passed':'')+'"><strong>'+esc(D.phases[t.id])+'</strong><span>第 '+t.due+' 周</span><small>'+({passed:'✓ 已通过',waived:'已调整',due:'需要检查',upcoming:'等待实际准备'}[t.status])+'</small></div>').join('')+'</div><p>当前要求：核对 '+req.checks+'/'+req.need+'，阶段准备 '+(m?.work.length||0)+'/'+(m?.id==='graduation'?2:1)+(a.term.stage==='doctor'?'，接收成果 '+req.accepted:'')+'。未通过可以补救或延期，等待中的稿件仍按等待记录。</p><div class="academy-actions">'+(m?btn('stage-prep','准备阶段材料','',!ready)+btn('stage-check','参加实际检查','',!ready||w.number<m.due):'')+(a.term.graduated&&!a.term.choice?btn('degree','决定阶段之后','',!ready):'')+'</div>');document.querySelector('.week-resources')?.after(card);
    const research=document.createElement('div');research.className='academy-grid';research.id='academic-research';research.innerHTML=fold(k.icon+' '+esc(k.name),'<p>'+esc(j?j.condition:k.start)+'</p><p class="academy-status">'+(j?'课题 v'+j.version+' · '+({waiting:'排队等待',blocked:'窗口临时改变',available:'窗口开放，尚未核对'}[j.status]||j.status)+' · '+(j.status==='waiting'?'还有 '+Math.max(0,j.due-A.tick(w))+' 个时间片段':'剩余 '+Math.max(0,j.expires-A.tick(w))+' 个时间片段'):A.resourceReady(w)?'当前方向、当前版本已有窗口复核回执。':'预约与实际复核分别占用生活片段。')+'</p>'+btn(j?'resource-work':'resource',j?'处理这个资源窗口':'预约本版资源','',!ready||j&&!['available','blocked'].includes(j.status))+fold('排期与复核历史',a.resource.history.slice(-5).map(t=>'<p>第 '+t.from+' 周 · v'+t.version+' · '+esc(t.status)+' · '+esc(t.receipt?.action||'没有实际核对回执')+'</p>').join('')||'<p>还没有过去的排期。</p>'),true)+fold('🤝 合作与贡献记录','<p>'+esc(co?co.partnerName+' · 阶段 '+co.step+'/3 · '+co.status:'先约定分工，实际交接，最后协商范围与署名。')+'</p>'+(co?'<ul>'+co.contributions.map(c=>'<li>'+esc(c.person||c.name||c.action||JSON.stringify(c))+'</li>').join('')+'</ul>':'')+btn(co?'collab-work':'collab',co?'推进或交接合作':'联系合作伙伴','',!ready)+(co?.agreement?'<p>共同署名：'+esc(co.agreement.authors?.join(' → '))+'。投稿会保存这份贡献快照。</p>':'')+fold('已完成的合作',a.collab.history.slice(-4).map(t=>'<p>'+esc(t.partnerName)+' · '+esc(t.status)+'</p>').join('')||'<p>还没有完成的合作。</p>'),true)+(r?fold('🛠️ 失败还有下一页','<p>'+esc(r.title)+'：'+esc(r.scene)+'</p><p>补救阶段 '+r.step+'，后续最早第 '+r.next+' 周交付。</p>'+btn('recovery','继续补救','',!ready),true):'');document.querySelector('#life-research')?.append(research);
    const community=document.createElement('section');community.id='academic-people';community.innerHTML=fold('🧑‍🎓 课题组关系与各自的生涯','<div class="academy-relationship"><div class="academy-you">📍 你<br><small>第 '+w.number+' 周</small></div><div class="academy-people">'+w.group.members.map(n=>{const person=a.people[n.id];return '<article class="academy-person"><strong>'+esc(n.icon)+' '+esc(n.name)+'</strong><span>'+esc(person?D.careers[person.phase]:window.MEETING_MENTOR_APPOINTMENTS?.titleOf(n)||window.MEETING_MENTORS.levels[n.level]?.title||'导师')+'</span><small>关系 '+Math.round(n.trust)+' · '+(person?'熟练度 '+person.skill+'/5':'自己的晋升与项目安排')+'</small><p>'+esc(person?.note||({grant:'正在安排项目与经费',promotion:'正在准备晋升材料',research:'正在推进自己的课题',teaching:'正在安排教学'})[w.world.npcs[n.id]?.goal]||'正在安排研究与生活')+'</p>'+(person?.calendarVersion===2?'<small>'+ esc(personTime(person))+'</small>':'')+(person?btn('person','相处、带教或求助',n.id,!ready||person.status!=='active'):'')+'</article>';}).join('')+'</div></div>'+fold('这周人物消息',a.news.map(n=>'<p>'+esc(n)+'</p>').join('')||'<p>大家正在各自安排生活。</p>')+fold('📔 学术年鉴 · '+a.yearbook.length+' 条',a.yearbook.slice().reverse().map(t=>'<article class="academy-year"><strong>'+esc(t.symbol)+' '+esc(t.name)+' · 第 '+t.week+' 周</strong><p>'+esc(t.text)+'</p>'+(t.personId&&a.people[t.personId]?'<button class="secondary" data-people-memory="'+esc(t.personId)+'">相处记录</button>':'')+'</article>').join('')||'<p>毕业的人与完成的校园故事会留在这里。</p>'),true);document.querySelector('#life-community')?.append(community);community.querySelectorAll('[data-people-memory]').forEach(b=>b.onclick=()=>window.MEETING_PEOPLE_MEMORY.show(w,b.dataset.peopleMemory));
    const pending=a.loans.filter(l=>l.status==='open'),shadows=a.foreshadows.filter(f=>f.status==='waiting'||f.status==='due');if(pending.length||shadows.length){const alerts=document.createElement('div');alerts.className='academy-alerts';alerts.innerHTML=fold('✉️ 约定与伏笔 · '+(pending.length+shadows.length),pending.map(l=>'<p>'+esc(a.people[l.personId]?.name||'合作伙伴')+' · 第 '+l.from+' 周借用，第 '+l.dueWeek+' 周归还。</p>'+btn('loan','处理归还或延长',l.id,!ready)).join('')+shadows.map(f=>{const d=D.foreshadows.find(d=>d.id===f.kind);return '<p>'+esc(d.title)+'：'+esc(d.intro)+'<small>源自第 '+f.from+' 周「'+esc(f.origin)+'」，后续第 '+f.due+' 周。</small></p>'+ (f.status==='due'?btn('foreshadow','看后来的那一页',f.id,!ready):'');}).join(''));document.querySelector('#life-planning')?.append(alerts);}
    const campus=document.createElement('div');campus.className='academy-campus';campus.innerHTML=fold('🌈 周末也有连续故事','<div class="academy-grid">'+D.campus.map(d=>{const g=a.campus[d.id];return '<article><strong>'+d.icon+' '+esc(d.name)+'</strong><p>'+g.step+'/'+d.steps+' · '+(g.finished?'已留入年鉴':w.number<g.next?'约好第 '+g.next+' 周再见':'下一次可以继续')+'</p>'+btn('campus',g.finished?'故事已收藏':'安排这个周末',d.id,!ready||w.day<5||g.finished||w.number<g.next)+'</article>';}).join('')+'</div>');document.querySelector('#life-planning')?.append(campus);
    document.querySelectorAll('[data-academic]').forEach(b=>b.onclick=()=>{if(A.dispatch(w,b.dataset.academic,b.dataset.target||null)){save();render();document.querySelector('.life-scene')?.scrollIntoView({behavior:'smooth',block:'start'});}else window.MEETING_APP.toast(window.MEETING_WEEK.actionReason(w)||'当前条件还不满足，请查看此项的进度和开放时间。');});
    if(a.term.choice==='ended'){const next=document.querySelector('#next-week');if(next){next.disabled=true;next.textContent='毕业年鉴已保存 · 可从首页开启新生涯';}}
  }
  function meeting(s){const a=s.academicDialogue;if(!a||document.querySelector('#academic-talk-history'))return;const box=document.createElement('details');box.id='academic-talk-history';box.className='academy-fold';const f=D.formats.find(d=>d.id===a.format);box.innerHTML='<summary>'+f.icon+' 本场形式：'+esc(f.name)+' · 连续对话 '+a.turns.length+' 轮</summary><p>老师会回到前面说过的话，实际记录决定能展示哪些内容。</p>'+a.turns.map(t=>'<p>第 '+t.round+' 轮 · '+esc(t.answer)+'</p>').join('')+(a.contradictions?'<p>已记录前后范围不一致 '+a.contradictions+' 次。</p>':'');document.querySelector('.meeting-context')?.after(box);if(!box.isConnected)document.querySelector('#app')?.append(box);}
  return {landing,decorate,meeting,menuConfig};
})();
