window.MEETING_ACADEMY=(()=>{
  'use strict';
  const D=window.MEETING_ACADEMIC_CONTENT,C=window.MEETING_CONTENT,copy=x=>JSON.parse(JSON.stringify(x)),clamp=x=>Math.max(0,Math.min(100,x));
  const tick=w=>(w.number-1)*14+w.day*2+w.slot;
  const enabled=w=>window.MEETING_EXPERIENCE?.enabled(w,'academy')!==false&&!!w.world&&!!w.group&&w.config.uncertainty!==false&&(!w.config.challenge||w.config.rulesVersion==='10');
  const stages=D.stages,scenarios=D.scenarios;
  function config(c){const stage=stages.some(d=>d.id===c.studyStage)?c.studyStage:'master',scenario=scenarios.some(d=>d.id===c.scenario)?c.scenario:'regular';c={...c,studyStage:stage,scenario};if(scenario==='dual'&&!window.MEETING_MIX.sanitize(c.mixProjects)){c.project='interdisciplinary';c.mixProjects=['data','clinical'];c.direction='data-1';}return c;}
  function term(stage,start,scenario){const compact=['poor-finish','last-eight'].includes(scenario),schedule=stage==='doctor'?[12,104,52,182,208]:[8,78,52,130,156],phases=stage==='free'?['annual','application']:Object.keys(D.phases);let milestones=phases.map((id,i)=>({id,due:start+(compact?[0,2,4,5,7][i]:stage==='free'?(i?43:51):schedule[i]-1),status:'upcoming',work:[],attempts:0,extension:0}));if(!compact&&stage!=='free')for(let year=2;year<(stage==='doctor'?4:3);year++)milestones.push({id:'annual',due:start+year*52-1,status:'upcoming',work:[],attempts:0,extension:0});milestones.sort((a,b)=>a.due-b.due);return {calendarVersion:2,stage,start,cycle:1,milestones,graduated:false,choice:null};}
  function calendar(w){const a=w.academy;if(!a||a.term.calendarVersion===2)return;const t=a.term;if(t.graduated||['poor-finish','last-eight'].includes(a.scenario)){t.calendarVersion=2;return;}const fresh=term(t.stage,t.start,a.scenario),used=new Set();for(const m of t.milestones){const replacement=fresh.milestones.find((n,i)=>n.id===m.id&&!used.has(i));if(replacement){used.add(fresh.milestones.indexOf(replacement));Object.assign(replacement,m,{due:replacement.due,status:['passed','waived'].includes(m.status)?m.status:'upcoming'});}}t.milestones=fresh.milestones;t.calendarVersion=2;for(const m of t.milestones)if(m.status==='upcoming'&&w.number>=m.due)m.status='due';}

  function person(w,m,rand){return {id:m.id,name:m.name,role:m.role,icon:m.icon,rank:m.rank,status:'active',phase:m.rank==='junior'?'learning':'draft',progress:m.rank==='junior'?0:3,skill:m.rank==='junior'?1:3,born:w.number,due:w.number+2+Math.floor(rand(w)*3),deadline:w.number+8+Math.floor(rand(w)*6),papers:[],training:[],relationships:[],trust:m.trust,ownWork:[],note:'还在安排自己的研究与生活。'};}
  function init(w,previous,rand){if(!enabled(w))return;const c=config(w.config);Object.assign(w.config,c);const old=previous?.academy;
    w.academy=old?copy(old):{version:1,term:term(c.studyStage,w.number,c.scenario),scenario:c.scenario,start:w.number,people:{},yearbook:[],serial:0,news:[],resource:{active:null,history:[],serial:0},collab:{active:null,history:[],serial:0},loans:[],recovery:{active:null,history:[],seen:[]},foreshadows:[],campus:Object.fromEntries(D.campus.map(d=>[d.id,{step:0,log:[],next:0,finished:false}])),dialogue:{history:[],promises:[]},lastResults:[],plan:null,lastTick:-1};
    calendar(w);const a=w.academy;a.plan=null;a.news=[];if(!old){
      if(c.scenario==='tiny-lab')w.group.members=w.group.members.filter(m=>m.rank==='mentor').slice(0,1);
      if(c.scenario==='dual'){w.group.members=w.group.members.filter(m=>m.rank!=='mentor'||m.id==='mentor-0');const second={id:'mentor-1',rank:'mentor',name:'跨组的孟老师',role:'导师',icon:'🧑‍🏫',trust:48,mentorStyle:'socratic'};w.group.members.splice(1,0,second);w.world.npcs[second.id]={goal:'teach',memory:[],mood:0};}
      if(c.scenario==='poor-finish'){w.group.balance=6;w.group.income=2;w.group.funding='毕业阶段需要精打细算';w.group.news.after=6;a.term.milestones.forEach(m=>m.due=Math.min(m.due,w.number+7));}
      if(c.scenario==='last-eight'){a.term.milestones.forEach((m,i)=>m.due=w.number+[0,2,4,5,7][i]);a.term.milestones[0].status='passed';w.resources.notes=50;}
    }
    for(const m of w.group.members){if(m.rank!=='mentor'&&!a.people[m.id])a.people[m.id]=person(w,m,rand);if(a.people[m.id])a.people[m.id].trust=m.trust;}
    if(old){advancePeople(w,rand);if(w.number>old.start&&(w.number-a.start)%8===0&&w.group.members.length<11&&a.scenario!=='tiny-lab'&&rand(w)<.65){const id='new-junior-'+(++a.serial),m={id,rank:'junior',name:['新来的乔师妹','新来的程师弟','新来的余师妹'][a.serial%3],role:a.serial%3===1?'师弟':'师妹',icon:'🧑‍🎓',trust:45};w.group.members.push(m);w.world.npcs[id]={goal:'teach',memory:[],mood:0};a.people[id]=person(w,m,rand);news(w,m.name+'入组了，听说过年鉴里的一段往届故事。');}}
    if(a.scenario==='mentor-away'&&w.number-a.start<6){w.world.npcs[w.group.members[0].id].mood=-2;news(w,'主导师还在出差，远程回复需要等待；预约求助会延后。');}
    if(a.resource.active&&a.resource.active.version!==w.world.artifact.version&&a.resource.active.status==='waiting')news(w,'旧方向的排期仍按旧版处理，新课题需要另约资源。');
    for(const m of a.term.milestones)if(m.status==='upcoming'&&w.number>=m.due)m.status='due';
    if(a.term.graduated&&a.term.choice==='continue'&&w.number>=a.term.start+stages.find(d=>d.id===a.term.stage).weeks){const oldTerm=copy(a.term);a.yearbook.push({week:w.number,type:'degree',name:'你',text:'完成了'+stages.find(d=>d.id===oldTerm.stage).name+'，保留这一段经历继续生活。',symbol:'🎓'});a.term=term('free',w.number,'regular');a.term.cycle=oldTerm.cycle+1;w.config.studyStage='free';}
    if(a.term.stage==='free'&&w.number>=a.term.start+52&&!milestone(w)){const cycle=a.term.cycle+1;a.term=term('free',w.number,'regular');a.term.cycle=cycle;}
    trim(w);
  }
  function news(w,text){w.academy.news.push(text);w.academy.news=w.academy.news.slice(-8);}
  function result(w,id,text){w.academy.lastResults.push({id,week:w.number,text,celebrated:false});w.academy.lastResults=w.academy.lastResults.slice(-24);}
  function advancePeople(w,rand){const a=w.academy;for(const n of Object.values(a.people)){if(n.status!=='active')continue;n.progress+=1+(rand(w)<.4?1:0);n.skill=Math.min(5,n.skill+(n.training.length&&rand(w)<.45?1:0));
      if(n.phase==='learning'&&n.progress>=4){n.phase='draft';news(w,n.name+'开始独立整理自己的小课题。');}
      else if(n.phase==='draft'&&n.progress>=8){n.phase='submitted';n.due=w.number+2+Math.floor(rand(w)*3);n.papers.push({status:'submitted',week:w.number});news(w,n.name+'投出了自己的稿件，审稿期间也有其他安排。');}
      else if(n.phase==='submitted'&&w.number>=n.due){const accepted=rand(w)<.5;n.phase=accepted?'defense':'revision';n.due=w.number+(accepted?2:1);n.papers.at(-1).status=accepted?'accepted':'revising';news(w,n.name+(accepted?'收到接收回信，开始准备答辩。':'收到修稿意见，这周帮助别人的余量减少。'));}
      else if(n.phase==='revision'&&w.number>=n.due){n.phase='defense';n.due=w.number+2;n.papers.at(-1).status=rand(w)<.75?'accepted':'rejected';news(w,n.name+'结束这轮投稿安排，开始准备自己的阶段答辩。');}
      else if(n.phase==='defense'&&w.number>=n.due){n.phase='job';n.due=w.number+2;news(w,n.name+'完成了自己的答辩，最近在找工作和安排去向。');}
      else if(n.phase==='job'&&w.number>=n.due){n.phase='alumni';n.status='alumni';n.note='照片、留言和贡献进入了年鉴。';a.yearbook.push({week:w.number,type:'graduate',personId:n.id,name:n.name,symbol:n.icon,text:n.training.length?'“以前一起核对的那一页，我还留着。”':'“记得给下一届留一份看得懂的记录。”'});w.group.members=w.group.members.filter(m=>m.id!==n.id);result(w,'alumni',n.name+'离组了，实际阵容和求助入口随之改变。');}
      if(['revision','defense','job'].includes(n.phase))n.note='自己的截止日期接近，可能无法马上帮忙。';else n.note=n.skill>=4?'已经熟悉材料，能帮助定位缺口。':'还有自己的学习和工作安排。';
      const goal=w.world.npcs[n.id];if(goal&&['revision','defense','job'].includes(n.phase)){goal.goal=n.phase==='job'?'job':'paper';goal.mood=-2;}
    }}
  function support(w,id){const a=w.academy;if(!a)return 0;const n=a.people[id];if(!n)return a.scenario==='mentor-away'&&w.number-a.start<6&&id===w.group.members[0].id?-.35:0;if(n.status==='alumni')return -.8;return Math.max(-.28,Math.min(.18,(n.skill-2)*.04-(['revision','defense','job'].includes(n.phase)?.18:0)));}
  function kind(w){const route=w.world.artifact.route,med=window.MEETING_MEDICAL?.find(route),id=med?.resource||window.MEETING_SPECIALTIES?.find(route)?.resource||window.MEETING_ROUTE_STORIES.forRoute(route)?.id||'clinical';return D.resources.find(d=>d.id===id)||D.resources[5];}
  const key=p=>p.route+':'+p.direction+':'+p.version;
  function resourceReady(w){return !!w.academy?.resource.history.some(j=>j.key===key(w.world.artifact)&&j.status==='recorded');}
  function milestone(w){return w.academy?.term.milestones.find(m=>!['passed','waived'].includes(m.status))||null;}
  function requirements(w,m=milestone(w)){if(!m)return {met:true,checks:0,work:0,accepted:0,need:0};const a=w.academy,p=w.world.artifact,checks=Math.max(p.checks.length,...(w.publication?.history||[]).map(t=>t.source.length),0),accepted=(w.publication?.history||[]).filter(t=>t.status==='accepted').length,need={proposal:1,midterm:2,annual:3,application:1,graduation:3}[m.id],work=m.work.length,preparation=(w.preparation?.sources||[]).some(s=>s.level===2&&s.direction===p.direction&&s.projectVersion===p.version),degree=a.term.stage==='doctor'&&m.id==='graduation'?accepted>=1:true;return {checks,work,accepted,need,met:checks>=need&&work>=(m.id==='graduation'?2:1)&&preparation&&degree};}
  function available(w){return !!w.academy&&w.status==='life'&&w.day!==4&&!w.pending&&!w.campus?.plan&&!window.MEETING_ASSIGNMENTS.offer(w)&&!(w.day===0&&w.slot===0&&!w.group.news.handled);}
  function option(text,action,effects={},extra={}){return {text,academyAction:action,effects,traits:{},career:{},work:{},preparationGains:{},flavor:'具体结果会在行动后揭晓。',...extra};}
  function build(w,type,target=null){const a=w.academy,p=w.world.artifact,j=a.resource.active,n=a.people[target],m=milestone(w),co=a.collab.active,r=a.recovery.active;let title='',scene='',choices=[];
    if(type==='resource'){const d=kind(w);title=d.icon+' '+d.name;scene=d.start+' 当前课题版本 '+p.version+'。等待期间可以读材料、生活或做其他课题。';choices=[option('正式预约这一版，整理对应条件并投入可用经费。','book',{energy:-6,stress:3}),option('借同门或合作方的入口，明确归还与交接时间。','borrow',{energy:-4,stress:2}),option('缩小需求，请导师协调一个有限窗口。','ask',{energy:-5,stress:2})];}
    else if(type==='resource-work'){const d=D.resources.find(d=>d.id===j.kind);title=d.icon+' 排期之后 · '+d.name;scene=(j.status==='blocked'?d.change:'窗口开放了，请对照预约时保存的条件。')+' '+d.condition+'。这份安排属于课题版本 '+j.version+'。';choices=[option('回到预约条件，实际核对记录，保留能够支持的范围。','resource-check',{energy:-10,notes:5,stress:3},{academyAvailable:j.status==='available'&&j.key===key(p)}),option('重新协调时间和条件，保留旧排期记录。','resource-rebook',{energy:-5,stress:4}),option('放弃这次窗口，把借用和材料交回。','resource-release',{energy:4,stress:-3})];}
    else if(type==='person'){title=n.icon+' '+n.name+' · '+D.careers[n.phase];scene=n.note+' 对方目前熟练度 '+n.skill+'/5。共同练过的材料会留下具体记录。';choices=[option(n.rank==='junior'?'一起核对一个小问题，让对方独立讲一遍。':'用这半天帮对方准备自己的材料或答辩。','train',{energy:-8,notes:3,stress:2}),option('提出一个有范围的求助，接受对方可能忙不过来。','person-help',{energy:-4,stress:2}),option('只聊聊自己的近况，把这半天留给关系和休息。','person-talk',{energy:7,stress:-6})];}
    else if(type==='loan'){const loan=a.loans.find(l=>l.id===target);title='🔌 借用要接回对方的安排';scene=(a.people[loan.personId]?.name||'合作伙伴')+'的设备或资料还有别的用途。约定交接在第'+loan.dueWeek+'周，借用源自第'+loan.from+'周的实际选择。';choices=[option('现在完成归还与记录交接，自己的后续另排。','loan-return',{energy:-5,stress:2}),option('先帮对方准备答辩，再共同确认可以借到哪一天。','loan-help',{energy:-10,stress:3}),option('继续占用入口，先赶自己的材料。','loan-keep',{energy:2,stress:6})];}
    else if(type==='stage-prep'){title='📅 '+D.phases[m.id]+' · 准备一个实际片段';scene='目标时间：第'+m.due+'周。当前阶段要求至少'+requirements(w,m).need+'份实际课题核对记录，并完成本阶段的准备；毕业检查需要两个准备片段，博士毕业还需要接收成果。';choices=[option('用这半天核对阶段材料，并计时练习说明边界。','stage-work',{energy:-9,slides:5,stress:2},{preparationGains:{rehearsal:2}}),option('梳理缺口与资源排期，申请适当调整阶段安排。','stage-plan',{energy:-4,stress:-2}),option('只把检查日期填进日历，暂时不处理材料。','stage-note',{energy:5,stress:-3})];}
    else if(type==='stage-check'){title='🎓 '+D.phases[m.id]+' · 轮到实际材料了';scene='检查按实际记录进行：课题核对 '+requirements(w,m).checks+'/'+requirements(w,m).need+'；阶段准备 '+m.work.length+'/'+(m.id==='graduation'?2:1)+'。等待中的稿件会按等待记录，不能写成接收。';choices=[option('提交做过的阶段材料，接受完成或需要补救的结果。','stage-submit',{energy:-8,stress:4}),option('说明尚缺的部分，申请延期并安排下一次检查。','stage-delay',{energy:-4,stress:2}),option('讨论换一个更小的方向，保留已经完成的阶段。','stage-pivot',{energy:-5,stress:4})];}
    else if(type==='degree'){title='🎓 阶段之后，怎样继续？';scene='阶段检查已经完成。你可以保留这一段经历，继续自由生涯，也可以接受新的博士阶段，或把这份年鉴留在这里。';choices=[option('完成这一阶段，继续自由生涯与校园生活。','degree-continue',{energy:8,stress:-6}),option('了解安排，开始一个新的博士阶段。','degree-doctor',{energy:-4,stress:6}),option('留下一份毕业年鉴，暂时结束这段生涯。','degree-end',{energy:8,stress:-8})];}
    else if(type==='collab'){title='🤝 合作课题 · 先把分工写清楚';scene='伙伴可以提供一段材料，你承担分析或解释；共同结论和署名仍需实际协商。没有同门时可以联系组外虚构伙伴。';choices=[option('约定各自一小段工作，先保留贡献与使用范围。','collab-start',{energy:-6,stress:2}),option('做一次组外试谈，确认是否存在可以共享的入口。','collab-external',{energy:-7,stress:3}),option('暂时不合作，保留自己能够承担的范围。','collab-pause',{energy:5,stress:-3})];}
    else if(type==='collab-work'){title='🧾 合作进行中 · '+co.partnerName;scene='分工阶段 '+co.step+'/3。'+['双方约定了任务，材料还没有实际交接。','伙伴提供了一段记录，但对扩大结论提出了异议。','工作各自有回执，现在要讨论贡献与作者顺序。','共同范围和署名已确认，可以整理投稿。'][co.step]+(co.absent?' 伙伴自己的截止日期接近，本次交接可能需要等待。':'');choices=[option(co.step===0?'完成自己负责的一段工作，记录来源与贡献。':co.step===1?'和伙伴对照材料，缩回共同确认的结论范围。':'按各自实际贡献共同确认署名和使用范围。','collab-work',{energy:-10,notes:4,stress:3}),option('先把自己写在最前面，贡献说明以后再补。','collab-claim',{energy:2,slides:3,stress:3}),option('结束这一轮合作，交接已有材料和贡献记录。','collab-stop',{energy:-5,stress:-3})];}
    else if(type==='recovery'){title='🛠️ 失败之后 · '+r.title;scene=r.scene+' 上次的失败记录保留，后续需要实际行动。';choices=r.step===0?[option('缩小问题，重新安排资源与补查。','recover-small',{energy:-6,stress:-3}),option('联系一个新的合作伙伴，明确新的分工。','recover-partner',{energy:-7,stress:2}),option('把失败整理成教学案例，说明当时没有做过的部分。','recover-teach',{energy:-8,slides:5,stress:-2})]:[option('实际完成这段补救的交付，保留范围与来源。','recover-finish',{energy:-9,stress:2},{academyAvailable:w.number>=r.next}),option('承认还需要时间，推迟这次交付。','recover-wait',{energy:3,stress:3}),option('停止这个方向，保留材料并寻找相邻问题。','recover-pivot',{energy:-5,stress:-2})];}
    else if(type==='foreshadow'){const f=a.foreshadows.find(f=>f.id===target),d=D.foreshadows.find(d=>d.id===f.kind);title='✉️ 后来的那一页 · '+d.title;scene=d.reveal+' 伏笔：第'+f.from+'周「'+f.origin+'」。';choices=[option('核对原来的约定，用这个片段做一个有范围的回应。','foreshadow-do',{energy:-7,notes:3,stress:2}),option('和对方重谈安排，说明哪些内容没有答应或不能做。','foreshadow-talk',{energy:-4,stress:1}),option('顺着热闹把故事说大，具体交接以后再做。','foreshadow-show',{energy:2,stress:5},{traits:{chaos:1}})];}
    else if(type==='campus'){const d=D.campus.find(d=>d.id===target),g=a.campus[target];title=d.icon+' '+d.name+' · '+(g.step+1)+'/'+d.steps;scene=d.scenes[g.step]+' 这也是一个实际生活片段，后续至少到下一周。';choices=[option('认真参加，给自己和朋友留出能做到的安排。','campus-do',{energy:10,stress:-8}),option('邀请新朋友一起来，接受这次安排可能临时改变。','campus-social',{energy:7,stress:-5}),option('这次先退出，和大家约好下次再来。','campus-pass',{energy:5,stress:-4})];}
    return {id:'academy-'+type+'-'+(target||j?.id||m?.id||w.number),academyType:type,academyTarget:target,day:w.day,slot:w.slot,project:p.route,title,scene,choices};
  }
  function dispatch(w,type,target=null){if(!available(w))return false;const a=w.academy;
    if(type==='resource'&&a.resource.active||type==='resource-work'&&!['available','blocked'].includes(a.resource.active?.status)||type==='person'&&a.people[target]?.status!=='active'||type==='loan'&&!a.loans.some(l=>l.id===target&&l.status==='open')||['stage-prep','stage-check'].includes(type)&&!milestone(w)||type==='stage-check'&&w.number<milestone(w).due||type==='degree'&&(!a.term.graduated||a.term.choice)||type==='collab'&&a.collab.active||type==='collab-work'&&(!a.collab.active)||type==='recovery'&&!a.recovery.active||type==='foreshadow'&&!a.foreshadows.some(f=>f.id===target&&f.status==='due')||type==='campus'&&(!a.campus[target]||a.campus[target].finished||w.day<5||w.number<a.campus[target].next))return false;
    const event=build(w,type,target);if(!event.choices.length)return false;a.plan=event;w.campus.plan={day:w.day,slot:w.slot,location:'academy',original:w.eventId};return true;
  }
  function prepare(w,rand){const a=w.academy;if(!a||a.lastTick===tick(w))return;a.lastTick=tick(w);a.plan=null;const j=a.resource.active;
    if(j?.status==='waiting'&&tick(w)>=j.due){j.status=j.obstacle?'blocked':'available';j.expires=tick(w)+D.resources.find(d=>d.id===j.kind).window;news(w,j.status==='blocked'?'排期临时改变，需要重新协调。':'约定的资源窗口开放了，要实际核对才会有回执。');}
    if(j?.status==='available'&&tick(w)>j.expires){j.status='expired';a.resource.history.push(copy(j));a.resource.active=null;news(w,'资源窗口错过了，预约没有变成实查。');}
    for(const l of a.loans)if(l.status==='open'&&tick(w)>l.due&&l.penaltyAt!==w.number){l.penaltyAt=w.number;window.MEETING_GROUP.trust(w,l.personId,-8);w.resources.stress=clamp(w.resources.stress+5);result(w,'loan-late','借用超过约定时间，对方的安排受到了影响。');}
    for(const f of a.foreshadows)if(f.status==='waiting'&&w.number>=f.due){f.status='due';news(w,D.foreshadows.find(d=>d.id===f.kind).reveal);}
    const failed=(w.publication?.history||[]).findLast(t=>['rejected','desk'].includes(t.status)&&!a.recovery.seen.includes(t.id));if(failed&&!a.recovery.active)startRecovery(w,'paper-'+failed.id,'退稿后的下一步','期刊没有接收这一稿，实际材料与评审意见仍在。',failed.id);
    if(w.day!==4&&available(w)){const m=milestone(w),loan=a.loans.find(l=>l.status==='open'&&tick(w)>=l.due-2),f=a.foreshadows.find(f=>f.status==='due');if(loan&&rand(w)<.4)a.plan=build(w,'loan',loan.id);else if(m&&w.number>=m.due&&w.day===3&&w.slot===1)a.plan=build(w,'stage-check');else if(f&&rand(w)<.16)a.plan=build(w,'foreshadow',f.id);}
    trim(w);
  }
  function current(w,raw){if(!w.academy)return raw;const a=w.academy;if(w.campus?.plan?.location==='academy')return copy(a.plan);let e=raw;if(a.plan&&!w.campus?.plan&&!raw?.choices?.some(c=>c.assignmentAction||c.groupAction))e=copy(a.plan);if(e?.worldType==='project'){e=copy(e);const verify=e.choices.find(c=>c.worldAction==='verify');if(verify&&!resourceReady(w)){verify.academyAvailable=false;verify.academyReason='需要本方向、本版本的资源窗口复核；可在课题安排区预约。';e.scene+=' 本版还没有资源窗口回执，预约与实查需要分别完成。';}}return e;}
  function receipt(w,j,c){const p=w.world.artifact,source={version:p.version,route:p.route,direction:p.direction,kind:'record',week:w.number,day:w.day,eventId:j.id,action:c.text,level:2,resourceId:j.id};p.checks.push(source);p.checks=p.checks.slice(-100);p.status=p.checks.length>=3?'ready':'checked';c.preparationRoute=p.route;c.preparationGains={record:2};return source;}
  function addLoan(w,personId,source){const a=w.academy;if(a.loans.some(l=>l.source===source))return;const n=a.people[personId],dueWeek=Math.min(w.number+2,n?.phase==='defense'?n.due:w.number+2);if(!a.foreshadows.some(f=>f.kind==='borrow'))addShadow(w,'borrow','借用了同门的资源入口');a.loans.push({id:'loan-'+(++a.serial),personId,source,from:w.number,dueWeek,due:(dueWeek-1)*14+6,status:'open'});}
  function startRecovery(w,id,title,scene,source=id){const a=w.academy;if(a.recovery.active||a.recovery.seen.includes(source))return;a.recovery.seen.push(source);a.recovery.active={id,title,scene,source,step:0,mode:null,from:w.number,next:w.number+1,log:[]};}
  function resolve(w,e,c,effects,rand){if(!e.academyType)return null;const a=w.academy,p=w.world.artifact,action=c.academyAction,target=e.academyTarget;let text='',success=true;const add=o=>{for(const [k,v] of Object.entries(o))effects[k]=(effects[k]||0)+v;};
    if(e.academyType==='resource'){const d=kind(w),peer=w.group.members.find(m=>m.rank!=='mentor'),mentor=w.group.members[0],budget=w.group.balance;success=action==='book'?budget>=d.cost&&rand(w)<.86:action==='borrow'?!!peer&&rand(w)<Math.max(.08,.3+peer.trust*.005+support(w,peer.id)):rand(w)<Math.max(.08,.25+mentor.trust*.005+support(w,mentor.id));if(action==='book'){w.group.balance=Math.max(0,budget-d.cost);}if(success){const id='resource-'+(++a.resource.serial);a.resource.active={id,key:key(p),version:p.version,direction:p.direction,route:p.route,kind:d.id,status:'waiting',from:w.number,due:tick(w)+d.wait+(a.scenario==='mentor-away'&&action==='ask'?14:0),expires:0,obstacle:rand(w)<.27,condition:d.condition,borrower:action==='borrow'?peer.id:null};if(action==='borrow')addLoan(w,peer.id,id);text='约定已经留下，资源要等到窗口开放后实际复核。';}else{text='这次协调没有落实，时间和投入已经用掉；可以另约或做小范围准备。';add({stress:4});}}
    else if(e.academyType==='resource-work'){const j=a.resource.active;if(action==='resource-check'){if(j.status!=='available'||j.key!==key(p))return null;receipt(w,j,c);j.status='recorded';j.receipt={week:w.number,eventId:e.id,action:c.text};a.resource.history.push(copy(j));a.resource.active=null;text='窗口里的材料实际核对完成，回执属于本方向、本课题版本；可以继续推进实查。';}else if(action==='resource-rebook'){j.status='waiting';j.due=tick(w)+D.resources.find(d=>d.id===j.kind).wait;j.obstacle=rand(w)<.16;text='你重新协调了条件，下一次窗口要继续等待；原预约仍保留。';}else{j.status='released';a.resource.history.push(copy(j));a.resource.active=null;for(const l of a.loans.filter(l=>l.source===j.id&&l.status==='open'))l.status='returned';text='窗口被交回，借用也已交接，没有留下实查回执。';}}
    else if(e.academyType==='person'){const n=a.people[target];if(action==='train'){n.training.push({week:w.number,version:p.version,route:p.route,eventId:e.id,action:c.text});n.training=n.training.slice(-12);n.skill=Math.min(5,n.skill+1);n.progress+=2;window.MEETING_GROUP.trust(w,n.id,4);text='你们实际练过一个小问题，对方熟练度提高，今后的帮助与发现缺口都可能受影响。';}else if(action==='person-help'){success=rand(w)<Math.max(.05,.3+n.trust*.004+support(w,n.id));if(success){c.preparationGains={method:1};text='对方给出一条可以继续核对的线索，没有替你完成整份准备。';}else{text='对方自己的截止安排接不住这次请求，这半天只留下了沟通。';add({stress:3});}}else{window.MEETING_GROUP.trust(w,n.id,2);text='你们聊了自己的近况，关系有了实际相处，没有把聊天记作课题完成。';}n.relationships.push({week:w.number,action});n.relationships=n.relationships.slice(-12);}
    else if(e.academyType==='loan'){const l=a.loans.find(l=>l.id===target);if(action==='loan-return'){l.status='returned';window.MEETING_GROUP.trust(w,l.personId,4);text='借用正式归还，对方可以继续自己的答辩与研究安排。';}else if(action==='loan-help'){l.due+=14;l.dueWeek++;const n=a.people[l.personId];if(n){n.progress+=2;n.training.push({week:w.number,eventId:e.id,action:c.text,version:p.version,route:p.route});}window.MEETING_GROUP.trust(w,l.personId,3);text='你付出实际时间帮对方准备，双方重新约定了归还时间。';}else{l.due=Math.min(l.due,tick(w)+2);window.MEETING_GROUP.trust(w,l.personId,-5);text='你继续占用入口，对方的安排受到挤压，临近交接不会自行消失。';}}
    else if(e.academyType==='stage-prep'){const m=milestone(w);if(action==='stage-work'){m.work.push({week:w.number,eventId:e.id,version:p.version,direction:p.direction,action:c.text});m.work=m.work.slice(-8);text='这一阶段留下了一次实际准备，检查仍需要对应的课题材料。';}else if(action==='stage-plan'){text='缺口与排期已经写进计划，材料核对和正式检查仍要另用片段完成。';}else text='日期被记住了，阶段准备没有增加。';}
    else if(e.academyType==='stage-check'){const m=milestone(w),met=requirements(w,m).met;m.attempts++;if(action==='stage-submit'&&met){const recovered=m.extension>0;m.status='passed';text='实际检查通过，已做和未覆盖的范围分别保留。';if(recovered)result(w,'stage-recovered',text);if(m.id==='graduation'){a.term.graduated=true;result(w,a.term.stage==='doctor'?'degree-doctor':'degree-master',text);}if(a.term.stage==='free'&&m.id==='annual')result(w,'stage-free',text);const scenarioMet=a.scenario==='poor-finish'?m.id==='graduation':a.scenario==='last-eight'?m.id==='graduation'&&w.number-a.start>=7:a.scenario==='mentor-away'?w.number-a.start<6:a.scenario==='tiny-lab'?!!a.collab.active?.agreement&&!a.collab.active.partnerId:a.scenario==='dual'?(w.config.mixProjects||[]).every(route=>w.preparation.sources.some(s=>s.route===route&&s.kind===w.jointKind&&s.level===2)):false;if(scenarioMet)result(w,{'poor-finish':'scenario-poor','mentor-away':'scenario-away','tiny-lab':'scenario-tiny','last-eight':'scenario-eight','dual':'scenario-dual'}[a.scenario],text);}else{m.status='upcoming';m.due=w.number+2;m.extension++;text=action==='stage-pivot'?'检查改为更小的范围，阶段时间后移，既有材料保留。':'这一轮需要补救，检查后移两周，缺少的实际材料仍要完成。';if(action==='stage-pivot')p.scope=Math.max(1,p.scope-1);if(m.id==='graduation')result(w,'degree-delay',text);startRecovery(w,'stage-'+m.id+'-'+m.extension,D.phases[m.id]+'后的补救','检查没有完成，下一轮要补实际材料。');}}
    else if(e.academyType==='degree'){a.term.choice={ 'degree-continue':'continue','degree-doctor':'doctor','degree-end':'ended'}[action];if(action==='degree-doctor'){a.yearbook.push({week:w.number,type:'degree',name:'你',symbol:'🎓',text:'完成上一阶段，进入新的博士阶段。'});a.term=term('doctor',w.number+1,'regular');w.config.studyStage='doctor';}text=action==='degree-end'?'这一段生涯已经归档，存档和结局图鉴仍保留。':action==='degree-doctor'?'新的博士阶段有自己的检查时间，旧稿与关系继续保留。':'你选择继续，完成这一阶段后会进入自由生涯。';}
    else if(e.academyType==='collab'){if(action==='collab-pause')text='你没有开始这轮合作，自己的材料范围保持明确。';else{const peers=w.group.members.filter(m=>m.rank!=='mentor'),peer=action==='collab-start'?peers[Math.floor(rand(w)*Math.max(1,peers.length))]:null;a.collab.active={id:'collab-'+(++a.collab.serial),key:key(p),version:p.version,direction:p.direction,route:p.route,partnerId:peer?.id||null,partnerName:peer?.name||'组外的乔同学',step:0,status:'working',from:w.number,next:w.number,contributions:[],agreement:null,absent:false};text='分工和材料范围已约定，各自工作与署名还需要真实处理。';}}
    else if(e.academyType==='collab-work'){const co=a.collab.active;if(action==='collab-stop'){co.status='ended';a.collab.history.push(copy(co));a.collab.active=null;result(w,'collab-return','双方完成交接，合作结束。');text='材料与贡献记录分别归档，下一次合作可以重新商量。';}else if(action==='collab-claim'){co.status='disputed';co.agreement=null;result(w,'collab-dispute','作者顺序没有得到共同确认。');if(co.partnerId)window.MEETING_GROUP.trust(w,co.partnerId,-7);text='伙伴对署名提出异议，稿件等待协商，贡献不会因为改名单而消失。';}else if(co.key!==key(p)){text='合作材料属于旧方向和旧版本，需要结束交接后为新课题重新约定。';success=false;}else if(co.step===0){co.step=1;co.contributions.push({person:'你',week:w.number,eventId:e.id,action:c.text,role:'分析与解释'});co.next=w.number+1;text='你负责的一段实际完成，贡献记录保留；伙伴的材料至少到下周再协调。';}else if(co.step===1){if(w.number<co.next){success=false;text='伙伴还没有完成自己的交接，今天先对齐条件，没有完成共同结论。';}else if(rand(w)<.2+Math.max(0,-support(w,co.partnerId))){co.absent=true;co.next=w.number+1;text='伙伴自己的截止日期临近，交接暂缓，已有贡献仍在。';success=false;}else{co.step=2;co.absent=false;co.contributions.push({person:co.partnerName,week:w.number,eventId:e.id,action:'提供材料并确认解释范围',role:'材料与复核'});receipt(w,{id:co.id},c);p.scope=Math.min(2,p.scope);text='伙伴提供的材料和共同范围实际对上了，留下本版实查与双方贡献。';}}else if(co.status==='agreed'){text='这一版共同署名已经确认；继续核对需要新的工作，已有协议保持原来的贡献范围。';}else{co.step=3;co.status='agreed';co.agreement={week:w.number,authors:['你',co.partnerName],contributions:copy(co.contributions),scope:p.scope};result(w,'collab-fair','双方实际确认了贡献、署名与共同范围。');text='贡献与作者名单共同确认，投稿会保存这份协议的独立快照。';}}
    else if(e.academyType==='recovery'){const r=a.recovery.active;if(r.step===0){r.mode={ 'recover-small':'small','recover-partner':'partner','recover-teach':'teach'}[action];r.step=1;r.next=w.number+1;r.log.push({week:w.number,eventId:e.id,action:c.text});if(r.mode==='small')p.scope=1;text='补救有了明确范围，下一段至少到下周，失败记录继续保留。';}else if(action==='recover-finish'){if(w.number<r.next)return null;if(r.mode==='small'&&!resourceReady(w)){text='新范围仍需资源复核，这次交付保留为待完成；可以先预约。';success=false;}else{r.log.push({week:w.number,eventId:e.id,action:c.text});r.status='completed';if(r.mode==='teach'){result(w,'recovery-teaching','失败案例实际整理完，课堂引用保留真实缺口。');addShadow(w,'failure',c.text);}else if(r.mode==='partner'){result(w,'recovery-collab','退稿后的新合作入口已经确认。');if(!a.collab.active)a.collab.active={id:'collab-'+(++a.collab.serial),key:key(p),version:p.version,direction:p.direction,route:p.route,partnerId:null,partnerName:'食堂认识的乔同学',step:0,status:'working',from:w.number,next:w.number,contributions:[],agreement:null,absent:false};}else{receipt(w,{id:r.id},c);result(w,'stage-recovered','缩小范围之后实际补查了一项材料。');}a.recovery.history.push(copy(r));a.recovery.active=null;text='这段补救真正交付了，失败没有被改写，后续有了新的入口。';}}else if(action==='recover-pivot'){r.status='pivot';a.recovery.history.push(copy(r));a.recovery.active=null;p.scope=1;text='你停止这一轮补救，保留材料，下一次可选择相邻问题。';}else{r.next=w.number+1;text='补救交付后移，缺口仍保留。';}}
    else if(e.academyType==='foreshadow'){const f=a.foreshadows.find(f=>f.id===target);f.status='resolved';f.resolution={week:w.number,eventId:e.id,action:c.text};text='这次回应接回了第'+f.from+'周的选择，原来的伏笔和今天的结果都能回看。';if(f.kind==='quote'&&action==='foreshadow-do')result(w,'foreshadow-quote',text);if(f.kind==='table'&&action==='foreshadow-do'&&!a.collab.active){a.collab.active={id:'collab-'+(++a.collab.serial),key:key(p),version:p.version,direction:p.direction,route:p.route,partnerId:null,partnerName:'食堂认识的乔同学',step:0,status:'working',from:w.number,next:w.number,contributions:[],agreement:null,absent:false};}if(action==='foreshadow-show')addShadow(w,'borrow',c.text);}
    else if(e.academyType==='campus'){const g=a.campus[target],d=D.campus.find(d=>d.id===target);if(action==='campus-pass'){g.next=w.number+1;text='你退出这次安排，小目标没有丢失，下一周可以继续。';}else{success=action==='campus-do'||rand(w)<.75;g.log.push({week:w.number,eventId:e.id,action:c.text,success});g.next=w.number+1;if(success)g.step++;text=success?'这次生活安排完成了，下一段至少到下周；研究与生活共用时间，各自留下记录。':'朋友临时有事，这次只留下相约，下一周可以再安排。';if(target==='meal'&&g.step===3)addShadow(w,'table',c.text);if(g.step>=d.steps){g.finished=true;result(w,'campus-'+target,text);a.yearbook.push({week:w.number,type:'campus',name:'你和朋友',symbol:d.icon,text:d.name+'有了这一阶段的结尾。'});}}}
    trim(w);return {type:e.academyType,action,target,text,success};
  }
  function addShadow(w,kind,origin){const a=w.academy;if(a.foreshadows.some(f=>f.kind===kind&&f.status!=='resolved'))return;a.foreshadows.push({id:'shadow-'+(++a.serial),kind,from:w.number,due:w.number+2,origin,status:'waiting'});}
  function afterLife(w,e,c,record){const a=w.academy;if(!a)return;if(record.routeStory?.action==='peer'&&record.routeStory.success){const t=w.routeStories.active;if(t?.partnerId)addLoan(w,t.partnerId,t.instance);}
    if(record.routeStory&&['verify','release'].includes(record.routeStory.action))for(const l of a.loans)if(record.routeStory.action==='release'&&l.source===(record.routeStory.instance||w.routeStories?.active?.instance||w.routeStories?.history?.at(-1)?.instance)||record.routeStory.action==='verify'&&l.source===(record.routeStory.instance||w.routeStories?.history?.at(-1)?.instance))l.status='returned';
    if((c.traits?.promise||0)>0&&!a.dialogue.promises.some(p=>p.source===e.id))a.dialogue.promises.push({id:'promise-'+(++a.serial),source:e.id,topic:e.title,week:w.number,due:w.number+1,status:'open',route:e.project||pRoute(w)});
    if(c.preparationGains?.record===2)for(const promise of a.dialogue.promises.filter(p=>p.status==='open'&&p.route===(c.preparationRoute||e.project)))promise.status='worked';
    if(c.traits?.chaos&&a.foreshadows.filter(f=>f.kind==='quote').length===0)addShadow(w,'quote',c.text);
    if(record.taskDone&&a.foreshadows.filter(f=>f.kind==='email').length===0)addShadow(w,'email',c.text);
    if(a.collab.active?.partnerId){const n=a.people[a.collab.active.partnerId];a.collab.active.absent=!!n&&['revision','defense','job'].includes(n.phase);}
    for(const n of Object.values(a.people)){const m=w.group.members.find(m=>m.id===n.id);if(m)n.trust=m.trust;}
    trim(w);
  }
  const pRoute=w=>w.world.artifact.route;
  function publicationAllowed(w){const co=w.academy?.collab.active;return !co||co.key!==key(w.world.artifact)||co.status==='agreed'||co.status==='ended';}
  function publicationSnapshot(w,t){const co=w.academy?.collab.active;if(t&&co?.key===key(w.world.artifact)&&co.status==='agreed')t.collaboration=copy(co.agreement);}
  function context(w,ctx){if(w.academy)ctx.academy=copy(w.academy);return ctx;}
  function afterMeeting(w,s){const a=w.academy;if(!a)return;if(s.academicDialogue){a.dialogue.history.push({week:w.number,format:s.academicDialogue.format,turns:copy(s.academicDialogue.turns),contradictions:s.academicDialogue.contradictions});a.dialogue.history=a.dialogue.history.slice(-12);for(const p of s.academicDialogue.newPromises)a.dialogue.promises.push({...p,id:'promise-'+(++a.serial),week:w.number,due:w.number+1,status:'open'});}
    if(C.endings.find(e=>e.id===s.ending)?.kind==='failure')startRecovery(w,'meeting-'+w.number,'没讲完的组会之后','上次汇报卡住了，可以缩小问题、寻找合作或整理失败案例。');
    if(s.academicDialogue?.juniorOutcome)result(w,s.academicDialogue.juniorOutcome,'同门从共同练过的材料接上了这次现场。');
    for(const r of a.lastResults)if(r.id===s.ending)r.celebrated=true;trim(w);
  }
  function ending(s){if(s.wrapUp!==2)return null;return s.weekContext?.academy?.lastResults.findLast(r=>!r.celebrated)?.id||null;}
  function trim(w){const a=w.academy;if(!a)return;a.yearbook=a.yearbook.slice(-48);a.resource.history=a.resource.history.slice(-20);a.collab.history=a.collab.history.slice(-12);a.loans=a.loans.slice(-20);a.recovery.history=a.recovery.history.slice(-12);a.recovery.seen=a.recovery.seen.slice(-40);a.foreshadows=a.foreshadows.slice(-24);a.dialogue.promises=a.dialogue.promises.slice(-30);for(const n of Object.values(a.people))n.training=n.training.slice(-12);for(const g of Object.values(a.campus))g.log=g.log.slice(-24);const alumni=Object.values(a.people).filter(n=>n.status==='alumni');for(const n of alumni.slice(0,Math.max(0,alumni.length-24)))delete a.people[n.id];}
  function valid(w){const a=w.academy;if(!a)return true;const resource=j=>j&&D.resources.some(d=>d.id===j.kind)&&Number.isInteger(j.version)&&j.version>0&&C.projects.some(p=>p.id===j.route)&&['waiting','available','blocked','recorded','expired','released'].includes(j.status)&&Number.isInteger(j.due)&&typeof j.key==='string';const collab=co=>co&&Number.isInteger(co.step)&&co.step>=0&&co.step<=3&&['working','disputed','agreed','ended'].includes(co.status)&&Array.isArray(co.contributions)&&co.contributions.length<=4&&typeof co.key==='string';return a.version===1&&stages.some(s=>s.id===a.term?.stage)&&scenarios.some(s=>s.id===a.scenario)&&Array.isArray(a.term.milestones)&&a.term.milestones.every(m=>Object.hasOwn(D.phases,m.id)&&Number.isInteger(m.due)&&['upcoming','due','passed','waived'].includes(m.status)&&Array.isArray(m.work)&&m.work.length<=8)&&['yearbook','news','loans','foreshadows','lastResults'].every(k=>Array.isArray(a[k]))&&a.yearbook.length<=48&&a.loans.length<=20&&a.foreshadows.length<=24&&a.lastResults.length<=24&&Object.values(a.people).every(n=>['active','alumni'].includes(n.status)&&Object.hasOwn(D.careers,n.phase)&&Number.isInteger(n.skill)&&n.skill>=1&&n.skill<=5)&&(!a.resource.active||resource(a.resource.active))&&a.resource.history.every(resource)&&(!a.collab.active||collab(a.collab.active))&&a.collab.history.every(collab)&&D.campus.every(d=>a.campus[d.id]&&Number.isInteger(a.campus[d.id].step)&&a.campus[d.id].step>=0&&a.campus[d.id].step<=d.steps)&&Array.isArray(a.dialogue.history)&&a.dialogue.history.length<=12&&Array.isArray(a.dialogue.promises)&&a.dialogue.promises.length<=30&&(!a.plan||a.plan.choices?.length===3);}
  for(const [id,kind,icon,title,desc] of D.endings)C.endings.push({id,kind,icon,title,desc,subtitle:'研究与生活各有后续，真实选择会接到后来。',hint:'完成相应阶段、合作、补救或校园支线，并抵达组会收尾。'});
  return {calendar,term,stages,scenarios,config,init,prepare,current,resolve,afterLife,context,afterMeeting,ending,valid,available,dispatch,build,kind,resourceReady,milestone,requirements,support,publicationAllowed,publicationSnapshot,addLoan,addShadow,advancePeople,startRecovery,tick,key};
})();
