/* 临时交办占用实际生活片段，接下消息不等于交付。 */
window.MEETING_ASSIGNMENTS=(()=>{
  'use strict';
  const C=window.MEETING_CONTENT,P=window.MEETING_PREPARATION,M=window.MEETING_MIX,copy=x=>JSON.parse(JSON.stringify(x));
  const templates=[
    ['one-page','boss','补一页背景说明','literature','明天要给合作方看，先把来源、已有工作和局限说明白。'],
    ['seminar','boss','整理临时研讨会的三个问题','boundary','老师刚参加完讲座，想知道新说法与你的材料在哪一步有关。'],
    ['reference','boss','核对一条被反复引用的说法','literature','群里传得很快，但老师希望看到原始出处与适用范围。'],
    ['explain','boss','准备三分钟的来访介绍','rehearsal','来访的人换了背景；一页能讲清楚，比十页标题更有用。'],
    ['compare','boss','比较两个方法的适用条件','method','老师需要做一个选择，让你先把条件和代价摆在同一页。'],
    ['records','boss','对回一次进展材料的来源','record','老师发现总结页省掉了来源，想在周五前确认对应关系。'],
    ['teaching','boss','帮忙整理教学中的一个例子','boundary','需要说明例子能支持哪一个判断，哪些地方只适合做示意。'],
    ['reply','boss','起草一段范围明确的答复','rehearsal','对方问了三个问题；老师希望你别在一段话里许下六个承诺。'],
    ['handoff','boss','接待来访者并做交接记录','record','预约临时提前，联系人不在。交接记录需要留给下一位接手的人。'],
    ['agenda','boss','排一份临时讨论的议程','rehearsal','大家的时间对不上，要区分必须决定的事项和可以以后再谈的问题。'],
    ['terms','boss','补一张术语与定义对照页','method','合作方对同一个词的理解不同。先把定义讲清，别急着画漂亮箭头。'],
    ['summary','boss','缩小一份过满的工作计划','boundary','老师说内容很多，但每项都只写了“进一步研究”。需要一个能检查的范围。'],
    ['peer-page','senior','帮看一页卡住的材料','record','同门说只看一页，后来又补充：这一页连着前面三份记录。'],
    ['peer-version','senior','核对两个同名版本','record','文件都叫最终版。要保留来源，不能只按修改时间挑一个。'],
    ['peer-method','senior','找一个做法的明确依据','method','同门记得见过类似处理，却不记得适用条件。'],
    ['peer-paper','senior','帮定位一条文献线索','literature','链接打不开，截图又没有出处。需要查到可核对的原始信息。'],
    ['peer-talk','senior','陪同门做一次限时试讲','rehearsal','对方只剩三分钟，却准备了十二页。你要听到卡住的具体地方。'],
    ['peer-counter','senior','整理讨论里的一个反例','boundary','大家已经聊了很久，但没有把反例成立的条件写出来。'],
    ['peer-room','senior','协调场地并留下交接单','record','预约撞车了。你需要确认谁要用、什么时候交接，不只是群里回一句收到。'],
    ['peer-folder','senior','给共享材料建立来源索引','record','现在能找到文件，却找不到谁改了哪一处。索引得能真的追溯。'],
    ['peer-question','senior','帮拆开一个过大的问题','boundary','同门希望做完全部，但时间只够一小步。需要共同确认取舍。'],
    ['peer-demo','senior','检查一段演示的说明文字','method','演示能运行，说明却跳过了几个条件。别把顺利播放当作已经验证。'],
    ['peer-citation','senior','补齐一页引用的出处','literature','标题看起来很像，实际研究的问题可能不同，需要打开原文核对。'],
    ['peer-coop','senior','写清合作中谁负责哪一步','rehearsal','几个人都以为下一步由别人接手，今晚需要一份范围明确的分工。']
  ].map(([id,who,title,kind,scene])=>({id,who,title,kind,scene}));
  const statuses={accepted:'已接 · 待处理',overdue:'已逾期 · 仍待交付',delivered:'完整交付',partial:'已交部分范围',declined:'已说明无法接下',withdrawn:'已交回未完成部分'};
  const active=w=>!!w.assignments,open=t=>['accepted','overdue'].includes(t.status),tick=w=>(w.number-1)*14+w.day*2+w.slot;
  const deadline=n=>`第${Math.floor(n/14)+1}周 · ${C.weekDays[Math.floor(n%14/2)]}${n%2?'下午':'上午'}结束前`;
  function init(w,previous,rand){if(window.MEETING_EXPERIENCE?.enabled(w,'assignments')===false||w.config.uncertainty===false)return;const old=previous?.assignments?.items||[],carried=old.filter(open),closed=old.filter(t=>!open(t)).slice(-16);w.assignments={version:1,items:copy([...closed,...carried]),offers:[],focus:null,penalties:{},notes:[]};const offsets=[1+Math.floor(rand(w)*2),4+Math.floor(rand(w)*2)];if(rand(w)<.35)offsets.push(10);const used=new Set();for(let n=0;n<offsets.length;n++){const who=n===0?'boss':n===1?'senior':rand(w)<.5?'boss':'senior',pool=templates.filter(t=>t.who===who&&!used.has(t.id)),e=pool[Math.floor(rand(w)*pool.length)],route=M?.routes(w)?.[Math.floor(rand(w)*2)]||w.config.project;used.add(e.id);w.assignments.offers.push({id:`assignment-${w.number}-${n}-${e.id}`,template:e.id,at:(w.number-1)*14+offsets[n],route,handled:false,giver:window.MEETING_GROUP?.giver(w,who,rand)||null});}}
  const originalInit=init;init=(w,previous,rand)=>{originalInit(w,previous,rand);if(w.assignments&&previous&&!w.config.challenge&&w.seed%5===0)w.assignments.offers=[];};
  const offer=w=>active(w)&&w.status==='life'&&!w.pending?w.assignments.offers.find(o=>!o.handled&&o.at===tick(w)):null;
  function detail(w,o){const t=templates.find(t=>t.id===o.template),p=C.projects.find(p=>p.id===o.route),person=o.giver||window.MEETING_LIFE_SURPRISES.person(w,t.who);return {...t,who:person.rank==='mentor'?'boss':t.who,giverId:person.id||null,route:o.route,person:person.name,topic:P.topic(p.id,t.kind)};}
  function choice(text,effects,action,id){return {text,effects,assignmentAction:action,assignmentId:id,flavor:'具体后果将在选择后揭晓。',traits:{},career:{},work:{progress:0,quality:0},preparationGains:{}};}
  function event(w,raw){if(!active(w)||!raw)return raw;const o=offer(w);if(!o)return raw;const d=detail(w,o);return {id:o.id,day:w.day,slot:w.slot,project:o.route,title:`临时交办 · ${d.person}：${d.title}`,scene:`${d.scene} 这次围绕「${d.topic}」。接下后还要留出实际处理时间。原定「${raw.title}」暂停；本片段用于沟通与交接，不会同时完成原定准备。`,choices:[choice('接下完整范围，确认截止时间，之后安排实际处理。',{energy:-3,stress:5},'accept',o.id),choice('先协商只交一份小范围材料，说明哪些部分暂不承担。',{energy:-2,stress:3},'negotiate',o.id),choice('说明自己已有的截止安排，把这项工作交回或请另找人。',{energy:2,stress:2},'decline',o.id)]};}
  function workEvent(w){if(!active(w)||!w.assignments.focus)return null;const t=w.assignments.items.find(t=>t.id===w.assignments.focus);if(!t||(!open(t)&&!w.pending))return null;return {id:'assignment-work-'+t.id,day:w.day,slot:w.slot,project:t.route,title:`处理临时交办 · ${t.title}`,scene:`${t.person}交来的「${t.topic}」。已处理 ${t.progress}/${t.units} 份，约定${deadline(t.due)}。${t.status==='overdue'?'截止时间已过，补交可以解决工作，逾期记录仍会保留。':''}本片段用于这件事；收拾文件或点击接单不会替代核对。`,choices:[choice('打开来源、逐项核对这一份，记录依据与仍未知的地方。',{energy:-11,notes:5,stress:3},'thorough',t.id),choice('先整理这一份可用线索，明确标出未经核对的部分。',{energy:-5,notes:3,stress:2},'partial',t.id),choice(t.extensionUsed?'交回未完成部分，说明已经做到哪一步。':'说明阻碍，申请再留一个生活片段。',{energy:-2,stress:4},t.extensionUsed?'withdraw':'extend',t.id)]};}
  function dispatch(w,id){if(!active(w)||w.status!=='life'||w.pending||w.campus?.plan||offer(w))return null;const t=w.assignments.items.find(t=>t.id===id);if(!t||!open(t))return null;w.assignments.focus=id;w.campus.plan={day:w.day,slot:w.slot,location:t.kind==='literature'?'library':'lab',original:w.eventId,assignment:id};w.eventId='assignment-work-'+id;return workEvent(w);}
  function resolve(w,e,c,effects,rand){if(!c.assignmentAction)return null;const a=w.assignments,act=c.assignmentAction,now=tick(w);let t=a.items.find(t=>t.id===c.assignmentId),text='';
    if(['accept','negotiate','decline'].includes(act)){const o=a.offers.find(o=>o.id===c.assignmentId);if(!o||o.handled)return null;const d=detail(w,o);o.handled=true;let status='accepted',units=2,scope='full';if(act==='decline'){status='declined';text='你把原有安排说清楚，没有把“收到”写成一个新承诺。对方保留了这次交回的记录。';c.career[d.who]=-1;}else if(a.items.filter(open).length>=3){status='declined';text='现有未完成交办已经占满余量，这次只能交回。没有新增一个做不到的承诺。';c.career[d.who]=-2;}else if(act==='negotiate'){const trust=w.group?.members.find(m=>m.id===d.giverId)?.trust??w.config.relations?.[d.who]??50,support=(w.socialWeek?.events[d.who]?.effects.support||0)+(window.MEETING_GROUP?.support(w)||0),agreed=rand(w)<Math.max(.15,Math.min(.9,.3+trust*.005+support));units=1;scope='small';if(!agreed){status='declined';text='对方这次需要完整范围，没接受小份交付。你没有偷偷接下原来的全部要求。';c.career[d.who]=-2;}else{text='对方同意先接一份小材料。范围已经改小，未承担的部分写进了约定。';c.career[d.who]=1;}}else{text='交办已接下，还没有交付。需要再安排两个生活片段，才能完成约定的核对。';c.traits.promise=1;}
      let due=now+(units===2?4:3);if(now%14<8)due=Math.min(due,(w.number-1)*14+8);t={id:o.id,template:o.template,who:d.who,person:d.person,title:d.title,topic:d.topic,kind:d.kind,giverId:d.giverId,route:o.route,from:w.number,acceptedAt:now,due,status,units,scope,progress:0,quality:0,extensionUsed:false,late:false,source:null};a.items.push(t);
    }else if(t&&open(t)){if(act==='extend'){t.extensionUsed=true;const trust=w.group?.members.find(m=>m.id===t.giverId)?.trust??w.config.relations?.[t.who]??50,support=(w.socialWeek?.events[t.who]?.effects.support||0)+(window.MEETING_GROUP?.support(w)||0),yes=rand(w)<Math.max(.12,Math.min(.88,.25+trust*.005+support));if(yes){t.due=Math.max(t.due,now)+2;t.status='accepted';text='对方同意多留一个生活片段。截止时间更新，已经发生的逾期仍有记录。';}else{text='这次没能延长截止时间，你需要按原约定交付，或明确交回未完成部分。';c.career[t.who]=-2;}}
      else if(act==='withdraw'){t.status='withdrawn';c.career[t.who]=-3;text='你交回了未完成部分，对方能重新安排人手。已做的记录留下，但完整交付没有发生。';}
      else{t.progress++;t.quality+=act==='thorough'?2:1;c.preparationGains={[t.kind]:1};c.traits.study=1;if(t.progress>=t.units){t.status=t.scope==='full'&&t.quality===t.units*2?'delivered':'partial';c.career[t.who]=t.status==='delivered'?(t.late?1:4):1;c.preparationGains={[t.kind]:t.status==='delivered'?2:1};text=t.status==='delivered'?'核对完成，约定范围有了完整交付回执。':'你交了一份范围有限的材料，并标明哪些部分还没有完整核对。';t.source={route:t.route,week:w.number,day:w.day,eventId:e.id,action:c.text,kind:t.kind,level:c.preparationGains[t.kind]};}else text='这一份已经处理，但完整交办还差一份。没有自动完成原定的其他准备。';}}
    if(t.giverId&&c.career[t.who])window.MEETING_GROUP?.trust(w,t.giverId,c.career[t.who]);return {id:t.id,action:act,status:t.status,progress:t.progress,units:t.units,text,late:t.late};
  }
  function settle(w,now=tick(w)){if(!active(w))return;for(const t of w.assignments.items.filter(open)){if(now>t.due&&!t.late){t.status='overdue';t.late=true;w.resources.stress=Math.min(100,w.resources.stress+5);w.assignments.penalties[t.who]=(w.assignments.penalties[t.who]||0)-4;if(t.giverId)window.MEETING_GROUP?.trust(w,t.giverId,-4);w.assignments.notes.push(`${t.person}：${t.title}超过了约定时间，仍需要实际处理。`);}}w.assignments.notes=w.assignments.notes.slice(-5);}
  function advance(w){if(!active(w))return;w.assignments.focus=null;settle(w,tick(w)+(w.status==='meeting'?1:0));}
  function drain(w){if(!active(w))return {};const changes=copy(w.assignments.penalties);w.assignments.penalties={};return changes;}
  function context(w,ctx){if(!active(w))return ctx;const items=w.assignments.items.filter(t=>t.from===w.number||open(t)),late=items.filter(t=>t.late);ctx.assignments={items:copy(items),notes:copy(w.assignments.notes)};ctx.debt=Math.min(6,ctx.debt+Math.min(2,late.filter(open).length));return ctx;}
  function scheduled(s){const items=s.weekContext?.assignments?.items;if(!s.live||s.wrapUp||s.assignmentAsked||s.choicesMade<5||!items?.length)return null;return {id:'assignment-question',phase:6};}
  function question(s){if(s.eventId!=='assignment-question')return null;const items=s.weekContext.assignments.items,t=items.find(t=>t.status==='overdue')||items.find(t=>t.status==='accepted')||items.find(t=>t.status==='delivered')||items.at(-1),full=t.status==='delivered',status=statuses[t.status];return {id:'assignment-question',phase:6,who:t.who,title:`“临时交给你的「${t.title}」，现在到了哪一步？”`,scene:`第${t.from}周，${t.person}实际交来的事是「${t.topic}」。记录为：${status}。${t.late?'曾超过约定时间；补交不会把这段经历抹掉。':''}`,quote:'“接下、交部分、核对完，要分开说。”',assignmentId:t.id,choices:[{text:'拿出完整交付的核对记录，讲清已完成范围和依据。',approach:'detail',effects:{evidence:5,patience:2,time:-3},flags:{rigor:1},prepared:{kind:t.kind,minimum:2,level:full?2:0,available:full,source:copy(t.source),reason:full?null:'这项交办没有完整交付回执；一般资料和别的任务不能代替它。'},result:'交付有了可核对的来路。',flavor:'你拿出的是这项交办实际留下的记录。'}, {text:'按实际记录说明进度、范围或无法接下的原因，不把接单当作完成。',approach:'cautious',effects:{evidence:full?0:-3,patience:1,time:-2},flags:{honest:1,...(open(t)?{debt:1}:{})},result:'当前状态被如实说明。',flavor:`真实状态是${status}。后续是否完成，仍由之后的实际行动决定。`}, {text:'先说已经基本做完，试着把剩下的部分留到会后。',approach:'direct',effects:{mood:3,patience:-5,time:-2},flags:{chaos:1,debt:1},risk:{chance:full?.15:.8,effects:{evidence:-12,patience:-9},flavor:'对方要求打开具体交付，口头的“基本做完”没能代替记录。'},result:'你扩大了对当前进展的说法。',flavor:'这句话没有改变交办的真实状态。'}]};}
  function afterAnswer(s,e,record){if(e.id==='assignment-question'){s.assignmentAsked=true;record.assignment={id:e.assignmentId,actual:s.weekContext.assignments.items.find(t=>t.id===e.assignmentId)?.status};}}
  function ending(s){const items=s.weekContext?.assignments?.items;if(!items||s.wrapUp!==2)return null;if(items.filter(t=>t.late&&open(t)).length>=2&&s.flags.chaos>=2)return 'assignment-overflow';if(items.filter(t=>t.status==='delivered'&&!t.late).length>=2&&s.flags.rigor>=2)return 'assignment-reliable';if(items.filter(t=>['partial','declined'].includes(t.status)).length>=2&&s.flags.honest>=3)return 'assignment-boundary';if(items.filter(t=>open(t)).length>=2&&s.flags.chaos>=4)return 'assignment-inbox';return null;}
  for(const [id,kind,icon,title,desc,hint] of [['assignment-overflow','failure','📨','收件箱毕业了，交付没有','你接下的工作超过了能安排的时间。两项逾期没有交付，组会要求先重新排清责任。','两项交办逾期且仍未完成，多次硬答。'],['assignment-reliable','open','🧾','可靠不等于无所不能','两份交办按约定完成了核对。你用真实回执换来了信任，也看清了自己的时间有多少。','本周至少两项完整准时交付，保持严谨。'],['assignment-boundary','open','🌿','这周学会了把范围说清','小份交付和明确交回让大家能继续安排工作。你留下了余量，没有用空承诺填满周历。','两次协商小份或说明无法接下，并诚实回应。'],['assignment-inbox','funny','📥','自动回复：收到，收到，收到','所有人都知道你回消息很快。现在你需要找出：哪一条收到，曾真正变成交付。','多项未完成交办与多次整活。']])C.endings.push({id,kind,icon,title,subtitle:'事情有人交来，时间仍只有一周。',desc,hint});
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function decorate(w,render,save){if(!active(w))return;const panel=document.createElement('section');panel.className='assignment-board';const all=w.assignments.items,items=all.filter(t=>t.from===w.number||open(t)),locked=w.pending||w.campus?.plan||offer(w)||w.status!=='life';panel.innerHTML=`<div class="section-line"><h3>📨 临时交办 · 接下不等于交付</h3><span>${items.filter(open).length} 件待处理</span></div><p>沟通、处理和准备共用生活片段。可以协商范围、争取延期，也可以说明无法接下；只有真实处理才产生交付回执。</p>${items.length?`<div class="assignment-list">${items.map(t=>`<article class="${t.status}"><small>${esc(t.person)} · ${esc(C.projects.find(p=>p.id===t.route).name)}</small><h4>${esc(t.title)}</h4><p>${esc(statuses[t.status])}${t.late?' · 有逾期记录':''} · 已处理 ${t.progress}/${t.units} 份</p><small>${esc(deadline(t.due))} · ${t.scope==='small'?'协商的小范围':'完整范围'}</small>${open(t)?`<button class="secondary" data-assignment="${esc(t.id)}" ${locked?'disabled':''}>用这段时间处理这件事 →</button>`:''}</article>`).join('')}</div>`:'<p class="muted">目前没有临时交办。消息可能在准备途中出现。</p>'}${w.assignments.notes.map(n=>`<p class="assignment-notice">${esc(n)}</p>`).join('')}`;document.querySelector('.week-board')?.before(panel);panel.querySelectorAll('[data-assignment]').forEach(b=>b.onclick=()=>{if(dispatch(w,b.dataset.assignment)){save();render();document.querySelector('.life-scene')?.scrollIntoView({block:'start',behavior:'smooth'});}else window.MEETING_APP.toast(window.MEETING_WEEK.actionReason(w)||'当前条件还不满足，请查看此项的进度和开放时间。');});if(w.pending?.assignment){const el=document.createElement('p');el.className='assignment-notice';el.textContent=`交办状态：${statuses[w.pending.assignment.status]} · 已处理 ${w.pending.assignment.progress}/${w.pending.assignment.units} 份。`;document.querySelector('.life-effects')?.after(el);}}
  function valid(w){if(!active(w))return true;const a=w.assignments;return a.version===1&&Array.isArray(a.items)&&a.items.length<=40&&new Set(a.items.map(t=>t.id)).size===a.items.length&&a.items.every(t=>templates.some(e=>e.id===t.template)&&Object.hasOwn(statuses,t.status)&&['boss','senior'].includes(t.who)&&Number.isInteger(t.due)&&[1,2].includes(t.units)&&Number.isInteger(t.progress)&&t.progress>=0&&t.progress<=t.units&&Number.isInteger(t.quality)&&t.quality>=0&&t.quality<=t.progress*2&&C.projects.some(p=>p.id===t.route))&&Array.isArray(a.offers)&&a.offers.every(o=>templates.some(t=>t.id===o.template)&&Number.isInteger(o.at)&&typeof o.handled==='boolean')&&(!a.focus||a.items.some(t=>t.id===a.focus&&(open(t)||!!w.pending)));}
  return {templates,statuses,active,open,tick,deadline,init,offer,event,workEvent,dispatch,resolve,advance,settle,drain,context,scheduled,question,afterAnswer,ending,decorate,valid};
})();
