(() => {
  const C=window.MEETING_CONTENT;
  C.locations=[
    {id:'library',icon:'📚',name:'图书馆',desc:'攒资料、找反例、认识统计老师'},
    {id:'lab',icon:'🔬',name:'研究工位',desc:'推进课题，取舍速度与质量'},
    {id:'cafe',icon:'🍜',name:'食堂与茶水间',desc:'恢复状态、结交同门、交换消息'},
    {id:'mentor',icon:'🎤',name:'空会议室',desc:'预演、整理备份、和导师聊一聊'},
    {id:'home',icon:'🛋️',name:'宿舍与操场',desc:'认真休息，也可以临时赶工'},
    {id:'wander',icon:'🐈',name:'校园闲逛',desc:'偶遇、奇思妙想与师门名场面'}
  ];
  C.workCards=[
    ['index','📑','文献索引','rigor',{evidence:5},'资料不多，但出处齐全。'],
    ['counter','🔍','一个反例','honest',{evidence:3,patience:4},'它拆掉一部分故事，也保住真实的问题。'],
    ['raw','🗒️','原始记录','rigor',{evidence:6},'你确实记得这条线从哪里来。'],
    ['negative','📉','诚实的平线','honest',{patience:6},'没有变化，也可以认真讲。'],
    ['result','📊','能解释的图','rigor',{evidence:4,patience:2},'这次你知道每根线是什么意思。'],
    ['note','🤝','师兄的便签','social',{mood:5,patience:3},'背面写着：实在不行先吃饭。'],
    ['team','🧩','合作分工表','social',{evidence:3,patience:4},'终于不是每一个问题都由你负责。'],
    ['backup','💾','真的能打开的备份','rigor',{evidence:4,time:1},'文件名只有一个“最终”。'],
    ['summary','🎯','三句话摘要','honest',{patience:4,time:1},'背景讲完之后，还记得研究问题。'],
    ['sleep','🌙','睡眠凭证','rest',{mood:9},'现场验真：你没有打哈欠。'],
    ['cat','🐾','猫爪签名','comedy',{mood:6,patience:2},'猫暂时同意你使用它的名义。'],
    ['meme','🫠','精准的梗图','comedy',{mood:7,evidence:-2},'图很准确，准确地描述了你的心情。']
  ].map(([id,icon,name,tag,effects,desc])=>({id,icon,name,tag,effects,desc}));
  C.researchStyles=[{id:'steady',name:'扎实推进',desc:'工位行动质量额外+4，进度少2。'}, {id:'sprint',name:'先做出一版',desc:'工位行动进度额外+4，质量少3。'}, {id:'team',name:'合作课题',desc:'食堂交流额外推进3，合作牌两张时底气+3。'}];
  C.weekTwists=[
    {id:'quiet',icon:'🍃',name:'难得安静的一周',desc:'没有额外干扰。正好试试新的安排。'},
    {id:'deadline',icon:'⏳',name:'截止日期提前了',desc:'工位推进额外+2；周五时间少3分钟。',meeting:{time:-3},work:2},
    {id:'rain',icon:'☔',name:'连下三天的雨',desc:'宿舍行动精力额外+4；校园闲逛精力少4。',byLocation:{home:{energy:4},wander:{energy:-4}}},
    {id:'festival',icon:'🥟',name:'食堂美食节',desc:'食堂行动精力额外+5；周五入场心态+3。',byLocation:{cafe:{energy:5}},meeting:{mood:3}},
    {id:'conference',icon:'🧳',name:'导师刚从会议回来',desc:'导师问题特别多：入场耐心少5；图书馆行动资料额外+4。',meeting:{patience:-5},byLocation:{library:{notes:4}}},
    {id:'network',icon:'📶',name:'校园网正在维护',desc:'工位和图书馆行动资料少3；空会议室行动幻灯片额外+4。',byLocation:{lab:{notes:-3},library:{notes:-3},mentor:{slides:4}}},
    {id:'open',icon:'🏛️',name:'校园开放日',desc:'食堂、闲逛行动压力额外-3；入场多1分钟。',byLocation:{cafe:{stress:-3},wander:{stress:-3}},meeting:{time:1}},
    {id:'printer',icon:'🖨️',name:'打印机集体罢工',desc:'空会议室行动幻灯片少3；带备份牌入场额外底气+4。',byLocation:{mentor:{slides:-3}},backupBonus:4}
  ];
  C.challenges=[
    {id:'steady',icon:'🌿',name:'稳稳下班',desc:'这周不熬夜，组会不翻车，周日精力至少50。'},
    {id:'rigor',icon:'🔎',name:'问题侦探',desc:'组会认真回应至少4次，散会底气至少75。'},
    {id:'honest',icon:'🪑',name:'给未知留一把椅子',desc:'组会诚实回应至少4次，导师耐心至少40。'},
    {id:'comedy',icon:'🎭',name:'欢乐也要散得了会',desc:'组会整活至少4次，同时避免翻车结局。'},
    {id:'team',icon:'🤝',name:'今天有人和我一起',desc:'本周去食堂交流至少2次，组会求助至少2次。'},
    {id:'repair',icon:'🧹',name:'不把坑全留到下周',desc:'处理至少1件遗留任务，散会解释债不超过1。'},
    {id:'research',icon:'📈',name:'课题向前一步',desc:'本周课题进度增加至少20，周日质量至少35。'},
    {id:'recover',icon:'🌅',name:'从上周的翻车站起来',desc:'上周组会失败，这周避免翻车，周日压力低于50。'}
  ];
  C.talents=[
    ['annotation','📖','边读边记','图书馆行动资料额外+3。'],['focus','🔬','小步实验','工位行动课题进度额外+2。'],
    ['careful','📏','先检查再下结论','工位行动课题质量额外+3。'],['network','🤝','饭桌上的同盟','食堂行动压力额外-4。'],
    ['rehearsal','🎤','空椅子也能听懂','空会议室行动幻灯片额外+4。'],['sleep','🌙','按时关机','宿舍行动精力额外+5。'],
    ['backup','💾','备份强迫症','带备份牌入场额外底气+4。'],['boundary','🛑','有限的承诺','每场额外解释债少1笔。'],
    ['patient','🍵','先把话说慢','周五入场导师耐心+3。'],['wander','💡','认真走神','闲逛行动资料额外+4。'],
    ['connector','🧩','让大家坐在同一边','合作牌两张的组合额外耐心+3。'],['comedian','🎭','笑点之后还有内容','喜剧牌两张的组合额外底气+3。']
  ].map(([id,icon,name,desc])=>({id,icon,name,desc}));
  const pick=(text,flavor,effects,traits={},work={},card=null,career={},risk=null)=>({text,flavor,effects,traits,work,card,career,risk});
  const rows=[
    ['library','书架上的反对意见','你找到一篇不同意你目前解释的文章。它没有礼貌，但很有用。',[
      pick('把反对理由读完，记下边界','这条反例没有替你结束课题，帮你缩小了问题。',{notes:14,energy:-8},{study:1,negative:1},{quality:5},'counter'),
      pick('只读和我问题有关的部分','你保留了一个能找到原文的索引。',{notes:9,energy:-4},{study:1},{progress:3},'index'),
      pick('先截图“这个问题尚未解决”','你终于找到一句能解释自己进度的原话。',{notes:3,stress:-3},{chaos:1},{},'meme')]],
    ['library','笔记本里还有别人的字','统计老师在你遗落的笔记本上写了一个问号。',[
      pick('主动请教那个问号','老师说问题比公式更需要先讲清楚。',{notes:12,energy:-6},{study:1,collaboration:1},{quality:6},'index',{stats:3}),
      pick('先用自己的话回答它','你把能回答的和不能回答的分成了两列。',{notes:8,stress:-4},{negative:1},{quality:4},'counter'),
      pick('给问号也画一个问号','这是一次双方都很有参与感的学术交流。',{energy:3,notes:2},{chaos:1},{},'meme')]],
    ['library','引用管理器发起内战','同一篇文章有四个名字。今天它准备四次进入你的参考文献。',[
      pick('统一记录，检查原文','版本少了，能用的资料多了。',{notes:12,energy:-7},{folder:1,backup:1},{quality:4},'index'),
      pick('先整理本周会用到的部分','你的范围管理比文献管理器成熟一点。',{notes:8,slides:5},{study:1},{progress:3},'summary'),
      pick('让四个版本进行民主投票','投票结果是四个版本都想当最新版。',{stress:-5,notes:-2},{chaos:1,folder:1},{},'meme')]],
    ['library','阅读桌只剩最后一个插座','对面同学也只剩最后百分之八的电。',[
      pick('轮流充电，交换资料','两个人的电脑都没关机，问题也开始互通。',{notes:10,energy:-5},{collaboration:1},{quality:3},'team',{senior:2}),
      pick('关电脑，手写问题框','你发现问题其实不需要充电。',{notes:9,stress:-3},{study:1},{progress:4},'summary'),
      pick('赌电脑撑得到我读完','阅读很专注，自动关机也很专注。',{notes:12,energy:-4},{night:1},{quality:2},'index',{}, {chance:.3,effects:{notes:-10},flavor:'电脑提前熄火，没保存的那段笔记得重新找。'})]],
    ['lab','课题卡在一个小地方','你知道哪里不对，还不知道它为什么不对。',[
      pick('做一次最小范围的检查','一小步留下了可追踪的原始记录。',{notes:6,energy:-12,stress:3},{study:1},{progress:11,quality:6},'raw'),
      pick('先做出粗糙的一版','你终于有东西可以讨论，也有细节要回来核对。',{slides:10,energy:-9,stress:4},{deadline:1},{progress:16,quality:-5},'result'),
      pick('把问题拆开，请同门一起看','进度没那么快，但这个坑不再只有你认识。',{notes:7,energy:-5,stress:-5},{collaboration:1},{progress:7,quality:5},'team',{senior:2})]],
    ['lab','那张图还是一条平线','平线本人认为它已经非常努力了。',[
      pick('核对记录，保留这次没有变化','你得到了一个可靠的“暂时没有”。',{notes:8,energy:-10},{negative:1,study:1},{progress:9,quality:8},'negative'),
      pick('换一个更小的问题继续做','假设小了一圈，研究重新动了起来。',{notes:7,energy:-8},{pivot:1},{progress:12,quality:3},'raw'),
      pick('把平线命名为极简主义成果','名字有了风格，结果仍然需要解释。',{slides:7,stress:-6},{chaos:1},{progress:3,quality:-3},'meme')]],
    ['lab','临时设备空出两个小时','预约表突然让出了一块空白，你的计划却没有带着它一起出现。',[
      pick('按已有计划做一小段','机会被你用在了一个有范围的问题上。',{notes:8,energy:-12},{study:1},{progress:13,quality:5},'raw'),
      pick('一口气把能做的全塞进去','你跑得很快，记录差点没跟上。',{slides:8,energy:-16,stress:7},{deadline:1},{progress:20,quality:-7},'result',{}, {chance:.25,effects:{energy:-8,notes:-7},flavor:'临时安排出了差错，最后半小时用来补记录。'}),
      pick('把机会让给更着急的同门','对方记住了这次帮忙，答应下次给你搭把手。',{energy:5,stress:-5},{collaboration:1},{progress:5,quality:2},'note',{senior:5})]],
    ['lab','桌上出现一份旧计划','这是两周前的你，给现在的你留下的豪言壮语。',[
      pick('按现有证据缩小计划','你删掉两项任务，真正的进度多了一点。',{notes:6,stress:-6,energy:-7},{pivot:1},{progress:10,quality:6},'summary',{taskDone:1,debt:-1}),
      pick('先完成最容易的一项','一件事落地，和十件事“即将完成”不同。',{slides:9,energy:-8},{study:1},{progress:14,quality:2},'result',{taskDone:1}),
      pick('在旧计划上补写“未来可期”','过去的你和未来的你，暂时没有达成和解。',{energy:4,stress:6},{promise:1},{progress:2},'meme')]],
    ['cafe','饭桌上的交换条件','师兄想请你看一段文字，也愿意帮你看一张图。',[
      pick('约好各看一小段，不互相加码','合作有了边界，也有了第二个视角。',{notes:8,energy:6,stress:-7},{collaboration:1,meal:1},{progress:5,quality:4},'team',{senior:4}),
      pick('今天先正常吃饭','没有产出的人也配吃一顿完整的饭。',{energy:15,stress:-9},{rest:1,meal:1},{},'sleep'),
      pick('承包整桌人的问题','你成为了群聊里最快回复“我来”的人。',{notes:4,stress:8},{promise:2,collaboration:1},{progress:8,quality:-3},'note',{senior:3})]],
    ['cafe','师门群在投票吃什么','投票从点菜开始，已经发展到了哲学层面。',[
      pick('把选项缩成两家，组织饭局','你展示了一种组会里也能用的协调能力。',{energy:10,stress:-5},{meal:1,collaboration:1},{progress:3},'note',{senior:3}),
      pick('和同门边吃边讲今天的卡点','一碗面之后，问题能用两句话表达了。',{notes:9,energy:8,stress:-5},{meal:1,study:1},{quality:4},'summary'),
      pick('宣布由食堂的猫担任终审','猫选了鱼，你们也暂时选了鱼。',{energy:8,stress:-7},{meal:1,chaos:1},{},'cat')]],
    ['cafe','陌生同学也在等散会','你们不是同一学科，叹气的时间却完全同步。',[
      pick('互相解释研究问题','外行的一句追问，帮你找到了表达里的空白。',{notes:8,energy:6},{collaboration:1},{progress:5,quality:4},'team',{senior:2}),
      pick('交换一个真正能做到的小建议','你们约好下次再聊，今天不用解决全部问题。',{energy:10,stress:-7},{rest:1},{quality:2},'note'),
      pick('成立临时散会互助协会','协会没有会费，有一张共同的梗图。',{energy:9,stress:-5},{meme:1,chaos:1},{},'meme')]],
    ['cafe','师兄说下周要交接工位','他的桌面看起来像十个课题共同搬家。',[
      pick('帮忙整理，也请教文件怎么留','你们把几份真正有用的经验写成了清单。',{notes:10,energy:-3,stress:-4},{collaboration:1,backup:1},{quality:4},'backup',{senior:4}),
      pick('先约一个散会后的饭点','你把一句“以后常联系”变成了具体的日历。',{energy:12,stress:-6},{meal:1,rest:1},{},'note',{senior:2}),
      pick('申请继承他的散会名言','你接过的不是全部工作，是一点对生活的解释权。',{energy:8,stress:-5},{chaos:1,meme:1},{},'meme')]],
    ['mentor','面对十把空椅子的预演','空椅子不提问，但你已经能听见老师的声音。',[
      pick('计时讲一遍，再删掉绕远的页','空椅子一致同意你终于讲清了开头。',{slides:14,notes:4,energy:-7},{study:1},{quality:4},'summary'),
      pick('把最怕被问的部分做成备份','准备不是保证全会，是知道卡住时先拿出什么。',{slides:11,notes:7,energy:-6},{backup:1},{quality:3},'backup'),
      pick('给椅子安排三个冷笑话','椅子没反应，说明预演环境非常接近真实组会。',{slides:5,stress:-8},{meme:1,chaos:1},{},'meme')]],
    ['mentor','老师提前问了一个问题','“这周你最想让大家帮你看什么？”',[
      pick('说出一个具体的问题','导师给出的任务单，第一次只有一项。',{notes:9,slides:7,stress:-4},{study:1},{quality:5},'summary',{boss:4}),
      pick('讲清楚已经知道和不知道的','未知被允许留下，不必装成结果。',{slides:8,stress:-6},{negative:1},{quality:4},'counter',{boss:3}),
      pick('先说这周一定会有大进展','老师记下了这句话，日历也记下了。',{slides:3,stress:8},{promise:2},{progress:5,quality:-2},'meme',{boss:1})]],
    ['mentor','投影仪认不出你的电脑','它今天只愿意显示一个写着“无信号”的成果。',[
      pick('检查转接和离线备份','文件没有再成为一次新的研究对象。',{slides:12,energy:-7},{backup:2},{quality:2},'backup'),
      pick('练习不用屏幕讲清问题','少了图，你发现自己的重点藏在哪里。',{notes:8,slides:6},{study:1},{quality:4},'summary'),
      pick('即兴讲解“无信号”的深层含义','你的临场表演获得了投影仪的持续支持。',{energy:4,stress:-7},{chaos:1},{},'meme')]],
    ['mentor','最后一页还叫谢谢','师兄说，也许可以把它改成今天真正想讨论的事。',[
      pick('列出一个判断、一个局限、一个请求','最后一页终于承担了结束之外的工作。',{slides:13,notes:6,energy:-6},{study:1,negative:1},{quality:5},'summary'),
      pick('先把本周欠的说明补齐','下周的你少收到了一份不明附件。',{slides:10,stress:-5},{backup:1},{progress:4},'backup',{taskDone:1,debt:-1}),
      pick('改成“谢谢，食堂还开着”','你向最后一页赋予了生活方向。',{slides:4,energy:4},{meal:1,chaos:1},{},'meme')]],
    ['home','今晚的电脑可以提前关机','课题不会因为今晚少一小时就忘记你的名字。',[
      pick('按时休息，留给明天一个人','你给后面的讨论留下了清醒的身体。',{energy:22,stress:-13},{rest:2},{},'sleep'),
      pick('只整理半小时，然后收工','一点记录和一点休息都保住了。',{energy:12,notes:6,stress:-7},{rest:1,backup:1},{quality:2},'backup'),
      pick('通宵再做一版','你打开了新版本，也透支了一段新睡眠。',{energy:-22,slides:16,stress:12},{night:2,deadline:1},{progress:12,quality:-4},'result')]],
    ['home','操场上的一圈没有截止日期','你可以跑，也可以走。这里没有人要求你交一张图。',[
      pick('慢慢走一圈，吃顿正常的饭','这不是拖延，是恢复一点选择的能力。',{energy:18,stress:-15},{rest:2,meal:1},{},'sleep'),
      pick('和同门边走边聊一个问题','问题小了一点，步数多了一点。',{energy:12,notes:5,stress:-8},{rest:1,collaboration:1},{progress:3},'note',{senior:2}),
      pick('把跑步轨迹也写成研究路线','它至少证明了你今天没有原地不动。',{energy:5,slides:5,stress:-6},{chaos:1},{progress:2},'meme')]],
    ['home','同门邀你看一部电影','电影片长两小时，导师口中的最后一个问题则很难估计。',[
      pick('看完电影，今晚不补工作','你记住了剧情，也暂时忘记了一个版本号。',{energy:19,stress:-13},{rest:2},{},'sleep'),
      pick('看完再写三句话备忘','明天的你可以找回今天停下的位置。',{energy:12,notes:6,stress:-7},{rest:1},{quality:2},'summary'),
      pick('讨论电影里那个很不严谨的图','大家建议下次带你看没有图的电影。',{energy:9,notes:4},{chaos:1,study:1},{quality:1},'counter')]],
    ['home','宿舍桌上的洗杯子任务','你终于发现杯子也有一种跨周研究计划。',[
      pick('收拾环境，顺手划掉一件待办','桌面和计划都空出了一小块地方。',{energy:12,stress:-10},{rest:1},{progress:3},'sleep',{taskDone:1,debt:-1}),
      pick('整理文件，再给自己泡一杯茶','备份存好了，今晚不需要继续惊心动魄。',{energy:10,slides:5,stress:-8},{backup:1,rest:1},{quality:3},'backup'),
      pick('宣布杯子正在进行长期培养','你为生活添加了一个非常不必要的项目名称。',{energy:7,stress:-5},{chaos:1},{},'meme')]],
    ['wander','实验室的猫巡查校园','它没有考勤卡，却比你更熟悉所有下班路线。',[
      pick('跟着走一小段，把脑子放松','它没有给研究意见，给了你一段安静时间。',{energy:12,stress:-9},{rest:1},{},'cat'),
      pick('把刚想到的问题记在手机里','走神没有直接产出答案，留下了一个可检查的想法。',{notes:8,energy:7},{pivot:1},{progress:4,quality:3},'counter'),
      pick('申请猫担任下一次联合主持','猫没有拒绝，也没有答应准时出席。',{energy:8,stress:-6},{chaos:1,meme:1},{},'cat')]],
    ['wander','校园海报邀请你跨界听讲','你认识标题里的每个字，合在一起却不太认识。',[
      pick('带着一个具体疑问去听','你带回一个新角度，没有把课题堆成十个方向。',{notes:10,energy:-4},{pivot:1,study:1},{progress:5,quality:4},'index'),
      pick('认识一位别的学科的同学','以后解释研究时，终于多了一个诚实的外行听众。',{notes:6,energy:6},{collaboration:1},{progress:4},'team',{senior:2}),
      pick('先认真研究茶歇时间','这也是一种对议程结构的细致阅读。',{energy:13,stress:-5},{meal:1,chaos:1},{},'meme')]],
    ['wander','校园广播念出了你的课题关键词','接下来的词是失物招领，气氛一下具体了。',[
      pick('顺便找回丢掉的笔记本','一份原始记录从生活里回到了研究里。',{notes:12,energy:-3},{backup:1},{quality:4},'raw'),
      pick('把这种巧合写进自己的周记','叙述没有改变结果，改变了你看待这一天的方式。',{energy:10,stress:-8},{rest:1},{progress:2},'summary'),
      pick('把广播当成课题宣传首发','课题的知名度暂时只覆盖了你和广播员。',{energy:7,stress:-4},{chaos:1,meme:1},{},'meme')]],
    ['wander','路边长椅已经坐了一位老师','你们共同面对一个非常普通的下午。',[
      pick('用两句话解释今天的进展','老师没有追问全部细节，问了一个好问题。',{notes:9,energy:3},{study:1},{progress:5,quality:3},'summary',{boss:2}),
      pick('聊聊组会以外的生活','你第一次发现老师也需要从会议里出来。',{energy:13,stress:-8},{rest:1,collaboration:1},{},'note',{boss:3}),
      pick('请教怎么优雅地宣布散会','老师建议你先学会不把每个回答都展开。',{slides:4,stress:-6},{chaos:1},{},'meme')]]
  ];
  C.campusEvents=rows.map(([location,title,scene,choices],i)=>({id:'campus-'+i,location,title,scene,choices}));
  const stories={
    boss:[['导师也有一张待办清单','周老师把两页计划递给你：“你先选一件真正能做到的。”'],['老师开始问你怎么判断','你以为他要检查进度，今天他问的是你为什么认为这条路值得走。'],['一项有范围的托付','周老师想让你帮忙带一次讨论。他说，先把时间和边界约清楚。']],
    stats:[['林老师的问号','“先别把方法名写这么大。你真正想区分什么？”'],['一条平线也值得留下','林老师看完记录，没有替你添加一个漂亮的差异。'],['把方法教给另一个同学','老师邀请你带着原始记录讲一次小讨论，先从它做不到什么讲起。']],
    senior:[['师兄把自己的旧便签给了你','便签上有三行提醒，最后一行是“别忘了吃饭”。'],['这次轮到你救他一下','师兄在组会前发现一个文件打不开。以前总是他替你补上一句。'],['离开工位，留下联系方式','师兄要搬到另一个地方了。他说，帮助不会因为工位空出来就自动结束。']]
  };
  for(const [person,chapters] of Object.entries(stories))chapters.forEach(([title,scene],chapter)=>{
    const location={boss:'mentor',stats:'library',senior:'cafe'}[person];
    C.campusEvents.push({id:`story-${person}-${chapter}`,location,story:{person,chapter,trust:[45,60,75][chapter]},title,scene,choices:[
      {...pick('把问题拆小，约清楚能做的部分','你们谈定了一个有范围的下一步。关系是在这类具体的事情里变近的。',{notes:10,stress:-6},{study:1,collaboration:1},{progress:5,quality:5},person==='stats'?'counter':person==='senior'?'note':'summary',{[person]:5}),decision:'boundary'},
      {...pick('认真合作，也坦白自己卡住的地方','对方没有要求你立刻变成无所不能的人。你也没有把帮助当成理所当然。',{notes:7,energy:5,stress:-7},{collaboration:1},{progress:7,quality:3},'team',{[person]:6}),decision:'together'},
      {...pick('先贡献一句师门新名言','你们笑完后仍然列下了一件具体的事。相处中可以有一点幽默。',{energy:8,stress:-5},{chaos:1,meme:1},{progress:3},'meme',{[person]:3}),decision:'humor'}]});
  });
  const endings=[
    ['fragile','failure','🏚️','进度条先毕业了，课题还没','“完成”两个字跑得比证据快。','你带来一份很快做出的版本，也带来了还没检查清楚的基础。导师把下一步改成核对，而不是再加一张图。周末可以慢一点，把已经跑出去的进度接回来。','课题推进很快，质量却很低。'],
    ['backlog','failure','📥','待办清单代替你完成了汇报','每一项都叫“下周”，没有一项认识下周。','老师把几周留下的任务排在一起。它们终于在屏幕上团聚，完成它们的人却还没团聚出足够的时间。你先划出最小的一项，决定不再把整周都抵押给未来。','积累至少三件未完成事项，又带着大量解释债散会。'],
    ['appendix-time','failure','📎','附录打开了第二场组会','主会场散了，备用页还想继续。','你准备了很多可靠的材料，但没有给它们安排优先顺序。最后一页赶上了截止时间，真正的结论还挤在后面。周末先练习只讲最必要的部分。','带多张证据牌，最后耗尽了组会时间。'],
    ['burnout','failure','🪫','课题在线，研究者离线','文件都在，持有文件的人正在重启。','这周被你塞进了很多工作，没有塞进足够的恢复。一次追问让剩余心态见了底。师兄没有继续递咖啡，建议先把晚上的计划减掉一半。','精力很低、压力很高，并在组会耗尽心态。'],
    ['library','funny','🪑','图书馆把你写进了座位表','你和那个插座拥有共同的通讯地址。','一周里你反复去找资料，今天的回应也很有根据。导师建议继续保持，但别真的把图书馆登记成住所。你决定带走笔记，暂时把座位留给其他人。','多次去图书馆，组会认真接住很多问题。'],
    ['cafe','funny','🍜','你成为了学术饭局召集人','你的合作网络，有明显的饭点结构。','大家终于在一场安排得很顺的讨论后吃上饭。你不仅记得谁研究什么，还记得谁不吃香菜。导师给你的下一项工作是主持，师兄给你的下一项工作是选餐厅。','多次去食堂交流，又在组会上展示社交能力。'],
    ['cat','funny','🐾','猫爪通过了同行评议','共同作者拒绝回复修改意见。','你把猫爪签名带到了讲台上，现场笑过之后终于同意散会。猫对这场汇报的评价是继续睡觉。你保留了名场面，也记住图表仍然需要人类解释。','带猫爪签名，并在组会上贡献几次整活。'],
    ['meme','funny','🏆','年度师门喜剧提名','奖品是一张下周汇报排班表。','你把日常积攒的笑料和两张喜剧牌一起带上台。大家笑得很认真，导师提醒下周的你也要认真。你拿到一项荣誉，和一份照常存在的任务。','两张喜剧牌形成组合，组会上也持续整活。'],
    ['appendix','funny','📚','附录获得了独立答辩席位','它想介绍自己的研究背景。','材料互相支撑得很好，唯一的问题是它们都很想发言。老师允许你保留它们作为后盾，建议下周让正片先讲完。师兄说附录可以坐旁听席，不必每次上台。','三张证据牌入场，认真回应并保住导师耐心。'],
    ['quality','funny','📏','你用很多种方式证明了“再确认一下”','检查已经非常成熟，课题还在起跑线上。','你熟悉每一个可能出错的地方，终于决定选一个很小的地方先往前做。导师认可你的谨慎，也提醒你给探索留一个有限的空间。周末的计划缩成一件能执行的事。','课题质量很高、进度较低，组会上愿意承认局限。'],
    ['sleep','funny','😴','你成了全组睡眠代言人','这是一次眼神清醒的学术发言。','你没有把睡眠全抵押给周五，现场也没有把自己全耗完。师兄询问你的作息秘诀，你说其实没什么秘诀，只是按时关过几次电脑。大家决定先从今晚试一次。','多次主动去休息，散会时心态仍然很稳。'],
    ['mentor','open','🍵','老师允许你把生活留在任务外','你们谈定了进度，也谈定了范围。','你和导师一路谈过计划、判断与托付。今天你终于能把未知说清，把承诺说小。下一周仍然有工作，但它不必占据日历上的全部空白。','完成导师支线，组会上诚实解释或清楚协调。'],
    ['stats','open','🔍','问号终于成了你的合作者','它没有消失，开始替你指路。','你从被方法名吓住，走到了能解释它的用途与边界。林老师没有帮你消除所有疑问。你们保留了几个真正值得继续检查的问题，足够下周往前走一步。','完成统计老师支线，认真回应并保住底气。'],
    ['senior','open','🔘','师兄把散会按钮交给了你','这次你也能为别人接住一句话。','从收到旧便签到替对方救场，再到工位外继续联系，你们的合作多了一个方向。师兄说下周轮到你帮新同学一点忙。你接过按钮，先试着为今天按下暂停。','完成师兄支线，在组会上多次求助与合作。'],
    ['work','open','📝','第一份小作品走出了会议室','它没有回答全部问题，已经有了自己的位置。','几周里你把问题讲清，把记录做稳，再把结果变成可讨论的作品。今天的阶段评审通过了。你给自己留下一份成果，也留下一件以后可以继续研究的事。','在第三阶段带着完整进度、可靠质量与足够底气完成组会。'],
    ['team','open','🧩','合作里终于写清了分工','有人一起做，也有人知道什么时候停。','饭桌上的交换变成了有范围的协作，分工表也真的走上了讲台。你没有把合作当成让别人承担全部问题。下一周，你们知道各自先做哪一件。','合作课题带两张合作牌，组会上愿意求助并讲得清楚。'],
    ['pivot','open','🛤️','小问题找到了自己的入口','计划少了几行，方向多了一点确定。','你没有强行让一个大故事立刻完成，而是把已经能检查的部分留下。导师接受先走小路的计划。结果仍然开放着，你终于知道该从哪里再试一次。','课题还在起步，质量已经提升，组会上诚实谈局限。'],
    ['recover','open','🌅','从上周的翻车里借到一条路','失败没有替下一周写完结局。','上周你没能顺利散会。这周你换了安排，把请求和承诺拆得更小。今天你带着足够清楚的东西讲完，不需要假装上周没发生过。周末可以继续，也可以先休息。','上周失败，这周诚实汇报并恢复足够底气。'],
    ['balanced','funny','🎒','你的手牌刚刚凑成一个人','会查资料，会开口，也记得休息。','三种不同的准备在现场接住了不同的问题。你没把自己练成全能模板，只是留下了几条备用的路。师兄觉得这套配置不错，建议下周继续带上一个正常吃饭的人。','三种不同类型的手牌入场，诚实回应并保住心态。'],
    ['collection','failure','🃏','底牌集齐了，主问题没带来','收藏图鉴很满，结论页有点空。','你拥有很多能帮忙的材料，却暂时没把它们收束成今天要讨论的判断。老师建议下周从问题开始选牌。那些收藏没有白攒，只需要重新安排它们上场的顺序。','集齐全部手牌，仍在组会上失去足够的底气。']
  ];
  C.campusEndingIds=endings.map(r=>'campus-'+r[0]);
  for(const [id,kind,icon,title,subtitle,desc,hint] of endings)C.endings.push({id:'campus-'+id,kind,icon,title,subtitle,desc,hint});
})();
