window.MEETING_CAMPUS_UI=(() => {
  const C=window.MEETING_CONTENT,G=window.MEETING_CAMPUS,A=window.MEETING_APP,$=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const names={energy:'精力',notes:'资料',slides:'幻灯片',stress:'压力',mood:'心态',evidence:'底气',patience:'耐心',time:'时间',progress:'课题进度',quality:'课题质量'};
  const effect=e=>Object.entries(e||{}).filter(([,v])=>v).map(([k,v])=>`${names[k]} ${v>=0?'+':''}${v}`).join(' · ');
  const tagNames={rigor:'证据',honest:'诚实',social:'合作',rest:'休息',comedy:'喜剧'};
  const stages=['明确问题','形成结果','提交作品','阶段作品完成'];
  const badgeData={'first-stage':['🌱','问题站住了'],'sustained':['🌿','结果成形'],'work-complete':['🏅','阶段作品提交'],'story-boss':['🍵','和导师谈定边界'],'story-stats':['🔍','一起面对未知'],'story-senior':['🤝','工位外的同盟'],explorer:['🗺️','校园全地图'],combo:['🃏','第一套组会组合'],challenge:['🎯','本周挑战完成'],comeback:['🌅','翻车后再出发']};
  function insert(html,anchor,before=true){const node=document.createElement('section');node.innerHTML=html;before?anchor.before(node):anchor.after(node);return node;}
  function decorate(w,render,save){if(!G.enabled(w))return;const g=w.campus,r=g.research,twist=C.weekTwists.find(t=>t.id===g.twist),quest=C.challenges.find(c=>c.id===g.challenge),update=()=>{save();render();};
    const top=insert(`<div class="campus-weather"><span>${twist.icon} ${twist.name}</span><p>${twist.desc}</p></div><div class="research-dashboard"><div><p class="eyebrow">跨周课题 / ${C.researchStyles.find(s=>s.id===r.style).name}</p><h3>${esc(r.title)}</h3><p>${stages[r.stage]}${r.stage<3?` · 下一次组会评审要求：进度 ${[30,65,100][r.stage]} / 质量 ${[20,35,50][r.stage]} / 底气 ${[45,60,70][r.stage]}，并避免翻车`:' · 可以在周日报告开启下一个小课题'}</p></div><div class="research-bars"><label>进度 <strong>${r.progress}</strong><i><b style="width:${r.progress}%"></b></i></label><label>质量 <strong>${r.quality}</strong><i><b style="width:${r.quality}%"></b></i></label></div></div><details class="campus-details"><summary>本周挑战：${quest.icon} ${quest.name} · 查看人物支线与收藏</summary><p>${quest.desc} 成功奖励2枚摸鱼币；每完成一周都获得1点成长。</p>${!w.log.length?`<div class="challenge-picks">${g.challengeOptions.map(id=>{const c=C.challenges.find(c=>c.id===id);return `<button data-challenge="${id}" class="${id===g.challenge?'selected':''}"><strong>${c.icon} ${c.name}</strong><small>${c.desc}</small></button>`;}).join('')}</div><label class="research-style">本周课题打法 <select id="research-style">${C.researchStyles.map(s=>`<option value="${s.id}" ${r.style===s.id?'selected':''}>${s.name} · ${s.desc}</option>`).join('')}</select></label>`:''}<div class="campus-people">${['boss','stats','senior'].map(id=>`<article><h4>${C.people[id].icon} ${C.people[id].name}</h4><p>信任 ${g.bonds[id]} · 支线 ${g.stories[id].chapter}/3章</p><small>${g.stories[id].chapter===3?'支线已完成，周五获得常驻帮助':`去${C.locations.find(l=>l.id===({boss:'mentor',stats:'library',senior:'cafe'}[id])).name}与对方相遇。下一章需要信任 ${[45,60,75][g.stories[id].chapter]}，每周最多推进一章。`}</small></article>`).join('')}</div><p>手牌收藏 ${g.cards.length}/12 · 已完成课题 ${g.completed.length} · 成长 ${g.talents.length}/12 · 徽章 ${g.badges.length}/10</p><div class="badge-list">${Object.entries(badgeData).map(([id,[icon,name]])=>`<span class="${g.badges.includes(id)?'earned':''}">${g.badges.includes(id)?icon:'○'} ${name}</span>`).join('')}</div></details>`,$('.week-board'));
    top.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=()=>{if(G.setChallenge(w,b.dataset.challenge))update();});if($('#research-style'))$('#research-style').onchange=e=>{if(G.setStyle(w,e.target.value))update();};
    if(w.status==='life'){
      const map=insert(`<div class="campus-map"><div class="section-line"><h3>${g.plan?'这半天已经有了去处':'这半天，由你来安排'}</h3><span>${g.plan?'选择后不能重抽场景':'选一个去处，或直接处理下面的原定日常'}</span></div><div class="campus-locations">${C.locations.map(l=>`<button data-location="${l.id}" ${w.pending||g.plan?'disabled':''} class="${g.plan?.location===l.id?'selected':''}"><span>${l.icon}</span><strong>${l.name}</strong><small>${l.desc}</small></button>`).join('')}</div></div>`,$('.week-board'));
      map.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>{if(W().useLocation(w,b.dataset.location)){update();$('.life-scene')?.scrollIntoView({block:'start',behavior:'smooth'});}});
      const event=W().current(w);
      if(w.pending?.campus){const f=w.pending.campus;const c=C.workCards.find(c=>c.id===f.card);insert(`<div class="campus-feedback"><p>${effect(f.work)||'课题先留在这里，生活也要继续。'}</p>${c?`<p>${c.icon} ${f.newCard?'收集到新手牌':'手牌已在收藏中'}：<strong>${c.name}</strong></p>`:''}${f.story?`<p>📖 ${C.people[f.story.person].name}支线推进到第 ${f.story.chapter} 章${f.story.chapter===3?'，常驻帮助已解锁':''}。</p>`:''}</div>`,$('.life-effects'),false);}
      else document.querySelectorAll('[data-life]').forEach((b,i)=>{const c=event.choices[i],extra=document.createElement('em');extra.className='work-preview';extra.textContent=[effect(G.previewWork(w,c)),c.card?'可收集：'+C.workCards.find(a=>a.id===c.card).name:'',c.risk?`${Math.round(c.risk.chance*100)}% 概率出现额外状况`:''].filter(Boolean).join(' · ');b.append(extra);});
      if(w.meeting?.researchReview&&w.day===5){const check=w.meeting.researchReview;insert(`<p class="research-review">${check.passed?'✓ 这次组会通过了课题阶段评审：'+stages[check.stage]:`课题暂未通过下一阶段：需要进度${check.progress}、质量${check.quality}、散会底气${check.evidence}并避免翻车。周末还能继续推进。`}</p>`,$('.week-context'),false);}
    }
    if(w.status==='meeting'){
      const bonus=G.deckBonus(w);const deck=insert(`<div class="deck-board"><div class="section-line"><h3>给这场组会，搭一手底牌</h3><span>已选 ${g.deck.length}/3 · 入场后锁定</span></div><p>最多带3张。相同类型两张会形成组合；三种不同类型也有组合。卡牌是常驻收藏，每场可以重新搭配。</p><div class="work-cards">${g.cards.map(id=>{const c=C.workCards.find(c=>c.id===id),selected=g.deck.includes(id);return `<button data-card="${id}" class="${selected?'selected':''}" ${g.deckLocked||(!selected&&g.deck.length>=3)?'disabled':''}><small>${c.icon} ${tagNames[c.tag]} ${selected?'✓ 已选':''}</small><strong>${c.name}</strong><span>${effect(c.effects)}</span><em>${c.desc}</em></button>`;}).join('')}</div><div class="deck-combos">${bonus.combos.length?bonus.combos.map(x=>`<span>✦ ${x}</span>`).join(''):'选两张同类型，或三张不同类型，试试组合。'}<p>手牌合计：${effect(bonus.effects)||'暂未选牌'}</p></div></div>`,$('.week-board'));
      deck.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{if(G.toggleCard(w,b.dataset.card))update();});
    }
    if(w.status==='report'){
      const report=g.report;const upgrades=insert(`<div class="campus-report"><h3>${report?.success?'🎯 本周挑战完成':'📒 挑战留待下一次'} · ${quest.name}</h3><p>${quest.desc}</p><p>本周获得1点成长。可用成长点：<strong>${g.points}</strong>。解锁的能力会继续带到以后每周。</p>${report?.success&&!report.claimed?'<button id="claim-challenge" class="secondary">领取挑战奖励 · +2摸鱼币</button>':''}${r.stage===3?'<button id="new-research" class="primary">这份作品完成了 · 开启下一个小课题</button>':''}<div class="talent-grid">${C.talents.map(t=>`<button data-talent="${t.id}" ${g.points<1||g.talents.includes(t.id)?'disabled':''} class="${g.talents.includes(t.id)?'selected':''}"><strong>${t.icon} ${t.name} ${g.talents.includes(t.id)?'✓':''}</strong><small>${t.desc}</small><em>${g.talents.includes(t.id)?'已解锁':'1点成长'}</em></button>`).join('')}</div></div>`,$('.week-board'));
      if($('#claim-challenge'))$('#claim-challenge').onclick=()=>{const earned=G.claimReport(w);save();A.getCareer().coins+=earned;A.persistCareer();render();};
      if($('#new-research'))$('#new-research').onclick=()=>{if(G.restartResearch(w))update();};upgrades.querySelectorAll('[data-talent]').forEach(b=>b.onclick=()=>{if(G.buyTalent(w,b.dataset.talent))update();});
    }
  }
  const W=()=>window.MEETING_WEEK;
  return {decorate,effect};
})();
