(() => {
  const C=window.MEETING_CONTENT;
  C.weekDays=['周一','周二','周三','周四','周五','周六','周日'];
  const choice=(text,flavor,effects,traits,career={})=>({text,flavor,effects,traits,career});
  const rows=[
    [0,'闹钟的三次上诉','新的一周开始了。你和闹钟对开庭时间有不同理解。',[
      choice('按时起床，先读一会儿','你把最清醒的半小时留给了自己。',{energy:-5,notes:12,stress:-3},{study:1,alarm:1}),
      choice('补觉，再慢慢去工位','睡眠不是一种需要向导师解释的罪。',{energy:15,stress:-7},{rest:1}),
      choice('凌晨刚睡，靠咖啡进入周一','咖啡可以代班，不能代替睡觉。',{energy:-15,notes:8,stress:9},{night:1,late:1})]],
    [0,'新建文件夹：最终版','电脑里已经有三个“最终版”，它们谁也不服谁。',[
      choice('整理来源，给版本编号','下次找文件时，你会感谢今天的自己。',{notes:10,slides:5,energy:-4},{folder:1,backup:1}),
      choice('约同门一起核对计划','对方指出了一个你一直没发现的小坑。',{notes:8,stress:-6},{collaboration:1},{senior:2}),
      choice('再建一个“最终版真的最终”','文件夹数量领先研究进度。',{slides:3,stress:3},{folder:2,chaos:1})]],
    [0,'本周计划有两页','第一行是研究计划，第二页全是你想吃的东西。',[
      choice('把本周问题缩到一个','能做完的计划，让周一不那么可怕。',{notes:10,stress:-5},{study:1}),
      choice('先和同门吃个午饭','饭桌上听到了一个能用的建议。',{energy:8,notes:4,stress:-5},{meal:1,collaboration:1},{coins:1}),
      choice('先告诉老师：这周都能做','周四的你已经在远处挥手求救。',{stress:10},{promise:2,deadline:1})]],
    [1,'资料像长出了腿','你记得昨晚看过那份材料，但它今天已经换了住所。',[
      choice('补好来源与页码','资料终于愿意在需要时出现。',{notes:12,energy:-6},{study:1,folder:1}),
      choice('请同门帮忙找，交换一杯茶','你们发现各自缺的恰好是对方知道的。',{notes:9,stress:-5},{collaboration:1},{senior:3}),
      choice('先画一张很大的路线图','路线图的面积先于内容成熟了。',{slides:9,notes:-5},{chaos:1})]],
    [1,'周二有一场旁听','主讲人说“这个细节不重要”，你突然精神了。',[
      choice('记下方法和适用边界','旁听留下的不是口号，是几个可检查的问题。',{notes:13,energy:-5},{study:1}),
      choice('课后问一个问题','开口前很紧张，问完反而轻松了。',{notes:8,stress:-6},{collaboration:1}),
      choice('给所有表情包配上学术字幕','群里很热闹，笔记本很安静。',{energy:4,notes:-3},{meme:2,chaos:1})]],
    [1,'午饭会诊你的进度','同门夹起一筷子菜，问你“这周汇报什么”。',[
      choice('讲清楚目前卡在哪儿','一顿饭没有解决课题，解决了孤独感。',{notes:8,stress:-8},{meal:1,collaboration:1}),
      choice('今天专心吃饭，晚上再想','你的注意力和胃都需要下班时间。',{energy:12,stress:-7},{rest:1,meal:1}),
      choice('即兴演讲菜价与科研预算','饭桌一致同意让你担任点菜负责人。',{energy:7,slides:-3},{meal:2,chaos:1})]],
    [2,'结果没有按故事发展','那个漂亮的假设，今天暂时没有漂亮的结果。',[
      choice('保留结果，把边界写清楚','没得到预期答案，也是一条真实记录。',{notes:12,slides:5,stress:-2},{negative:1,study:1}),
      choice('找同门讨论另一条解释','你开始相信问题可以慢慢改。',{notes:8,stress:-6},{negative:1,collaboration:1,pivot:1}),
      choice('先把坐标轴调得很优雅','图变好看了，问题还在原来的位置。',{slides:12,notes:-8,stress:6},{chaos:1})]],
    [2,'打印机召开独立组会','它只打出封面，随后进入漫长的沉思。',[
      choice('改成电子备份，检查一遍','投影坏了也还有第二条路。',{slides:9,energy:-4},{backup:1,printer:1}),
      choice('借同门的设备，顺手帮忙排版','互相救场成了今天最有效的合作。',{slides:7,stress:-4},{collaboration:1,printer:1}),
      choice('把打印机故障写成一首诗','最后一句是“请检查纸盒”，大家觉得很有力量。',{energy:5,slides:-3},{printer:2,chaos:1})]],
    [2,'群消息：能顺便加一页吗','“顺便”两个字从屏幕里走出来，坐上了你的肩膀。',[
      choice('问清用途，只补必要的一页','边界被说清楚后，工作也清楚了。',{slides:9,energy:-5,stress:2},{study:1}),
      choice('坦白时间有限，约到下周','你写下了承诺，也写下了它的截止日期。',{stress:-3},{promise:1}),
      choice('回复没问题，一口气承诺三件事','微信上的你勇敢，日历上的你沉默。',{stress:12,energy:-8},{promise:2,deadline:1})]],
    [3,'幻灯片的午夜施工','“再改一页就睡”，听起来像昨天的录音。',[
      choice('列好重点，按时停工','少两页动画，多一点清醒。',{slides:12,energy:6,stress:-5},{rest:1,backup:1,alarm:1}),
      choice('把未完成处明确标出来','你决定让汇报反映真实进度。',{slides:8,notes:5,stress:-3},{negative:1}),
      choice('通宵补完，咖啡开始加班','每一页都完成了，只有你还没加载完成。',{slides:20,energy:-30,stress:15},{night:2,deadline:1})]],
    [3,'汇报前的预演','空会议室里，椅子暂时都很好说话。',[
      choice('计时演练，把重点提前','真正需要讲的部分终于不在最后一页。',{slides:14,notes:4,energy:-5},{study:1,backup:1}),
      choice('请同门提问，承认暂时答不了的','预演的难题让正式组会少一点意外。',{notes:10,stress:-7},{collaboration:1}),
      choice('给整套幻灯片加梗图','椅子没笑，你觉得是它们比较内向。',{slides:6,notes:-3},{meme:2,chaos:1})]],
    [3,'云盘同步冲突','两个文件都叫最新版，云盘建议你自己决定。',[
      choice('核对版本，另存离线备份','你把风险关在了一个有名字的文件夹里。',{slides:8,energy:-5},{backup:2,folder:1}),
      choice('退回稳定版本，删掉花活','旧版本不酷，但它能打开。',{slides:4,stress:-4},{backup:1}),
      choice('随手覆盖，明天再检查','文件没有抗议，问题也没有消失。',{slides:-18,stress:8},{erased:1,chaos:1})]],
    [4,'周五早晨：门还没开','距离组会还有一点时间。饭、觉、文件，都在排队。',[
      choice('检查文件，吃饭，准时到场','你带着能打开的文件和吃过饭的身体进入会议室。',{energy:10,slides:7,stress:-6},{backup:1,meal:1}),
      choice('把还欠的内容列在最后一页','每一项都有明确的现状与下一步。',{notes:10,slides:5,stress:-3},{study:1}),
      choice('起晚了，抱着电脑一路狂奔','这一次，是你的鞋先开始答辩。',{energy:-14,stress:12},{late:2,deadline:1})]],
    [4,'门口遇到了同门','大家都在检查U盘，表情像即将共同登机。',[
      choice('互相检查备份，约好救场','有人知道你卡在哪里，是一种可见的底气。',{slides:8,stress:-8},{backup:1,collaboration:1},{senior:2}),
      choice('坐下整理第一页的表达','开头终于能用两句话说明白。',{notes:10,stress:-3},{study:1}),
      choice('提前竞选散会后的点菜负责人','你在正式入场前获得了一个行政头衔。',{energy:5},{meal:2,chaos:1})]],
    [4,'最后十分钟','你还有机会多加两张图，也有机会停止多加两张图。',[
      choice('保持稳定版本，不再临时扩张','今天的你决定给昨天的你一点信任。',{slides:5,stress:-6},{backup:1}),
      choice('把局限写清楚再入场','没有答案的地方，也有可以诚实说的话。',{notes:9},{negative:1}),
      choice('临时承诺会上再补充细节','还没开会，下周的待办已经加一了。',{stress:8},{promise:1})]],
    [5,'周六的群消息','散会了，群聊并没有散会。你可以决定什么时候回复。',[
      choice('集中回复，把周末留出一半','问题有人处理，你也拥有了休息时间。',{energy:12,stress:-10},{rest:1}),
      choice('和同门复盘一个真正卡住的问题','这次讨论没有投影仪，也没有必须装懂的压力。',{notes:10,stress:-5},{collaboration:1}),
      choice('把昨日名场面剪成表情包','你没成为组会之光，成为了群聊置顶。',{energy:7,stress:-4},{meme:2,chaos:1})]],
    [5,'导师的小本本来到周末','你说过“之后补一下”的事，现在有了自己的名字。',[
      choice('兑现一项，写好简短的回执','一个坑被填上了。它没有变成三个新坑。',{notes:9,energy:-6,stress:-8},{study:1},{taskDone:1,debt:-1}),
      choice('重新商量优先级，只留真正需要的','范围变小了，问题变清楚了。',{notes:6,stress:-8},{pivot:1},{taskDone:1}),
      choice('再建一个待办文件夹','你完成了待办的收容工作。',{stress:5},{folder:2,unfinished:1})]],
    [5,'周末突然空出一下午','日历白了一块，仿佛有人把你从附件里解压了出来。',[
      choice('出去走走，吃顿正常的饭','没有产生图表，产生了一个心情不错的人。',{energy:20,stress:-15},{rest:2,meal:1}),
      choice('读一个感兴趣但不急用的问题','兴趣暂时不用向进度表证明自己。',{notes:10,energy:6,stress:-6},{pivot:1,study:1}),
      choice('睡醒发现是周日晚上的错觉','你穿越了一个很便宜的时间洞。',{energy:15,stress:4},{rest:1,late:1})]],
    [6,'周日：下周能不能少一点坑','上周的你和下周的你，在日历前进行一次交接。',[
      choice('处理一项遗留问题，写下交接','下周终于不必从猜测自己的文件开始。',{notes:9,slides:5,stress:-8},{backup:1},{taskDone:1,debt:-1}),
      choice('给下周留一个可完成的目标','计划少了一行，执行多了一点可能。',{notes:8,stress:-7},{rest:1,pivot:1}),
      choice('所有任务统一改名“下周再说”','未来的你收到了一封没有退订按钮的邮件。',{stress:9},{unfinished:1,folder:1})]],
    [6,'生活也需要一页总结','除了组会，这周还有饭、朋友、散步和没洗的杯子。',[
      choice('收拾工位，认真休息','进度之外的生活也被你照顾到了。',{energy:18,stress:-12},{rest:2}),
      choice('记下一个想继续研究的小问题','不是每一个问题都需要立刻变成指标。',{notes:10,stress:-5},{study:1,pivot:1}),
      choice('把本周写成一份校园荒诞周报','组会输赢之外，你保留了解释生活的权利。',{energy:8,stress:-7},{meme:1,chaos:1},{coins:1})]],
    [6,'星期一在窗外排队','你终于明白，周末不需要证明它比工作日高效。',[
      choice('把电脑关上，留一点期待','下周不一定容易，但你不必今晚就过完它。',{energy:20,stress:-12},{rest:2}),
      choice('约下周一起解决一个具体问题','你把任务变成了一次有范围的合作。',{notes:8,stress:-6},{collaboration:1}),
      choice('设置七个闹钟，名称全是论文标题','下周早晨会是一场多学科联合研讨会。',{slides:3,stress:4},{alarm:2,chaos:1})]],
  ];
  C.lifeEvents=rows.map(([day,title,scene,choices],i)=>({id:'life-'+i,day,title,scene,choices}));
  for(const p of C.projects){
    for(let day=0;day<3;day++) C.lifeEvents.push({id:`life-${p.id}-${day}`,project:p.id,day,slot:1,title:`${p.name} · ${p.topics[day]}`,scene:`周五要汇报${p.topics[day]}。桌上的笔记、文件和你，都还处在“进行中”。`,choices:[
      choice(`核对${p.topics[day]}，记录依据与疑问`,`你整理了${p.topics[day]}，周五讲到这里时会多一点准备。`,{notes:14,slides:8,energy:-9},{study:1}),
      choice(`约同门讨论${p.topics[day]}`,`讨论让你找到一个更清楚的表述；你也帮对方看了一小段材料。`,{notes:10,slides:6,energy:-4,stress:-5},{collaboration:1,...(day===2?{pivot:1}:{})},{senior:2}),
      choice(`先承诺${p.topics[day]}都准备好了`,`群聊中的进度超过了工位上的进度。周五会有人记得这句话。`,{slides:3,stress:8},{promise:1,deadline:1})]});
    C.lifeEvents.push({id:`life-${p.id}-feedback`,project:p.id,day:5,slot:1,title:`${p.name} · 散会后的回声`,scene:`组会里的问题已经带回工位。你可以处理一个遗留事项，也可以先恢复一下。`,choices:[
      choice(`补好一项关于${p.topics[2]}的说明`,'你没有把整场组会重做一遍，只把一项说不清的事写清楚。',{notes:12,slides:7,energy:-7,stress:-6},{study:1},{taskDone:1,debt:-1}),
      choice('承认路线需要调整，重新划定范围','问题的方向变了，这一周的经历仍然有用。',{notes:8,stress:-8},{pivot:2,negative:1},{taskDone:1}),
      choice(`给“${p.ending}”写一段番外`,'这份番外不会进入正式汇报，但同门建议你继续连载。',{energy:10,stress:-5},{meme:1,chaos:1})]});
  }
})();
