/* Activity time is separate from the old morning/afternoon event windows. */
window.MEETING_DAILY_TIME=(()=>{
 const N=window.MEETING_NARRATIVE_WORLD,P=N?.pair||((z)=>z),copy=x=>JSON.parse(JSON.stringify(x)),clamp=x=>Math.max(0,Math.min(100,x));
 const enabled=w=>w?.config?.dailyTime==='hours'&&!w.config.challenge;
 const balanced=s=>!s?.weekContext?.world?.challenge&&!s?.config?.challenge&&(s?.balanceVersion===1||s?.config?.balanceVersion===1);
 const minute=w=>enabled(w)?w.clock.minute:w.slot?840:540;
 const label=w=>String(Math.floor(minute(w)/60)).padStart(2,'0')+':'+String(minute(w)%60).padStart(2,'0');
 const due=w=>!w.meeting&&(window.MEETING_WEEK_RHYTHM?.due(w)??true);
 const end=w=>w.day===4&&due(w)?840:1260;
 function duration(w,e,c){if(c.dailyRest)return Math.min(30,Math.max(1,end(w)-minute(w)));if(c.assignmentAction)return e.id.startsWith('assignment-work')?(c.assignmentAction==='thorough'?90:45):15;if(c.worldAction==='verify'||c.academyAction==='resource-work')return 120;if(c.academyAction==='book'||c.academyAction==='borrow'||c.academyAction==='ask')return 30;if(c.preparationGains&&Object.values(c.preparationGains).some(v=>v===2)||e.prepKind&&c.work?.quality)return 90;if(c.traits?.night)return 180;if(c.traits?.meal||e.liveLocation==='food'||e.location==='food')return 45;if(c.traits?.rest||c.effects?.energy>=8)return 60;if(e.assignment||e.id.startsWith('assignment-offer')||e.groupType)return 30;if((c.effects?.energy||0)<=-9)return 90;if((c.effects?.energy||0)<=-5)return 60;return 30;}
 function need(w,e,c){if(c.dailyRest||(c.effects?.energy||0)>=0)return 0;const d=duration(w,e,c);return d>=120?14:d>=90?10:d>=60?5:0;}
 function available(w,e,c){return !enabled(w)||w.resources.energy>=need(w,e,c)&&duration(w,e,c)<=end(w)-minute(w);}
 function restEvent(w){return {id:'daily-rest',day:w.day,slot:w.slot,project:w.config.project,title:P('给自己留一点余量','Leave yourself some room'),scene:P('这段时间留给休息、喝水和整理下一步，不会同时生成研究证据。','This time is for a break, water and planning the next step. It does not produce research evidence.'),choices:[{text:P('休息一下，再安排下一件事。','Take a break before the next activity.'),flavor:P('你暂时离开屏幕，给接下来的工作留了一点精力。','You step away from the screen and recover some energy for later work.'),effects:{energy:9,stress:-5},traits:{rest:1},career:{},work:{},preparationGains:{},dailyRest:true}]};}
 function fridayEvent(w,event){if(w.day!==4||due(w)||w.campus?.plan||w.surprise||!window.MEETING_CONTENT.lifeEvents.some(e=>e.id===event.id&&e.day===4))return event;const rows=[['把讨论整理成下一步','把当前材料、疑点和约定分别记下，写清楚哪些事情仍需要实际处理。'],['周五的研究还在继续','今天可以处理材料、交流具体问题，也可以给自己留一些余量。'],['收尾与生活都有自己的位置','文件需要交接，人也需要吃饭。整理安排不会自动完成未核对的问题。']],row=rows[w.log.filter(r=>r.day===4).length%rows.length];return {id:'daily-friday-'+(w.log.filter(r=>r.day===4).length%3),day:4,slot:w.slot,project:w.config.project,title:P(row[0],['Turn discussion into next steps','Research continues on Friday','Leave room for work and life'][w.log.filter(r=>r.day===4).length%3]),scene:P((w.meeting?'这场组会已经结束。':'今天没有安排组会。')+row[1],()=>`${w.meeting?'The meeting is over.':'There is no meeting today.'} Separate records, unresolved questions and commitments; planning does not complete unchecked work.`),choices:[{text:P('整理材料和待办，注明尚未核对的部分。','Organize materials and next steps, marking what remains unchecked.'),flavor:P('记录更清楚了，未完成的核对仍留在待办里。','The records are clearer. Unfinished checks remain open.'),effects:{energy:-4,notes:4,slides:3},traits:{folder:1},career:{},work:{},preparationGains:{}},{text:P('找同门交流具体疑问，先说明自己知道多少。','Discuss a concrete question with a peer and state what you know.'),flavor:P('你们交换了想法，没有把聊天当成核对完成。','You exchange ideas without treating a conversation as a completed check.'),effects:{energy:-3,stress:-4},traits:{collaboration:1},career:{},work:{},preparationGains:{}},{text:P('吃顿饭、走一走，把余量留给自己。','Have a meal and a walk, leaving some energy for yourself.'),flavor:P('你把这段时间留给了生活。','You leave this time for life outside work.'),effects:{energy:15,stress:-8},traits:{rest:1,meal:1},career:{},work:{},preparationGains:{}}]};}
 function decorate(w,event){if(!enabled(w)||!event)return event;const e=copy(fridayEvent(w,event));for(const k of ['title','scene','quote'])if(e[k])e[k]=text(e[k]);e.choices.forEach(c=>{c.text=text(c.text);c.durationMinutes=duration(w,e,c);c.energyRequired=need(w,e,c);c.dailyAvailable=available(w,e,c);c.dailyReason=w.resources.energy<c.energyRequired?P('这项集中工作需要至少 '+c.energyRequired+' 点精力；可以先休息或选择轻任务。',()=>`This focused activity needs at least ${c.energyRequired} energy. Take a break or choose lighter work first.`):P('剩余时间不足以完整完成这项安排。', 'There is not enough time left to complete this activity.');});if(!e.choices.every(c=>c.groupAction||['accept','negotiate','decline'].includes(c.assignmentAction))){const c=restEvent(w).choices[0];c.durationMinutes=duration(w,e,c);c.dailyAvailable=true;e.choices.push(c);}return e;}
 function init(w){if(enabled(w))w.clock={version:1,minute:540,overnights:0};}
 function upgrade(w){if(!w||w.config.challenge||w.clock)return w;w.config={...w.config,dailyTime:'hours',balanceVersion:1};w.clock={version:1,minute:w.status==='report'?1260:w.status==='meeting'?840:w.slot?840:540,overnights:0};return w;}
 function advance(w){if(!enabled(w))return false;const r=w.log.at(-1),d=r?.time?.duration||60;w.clock.minute+=d;if(w.day===4&&due(w)&&w.clock.minute>=840){w.clock.minute=840;w.status='meeting';return true;}if(w.clock.minute>=1260){if(w.day===6){w.clock.minute=1260;w.slot=1;w.status='report';window.MEETING_CAMPUS?.settleReport(w);return true;}const old=w.resources.energy,oldStress=w.resources.stress,gain=w.log.some(x=>x.day===w.day&&x.traits?.night)?12:22;w.resources.energy=clamp(old+gain);w.resources.stress=clamp(w.resources.stress-6);r.overnight={energy:w.resources.energy-old,stress:w.resources.stress-oldStress};w.clock.overnights++;w.day++;w.clock.minute=540;}w.slot=w.clock.minute<840?0:1;return true;}
 function afterMeeting(w){if(enabled(w)){w.day=4;w.slot=1;w.clock.minute=930;}}
 function lifeEffects(w,e,c,raw){const out={...raw};if(balanced(w)&&out.energy<0)out.energy=-Math.max(1,Math.ceil(-out.energy*.38));return out;}
 const reasonable=c=>!c.hardStop&&!c.flags?.chaos&&c.semantic!=='complete'&&!!(c.flags?.honest||c.flags?.rigor||c.flags?.help||c.prepared?.available);
 function meetingEffects(s,c,raw,e=null){const out={...raw};if(!balanced(s)||c.hardStop)return out;if(out.patience<0){out.patience=-Math.max(1,Math.round(-out.patience*(c.flags?.chaos?.55:.4)));if((c.flags?.honest||c.prepared?.available)&&!c.flags?.chaos&&!c.flags?.debt&&out.evidence>-10)out.patience=Math.max(-2,out.patience);}const crisis=e?.flaw||e?.id==='live-followup'||s.eventId?.startsWith('live-flaw-')||s.eventId==='live-followup';if(s.difficulty==='normal'&&!crisis&&reasonable(c)&&!(out.evidence<-12)){out.patience=Math.max(0,out.patience||0);out.mood=Math.max(0,out.mood||0);if(out.evidence<0)out.evidence=c.prepared?.available?Math.max(-2,out.evidence):Math.max(-2,Math.ceil(out.evidence*.5));if(out.time<0)out.time=Math.max(-2,out.time);}else if(s.difficulty==='normal'&&!c.flags?.chaos){if(out.mood<0)out.mood=-Math.max(1,Math.ceil(-out.mood*.5));if(crisis&&out.evidence<0)out.evidence=-Math.max(1,Math.ceil(-out.evidence*.6));}return out;}
 function initMeeting(s){if(balanced(s)){s.stats.patience=clamp(s.stats.patience+(s.difficulty==='normal'?15:10));s.stats.time=Math.min(65,s.stats.time+(s.difficulty==='normal'?14:8));}}
 function text(s){const change=z=>String(z).replace(/这半天/g,'这段时间').replace(/上半天/g,'上午').replace(/下半天/g,'下午').replace(/生活片段/g,'安排').replace(/一个片段/g,'一段时间').replace(/half[- ]day/gi,'activity').replace(/first half of the day/gi,'morning').replace(/second half of the day/gi,'afternoon');const z=change(s);return z===s?s:P(z,()=>change(N?.english?.(s)||s));}
 function ui(w,root){if(!enabled(w))return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode())if(n.parentElement&&!['SCRIPT','STYLE','TEXTAREA'].includes(n.parentElement.tagName))n.textContent=text(n.textContent);}
 function valid(w){return !enabled(w)||!!w.clock&&w.clock.version===1&&Number.isInteger(w.clock.minute)&&w.clock.minute>=540&&w.clock.minute<=1260&&Number.isInteger(w.clock.overnights)&&w.clock.overnights>=0&&w.clock.overnights<=7&&(w.status!=='life'||w.clock.minute<end(w));}
 return {enabled,balanced,minute,label,end,duration,need,available,restEvent,decorate,init,upgrade,advance,afterMeeting,lifeEffects,meetingEffects,reasonable,initMeeting,text,ui,valid};
})();
