/* Overview entrances remain on one screen; scenes move into a modal without cloning handlers. */
window.MEETING_DASHBOARD_UI=(()=>{
 let lastAuto='';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function clear(){const d=document.querySelector('#daily-event-dialog');if(d){if(d.open)d.close();d.replaceChildren();}}
 function availability(w){
   const reason=window.MEETING_WEEK.actionReason(w),selector='[data-preparation],[data-location],[data-academic],[data-publication],[data-retarget],[data-assignment],[data-opportunity],[data-joint],#mix-joint,#world-project,#route-story-dispatch,#week-food,#week-friends,#direction-pivot,#direction-target,#direction-filter';
   const controls=[...document.querySelectorAll('#app '+selector.split(',').join(',#app '))];
   for(const b of controls){if(reason)b.disabled=true;if(b.disabled){let text=reason;if(!text){if(b.dataset.publication==='submit')text='先完成当前课题的三次实查，并整理结论，再投稿。';else if(b.dataset.publication==='new')text='当前课题投稿后，才能开始下一课题。';else if(b.dataset.academic==='campus')text='这条校园故事在周末或约好的下一周继续。';else if(b.dataset.academic==='resource-work')text='资源窗口还在等待，开放后再处理。';else text='此项尚未到开放时间，或需要先完成前一步。请查看上方进度。';}b.title=text;b.setAttribute('aria-label',b.textContent.trim()+'。'+text);}}
   if(reason)for(const id of ['life-planning','life-research','life-community']){const panel=document.querySelector('#'+id);if(!panel)continue;const n=document.createElement('div');n.className='action-availability';n.setAttribute('role','status');const p=document.createElement('p');p.textContent=reason;const b=document.createElement('button');b.className='secondary';b.textContent='打开正在等待的事件 →';b.onclick=()=>document.querySelector('#daily-event-dialog')?.showModal();n.append(p);if(w.status==='life')n.append(b);panel.prepend(n);}
   const event=window.MEETING_WEEK.current(w);
   document.querySelectorAll('[data-life]').forEach((b,i)=>{const c=event.choices[i],p=window.MEETING_PREPARATION,blocked=p?.enabled(w)&&!p.lifePreview(w,event,i).available;if(c?.academyAvailable===false||c?.publicationAvailable===false||blocked){b.disabled=true;const n=document.createElement('small');n.className='choice-lock';n.textContent='🔒 '+(c.academyReason||(c.publicationAvailable===false?'先完成这轮要求的修稿核对，再正式修回。':blocked?'先整理本方向的原始材料，再作这项回应。':'这项需要先完成相应准备或等到开放时间。'));b.title=n.textContent;b.append(n);}});
 }
 function decorate(w){if(!['life','meeting','report'].includes(w.status))return;const board=document.querySelector('#daily-scene');if(!board)return;availability(w);if(w.status!=='life'){const menu=document.querySelector('.life-hub-menu');if(menu){const layout=document.createElement('div');layout.className='dashboard-overview dashboard-report';board.before(layout);layout.append(board,menu);}const stage=document.querySelector('#academy-stage');if(stage)document.querySelector('#life-research')?.prepend(stage);return;}const event=window.MEETING_WEEK.current(w),nodes=[...board.childNodes],id=w.id+':'+w.day+':'+w.slot+':'+event.id;
   let modal=document.querySelector('#daily-event-dialog');if(!modal){modal=document.createElement('dialog');modal.id='daily-event-dialog';modal.className='daily-event-dialog';document.body.append(modal);}clear();
   const head=document.createElement('div');head.className='dialog-head';head.innerHTML='<strong>📨 '+(w.pending?'行动后果':'当天事件')+'</strong><button class="close" aria-label="收起事件">×</button>';modal.append(head,...nodes);head.querySelector('button').onclick=()=>modal.close();
   const active=!!(w.surprise||window.MEETING_ASSIGNMENTS.offer(w)||w.academy?.plan||w.campus?.plan||w.world?.plan||w.world?.focus||w.sideStories?.plan||w.taskFocus||w.publication?.plan||w.routeStories?.plan),summary=document.createElement('section');summary.className='daily-overview-card';summary.innerHTML='<p class="eyebrow">'+(active?'📨 有新情况':'☀️ 今日安排')+' · '+window.MEETING_CONTENT.weekDays[w.day]+' · '+(w.slot?'下半天':'上半天')+'</p><h1>'+esc(event.title)+'</h1><p>'+esc(w.pending?w.pending.flavor:event.scene)+'</p><button class="primary" id="open-daily-event">'+(w.pending?'查看行动后果':active?'处理这次事件':'打开当天安排')+' →</button>';board.append(summary);summary.querySelector('button').onclick=()=>modal.showModal();
   const menu=document.querySelector('.life-hub-menu');if(menu){const layout=document.createElement('div');layout.className='dashboard-overview';board.before(layout);layout.append(board,menu);}
   const stage=document.querySelector('#academy-stage');if(stage)document.querySelector('#life-research')?.prepend(stage);
   if(w.pending||w.campus?.plan||active&&id!==lastAuto){lastAuto=id;modal.showModal();}
 }
 document.addEventListener('keydown',e=>{const d=document.querySelector('#daily-event-dialog');if(!d?.open||e.altKey||e.ctrlKey||e.metaKey||e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Enter'&&d.querySelector('#life-next')&&!e.target.matches('button.close')){e.preventDefault();d.querySelector('#life-next').click();return;}if(![1,2,3].includes(Number(e.key)))return;const b=d.querySelectorAll('[data-life]')[Number(e.key)-1];if(b&&!b.disabled){e.preventDefault();b.click();}});
 return {clear,decorate};
})();
