/* Every playable direction owns an immutable bank. The authored subject packets are
   shared building blocks, not a claim that 2,484 novels were written independently. */
window.MEETING_DIRECTION_LIBRARY=(()=>{
 'use strict';
 const D=window.MEETING_DIRECTIONS,C=window.MEETING_CONTENT,N=window.MEETING_NARRATIVE_WORLD;
 if(!N)return {meeting:(_,raw)=>raw,life:(_,raw)=>raw};
 const P=N.pair,E=N.english;
 // id; permitted families; subject pattern; material; check; snag; inference limit.
 // Each bilingual cell is deliberately about academic evidence, not a lab protocol.
 const rows=`
human-geography;science,economics,management,law;人文地理|经济地理|城市地理|文化地理;空间单元、人口活动与区域制度记录|spatial units, human activity and regional institutional records;区分个人与区域层面的关系，核对空间尺度与边界|separate individual and regional relationships and check spatial scales and boundaries;区域平均关系被直接当成每个人的行为规律|regional average relationships were treated as individual behavior;区域关系不能直接代替个人关系，空间边界变化也会改变比较|regional relationships do not directly establish individual relationships and boundary changes affect comparisons
ontology;philosophy;存在|形而上|模态|时间哲学|同一性|属性|可能世界|本体|过程哲学;概念定义、论证前提与反例|concept definitions, argumentative premises and counterexamples;区分逻辑可能、理论设定和经验事实|separate logical possibility, theoretical assumptions and empirical facts;用来支持结论的反例已经预设了有争议的前提|a supporting counterexample already assumes the disputed premise;想象得出一个情形不独立证明它在理论上可能|an imaginable scenario does not alone establish theoretical possibility
mind;philosophy;心灵|身心|意识|认知哲学;思想实验、意识概念与经验研究的原文|thought experiments, consciousness concepts and empirical source texts;分开第一人称描述、功能解释与实验指标|separate first-person descriptions, functional explanations and experimental measures;任务表现被直接写成了主观体验本身|task performance was treated as subjective experience itself;解释功能与解释体验可能是不同的论证目标|explaining function and explaining experience can be different argumentative targets
aesthetic;philosophy;美学|解释学|艺术哲学;作品语境、评价语汇与解释文本|work contexts, evaluative vocabulary and interpretative texts;区分作品特征、解释依据与价值判断|separate work features, interpretative grounds and value judgments;一位评论者的评价被当成了作品唯一的意义|one critic's evaluation was treated as a work's sole meaning;流行程度不能独立决定审美价值或解释成立|popularity does not alone determine aesthetic value or interpretative validity
religion;philosophy;宗教|神学;经文本、仪式语境与不同传统的释义|scriptural texts, ritual contexts and interpretations across traditions;核对译词与历史语境，区分内部论证和外部描述|check translations and historical contexts and separate internal argument from external description;不同传统中相似的译词被当成同一概念|similar translated words across traditions were treated as one concept;同名译词不能保证信仰实践和概念相同|shared translated terms do not establish identical practices or concepts
industrial-safety;engineering;安全工程|事故|应急|职业安全;事故时间线、暴露条件与报告覆盖范围|incident timelines, exposure conditions and report coverage;区分危险源、暴露机会与报告制度变化|separate hazards, exposure opportunities and reporting changes;报告渠道改善后事故记录增加被写成风险必然上升|more records after reporting improved were described as necessarily greater risk;记录数量需要暴露分母和报告条件才能比较|record counts need exposure denominators and reporting conditions for comparison
process;engineering;化工|化学工程|传递过程|反应工程|分离过程|过程强化|工况;系统边界、物料衡算与工况记录|system boundaries, material balances and operating records;在同一系统边界下核对衡算与工况差异|check balances and operating differences under matched system boundaries;一组评价遗漏了辅助环节的资源消耗|one assessment omitted resource use in auxiliary stages;局部效率改善不能直接写成全系统效益提高|local efficiency improvements do not establish a whole-system benefit
medical-device;medicine;医学技术|设备|听觉|言语技术;使用任务、设备版本与技术评价记录|use tasks, device versions and technical assessment records;区分设备测量性能、使用反馈与临床结局|separate measurement performance, use feedback and clinical outcomes;设备读数更稳定被直接写成患者结局改善|more stable readings were described as better patient outcomes;技术性能不能代替患者相关结局和使用条件|technical performance does not replace patient-related outcomes or use conditions
heart-failure;medicine;心力衰竭|心衰|心肌病;心功能分型、症状时段与再住院随访|cardiac-function groups, symptom periods and rehospitalization follow-up;对齐分型和随访窗口，区分功能指标与患者结局|align groups and follow-up windows and separate functional indicators from patient outcomes;功能指标改善与再住院记录覆盖的时期不同|functional improvement and rehospitalization records cover different periods;功能指标的变化不独立代表长期临床结局|functional-indicator change does not alone represent long-term clinical outcomes
rhythm;medicine;心律|电生理|心电;监测时长、事件定义与症状日记|monitoring durations, event definitions and symptom diaries;按监测窗口比较事件，区分未捕获和未发生|compare events by monitoring windows and separate uncaptured from absent events;监测时间更短的一组被写成事件更少|a group with shorter monitoring was reported to have fewer events;没有记录到事件不等于事件没有发生|an unrecorded event is not necessarily an absent event
genetic-association;medicine,science;遗传|变异;变异注释版本、来源群体与表型定义|variant-annotation versions, source populations and phenotype definitions;对照群体背景、注释与表型，区分关联和功能解释|check population context, annotations and phenotypes and separate association from function;关联的变异被直接说成已经找到致病机制|an associated variant was described as an established disease mechanism;关联位点、作用基因与机制是不同层次的证据|associated loci, effector genes and mechanisms are different evidence levels
oral-function;medicine;牙周|咀嚼|修复|正畸;牙位索引、功能任务与患者体验|tooth-site indexes, functional tasks and patient experiences;比较结构评价与真实任务表现，保留个体对应|compare structural assessments and task performance while retaining person linkage;影像上的结构改善被当成咀嚼体验已经改善|structural image improvement was treated as improved chewing experience;结构指标不能独立替代功能和患者体验|structural indicators do not alone replace function and patient experience
measurement-scale;medicine,education;量表|患者报告|心理测量|构念|生活质量;条目版本、填答者与缺失条目|item versions, respondents and missing items;先确认量表含义和适用对象，再比较总分|confirm a scale’s meaning and applicable population before comparing totals;删去不同条目后仍沿用原来总分的解释|different omitted items retained the original total-score interpretation;总分相同不保证测量的内容相同|equal totals do not guarantee identical measured content
numerical;science;计算数学|数值|近似|误差;离散设置、误差指标与参考解|discretization settings, error indicators and reference solutions;区分离散误差、舍入误差与模型近似|separate discretization, rounding and model-approximation errors;迭代停止后结果稳定，被误写成误差已经很小|stable stopped iterations were described as small error;数值稳定和接近目标解需要分别检验|numerical stability and closeness to a target solution need separate checks
optimization;science,engineering,economics,management;优化|运筹|匹配|调度|规划算法;目标函数、可行约束与对照方案|objective functions, feasibility constraints and comparison plans;先确认可行性，再比较目标值与资源取舍|confirm feasibility before comparing objective values and resource tradeoffs;目标值更好的一组其实放宽了约束|a better objective value came from relaxed constraints;目标更优不等于在同一约束下更优|a better objective is not necessarily better under the same constraints
game-theory;economics;博弈|微观理论|信息经济|经济网络;参与者信息、策略集合与均衡条件|participants’ information, strategy sets and equilibrium conditions;说明信息何时可见，核对解的条件|state when information is visible and check solution conditions;推导时让参与者知道了模型原本没有提供的信息|participants were given information absent from the model;一个均衡存在不保证现实一定出现该结果|existence of an equilibrium does not guarantee its real-world occurrence
labor;economics;劳动|就业|职业流动|迁移与收入|教育经济;劳动参与、工作时长与来源样本|labor participation, work hours and source samples;分开是否就业、收入和时长，检查样本进入方式|separate employment, income and hours and check sample entry;只比较仍有工作的人，退出者被完全遗漏|comparisons include only retained workers and omit leavers;就业者之间的差异不能代表所有人的政策效果|differences among employed people do not represent a policy effect on everyone
macro;economics;宏观|增长|货币|发展经济;统计修订版本、时期与总量口径|statistical revisions, periods and aggregate definitions;区分名义变化、实际变化与统计修订|separate nominal changes, real changes and statistical revisions;历史序列修订后被当成当时就可见的数据|a revised historical series was treated as available at the time;后来的修订资料不能倒填进当时的信息集|later revisions cannot be inserted into the earlier information set
accounting;management;会计|审计|财务报告|盈余|内部控制;确认时点、报表口径与审计证据|recognition dates, reporting definitions and audit evidence;对齐会计期间与合并范围，保留口径变动|align accounting periods and consolidation boundaries and retain definition changes;合并范围扩大，被直接写成原业务增长|expanded consolidation was described as growth of the original business;报表变化需要区分业务变化与确认口径变化|report changes need to distinguish business changes from recognition changes
asset-pricing;economics;资产定价|金融计量|量化|风险度量;收益时期、风险因子与信息时间轴|return periods, risk factors and information timelines;比较同一信息集下的风险调整表现|compare risk-adjusted performance under the same information set;模型在回看样本拟合很好，换时期误差明显变大|retrospective fit deteriorates in another period;样本内拟合不能独立证明预测或定价能力|in-sample fit does not alone establish forecasting or pricing ability
translation;literature;翻译|译文|译介;原文版本、译文取舍与目标读者|source editions, translation choices and target readers;把准确、语境和翻译目的分别讨论|discuss accuracy, context and translation purpose separately;为目标读者改写的句子被按逐词对应评价|a reader-adapted passage was evaluated by word-for-word correspondence;译文评价必须说明目的与语境，而不只是相似词数|translation assessment needs purpose and context, not only matching words
language-learning;literature;第二语言|习得|双语学习|外语教育;学习阶段、任务条件与学习者反应|learning stages, task conditions and learner responses;区分语言知识、任务熟悉和实际使用表现|separate language knowledge, task familiarity and use performance;练熟同一套题的提高被写成普遍语言能力提高|improved performance on practiced items was described as general proficiency;练习题表现不能独立代表新情境下的语言运用|practice-item performance does not alone represent use in new contexts
digital-humanities;literature,history;数字人文|数字文本|文本编码|数字史料;文本版本、识别误差与编码规则|text editions, recognition errors and coding rules;抽查数字化误差，保留文本到指标的转换|sample digitization errors and retain the transformation from text to indicators;识别错误集中在旧版字体，词频变化被误写成思想变化|recognition errors in older typefaces were described as changes in thought;文本计数必须回到版本和语境检验解释|text counts need edition and context checks for interpretation
historical-geography;history;历史地理|地图|空间变迁;历史地名、图件年代与地方文献|historical place names, map dates and local sources;区分地名沿用、空间范围变化与图件绘制时间|separate persistent names, boundary changes and map-production dates;同名地名在两幅图上其实指不同范围|the same place name refers to different boundaries on two maps;地名相同不能独立证明空间对象连续|the same name does not alone establish spatial continuity
archaeometry;history;科技考古|考古测量|年代测量|保护科学;材料语境、测量不确定性与保存状态|material context, measurement uncertainty and preservation state;对照材料进入测量的语境和年代解释|match material context to measurement and chronological interpretation;材料测得的年代被直接等同于整处遗址的年代|a material date was equated with the date of an entire site;材料年代和遗址活动年代需要解释连接|material dates and site-activity dates need an interpretive connection
crop-breeding;agriculture;遗传育种|育种|种质|品种|种子;种质背景、目标性状与多环境表现|germplasm backgrounds, target traits and multi-environment performance;区分遗传背景、环境变化与目标性状取舍|separate genetic backgrounds, environmental changes and trait tradeoffs;只在一个环境表现好的材料被写成全面更优|material performing well in one environment was described as universally superior;单环境表现不能替代稳定性和多性状比较|single-environment performance does not replace stability and multiple-trait comparisons
remote-sensing;science,engineering,interdisciplinary;遥感|地球观测;影像日期、空间分辨率与地面参照|image dates, spatial resolutions and ground references;对齐时间与尺度，保留未能观测的区域|align times and scales and retain unobserved areas;云遮挡区域被当成地表没有变化|cloud-obscured areas were treated as unchanged land;影像缺测不等于地表状态没有变化|missing imagery does not mean unchanged surface conditions
area-studies;interdisciplinary;区域国别|区域研究|国别|国际区域;当地文献、语言版本与制度语境|local sources, language versions and institutional contexts;分开本地概念、译词与跨地区比较框架|separate local concepts, translations and comparative frameworks;同一个译词遮住了两地制度含义的差别|a common translation hides different local institutional meanings;跨地区比较需要解释对象如何可比|cross-region comparison needs an account of comparability
heritage;interdisciplinary,arts,history;遗产|保护|博物馆|策展;对象来源、保存状态与展示解释|object provenance, preservation state and exhibition interpretation;区分保存目标、展示叙事与使用者理解|separate conservation goals, exhibition narratives and user understanding;展示采用的复原想象被游客当成确定历史|visitors treat an imagined reconstruction as established history;复原与展示解释需要标明依据和不确定性|reconstructions and display interpretations need evidence and uncertainty labels
logic;philosophy;逻辑|语义|证明论|模型论;形式语言、语义结构与推导树|formal languages, semantic structures and derivation trees;分清语法推导与语义有效性，核对所用系统|distinguish syntactic derivation from semantic validity and check the system used;一个规则从另一套逻辑系统借来，前提却没跟过来|a rule was borrowed from another logic without its premises;在一套系统中成立不等于在所有逻辑中成立|validity in one system does not establish validity in every logic
ethics;philosophy;伦理|道德|价值|责任|规范;价值理由、冲突案例与行动者立场|value reasons, conflict cases and agents’ positions;说明理由如何支持规范判断，检查反例是否公平|explain how reasons support a normative judgment and whether counterexamples are fair;支持率最高的做法被写成道德上最正当|the most popular action was described as morally best justified;事实上的偏好不能独立推出应当如何行动|observed preferences do not alone establish what ought to be done
epistemic;philosophy;认识|知识|证成|证言|怀疑|科学解释;知识主张、证成理由与反例|knowledge claims, justificatory reasons and counterexamples;区分相信、为真与有理由相信，核对论证对象|distinguish belief, truth and justified belief and check the argument’s target;一个幸运猜中的例子被当成可靠知识|a lucky correct guess was treated as reliable knowledge;碰巧为真不等于已解释知识何以成立|accidental truth does not explain how knowledge is established
philosophical-history;philosophy;中国哲学|西方哲学|思想史|儒|道家|佛教|宗教|文本;原典版本、术语译法与思想语境|source editions, term translations and intellectual contexts;分开原典用词、后世解释与现代重构|separate source usage, later commentary and modern reconstruction;现代译词让两段原典看起来讨论同一个概念|modern translations make two passages appear to discuss the same concept;译词相同不能独立证明概念连续或立场相同|the same translated term does not establish conceptual continuity or agreement
orthopedic;medicine;关节|脊柱|骨创伤|骨与|骨科|软骨|步态|植入物|运动损伤;影像随访、步态任务与功能评价记录|imaging follow-up, gait tasks and functional assessments;区分结构变化、疼痛报告与功能表现|separate structural changes, pain reports and functional performance;影像评分变好了，日常活动的记录却没有变化|image ratings improved without a change in daily-activity records;结构表现不能直接替代患者功能结局|structural findings do not directly replace functional outcomes
urologic;medicine;泌尿|排尿|盆底|男性健康|结石;症状日记、检查日期与生活质量记录|symptom diaries, examination dates and quality-of-life records;对齐症状记录窗口与功能评价条件|align symptom recording windows with assessment conditions;症状日记只填了工作日，遗漏最不方便的时段|diaries include only working days and omit difficult periods;部分时段的体验不能代表完整生活质量|experience during selected periods does not represent overall quality of life
skin;medicine;皮肤|瘢痕|毛发|创面|屏障|外观;拍摄条件、分级意见与患者体验记录|image conditions, grading judgments and patient experiences;保留照明、评分者和填答时点的差异|retain lighting, rater and response-time differences;前后照片光线不同，外观改善被写得过满|different lighting inflated the account of appearance improvement;外观照片不能独立证明功能或生活质量改善|appearance photographs alone do not establish functional or quality-of-life improvement
anatomy;medicine,science;解剖|组织与发育|系统生理|生理|发育;结构图谱、发育阶段与功能观察记录|structural atlases, developmental stages and functional observations;对应结构、阶段与观察条件，不用形态代替功能|match structures, stages and conditions without substituting morphology for function;不同发育阶段的记录被排成同一个正常基线|different developmental stages were merged into one normal baseline;结构相似不自动证明功能相同|similar structures do not automatically establish similar function
forensic;medicine;法医|鉴定|物证;材料来源链、鉴定问题与意见版本|provenance chains, assessment questions and opinion versions;核对材料如何进入分析，区分观察与鉴定推论|check how materials entered assessment and separate observations from inferences;转交资料只保留摘录，关键上下文没有随附|transferred extracts omit essential context;结论必须受材料来源和委托问题的限制|an opinion is limited by provenance and the question commissioned
health-services;medicine;健康服务|卫生政策|卫生经济|医疗服务|临床信息|健康经济;服务路径、支付口径与使用者反馈|service pathways, payment definitions and user feedback;分开服务可及、使用与结果，核对就医选择|separate access, use and outcomes and check care-seeking selection;使用服务的人原本就更容易获得后续随访|service users already had better access to follow-up;服务使用差异不能直接视作服务效果|differences in service use do not directly establish service effects
review-study;medicine;临床研究设计|循证|证据综合|系统综述|医学文献;研究设计、纳入标准与结局定义|study designs, eligibility criteria and outcome definitions;比较对象与设计后再合并证据，保留不一致|compare populations and designs before synthesizing evidence and retain disagreements;同名结局来自不同测量窗口却被合成同一个结果|identically named outcomes from different windows were pooled;合并更多研究不自动提高证据可比性|combining more studies does not automatically improve comparability
cryptography;engineering,interdisciplinary;密码|密码学;安全定义、攻击者假设与证明步骤|security definitions, adversary assumptions and proof steps;逐项核对安全游戏和归约所需条件|check the security game and conditions needed by the reduction;结论用了比开头更弱的攻击者模型|the conclusion uses a weaker adversary than the opening claim;某个安全模型下的证明不能直接保证所有部署情境|a proof in one security model does not guarantee every deployment setting
database;engineering;数据库|数据工程|查询|事务;查询工作负载、事务记录与故障时间轴|query workloads, transaction records and fault timelines;分开延迟、吞吐量与一致性，标明故障期间的行为|separate latency, throughput and consistency and mark behavior during failures;高吞吐量来自放宽一致性，报告却只写性能提高|relaxed consistency produced throughput gains but the report only claims better performance;负载、语义与故障条件不同的分数不能直接排序|scores from different workloads, semantics and failures cannot be directly ranked
vision;engineering,interdisciplinary;计算机视觉|图像识别|视觉计算;图像来源、标注一致性与场景评估记录|image provenance, annotation consistency and scenario assessments;按来源分开开发与评估，核对遮挡和光照情境|separate development and assessment by source and check occlusion and lighting contexts;来自同一段视频的相邻帧跨进训练和测试|adjacent frames from one video enter both training and testing;测试分数需要说明是否见过相同来源与场景|test scores need an account of shared sources and scenarios
nlp;engineering,interdisciplinary;自然语言|语言模型|文本计算;语料体裁、任务定义与人工评阅记录|corpus genres, task definitions and human evaluations;区分流畅性、事实正确与任务完成|separate fluency, factual correctness and task completion;回答读起来很顺，引用的出处却无法对回原文|a fluent answer has citations that cannot be traced to the source;流畅表达和自动指标都不能单独证明事实可靠|fluency and automated scores alone do not establish factual reliability
library-science;management;图书|情报|信息管理|档案|知识组织|数字保存;目录字段、检索任务与版本保存记录|catalog fields, retrieval tasks and preservation versions;比较检索目标、相关性判断与来源完整性|compare retrieval goals, relevance judgments and source integrity;检索到了更多条目，但相同文献的副本占了大半|more results were found but duplicates make up most entries;条目数量不等于有效资料或长期可读性|entry counts do not establish useful material or long-term readability
tourism;management;旅游|游客|目的地|文旅;访问季节、游客行为与服务体验记录|visit seasons, visitor behavior and service experiences;区分游客群体、季节与目的地条件|separate visitor groups, seasons and destination conditions;节庆游客的评价被推广为全年居民体验|festival visitors’ responses were generalized to year-round residents;短期游客反馈不能代表所有使用者或全年状态|short-stay feedback does not represent every user or the whole year
aquatic;agriculture;水产|鱼|养殖|海水;水域条件、来源群体与生长记录|water conditions, source populations and growth records;区分水域、季节与个体差异|separate water bodies, seasons and individual variation;两组对象来自不同水域，差异却都归给一个管理因素|groups from different water bodies were attributed to one management factor;生长差异需要水域和群体背景的限定|growth differences need limits on water-body and population context
protection;agriculture;植保|植物保护|虫|病害|植物病|抗逆;受损记录、发生时期与管理背景|damage records, occurrence periods and management context;核对观察窗口、地块和受损定义|check windows, plots and damage definitions;观察只覆盖可达地块，未到的地方被填成无受损|accessible plots were observed while unvisited sites were entered as undamaged;覆盖不足不能直接证明全区域的发生程度|incomplete coverage does not establish occurrence across a region
animal-science;agriculture;畜|动物|饲料|繁殖;个体来源、群体管理与表现记录|individual provenance, group management and performance records;把个体、同群和管理条件分开比较|separate individuals, shared groups and management conditions;同一管理群的多次记录被当成不同来源|repeated records from one managed group were treated as different sources;一种群体条件下的表现不能直接推广到所有对象|performance in one group setting does not directly generalize to all subjects
rheumatic;medicine;风湿|关节炎|结缔组织;活动度量表、复诊时点与患者报告|activity scales, review dates and patient reports;区分评分者、症状时段与患者体验|separate raters, symptom periods and patient experience;活动度只在复诊时记录，缺诊者的状态未知|activity is recorded only at reviews, leaving nonattenders unknown;复诊记录不能代表所有时段与所有患者|review records do not represent all periods or all patients
cardiac;medicine;心脏|心血管|心肌|冠心|心律|心衰|心力衰竭;随访时点与心功能记录|follow-up dates and cardiac-function records;对齐基线与复查窗口，单列未复查者|align baseline and review windows and list people without a review separately;复查者的基线状态与未复查者不同|reviewed and unreviewed people differ at baseline;复查改善不能代表所有入组者，也不能直接解释治疗作用|improvement among reviewed participants neither represents all entrants nor establishes a treatment effect
respiratory;medicine;呼吸|肺|气道;肺功能版本、症状记录与复查日期|lung-function versions, symptoms and review dates;分开仪器版本与观察窗口，再核对失访|separate instrument versions and observation windows before checking loss to follow-up;新版设备上线恰好碰到随访间隔改变|an instrument upgrade coincides with changed follow-up intervals;测量变化与疾病变化要分别讨论|measurement change and disease change need separate explanations
digestive;medicine;消化|胃|肠|肝|胰|胆;内镜描述、病理索引与饮食记录|endoscopy descriptions, pathology indexes and diet records;保留同一人的不同检查日期，核对报告术语|retain examination dates within a person and check report terminology;饮食记录漏了周末，检查报告也换过模板|diet records omit weekends and examination templates changed;一次检查和一段生活记录不能共同证明长期过程|one examination and a short lifestyle record cannot establish a long-term process
metabolic;medicine;糖尿|代谢|内分泌|甲状腺|垂体|肾上腺|肥胖;代谢测量单位、设备版本与生活方式记录|metabolic units, device versions and lifestyle records;对照原始单位和记录时段，标明设备更换|check original units and recording periods and mark device changes;连续监测与门诊单次记录被合成了一个指标|continuous monitoring and single clinic readings were merged into one indicator;不同记录方式不能直接视作同一个暴露|different recording modes are not automatically the same exposure
renal;medicine;肾|透析|水盐;估计公式、检验时点与转院随访记录|estimation formulas, laboratory dates and transfer follow-up records;保留公式版本，检查转院后的结局是否缺失|retain formula versions and check outcomes after transfers;公式更新后，旧值和新值直接连成趋势|old and new formula values were joined into one trend;公式造成的差异不能写成病程加速|formula differences cannot be described as disease acceleration
hematology;medicine;血液|造血|贫血|凝血|血栓|血小板|输血;分型版本、形态复核意见与转诊来源|classification versions, morphology reviews and referral sources;保留分型更新前后对应表及读者分歧|retain classification crosswalks and reader disagreements;新转诊来源改变了分型构成|new referral sources change the classification mix;来源构成变化不等于疾病发生变化|a changed source mix is not a change in disease occurrence
neuro;medicine;神经|脑|认知障碍|癫痫|头痛;影像分区版本、任务记录与功能量表|image-parcellation versions, task records and functional scales;按个体核对时点，区分软件变化和练习效应|check times within people and separate software changes from practice effects;重复评估后的熟悉度被当成认知改善|familiarity after repeated testing was treated as cognitive improvement;量表变化不能独立定位神经机制|scale changes alone cannot locate a neural mechanism
oncology;medicine;肿瘤|癌|放疗;分期版本、随访截止与后续处置记录|staging versions, follow-up cutoffs and subsequent management records;区分结局定义、随访时长与后续处理|separate outcome definitions, follow-up duration and later management;短随访组与长随访组被直接比较|groups with short and long follow-up were compared directly;观察关联不能承诺个体疗效|an observational association cannot promise an individual benefit
infection;medicine;感染|传染|抗感染|宿主反应;转诊构成、编码版本与公开队列记录|referral mix, coding versions and public cohort records;核对登记定义与入组时期，不把编码变化当趋势|check registration definitions and entry periods rather than treating coding changes as trends;编码规则改变却没有留在时间轴上|a coding-rule change is absent from the timeline;病例登记变化不直接等于真实发生率变化|registration changes do not directly establish incidence changes
surgery;medicine;外科|手术|麻醉|急诊|重症|移植;过程记录、处置时间轴与结局定义|process records, management timelines and outcome definitions;区分术前状态、过程环节与术后观察|separate baseline status, process steps and later observations;同一个并发事件在两个表里用了不同定义|one complication has different definitions in two tables;过程先后不能独立证明某个环节造成结局|temporal sequence alone cannot establish which step caused an outcome
life-course;medicine;儿童|儿科|妇|产|围产|生殖|老年|衰弱;年龄窗口、照护者填答与阶段随访记录|age windows, caregiver responses and life-stage follow-up;按年龄和填答者区分量表，核对阶段转换|separate scales by age and respondent and check life-stage transitions;照护者代填与本人填答被混为同一体验|caregiver and self-reported responses were treated as the same experience;跨年龄或跨填答者比较需要另外说明可比性|comparisons across ages or respondents need an account of comparability
oral;medicine;口腔|牙|颌;检查部位索引、影像与评分者意见|site indexes, images and rater comments;区分牙位、个体和评分者，保留不同判断|separate sites, people and raters and retain disagreements;多个牙位被当成多个互不相关的人|multiple sites were counted as unrelated people;部位差异不能直接推广为人群差异|site differences cannot directly be generalized to population differences
sensory;medicine;眼|耳|鼻|喉|听力|视力;功能测试条件、侧别与重复评估记录|functional-test conditions, laterality and repeated assessments;把侧别与个体对应，核对测试环境|link sides to people and check the testing environment;两侧测量与同一人的复测被摊成独立样本|bilateral and repeated measurements were flattened into independent observations;重复测量增多不等于独立对象增多|more repeated measurements do not mean more independent subjects
nursing;medicine;护理|照护;班次交接表、护理过程与患者体验记录|shift handovers, care processes and patient-experience records;区分护理实施、交班记录和患者报告|separate delivered care, handover documentation and patient reports;交班表写了完成，患者记录却没有同一时段的反馈|the handover says completed while patient feedback is missing for that period;流程完成不等于患者体验改善|process completion does not establish improved patient experience
rehab;medicine;康复|辅助|功能训练;功能任务、量表版本与家庭参与记录|functional tasks, scale versions and home participation records;对照任务目标、评估者和真实使用情境|compare task goals, assessors and actual use contexts;训练场上的表现被直接写成日常功能恢复|training performance was described as recovery in everyday life;受控任务表现不能代替生活参与结局|controlled task performance does not replace participation outcomes
population;medicine;预防|公共卫生|流行|卫生|健康传播|人群|营养;登记分母、调查框与健康服务记录|registration denominators, sampling frames and health-service records;先核对覆盖人口与时期，再比较比例|check population coverage and periods before comparing proportions;宣传活动后登记入口增加，被误写成风险突然升高|expanded registration after outreach was described as a sudden risk increase;登记或问卷结果需要覆盖范围和选择过程的限定|registry or survey results require limits on coverage and selection
pharma;medicine;药|制剂|药物|药理|药代|药剂;药物来源、测量单位与作用评价记录|compound provenance, measurement units and effect-assessment records;分开作用信号、暴露条件与安全性记录|separate effect signals, exposure conditions and safety records;不同来源的作用指标换算后看似一致，原口径却不同|converted effect indicators look consistent despite different original definitions;一个作用指标不等于有效、安全或可用于临床|one effect indicator does not establish efficacy, safety or clinical usefulness
imaging;medicine;影像|病理|检验|超声|核医学;设备平台、读者判断与个体索引|platforms, reader judgments and person indexes;按个体划分记录，保留平台版本和读者分歧|partition by person and retain platform versions and reader disagreements;一人的多张图像同时进入开发和评估资料|images from one person enter both development and assessment;图像数量不能代替独立个体和外部评估|image counts cannot replace independent people and external assessment
biomedical;medicine,science,agriculture;细胞|分子|遗传|组学|蛋白|免疫|生物|微生物|病原|病毒|细菌;样本来源、批次索引与注释版本|sample provenance, batch indexes and annotation versions;区分生物对象与重复测量，核对批次构成|separate biological subjects from repeated measurements and check batch composition;最强的一组差异恰好全部来自同一批次|the strongest differences all come from one batch;高维差异或数据库关联不能独立证明机制|high-dimensional differences or database associations cannot alone establish a mechanism
traditional;medicine;中医|中药|方剂|经方|针灸;术语来源、辨识规则与研究记录|term sources, classification rules and research records;把历史解释、现代观察与具体评价分别记下|record historical interpretation, modern observation and assessment separately;不同文献中的同名分类被直接合并|identically named categories from different sources were merged;传统解释与现代评价之间需要明确证据接口|traditional explanations and modern assessments need an explicit evidence interface
vet;agriculture;兽|动物健康|动物医学;物种、来源群体与健康观察记录|species, source populations and health observations;区分个体与群体，保留来源和观察条件|separate individuals from groups and retain source conditions;来自同一养殖场的记录被看作互不相关|records from one holding were treated as unrelated;一种物种或场景的结果不能直接推广到另一种|results in one species or setting do not directly generalize to another
crop;agriculture;作物|栽培|种子|育种|园艺|蔬菜|果|茶|农艺;地块、品种、季节与管理记录|plots, varieties, seasons and management records;比较时同时核对地块条件和管理差异|check plot conditions and management differences together;看似较好的品种恰好都在同一块地|the apparently better variety is concentrated in one plot;品种差异与地块、季节效应不能混在一起|variety differences cannot be conflated with plot and season effects
ecology;agriculture,science,engineering;林|生态|环境|土壤|水文|气候|海洋|地理|地质;采样位置、时间窗口与环境背景记录|locations, time windows and environmental context;画出实际覆盖范围，保留天气与缺测时段|map actual coverage and retain weather and missing periods;雨后未能到达的点被填成没有变化|inaccessible post-rain sites were filled in as unchanged;缺测不是零，局部观察不能代替整个区域|missing is not zero and local observations cannot represent the whole region
food;agriculture,engineering,medicine;食品|食物|加工|营养;批次来源、评价条件与保存时间记录|batch sources, evaluation conditions and storage times;把批次与评价顺序分开，保留原始口径|separate batches from evaluation order and preserve definitions;同一批次重复评价被当作不同来源|repeat assessments of one batch were counted as different sources;评价信号不直接证明实际消费情境的效果|assessment signals do not directly prove an effect in consumption contexts
math;science,engineering,economics;数学|分析|方程|代数|几何|拓扑|组合|优化|概率|数理|运筹;定义、引理依赖与边界例子|definitions, lemma dependencies and boundary examples;逐步标出用到的条件，再检验退化情形|mark assumptions used at each step and inspect degenerate cases;证明中途用了命题开头没有写的条件|the proof uses an assumption absent from the statement;算例不能替代证明，也不能替缺失条件背书|examples do not replace a proof or justify omitted assumptions
statistics;science,medicine,economics,management;统计|计量|因果|测量理论|数据分析;独立对象索引、缺失模式与模型诊断|independent-unit indexes, missingness patterns and model diagnostics;先说明估计目标和独立单位，再看不确定性|state the estimand and independent unit before uncertainty;同一对象的多次记录被当成更多独立证据|repeated records of a subject were treated as additional independent evidence;显著性与精度不能替代设计和识别条件|significance and precision do not replace design or identification conditions
physics;science;物理|凝聚|光|粒子|量子|声|天体|宇宙|天文;标定、背景信号与模型近似记录|calibration, background signals and model approximations;对照背景与测量条件，说明近似成立的范围|compare background and measurement conditions and state approximation limits;修正背景的方法恰好抹掉了想解释的差异|background correction removes the difference under study;曲线拟合相似不等于物理解释唯一|a similar fitted curve does not make a physical explanation unique
chemistry;science,engineering;化学|材料|高分子|催化|晶|表征|电化学;材料批次、表征条件与使用环境记录|material batches, characterization conditions and use environments;比较结构描述、测量设置和状态变化|compare structure descriptions, settings and changes of state;最漂亮的表征来自没有进入其他评价的批次|the best characterization comes from a batch absent from other assessments;单项表征不能直接代表稳定性与使用表现|one characterization does not establish stability or use performance
computing;engineering,science,interdisciplinary;机器学习|人工智能|识别|深度学习|模式|智能|推荐;数据来源、对象划分与外部评估记录|data provenance, subject splits and external assessment records;检查训练与评估是否共享对象，核对时间边界|check shared subjects across training and evaluation and respect time boundaries;随机划分把同一来源的信息带进了评估|random splitting carries source information into evaluation;内部高分不等于换场景后仍然可靠|a high internal score does not establish reliability in a new setting
software;engineering,science;软件|系统|数据库|网络|计算机|编译|分布|安全|云|存储;运行版本、依赖清单与故障日志|runtime versions, dependencies and fault logs;在同一条件下复查，区分环境与功能变化|recheck under matched conditions and separate environment from functional changes;演示机上的默认参数与实际使用环境不同|demo defaults differ from the use environment;一次运行成功不等于稳定性或可复现性|one successful run does not establish stability or reproducibility
interaction;engineering,arts;人机|交互|用户|可用|产品|服务设计;任务脚本、原型版本与用户反馈|task scripts, prototype versions and user feedback;对照用户目标与任务完成，保留失败路径|compare user goals with task completion and retain failure paths;熟人试玩的评价被当作目标用户反馈|feedback from familiar testers was treated as target-user evidence;喜欢作品与完成任务不是同一个结局|liking a product and completing a task are different outcomes
electronics;engineering;电子|电路|传感|信号|通信|电磁|微波|集成|芯片|半导体;信号标定、器件状态与测试条件|signal calibration, device states and test conditions;把仿真参数与实际测量条件逐项对应|match simulation parameters to measurement conditions;两次测量的信号差异来自标定版本|calibration versions explain differences between measurements;仿真和台架表现不能直接代替现场可靠性|simulation and bench performance do not replace field reliability
mechanical;engineering;机械|力学|控制|自动|机器人|航空|航天|车辆|船|交通|能源|动力|电气;工况、台架日志与接口版本|operating conditions, test-rig logs and interface versions;对照载荷范围、控制条件和实际接口|compare load ranges, control conditions and actual interfaces;新接口下的失败被归到原来的模型上|a failure under a new interface was attributed to the old model;演示通过不能证明所有工况下有效|a successful demonstration does not establish validity under every condition
construction;engineering;建筑|城乡|规划|土木|结构|建造|水利|测绘|矿;场地资料、设计版本与约束清单|site records, design versions and constraint lists;让方案与场地、规范假设和反馈对应|match designs to sites, stated constraints and feedback;委托方改了用途，旧方案仍按原指标验收|the client changed the use but the design retained old acceptance criteria;方案可行性要对应具体场地与用途|feasibility must correspond to a particular site and use
economics;economics;经济|劳动|发展|产业|贸易|财政|税|公共|资源|市场|就业|家庭;分配规则、样本来源与比较组记录|allocation rules, sample sources and comparison groups;核对选择过程与政策时点，区分描述和识别|check selection and policy timing and distinguish description from identification;参与者原本就与未参与者不同|participants already differ from nonparticipants;相关关系不能直接写成政策因果效果|correlation cannot directly be described as a causal policy effect
finance;economics,management;金融|资产|银行|保险|风险|证券|投资|财务|会计|审计;信息发布时间、风险口径与会计定义|information release times, risk definitions and accounting definitions;对齐信息可获得时间，保留口径变化|align information availability and retain definition changes;评价用了当时尚未公开的信息|assessment uses information unavailable at the time;回看表现不等于事前决策能达到同样结果|retrospective performance does not establish prospective decision performance
organization;management;组织|管理|运营|工商|人力|物流|供应|战略|创新|创业|工业工程;流程文件、岗位访谈与交付记录|process documents, role interviews and delivery records;分开正式规定与实际执行，再核对责任接口|separate formal rules from practice and check responsibility interfaces;文件上已经交接，执行者却没有收到材料|documents say handed over but the recipient has no materials;制度设计不等于实际执行或组织绩效|institutional design does not establish implementation or performance
policy;law,management;公共|政策|行政|治理|政治|国际关系|比较政治;制度文本、执行材料与对象反馈|institutional texts, implementation records and participant feedback;比较制度情境，保留执行层次与时间|compare institutional contexts and retain levels and periods of implementation;两个地方用了同名制度，执行条件却不同|two places use the same institutional label under different conditions;制度名称相同不保证比较对象相同|the same institutional name does not establish comparable cases
law;law;法|诉讼|权利|刑|证据|司法|规范;规范版本、案件事实与裁判理由|norm versions, case facts and adjudicative reasons;区分效力、事实认定与规范推论|separate validity, findings of fact and normative inference;援引的条文版本与案例发生时期不对应|the cited norm version does not match the case period;案例数量不能独立证明规范应如何解释|case counts do not alone determine normative interpretation
society;law;社会|调查|人口|人类学|民俗|民族|关系|田野;抽样框、访谈语境与参与关系记录|sampling frames, interview contexts and participation relationships;保留访问条件、研究者位置与沉默的对象|retain access conditions, researcher position and unheard participants;愿意受访的人恰好集中在同一种关系网络|willing participants cluster within one relationship network;受访叙述不能直接代表所有群体|interview accounts do not directly represent every group
philosophy;philosophy;.;原文段落、概念定义与论证前提|source passages, concept definitions and argumentative premises;把作者原意、解释与自己的推论分开|separate the source position, interpretation and personal inference;关键术语在两位作者那里承担不同作用|a key term has different roles in two authors;经验例子不能独立解决规范或概念争议|empirical examples alone do not settle normative or conceptual disputes
psychology;education,medicine,law;心理|认知|行为|心理测量;任务说明、构念定义与被试反应记录|task instructions, construct definitions and participant responses;核对任务操纵与测量含义，保留练习顺序|check task manipulations and measurement meanings and retain practice order;中途改过指导语，却把前后得分直接合并|changed instructions were followed by direct pooling of scores;任务指标不能直接等同于完整心理构念|a task indicator is not identical to a complete psychological construct
education;education,medicine;教育|教学|课程|学习|教师|学校|学前|特殊;课堂目标、活动记录与学习过程材料|classroom goals, activities and learning-process materials;让任务、教学目标与评价对应，保留班级差异|match tasks, teaching goals and assessment and retain class differences;换了老师也换了活动，改善却全归到工具上|teacher and activity changes were attributed entirely to the tool;课后高分不能独立证明某项教学设计有效|higher later scores do not alone prove an instructional design effective
sport;education;运动|体育|训练|竞赛|健身;训练负荷、测试环境与恢复记录|training loads, test environments and recovery records;对照负荷与恢复时间，区分熟悉任务与真实进步|check loads and recovery and separate task familiarity from progress;状态最好的同学恰好都在较充分休息后测试|the best-performing participants were all tested after more rest;一次成绩不能代表长期训练效应|one performance cannot represent a long-term training effect
language;literature;语言|语法|语音|语义|语用|话语|翻译|习得|词|双语;语料出处、体裁、语境与标注记录|corpus provenance, genres, contexts and annotations;保留语境与标注分歧，再比较表达功能|retain context and annotation disagreements before comparing functions;反问句在自动标注里全被计为普通陈述|rhetorical questions were all annotated as ordinary statements;频率差异不能脱离体裁和语境解释|frequency differences need genre and context for interpretation
literature;literature;文学|文本|诗|小说|叙事|比较|文艺|修辞;作品版本、发表语境与引文出处|text editions, publication context and quotation sources;对照版本差异，区分人物话语与作者判断|compare editions and distinguish character speech from authorial judgment;后来的删改本被当成作品初刊的原貌|a later revised edition was treated as the first publication;局部引文不能独立支撑整段时代或作者判断|a local quotation alone cannot support a whole account of an era or author
media;literature,law,arts;新闻|传播|媒介|出版|广告|视听|影视;传播时间、平台机制与受众资料|distribution timing, platform mechanisms and audience records;分开内容、推荐入口与实际触达|separate content, recommendation routes and actual reach;平台推荐规则改变，被写成受众兴趣突然转向|changed recommendations were described as a sudden shift in audience interests;可见互动不能代替全部受众的态度|visible interactions do not represent every audience member’s attitude
history;history;.;史料出处、形成时间与版本传承|source provenance, formation dates and textual transmission;把事件时间、成文时间与后人解释分开|separate event dates, writing dates and later interpretations;多年后的回忆被当成事件当天的记录|a later memoir was treated as a contemporary record;后来的知识不能倒填给当时的行动者|later knowledge cannot be attributed to actors at the time
archaeology;history;考古|文物|遗产|器物|层位|古建筑;出土语境、层位记录与器物比较材料|find contexts, stratigraphic records and comparative objects;核对层位、扰动与比较对象的年代|check layers, disturbances and the dates of comparative objects;脱离出土语境的器物被用来定整处遗址的年代|an uncontextualized object was used to date an entire site;形制相似不能独立证明同一年代或交流关系|similar form does not alone establish the same date or cultural contact
arts;arts;艺术|美术|视觉|绘画|雕塑|设计|策展|工艺;创作版本、展示语境与观众反馈|creative versions, display contexts and audience feedback;对照创作意图、形式变化与实际观看经验|compare intentions, formal changes and viewing experiences;预展熟人的反馈被用来代表公众观看|familiar preview feedback was treated as public reception;表达意图不能直接等同于观众理解|creative intention is not identical to audience understanding
performance;arts;音乐|表演|舞蹈|戏|舞台|曲|声乐;排练版本、演出条件与听众反馈|rehearsal versions, performance conditions and audience feedback;区分练习状态、现场条件与审美判断|separate rehearsal state, live conditions and aesthetic judgment;试演场地和正式演出场地的声音条件不同|trial and public venues have different acoustic conditions;一次演出反馈不能代表作品全部接受史|one performance response cannot represent a work’s entire reception
military;military;.;公开史料、概念来源与抽象推演假设|public historical sources, concept origins and abstract scenario assumptions;保留史料形成时期与推演前提，不倒填事后知识|retain source periods and scenario premises without hindsight;推演者提前知道了历史上的结局|scenario participants were given the historical outcome in advance;抽象推演不等于现实预测或操作方案|an abstract scenario is neither a real-world prediction nor an operational plan
cross;interdisciplinary;.;两侧对象定义、资料单位与方法接口|object definitions, data units and methodological interfaces from both fields;分别保留两侧依据，再检查接口是否改变含义|retain each field’s evidence and check whether the interface changes meaning;两边同名的指标实际测量不同对象|identically named indicators measure different objects across the fields;组合两种方法不自动形成跨学科证据|combining methods does not automatically establish interdisciplinary evidence
`;
 const packets=rows.trim().split('\n').map(line=>{const[id,families,match,...cells]=line.split(';');return {id,families:families.split(','),match:new RegExp(match),...Object.fromEntries(['material','check','snag','limit'].map((key,i)=>[key,P(...cells[i].split('|'))]))};});
 // Specific packets precede general ones. Some broad packets match all members of
 // one family; test narrow patterns first rather than letting that swallow them.
 const broad=new Set(['philosophy','history','military','cross']);
 function classify(d){const route=C.projects.find(p=>p.id===d.route),allowed=packets.filter(p=>p.families.includes(route.family));let narrow=allowed.filter(p=>!broad.has(p.id));
  const use=(id,basis='host-discipline')=>({packet:packets.find(p=>p.id===id),basis});
  if(/教育|教学|课程/.test(d.name)&&!/教育史|教学史|课程史/.test(d.name)&&!['history','military'].includes(route.family))return use('education','method');
  // The host meaning precedes ambiguous words: analytical chemistry is not
  // mathematical analysis, atomic physics is not molecular biology.
  if(d.route==='theory')return use(/计算数学|数值/.test(d.name)?'numerical':/优化|运筹/.test(d.name)?'optimization':'math');
  if(d.route==='film-studies')return use('media');
  if(['agriculture','agri-economics'].includes(d.route)&&/经济/.test(d.name))return use('economics','method');
  if(['agriculture','agricultural-engineering'].includes(d.route)&&/工程/.test(d.name))return use('mechanical','method');
  if(['mechanical','automation','electrical-engineering'].includes(d.route)&&/控制|机器人|机电/.test(d.name))return use('mechanical','method');
  if(d.route==='chemistry')return use('chemistry');
  if(d.route==='physics'||d.route==='photonics'||d.route==='astronomy')return use('physics');
  if(d.route==='history')return use(/考古/.test(d.name)?'archaeology':/地理/.test(d.name)?'historical-geography':'history');
  if(d.route==='geography')return use(/人文|经济|城市|旅游|文化/.test(d.name)?'human-geography':/遥感|空间分析|地理信息/.test(d.name)?'remote-sensing':/教育/.test(d.name)?'education':'ecology');
  if(d.route==='aerospace')return use(/空间环境/.test(d.name)?'physics':/电子/.test(d.name)?'electronics':'mechanical');
  if(d.route==='communications'||d.route==='instruments-engineering')return use('electronics');
  if(d.route==='environment'||d.route==='ecology-studies')return use(/化学/.test(d.name)?'chemistry':'ecology');
  if(d.route==='statistics')return use('statistics');
  // Host discipline controls methods: cardiac nursing is nursing, cardiac images
  // are imaging, and drug metabolism is not automatically a clinical cohort.
  const explicit={'clinical':'review-study','health-policy':'health-services','health-economics':'health-services','orthopedics':'orthopedic','urology':'urologic','plastic-surgery':'skin','dermatology':'skin','anatomy-physiology':'anatomy','forensic-medicine':'forensic','science-history':'history','armament-history':'military','military-technology-history':'military','information-management':'library-science','tourism-management':'tourism','aquatic-science':'aquatic','animal-science':'animal-science','plant-protection':'protection','rheumatology':'rheumatic','integrated-medicine':'traditional','special-medicine':'population'};
  // Broad clinical has its own subtopics; do not force all nine into study design.
  const host=(d.route!=='clinical'?explicit[d.route]:null)||(route.family==='medicine'?(/护理/.test(route.name)?'nursing':/中药/.test(route.name)?'traditional':/药学|药理|药剂/.test(route.name)?'pharma':/影像|检验|病理|核医学/.test(route.name)?'imaging':/康复/.test(route.name)?'rehab':null):null);
  if(host)return {packet:packets.find(p=>p.id===host),basis:'host-discipline'};
  if(route.family==='medicine'&&/影像|病理|检验|超声/.test(d.name))return {packet:packets.find(p=>p.id==='imaging'),basis:'method'};if(/人机|交互|可用性/.test(d.name)&&['engineering','arts'].includes(route.family))return {packet:packets.find(p=>p.id==='interaction'),basis:'method'};
  if(route.family==='medicine'&&/教学|教育/.test(d.name))return {packet:packets.find(p=>p.id==='education'),basis:'method'};
  const named=narrow.find(p=>p.match.test(d.name));if(named)return {packet:named,basis:'direction'};const parent=narrow.find(p=>p.match.test(route.name));if(parent)return {packet:parent,basis:'route'};const defaults={philosophy:'philosophy',economics:'economics',law:'society',education:'education',literature:'literature',history:'history',science:'physics',engineering:'mechanical',agriculture:'crop',medicine:'population',military:'military',management:'organization',arts:'arts',interdisciplinary:'cross'};return {packet:packets.find(p=>p.id===defaults[route.family]),basis:'family'};}
 const banks=new Map();
 const question=(d,q,kind)=>P(({literature:'「'+d.name+'」：文献结论不一致时，怎样用'+q.material+'判断两篇工作是否真的在回答同一个问题？',method:'「'+d.name+'」：如果'+q.snag+'，现有比较会混入什么？你先核对哪一个条件？',record:'「'+d.name+'」：只看到汇总页，能排除“'+q.snag+'”吗？需要回到哪些记录？',boundary:'「'+d.name+'」：同门想扩大结论，但'+q.snag+'。你能保留什么，必须撤回什么？',rehearsal:'「'+d.name+'」：把问题讲给非本专业的人，怎样解释“'+q.limit+'”，又不把它说成什么都不能知道？'})[kind],()=>({literature:`${E(d.name)}: when papers disagree, how can ${E(q.material)} reveal whether they answer the same question?`,method:`${E(d.name)}: if ${E(q.snag)}, what enters the comparison and which condition do you check first?`,record:`${E(d.name)}: can a summary rule out that ${E(q.snag)}? Which records must you reopen?`,boundary:`${E(d.name)}: a colleague wants a wider claim, but ${E(q.snag)}. What remains and what must be withdrawn?`,rehearsal:`${E(d.name)}: explain why ${E(q.limit)} to a non-specialist without claiming nothing can be known.`})[kind]);
 for(const d of D.all){const classified=classify(d),q=window.MEETING_DIRECTION_STUDY?.refine?.(d,classified.packet)||classified.packet,basis=classified.basis,problems=Object.fromEntries(['literature','method','record','boundary','rehearsal'].map(kind=>[kind,{id:d.id+'-question-'+kind,kind,title:question(d,q,kind),material:q.material,check:q.check,limit:q.limit}]));const bank={id:d.id,route:d.route,direction:d.name,topic:d.topic,packet:q.id,basis,refined:!!q.refinement,depthCase:q.depthCase||null,material:q.material,check:q.check,snag:q.snag,limit:q.limit,questions:problems,story:[P('课题「'+d.name+'」准备往前走。先排查一个可能的缺口：'+q.snag+'。在核对前，这还是问题清单中的一项。',()=>`Before advancing ${E(d.name)}, investigate a possible gap: ${E(q.snag)}. It remains a question until checked.`),P('「'+d.name+'」进入下一段。讨论时要回到'+q.material+'，先'+q.check+'；有没有解决问题，以实际行动的结果为准。',()=>`The next stage in ${E(d.name)} returns to ${E(q.material)}: ${E(q.check)}. Resolution depends on the actual action result.`),P('到了「'+d.name+'」这一轮的交接日，有人想把小结果写得更完整。你留下的记录会决定能说到哪里：'+q.limit+'。',()=>`At the ${E(d.name)} handover, someone wants a bigger account. The record sets its scope: ${E(q.limit)}.`)]};banks.set(d.id,Object.freeze({...bank,questions:Object.freeze(Object.fromEntries(Object.entries(bank.questions).map(([k,v])=>[k,Object.freeze(v)]))),story:Object.freeze(bank.story)}));}
 function get(id){return banks.get(id)||null;}
 function active(holder){const p=holder?.world?.artifact||holder?.weekContext?.world?.artifact,d=holder?.config?.direction||holder?.direction;return get(p?.direction||d);}
 function words(bank,kind,stance){const q=bank.questions[kind]||bank.questions.boundary,name=bank.direction;return P(({receipt:'我先对照「'+name+'」的实际准备记录，说明为何需要'+bank.material+'，怎样'+bank.check+'；'+bank.limit+'。具体问题是否排除，还得看核对结果。',bounded:'我这轮还拿不出「'+name+'」的完整核对。我会先查'+bank.material+'，重点看是否存在“'+bank.snag+'”；未查之前先收住这项解释。',claim:'我觉得「'+name+'」已经可以按一个完整结论讲了，暂时把这个差异放到附录，先推进后续讨论。',rehearsal:'我先讲「'+name+'」的问题，再讲现有材料怎样支持它，最后把'+bank.snag+'留作待查；不把流畅的试讲当成完成核对。'})[stance],()=>({receipt:`I will use my actual preparation for ${E(name)} to explain why ${E(bank.material)} matters and how to ${E(bank.check)}. ${E(bank.limit)}. Whether the concern is ruled out still depends on the checks.`,bounded:`I do not have a complete check for ${E(name)} this round. I will inspect ${E(bank.material)} for the possibility that ${E(bank.snag)}, keeping the claim narrow until then.`,claim:`I think ${E(name)} is ready for a complete account. I will move this discrepancy to the appendix and proceed with the discussion.`,rehearsal:`I will explain the question in ${E(name)}, how current materials support it, and why ${E(bank.snag)} still needs checking. A fluent rehearsal is not a completed check.`})[stance]);}
 function meeting(s,raw){if(!raw||s.weekContext?.world?.challenge||s.config?.challenge||s.weekContext?.config?.challenge)return raw;const story=raw.id==='route-story-question'?window.MEETING_ROUTE_STORIES?.selected(s):null,b=story?.direction?get(story.direction):active(s);if(!b||raw.project&&raw.project!==b.route)return raw;const known=raw.id?.startsWith('prepared-')||raw.id?.startsWith('reviewed-')||/-med-|special-/.test(raw.id)||raw.academicTalk||raw.flaw||raw.id==='live-followup'||raw.id==='side-story-question'||raw.id?.startsWith('route-story-question');if(!known)return raw;
  const kind=raw.flaw?.kind||raw.prepKind||raw.choices?.find(c=>c.prepared)?.prepared?.kind||({0:'rehearsal',1:'literature',2:'method',3:'record',4:'boundary',5:'method',6:'record',7:'rehearsal',8:'boundary'})[raw.phase]||'boundary',e={...raw,bankId:b.id,bankKind:kind,choices:raw.choices.map(c=>({...c}))};
  // Keep explicit failure/demo and joint-contribution replies intact. Other answers
  // retain their original consequences, availability and semantic action tokens.
  if(!raw.academicTalk&&!raw.id?.includes('story-question')){e.title=b.questions[kind]?.title||b.questions.boundary.title;e.quote=e.title;e.scene=P('老师用「'+b.direction+'」举了一个讨论案例：'+b.snag+'。请说明你会怎样辨别，并对照自己的实际准备回应。',()=>`A discussion case in ${E(b.direction)}: ${E(b.snag)}. Explain how to distinguish it and use your actual preparation.`);}
  if(raw.flaw||raw.id==='live-followup'){e.title=P('「'+b.direction+'」· '+raw.title,()=>`${E(b.direction)} · ${E(raw.title)}`);e.scene=P('这轮追问需要回到'+b.material+'：'+b.check+'。',()=>`This follow-up returns to ${E(b.material)}: ${E(b.check)}.`)+'\n\n'+raw.scene;}
  e.choices=e.choices.map(c=>{if(c.hardStop)return c;if(raw.flaw||raw.id==='live-followup'){const text=c.approach==='detail'?P('停下这一页，先'+b.check+'。说明原来的判断暂时缺哪项条件，接受这轮进度损失。',()=>`Pause this slide and ${E(b.check)}. State the missing condition and accept lost progress.`):c.approach==='cooperate'?P('请同门共同看'+b.material+'，列出各自能核对的部分，暂缓完整结论。',()=>`Ask a peer to examine ${E(b.material)}, divide the checks and postpone the full claim.`):P('撤回「'+b.direction+'」中超出材料的表述：'+b.limit+'。把未解决的部分明确留作后续。',()=>`Withdraw unsupported wording in ${E(b.direction)}: ${E(b.limit)}. Explicitly leave the unresolved part for follow-up.`);return {...c,text};}
   const generic=/当前课题的准备记录|一个能完成的补查|替章节取名|已经核对的记录|先承认这部分还不完整|疑难附录|本周已经准备的材料|目前还无法回答|解释草图|准备到了哪里|拿出这条支线的完整记录/.test(c.text);if(!generic&&!c.prepared&&!c.semantic&&!c.routeAnswer)return c;if(raw.academicTalk==='format'&&/故障/.test(raw.title)||c.semantic==='joint'||c.semantic==='promise'||c.semantic==='complete')return c;const stance=c.prepared?'receipt':c.semantic==='bounded'||c.flags?.honest?'bounded':c.flags?.chaos?'claim':'bounded';return {...c,text:words(b,kind,stance)};});return e;
 }
 function life(w,raw){if(!raw||w.config.challenge)return raw;const b=active(w);if(!b||raw.project&&raw.project!==b.route)return raw;const routeChoice=raw.choices?.find(c=>c.routeAction!==undefined),sideChoice=raw.choices?.find(c=>c.storyAction!==undefined);const kind=raw.prepKind;if(!routeChoice&&!sideChoice&&!kind)return raw;const e={...raw,bankId:b.id,choices:raw.choices.map(c=>({...c}))};
  if(routeChoice){const t=w.routeStories?.active;if(t&&t.direction===b.id&&t.projectVersion===w.world?.artifact?.version)e.scene=P('这条长线的方向核对卡：', 'Disciplinary check for this arc:')+'\n'+b.story[Math.min(2,t.step)]+'\n\n'+raw.scene;}
  if(sideChoice&&w.sideStories?.active?.direction===b.id){e.scene=raw.scene+'\n\n'+P('你把偶遇留下的线索放回「'+b.direction+'」来考虑：先核对'+b.material+'，留意'+b.snag+'。这件事是否值得继续，还要看它与本课题的关系。',()=>`Relate this incidental clue to ${E(b.direction)}: check ${E(b.material)} and watch for ${E(b.snag)}. Whether to continue depends on its connection to this project.`);}
  if(kind){e.title=P('「'+b.direction+'」· '+window.MEETING_PREPARATION.names[kind],()=>`${E(b.direction)} · ${E(window.MEETING_PREPARATION.names[kind])}`);e.scene=P('今天处理「'+b.direction+'」的'+b.material+'。先考虑一个可能的缺口：'+b.snag+'。这半天先'+b.check+'；完成到哪一步会留在实际准备记录里。',()=>`Today’s ${E(b.direction)} work uses ${E(b.material)}. ${E(b.snag)}; this slot will ${E(b.check)}. Only completed preparation is recorded.`);}
  return e;
 }
 const labels={literature:P('读文献时怎样比较','Comparing readings'),method:P('设计为何这样安排','Why this design'),record:P('从汇总回到原始材料','From summaries to sources'),boundary:P('结论能讲到哪里','The scope of a claim'),rehearsal:P('把复杂问题解释清楚','Explaining a complex question')};
 function delivery(id,kind,approach){const b=get(id);if(!b)return '';return approach==='brief'?P('先给一个短答：「'+b.limit+'」。再用实际准备记录解释'+b.material+'为何重要，不把没核过的细节塞进结论。',()=>`A short answer first: ${E(b.limit)}. Use actual preparation to explain why ${E(b.material)} matters, without adding unchecked details.`):P('先说明「'+b.direction+'」的适用范围：'+b.limit+'。随后对照实际笔记，把'+b.material+'中核过和未核过的部分分开。',()=>`Start with the scope in ${E(b.direction)}: ${E(b.limit)}. Separate checked and unchecked parts of ${E(b.material)} using actual notes.`);}
 function lesson(s,e,c,r){if(!e.bankId)return;const b=get(e.bankId),kind=e.bankKind||e.prepKind||c.prepared?.kind||'boundary';const rationale={literature:P('遇到不同结论，先对照研究问题与'+b.material+'，再看是不是对象、窗口或定义不同。只数支持与反对的文章，无法解释分歧。',()=>`When findings differ, compare the question and ${E(b.material)} and inspect objects, windows and definitions. Counting papers for and against does not explain disagreement.`),method:P('这题关注比较的条件，而不只是工作有没有做完。'+b.check+'，才能判断“'+b.snag+'”是否会改变原来的解释。',()=>`This question concerns comparison conditions rather than completion alone. ${E(b.check)} to decide whether ${E(b.snag)} changes the interpretation.`),record:P('汇总页会压掉一些差异。要回到'+b.material+'，确认每一项判断怎样从原始记录得到；多了一页汇总不等于多了独立证据。',()=>`Summaries hide differences. Reopen ${E(b.material)} to trace each claim; another summary page is not another independent piece of evidence.`),boundary:P(b.limit+'。缩小结论时，应指出具体缺口并保留仍能支持的部分，而不是把整份工作都说成没有意义。',()=>`${E(b.limit)}. Narrow a claim by locating the gap while retaining supported parts, rather than dismissing the entire work.`),rehearsal:P('讲得清楚要同时交代问题、依据和未决部分。故事可以帮助理解，不能替代'+b.material+'，也不能把例子悄悄变成普遍结论。',()=>`Clarity requires a question, evidence and unresolved parts. A story helps understanding but does not replace ${E(b.material)} or turn an example into a universal claim.`)};
  r.learning={direction:b.id,kind,title:labels[kind]||labels.boundary,text:rationale[kind]||rationale.boundary,eventId:e.id,version:s.weekContext?.world?.artifact?.version||null};
 }
 function archive(w,s){if(w.config.challenge)return;const old=w.learningNotes||[],newNotes=s.log.filter(r=>r.learning).map(r=>({...r.learning,week:w.number,question:r.title,answer:r.answer}));w.learningNotes=[...old,...newNotes].slice(-80);}
 // Correct biography research anchors using the same method ownership as play.
 const V=window.MEETING_RESEARCH_VIGNETTES;
 if(V){const original=V.forDirection;V.forDirection=d=>{const b=get(d?.id);if(!b)return original(d);const q=original(d);return {...q,topic:P(d.name+' · '+d.topic,()=>`${E(d.name)} · ${E(d.topic)}`),work:P(b.material+'的整理与比较',()=>`Organization and comparison of ${E(b.material)}`),problem:b.snag};};}
 return {get,active,banks,packets,classify,meeting,life,words,lesson,archive,labels,delivery,coverage:()=>D.all.map(d=>({id:d.id,name:d.name,route:d.route,packet:get(d.id).packet,basis:get(d.id).basis,questions:Object.keys(get(d.id).questions).length,storyStages:get(d.id).story.length}))};
})();
