/* Authored scene sequences; the existing engines own choices, timing and consequences. */
window.MEETING_EDITORIAL_SCENES={
 arcs:{
 compute:[
 ['电脑停在开机画面，风扇还转着，硬盘却认不出来。你昨天只把两张图发到了群里，日志和环境文件都在这台机器上。维修点的人看了接口，问有没有备份，然后说得先排检测。借设备的同门刚收到大修意见，把自己的电脑合上：“可以借，但别动我那个环境。我下周要把稿子交回去。”导师的消息也到了：周五先讲复现结果。','The computer is stuck at startup with no disk detected. Yesterday you sent two figures to the group, leaving logs and environment files on this machine. The repair desk asks about backups and a diagnostic queue. A peer offers a computer without changing the environment needed for next week’s revision. The supervisor still expects a replication report on Friday.'],
 ['机器能用了，屏幕上的曲线却不像旧图。你把两个窗口并排放着，同门过来看了一眼，先问名单是不是同一份。合作方发来压缩包，说旧版“应该就是这么跑的”，里面却少了一份输入说明。你想起当时为了赶截图，临时改过一个设置，具体改在哪里已经记不清了。离下一场汇报越来越近，得决定从旧文件里追，还是先在新环境做一个小例子。','Access returns, but the curve differs from the old figure. A peer asks whether the input lists match. A partner’s archive lacks one input note, and you vaguely remember changing a setting for the screenshot. Time is running short: reconstruct the old run or build a small example in the new environment.'],
 ['合作方发来的最终版幻灯片已经换上了另一张图，配色漂亮，趋势也干净：“展示先用这张吧，细节以后补。”你打开附件，输入名单仍没找到。借电脑的同门在群里提醒大家，他今晚要通宵修稿。你看着桌上的电源适配器，忽然意识到这件事已经不只是一张图：设备要还，报告要交，而你还没决定哪一部分结果愿意当众认领。','The partner’s final slides use a polished replacement figure: details can follow later, they say. The input list is still missing. The lending peer needs the computer for an overnight revision. Equipment, reporting and ownership of the result now meet at one decision.']],
 proof:[
 ['你在纸上圈住最后一个条件，来回看了三遍。删掉它，结论好像就不成立；留着它，报告标题又说得太大。导师刚从研讨会回来，记得你上次说过“应该可以推广”。同门答应一起看一会儿，打开自己的草稿时露出一张资格检查通知。两个人都缺时间。你把原文翻到定理那一页，第一次注意到证明开头还有一句没有抄进笔记的话。','One condition seems essential, yet the talk title claims a general result. Returning from a seminar, the supervisor remembers your promise to generalize. A peer can help briefly before a qualifying review. Reopening the original theorem reveals a sentence missing from your notes.'],
 ['同门把一个反例写在纸角，推到你面前。你先觉得它不符合定义，翻回原文才发现，两篇文章对同一个词用了不同约定。原来的六页推导也许能保住一半，但需要换一个更窄的命题。导师在群里问能否今天发一版，你们谁都没马上回复。桌上那张反例纸已经被咖啡洇湿了一角，偏偏是现在最有用的一张。','A peer offers a counterexample. Two sources use different conventions for the same term; half the derivation might survive as a narrower proposition. The supervisor asks for a draft today. The coffee-stained counterexample is suddenly the most useful page on the table.'],
 ['导师把新猜想写在白板最上面，问能不能“顺便”放进报告。原定时间仍是十五分钟。你包里放着已经改过的有限情形，同门则等着你把答应交换的推导发过去。白板越写越满，你要决定今天到底交哪一个版本：讲清已有的那一步，沿着新猜想继续冒险，还是把推广留成一个没有答案的问题。','The supervisor adds a broader conjecture to the whiteboard, although the talk remains fifteen minutes. You have a bounded result and owe a peer a derivation. Choose between the supported step, a risky broader claim or an explicitly open question.']],
 bench:[
 ['平台门上贴着停机通知，预约表旁边多了一行红字。管理员说维修件还没到，不能给你一个确定日期。你的旧记录本夹着一张没填完的条件表，原本打算这次补齐。隔壁组也来问空位，大家站在走廊上翻日历。导师想在阶段报告里放这组结果，现在先得回答：设备没开，手头还有哪部分能继续做？','The platform posts a downtime notice; the repair part has not arrived. Your notebook contains an unfinished conditions sheet intended for this visit. Another group wants a slot too. Before a stage report, decide what can continue without the equipment.'],
 ['管理员腾出一个短窗口，提醒结束后下一组马上接手。你翻出两份旧记录，同一栏的数值却差了一截，连材料标签也不完全一致。平台当天的状态表可以查，缺的那页笔记仍找不到。同门说先把最重要的一项看完，别试图在这个窗口里补回整个星期。你得在有限时间里决定，究竟查哪一个差异。','A short slot opens before the next group arrives. Old records disagree and material labels differ. The platform status sheet is available, but a notebook page is missing. There is time for the most important discrepancy, not the whole week’s work.'],
 ['学院催交阶段总结，模板里给每组留了一页。导师在草稿上划出一块位置，希望放最新结果。管理员提醒下一轮维护即将开始，借排期的同门也来确认归还。你手里有一部分整理好的记录，还有一部分只是旧文件里的漂亮图。填满这一页并不难，难的是决定哪张图下面，你愿意写上自己的名字。','The college requests a one-page stage summary. The supervisor wants the newest result, maintenance is approaching, and a peer needs the borrowed slot back. Some records are organized; other figures remain unchecked. Filling the page is easy, deciding what to sign is harder.']],
 clinical:[
 ['合作联系人发来一条语音，背景里有人叫他名字。他说排班变了，原定那段资料今天只能整理一半，剩下的得等下一轮。你已经把汇报目录写好了，现在第三页之后都是空的。熟悉现场的同门愿意帮忙问一次，但也提醒对方不是专门替课题服务的人。你删掉了一条催促消息，开始想怎样把这次交付重新谈清楚。','A busy partner says a schedule change leaves only half the material available. Your report becomes empty after page three. A knowledgeable peer can ask once, but the contact has ordinary duties too. You delete an impatient message and reconsider the deliverable.'],
 ['补来的表终于填满了，两个观察窗口却不同。联系人说上一份是按工作需要整理的，所以几列没有保留。你把表格打印出来，用两种颜色标记，越标越发现它们回答的不是同一个问题。导师问是不是可以先合起来看看。同门没有替你回答，只把空白的那一列指给你看。','The completed table covers two different observation windows; several old columns were never retained. Printed sheets in two colors reveal different questions. The supervisor asks about combining them, while a peer quietly points to the missing column.'],
 ['合作方要开内部讨论会，希望带走一句能用的判断。导师想把这次合作延续下去，也问你能否再讲完整一点。你眼前的记录只覆盖一小段情境，会上却可能有人把它写进下一年的计划。联系人说：“至少告诉我们，哪一部分你现在能确认。”这句话让你松了口气，也让你更难靠一个大标题混过去。','The partner wants one usable judgment for an internal meeting, and the supervisor hopes to continue the collaboration. The records cover only a small setting but may influence a broader plan. Asked what you can confirm now, you must choose the scope you can defend.']],
 field:[
 ['约好的对象取消见面，消息只有一句“最近不太方便”。车票还在订单里，访谈提纲已经打印。另一个联系人可以介绍人，却先问录音给谁听、整理稿会写到哪里。你原来觉得联系成功就算迈过了最难的一步，现在才发现还没开始。愿意牵线的同门也在赶自己的报告，问你什么时候能把新说明发过来。','The interview is cancelled with a brief message. Tickets and printed questions remain. A new gatekeeper asks who will hear recordings and where the account will appear. A peer can introduce someone, but needs your explanation before their own deadline.'],
 ['新对象讲了半个小时，几乎没有按你的提纲走。一个被你当成普遍经历的情境，在这里并不常见。你几次想把话题拉回来，最后停下了笔。对方看你不再写，问是不是这些不重要。你得决定继续追原来的比较，还是先把眼前这个人的经历讲完整；前一份访谈也突然显得没有那么简单。','The new participant scarcely follows the guide; an experience you thought common is unusual here. When you stop writing, they ask whether this is unimportant. Continue the original comparison or understand this person’s account, while reconsidering the first interview.'],
 ['对象看完整理稿，指着一句很鲜明的话说，这样写出去别人会知道是谁。导师觉得这段最能打动听众，删掉以后报告似乎少了一半力量。你收到对方第二条消息：“意思没错，但那天我不是在说所有人。”你把那句话从投影页复制到笔记里，重新读它前后的几行，准备决定这段故事怎样被讲出去。','The participant worries a vivid line will identify them and clarifies it was not about everyone. The supervisor considers it the strongest part of the talk. Re-reading the surrounding passage, you decide how this account can be told.']],
 archive:[
 ['阅览室临时检修，预约短信变成了延期通知。你手里那份转录没有完整书目信息，页码还属于另一版。编辑催一段可用的引文，同门说自己存过一张索引照片，得回去找。你把原来要放进报告的句子读了一遍，很顺口，顺口到有点不放心。现在能做的是等原件、借索引，或告诉导师这条引用还不能定。','Archive repairs postpone the visit. The transcription lacks full bibliographic details and uses another edition’s pages. An editor wants the quotation; a peer may have an index photo. The smooth sentence begins to feel suspicious before the original can be checked.'],
 ['原件上那个词比转录多一个字。你先以为是抄错，翻到编者说明才发现另一版有过系统整理。两种说法都能接进你的论证，却会把问题带到不同地方。阅览室快关门，旁边有人开始收书。你必须决定今天追哪一条来路，哪些页先留下索引，下次再看。','One word differs from the transcription. Editorial notes reveal systematic changes in another edition. Both readings fit the argument but lead in different directions. With closing time approaching, choose which provenance to trace and which pages to index for another visit.'],
 ['展板已经排版，编辑把最顺口的句子放到了中央。你的索引却显示，它是后来改写的，不是原作者当时的措辞。同门还等着你补回借去的版本表。编辑问能不能只改脚注，别动整体版面。你看着那行大字，决定是保住展示效果，还是让两个版本的分歧真正出现在读者面前。','The display features the smoothest sentence, but your index places it in a later rewrite. A peer awaits a borrowed edition table. The editor proposes changing only the footnote; decide whether the disagreement belongs in the display itself.']],
 survey:[
 ['委托方的邮件把“描述现状”改成了“比较方案”，还特意说这次只是小调整。你打开原来的表，根本没有新问题需要的几列。导师问能不能先帮对方渡过会议。对方联系人把标题发了三遍，每次更明确一点，交付日期却一动不动。你得先决定这句话算改题，还是算自己又多了一段活。','The client calls a switch from description to comparison a small adjustment. Your table lacks the needed columns. The title becomes clearer across three emails while the deadline stays fixed. Decide how to negotiate the new work.'],
 ['新表到了，数字整齐，表头也统一了。你查注释才发现，两组对象与统计时间都不同。联系人说旧表是为另一项工作做的，原始说明未必找得回来。几分钟就能拼出一张大表，重新整理却要花掉这半天。导师的会议还在等一个结果，你得决定让这张表回答多少问题。','The new table looks consistent until its notes reveal different populations and reporting periods. Old source notes may be missing. A large merged table is quick, a common definition takes the afternoon. Decide how much the table can answer.'],
 ['会议议程上已经有了你的标题，最后一栏写着“建议”。合作方说领导没时间听太多过程，导师想借这个结果谈下一项项目。你只复查过其中一张小表。打印机吐出整齐的一叠纸，你在第一页停了笔：这次是给出有限建议，带着缺口先交，还是撤回那个已经排进议程的结论？','The agenda already promises recommendations. The partner wants brevity and the supervisor sees a new project, but you checked only a small table. The printed packet forces a choice among bounded advice, incomplete delivery and withdrawing the announced conclusion.']],
 environment:[
 ['出发前，天气预报和场地通知同时变了。原地点关闭，另一个点可以进去，但地形和观察时段都不同。司机问还走不走，交通费已经报过一轮。同门把备用地图摊开，你发现替换地点也许会把整个比较改掉。得赶在大家上车之前决定：等窗口、借入口，还是重谈这轮观察范围。','Weather and site access change just before departure. The alternative site differs in terrain and time; transport funding was already arranged. A backup map reveals the comparison may change entirely. Decide before everyone boards.'],
 ['两处记录放在一起，时间差和尺度差都露出来了。制图同门把配色做得很连续，缺测地块看起来也像有结果。你关掉一个图层，白色空洞突然出现在屏幕中央。同门说这样交出去不好看，可现在这片空白比周围的颜色更接近你实际知道的情况。','Records disagree in time and scale. A polished map colors unobserved areas continuously; disabling a layer exposes a white gap. The peer dislikes the appearance, but the gap better represents what is known.'],
 ['合作方圈出了更大的区域，希望把局部地图放进下一轮方案。新的天气窗口仍没定，借用的场地安排也要交回。导师问那片空白是否能先用“合理推测”补上。你手边还有一张地点与日期的表，知道哪里真的去过，哪里只是地图上看起来顺路。接下来的展示会把这两件事混在一起，或明确分开。','The partner wants a broader regional map. Weather remains uncertain and site access must be returned. A suggestion to fill the gap with plausible inference meets your table of actual sites and dates. Decide how the display distinguishes visits from assumptions.']],
 engineer:[
 ['样机演示前，台架暂停开放，合作方又换了一版接口说明。旧程序连不上，报错指向一个你没见过的参数。同门正在给自己的样机打包，能借的时间很短。工程联系人说新版本“基本兼容”，你对着这个词看了一会儿。真正要决定的是，这周还能测试哪一段，而不是先给旧程序判死刑。','The rig closes and a new interface version breaks the connection before a demonstration. A peer has little time before shipping a prototype. “Mostly compatible” is not a test result; decide what remains testable this week.'],
 ['短窗口终于开放。同一个输入在两版接口里含义不同，现场人员说说明书末尾有一条补充。你翻到那一页，发现它解释了昨天最困惑的报错。能跑通的是原定演示的一部分，新工况还没有覆盖。台架倒计时已经开始，你得选择继续查接口，还是先做一个承认限制的小演示。','A short rig slot reveals changed input semantics explained in an appendix. Part of the demonstration runs, while new conditions remain untested. With the slot counting down, trace the interface or build a bounded demonstration.'],
 ['演示名单排好了，合作方又加一个现场条件，说这样观众更容易看出效果。你没在台架上试过它。同门问演示结束后几点能取回设备，导师则想知道有没有把握。展位牌已经打印出组名，退掉很麻烦，上去也不是按一下播放键那么简单。你决定今天带哪一种版本走到台架前。','The scheduled demonstration gains an untested condition. A peer needs the equipment back and the supervisor asks about confidence. The group’s sign is already printed; choose which version to take to the rig.']],
 design:[
 ['展前电话说受众换了：原来是熟悉作品的人，现在要给第一次接触的观众看。你站在已经布置一半的展位里，手边还是旧说明牌。同门问要不要继续贴，策展联系人说位置不能空。改标题很快，让作品适合新受众却不是同一件事。你得争取一次试看，借一个入口，或干脆改成过程展示。','The audience changes from familiar users to newcomers halfway through installation. Old labels remain in hand and the organizer needs the slot filled. A trial, borrowed display access or work-in-progress framing may help; renaming alone cannot adapt the work.'],
 ['试看的人说很好看，却各自理解成不同的用途。有一位没有按你的设想使用，卡住后抬头问是不是自己弄错了。合作方只记下好评，导师问那个实际任务到底有没有完成。你回看原型记录，发现最该改的地方也许不是颜色或标题，而是第一步从哪里开始。','Trial viewers like the work for different reasons. One newcomer gets stuck and assumes it is their fault. The partner records praise while the supervisor asks about task completion. The first step may matter more than color or title.'],
 ['印好的标题写着“面向所有人的成熟方案”，比你的原型大了好几圈。评审时间已经排定，同门还在等最终布置图。改成过程展示会让合作方失望，保持原样则要当场解释那些没做过的使用情境。你把说明牌放在桌上，开始改最后一段话：这次到底展示一个解决方案，还是展示它怎样一步步被做出来。','The printed title promises a mature solution for everyone. Reframing disappoints the partner; retaining it requires explaining untested situations. Before the review and final installation, decide whether to show a solution or its development.']]
 },
 sides:{
 poster:[['你在走廊海报前停下来，一个熟悉的词被两条箭头连到陌生地方。脚注小得要弯腰看，作者正在收拾展板，说为了省版面删过一段说明。明天展览结束，如果要问，现在正好能问到人。','A familiar term on a corridor poster connects to unexpected nodes. The author is dismantling it tomorrow and mentions a deleted explanation; this is your chance to ask.'],['作者回了消息，箭头是示意，不是证明。他补发了删去的一页，顺便问你的专业怎样用这个词。你们都觉得有意思，真正对上材料时却发现中间还缺一步。','The author explains the arrow is illustrative and sends the omitted page. Comparing how the term is used reveals a missing step between the materials.'],['小讨论改到周末，作者带来旧稿，开头先说自己不擅长公开辩论。旁边有人已经拍了那张图，准备讲给自己的组听。你要决定怎样介绍刚才弄清的那一步，才不让作者和那条箭头一起变成笑话。','At a weekend discussion, the author brings an old draft while someone prepares to retell the photographed figure. Explain the clarified step without turning the author into a joke.']],
 archive:[['借来的书里掉出一页摘录，铅笔圈住一句很适合你的汇报的话。页角只有一个数字，没有作者和年份。同门说这本书转过几个人，下周得还。那句话已经进了你的草稿，现在要决定追不追它的出处。','A borrowed book drops an unsigned excerpt with a useful sentence. The book passed through several readers and is due next week; the quote is already in your draft.'],['管理员找到了旧版目录。流传的摘录少了一个限定词，页码也对不上。你把两份纸并排放着，原来最有力的那句话忽然温和了很多。书还在借期里，今天还有机会回到原页。','An old edition’s index reveals a missing qualifier and different page number. The powerful sentence becomes more tentative when compared with the original.'],['另一位同学也在追这个出处，愿意交换找到的页码，但课程论文今晚要交。你们在书架旁各自拿着手机，谁都不想再把相同的地方找一遍。可以一起补索引，也可以只交换已确认的那几页。','Another student offers page references before a course deadline. Beside the shelves, you can complete an index together or exchange only the pages already confirmed.']],
 club:[['朋友临时缺一个讲者，问你能不能把自己的研究讲给社团听。海报已经发了，下面留着你的名字。朋友说不用多专业，大家想知道你每天到底在忙什么。你想起自己的第一张汇报图，完全不知道从哪一句开始删。','A society needs a speaker and the poster already carries your name. Friends want to know what you do every day; your usual first slide offers no obvious starting point.'],['活动压缩到五分钟，朋友在群里发了一个听众问题：“所以这个现在能用了吗？”你删掉两页背景，又把一句限制加回来。试讲只剩这半天，讲得懂与讲得准得同时挤进五分钟。','The talk shrinks to five minutes and someone asks whether the work is usable now. You cut background and restore a caveat before the only rehearsal slot.'],['现场有人举手机拍照，主办方要把摘要发到社团账号。你发现大家记住的是那个类比，没人记得你后面补的一句话。朋友把发布稿递过来，说现在改还来得及。','Attendees photograph the analogy but miss its caveat. The organizer’s summary can still be edited before publication.']],
 rumor:[['群里那张教程被转发了好几次，标题说能省掉一周。师兄问你是否试过，截图下半截恰好没了。发送者说自己确实很快跑完一次，还发来一个得意的表情。你也很想省时间，先得找到被裁掉的那一栏。','A forwarded tutorial promises a week saved, with its lower conditions cropped out. A peer wants to try it; the sender recalls one fast run. Find the missing condition first.'],['原作者补充，只试过一种输入，别的情况没有检查。同门正在赶稿，问这种差别是不是不用太在意。你把自己的问题写在旁边，两个设置看起来相近，却还不是同一个。','The author tested one input only. A peer facing a deadline wants to overlook the difference, but your setting is merely similar.'],['同门已经把方法放进组会草稿，问你能不能替它说两句。前面到底查过多少，现在突然变得很重要。你不是只在回答这个办法好不好，也在决定别人能不能引用你说过的话。','A peer’s meeting draft includes the method and asks for your endorsement. Earlier checking now determines what others can quote you as supporting.']],
 festival:[['校园节给研究生留了一张小桌，旁边是烘焙社团。你想用日常物品讲一个概念，同门担心讲得太难没人停。主办方说电源只有一个插口，演示得再缩一点。','The research table sits beside the baking society with one power socket. A simple everyday illustration must fit both the audience and the space.'],['宣传稿把你的展示写成了一项突破，读起来比课题本身激动得多。同门觉得吸引人也好，你却想起那些物品只是示意。海报今晚印，主办方问哪几个字一定要改。','Publicity calls the illustration a breakthrough. With printing tonight, the organizer asks which words must change.'],['路过的老师停下问这个演示说明了什么，小朋友同时问能不能再来一遍。你一边收拾桌上滚开的物品，一边决定给两个听众各讲哪句话。身后的宣传牌还写着刚改过的标题。','A teacher asks what the demonstration establishes while a child wants another try. Different explanations must fit beside the revised publicity sign.']],
 backup:[['共享盘里有两份“最终版”，只差一句结论。离组同门留下几十个文件夹，没有变更表。你原本只是来找一张图，现在多了一个问题：今天大家正在引用的，是哪一份？','Two final drafts differ by one claim. A former peer left dozens of folders without an index; which version is everyone citing?'],['编辑者记得收到意见后改过一次，记录散在两个文件夹里。他愿意指路，没空陪你整天找。你打开旧批注，终于看见那句话为什么被删，但还没找到所有相关附件。','The editor recalls a revision after review and points to two folders. An old annotation explains the deletion, while attachments remain missing.'],['合稿的人提议按修改时间覆盖，省得继续比对。另一位同学提醒那会丢掉改题的过程。你看着桌面上越开越多的窗口，要决定留下完整变更表，还是只把已经找到的线索交出去。','A merger by modification date would save time but lose why the question changed. Decide between a full change table and a partial handover.']],
 walk:[['朋友带来另一个专业的人，散步时发现你们都在说同一个方法。话题很快热起来，对方问能不能合作。你们停在路口才发现，连各自输入是什么都还没说过。','A walk reveals a same-named method in another discipline and enthusiasm for collaboration before even exchanging input types.'],['对方发来小例子，输出回答的却是另一个问题。你写了一段说明，又删掉一半，怕显得在拒绝。他回说自己也想弄清，下一次能不能把两边的例子都带来。','The example answers another question. A hesitant reply leads to an invitation to compare both examples rather than abandon the contact.'],['对方提议请导师旁听，聊天突然有了正式议程。你们已经对过一部分条件，还有一处连接只停留在想法。该讲到哪一步，决定了这次是开始合作，还是留下一个值得再聊的问题。','A supervisor joins the next discussion. Some conditions match, one link remains speculative; decide how formally to present it.']],
 'lost-and-found':[['失物招领处有个厚资料夹，封面只写了一串缩写。你翻到手写索引，发现它也许能帮到自己的课题。值班同学递来登记表，说先找到主人，里面的纸暂时别拍。','A lost folder has only initials on the cover and a potentially useful index. Register it and locate the owner before copying anything.'],['主人来认领，指着几页说是同伴后来加的。他允许你对照索引，不想整个夹子被传出去。你们坐下来拆分几种笔迹，原来看起来完整的一套材料也有不同来路。','The owner identifies later additions and permits index comparison, not full circulation. Different handwriting reveals different sources.'],['主人分享了整理方法，也愿意留下已经确认的索引。你们交换联系方式，约好用到哪一页再问一次。归还资料以后，这个偶遇可以继续变成互相帮忙，也可以就在门口道一声谢。','The folder is returned with a confirmed index and contact details. The encounter may become mutual help or end with thanks.']]
 },
 campus:{
 meal:[['隐藏菜只剩两份，朋友还在从另一栋楼赶来。窗口师傅看着队伍，说最多替你留到下一锅出锅。你站在两个托盘前，才发现集菜单也得先把人等到。','Only two special meals remain and a friend is still crossing campus. The cook can hold one only briefly.'],['第二张菜单和照片不一样，朋友尝了一口就放下筷子。师傅问是不是太咸，你们开始认真讨论味道，最后给下一次留了一条建议。','The second meal differs from its photo. Honest feedback becomes a suggestion for the next visit.'],['拼桌碰到隔壁组，对方听见你们聊课题，随口说自己也遇到过。筷子还没停，联系方式先加上了；合作的事，吃完再谈也来得及。','A shared table brings another group’s similar problem and contact details before any collaboration is agreed.'],['朋友想把菜单照片排成一页“本学期没白吃”。有人没赶上最后一顿，发来一句留言。你数了数图片，发现记得最清楚的不是菜，而是谁坐在哪边。','A semester food collage includes a message from an absent friend; the seats are more memorable than the dishes.']],
 board:[['朋友把牌洗好，给你留了座位。你还惦记没整理完的材料，大家说可以先玩一局，到约好的时间就收。你把手机扣在桌上，第一次开始认真计算怎么玩，而不是怎么汇报。','A seat and a single game are reserved around unfinished work. The phone goes face down as the calculation changes from reporting to playing.'],['新同学第一次来，上次输最多的人负责讲规则。讲到一半他自己也忘了，大家一起翻说明书，比上一局赢的时候还笑得大声。','Last week’s loser teaches a newcomer, then needs the rulebook; the confusion is funnier than winning.'],['想固定聚会，大家的截止日期却完全错开。有人把“每周必须来”划掉，改成能来就说一声。你们拍了张桌面照，留给缺席的人猜谁又输了。','Conflicting deadlines produce flexible gatherings and a table photo for absent friends.']],
 cat:[['猫缩在长椅下面，旁边放着值班同学的记录板。你想靠近拍照，被轻声叫住：它刚被施工声吓过。你在远处坐下，等它自己决定要不要出来。','A frightened cat stays under a bench; the volunteer asks for quiet distance instead of photos.'],['值班同学快毕业，要找人接下一段照看时间。你已经认得猫，第一次认真仔细看轮换表才知道，还有好几个人一直在做这件事。','A graduating volunteer needs a replacement on a rota you had not noticed despite recognizing the cat.'],['雨天猫窝要挪，大家在群里一边看天气一边找位置。你不一定能每次都在，却可以接一段说好的安排。它睡在新的角落里，好像根本不知道大家开过一场小组讨论。','Rain prompts a jointly planned shelter move and a manageable agreed shift; the cat sleeps through the human discussion.'],['有人做了一页猫的学期相册，封底是轮换名单。几张模糊照片拍到了你的鞋，大家说这也算合影。毕业的人留下钥匙，新人接着来。','A cat album ends with the care rota; blurred photos include your shoes, and a departing volunteer leaves the keys.']],
 band:[['排练室剩一个小时，朋友问你唱不唱得完这一首。你说先试，第一遍副歌就进错了拍。大家停下来笑了一次，重新从最简单的那段开始。','One rehearsal hour remains; a missed chorus leads to laughter and a simpler restart.'],['海报上印着你们的名字，演出日期恰好靠近一轮截止。朋友说歌可以少一首，人别唱到第二天没法上课。你们把歌单重新排短。','The concert overlaps a deadline, so the set is shortened rather than sacrificing the next day.'],['音箱出故障，借设备的人自己也有安排。大场面可能做不成，大家围着一把旧木吉他试了一遍，突然发现小版本也不是那么难听。','An amplifier fails and the lender is busy; a one-guitar version turns out workable.'],['最后一首唱完，台下没有你想象中那么多人，朋友却都在。照片拍糊了，录音还有咳嗽声。你们听了一遍，说下次至少别把开场那句唱错。','A modest audience of friends hears the final song; a blurred photo and imperfect recording become plans for next time.']]
 }
};
