/* Offline display localization. Logic, action IDs and save data stay in the source language. */
window.MEETING_I18N=(()=>{
  'use strict';
  const labels={zh:'中文',en:'English',ja:'日本語',ko:'한국어'},KEY='meeting-survival-language',originals=new WeakMap(),attributes=new WeakMap(),tries={},dictionaries={};let language='zh',observer=null,queued=false;
  try{const saved=localStorage.getItem(KEY);if(Object.hasOwn(labels,saved))language=saved;}catch{}
  if(typeof document!=='undefined'&&Object.hasOwn(labels,document.documentElement.dataset.defaultLanguage))language=document.documentElement.dataset.defaultLanguage;
  const glossary={
    '组会求生':['Lab Meeting Survivor','研究室ミーティング・サバイバー','연구실 미팅 생존기'],
    '同学，':['Hey, student.','学生さん、','대학원생 여러분,'], '你能':['Can you','無事に','무사히'], '活着散会':['survive this meeting','ミーティングを乗り切れる','미팅을 마칠 수 있나요'], '吗？':['?','？','?'],
    '我的一周':['My week','今週の生活','나의 한 주'],'补给站':['Supply shop','補給所','보급소'],'结局图鉴':['Ending collection','エンディング図鑑','엔딩 도감'],'开始新的一周 ↗':['Start a new week ↗','新しい一週間を始める ↗','새로운 한 주 시작 ↗'],'只玩一场组会':['Play one meeting','ミーティングを一回だけ遊ぶ','미팅 한 판만 하기'],
    '导师':['Supervisor','指導教員','지도교수'],'导师耐心':['Supervisor patience','指導教員の忍耐','지도교수의 인내'],'师兄':['Senior student','先輩','선배'],'师姐':['Senior student','先輩','선배'],'师弟':['Junior student','後輩','후배'],'师妹':['Junior student','後輩','후배'],'师兄师姐':['Senior students','先輩たち','선배들'],'师弟师妹':['Junior students','後輩たち','후배들'],
    '心态':['Morale','メンタル','멘탈'],'精力':['Energy','体力','체력'],'资料':['Materials','資料','자료'],'幻灯片':['Slides','スライド','슬라이드'],'压力':['Stress','ストレス','스트레스'],'底气':['Evidence readiness','根拠の充実度','근거 준비도'],'时间':['Time','時間','시간'],'本场评分':['Meeting score','今回のスコア','이번 미팅 점수'],'撑过回合':['Rounds survived','耐えたラウンド','버틴 라운드'],'整活次数':['Chaotic responses','おふざけ回数','장난스러운 답변 횟수'],
    '背景与文献':['Background and literature','背景・文献','배경 및 문헌'],'方法与依据':['Methods and rationale','方法・根拠','방법 및 근거'],'结果与原始材料':['Results and original records','結果・元資料','결과 및 원자료'],'结论边界':['Limits of conclusions','結論の適用範囲','결론의 적용 범위'],'表达与预演':['Presentation and rehearsal','説明・リハーサル','발표 및 리허설'],
    '尚未准备':['Not prepared','未準備','준비되지 않음'],'只有线索，完整回答未解锁':['Clues only; full answer locked','手がかりのみ。完全な回答は未解放','단서만 있음 · 완전한 답변 잠김'],'已核对，可据此回答':['Verified; usable as an answer source','確認済み。根拠として回答可能','확인 완료 · 답변 근거로 사용 가능'],
    '已接 · 待处理':['Accepted · work pending','引受済み・未処理','수락함 · 처리 대기'],'已逾期 · 仍待交付':['Overdue · delivery pending','期限超過・未納品','기한 초과 · 전달 대기'],'完整交付':['Full delivery','全範囲を提出済み','전체 범위 전달 완료'],'已交部分范围':['Partial scope delivered','限定範囲を提出済み','일부 범위 전달 완료'],'已说明无法接下':['Declined with explanation','引き受けられないと説明済み','수락 불가 사유 설명 완료'],'已交回未完成部分':['Unfinished scope returned','未完了分を返却済み','미완료 부분 반환 완료'],
    '周一':['Monday','月曜日','월요일'],'周二':['Tuesday','火曜日','화요일'],'周三':['Wednesday','水曜日','수요일'],'周四':['Thursday','木曜日','목요일'],'周五':['Friday','金曜日','금요일'],'周六':['Saturday','土曜日','토요일'],'周日':['Sunday','日曜日','일요일'],'上半天':['first half','前半','전반'],'下半天':['second half','後半','후반'],
    '摸鱼币':['Leisure coins','息抜きコイン','휴식 코인'],'翻车结局':['Failure endings','失敗エンディング','실패 엔딩'],'滑稽结局':['Comic endings','コミカルなエンディング','코믹 엔딩'],'开放结局':['Open endings','オープンエンディング','열린 엔딩'],'未解锁结局':['Undiscovered ending','未発見のエンディング','미발견 엔딩'],
    '选择后揭晓':['Revealed after choosing','選択後に判明','선택 후 공개'],'时间往前走':['Move time forward','時間を進める','시간 진행'],'回到门口 · 自动保存':['Back to setup · autosaved','入口に戻る・自動保存','설정으로 돌아가기 · 자동 저장'],'继续汇报':['Continue presenting','報告を続ける','발표 계속'],'看看我的结局':['See my ending','エンディングを見る','내 엔딩 보기'],'现场回应':['Your response','その場の返答','현장 답변'],'完整回答':['Full answer','根拠のある回答','완전한 답변'],
    '单机 · 随时开玩':['Offline-capable · Play anytime','一人用・いつでもプレイ','싱글 플레이 · 언제든 시작'],'币':['coins','コイン','코인'],'音效 关':['Sound off','音声オフ','효과음 끔'],'音效 开':['Sound on','音声オン','효과음 켬'],'初入师门':['New to the lab','研究室の新人','연구실 신입'],'每场随机':['Random each meeting','毎回ランダム','미팅마다 무작위'],'理学':['Natural sciences','自然科学','자연과학'],'法学':['Law','法学','법학'],'教育学':['Education','教育学','교육학'],'交叉学科':['Interdisciplinary','学際研究','융합학문'],'捧场型':['Encouraging','応援タイプ','격려형'],'细节控':['Detail-focused','細部重視','세부사항 중시'],'往事型':['Storyteller','昔話タイプ','이야기형'],'冷面型':['Strict','厳格タイプ','엄격형'],'大佬突袭':['Expert ambush','大物研究者の飛び入り','거물 연구자의 갑작스러운 방문'],'正常组会':['Normal lab meeting','通常の研究室ミーティング','일반 연구실 미팅'],
    '熬夜卷王':['Night-owl overachiever','徹夜の頑張り屋','밤샘 과몰입형'],'淡定摸鱼人':['Calm slacker','落ち着いた省エネ派','느긋한 휴식파'],'学术社交王':['Academic social butterfly','学術界の社交家','학계 사교왕'],'师兄救我':['Senior, help me!','先輩、助けて！','선배, 도와주세요!'],
    '证明有边界，组会没有。':['Proofs have boundaries. Meetings do not.','証明には境界がある。ミーティングにはない。','증명에는 경계가 있지만 미팅에는 없다.'],'程序能跑，研究者想跑。':['The code runs. The researcher wants to run away.','コードは動く。研究者は逃げたい。','코드는 돌아간다. 연구자는 도망가고 싶다.'],'你在田野，组会在找你。':['You are in the field. The meeting is looking for you.','あなたはフィールドへ。ミーティングはあなたを探す。','당신은 현장에, 미팅은 당신을 찾는다.'],'甲方说好，但再改一下。':['The client approves—then asks for one more revision.','クライアントは承認した。でも、もう一度修正。','클라이언트가 승인했다. 하지만 한 번만 더 수정하자.'],'轨道很远，组会很近。':['The orbit is far away. The meeting is very close.','軌道は遠い。ミーティングはすぐそこ。','궤도는 멀다. 미팅은 코앞이다.'],'流程有节点，组会没有。':['Processes have endpoints. Meetings do not.','手順には節目がある。ミーティングにはない。','절차에는 단계가 있다. 미팅에는 끝이 없다.'],'机制图很满，购物车很空。':['The mechanism diagram is full. Your shopping cart is empty.','機序の図はぎっしり。買い物かごは空っぽ。','기전 도식은 가득하다. 장바구니는 비어 있다.'],
    '全部':['All','すべて','전체'],'条路线':[' routes','ルート','개 경로'],'种结局':[' endings','種類のエンディング','개 엔딩'],'本局':['This run','今回','이번 플레이'],'本片段来自：':['Current scene: ','今回の場面：','현재 장면: '],'本周核对类别：':['Interface category this week: ','今週確認する種類：','이번 주 연결 검토 범주: '],'临时交办 · 接下不等于交付':['New requests · accepting is not delivery','臨時の依頼・引受と提出は別','갑작스러운 부탁 · 수락과 전달은 다르다'],'件待处理':[' pending requests','件が未処理','건 처리 대기'],'经费余量':['Funding available','研究費の余裕','연구비 여유'],'已处理':['Work completed','作業済み','처리 완료'],'份':[' units','件','개 작업'],'已接':['Accepted','引受済み','수락함'],'准备 · 生活':['Preparation · Life','準備・生活','준비 · 생활'],'反馈 · 休息':['Feedback · Rest','振り返り・休息','피드백 · 휴식'],
    '🌉 核对真正的交叉接口':['🌉 Verify the interdisciplinary interface','🌉 分野間の接続を確認する','🌉 실제 융합 연결 검토'],'🍜 吃点什么 · 选一顿饭':['🍜 Plan a meal','🍜 食事を選ぶ','🍜 식사 선택'],'组会留下的事':['Meeting follow-ups','ミーティング後の課題','미팅 후속 과제'],'选择角色':['Choose a character','キャラクターを選ぶ','캐릭터 선택'],'难度':['Difficulty','難易度','난이도'],'本周时间线':['Weekly timeline','今週の時間軸','이번 주 일정'],'虚构实验室：三位老师坐在长桌前，你在投影幕旁汇报':['Illustration of a fictional lab meeting','架空の研究室ミーティングのイラスト','가상의 연구실 미팅 삽화'],
    '这周怎么准备，周五就怎么回答。':['Your week shapes what you can answer on Friday.','今週の準備が、金曜に答えられることを決める。','이번 주 준비가 금요일에 답할 수 있는 내용을 결정한다.'],'准备决定你能讲什么，现场决定对方买不买账。漏洞、连续追问和关系波动，每场重新面对。':['Preparation gives you evidence. The room decides how your response lands. Expect flaws, follow-up questions and changing relationships.','準備は話せる内容を決める。その場の空気は相手の反応を変える。弱点、追問、人間関係の変化に毎回向き合う。','준비는 말할 근거를 만든다. 현장 분위기는 반응을 바꾼다. 허점, 추가 질문, 관계 변화가 매번 찾아온다.'],
    '叶':['Ye','葉','예'],'方':['Fang','方','팡'],'陈':['Chen','陳','천'],'许':['Xu','許','쉬'],'宋':['Song','宋','쑹'],'林':['Lin','林','린'],'唐':['Tang','唐','탕'],'沈':['Shen','沈','선'],'顾':['Gu','顧','구'],'孟':['Meng','孟','멍'],'梁':['Liang','梁','량'],'韩':['Han','韓','한'],'苏':['Su','蘇','쑤'],'赵':['Zhao','趙','자오'],
    '周老师':['Supervisor Zhou','周先生','저우 교수'],'林老师':['Supervisor Lin','林先生','린 교수'],'陈师兄':['Senior Chen','陳先輩','천 선배'],'许师兄':['Senior Xu','許先輩','쉬 선배'],'叶师姐':['Senior Ye','葉先輩','예 선배'],'林师姐':['Senior Lin','林先輩','린 선배'],'小同学':['Student','学生さん','학생'],
    '● 当前':['● Current','● 現在','● 현재'],'仪器记录':['Instrument records','機器の記録','기기 기록'],'的一周':["'s week",'の一週間','의 한 주'],'临时交办':['New request','臨時の依頼','갑작스러운 부탁'],'查看本周准备记录':['View this week’s preparation records','今週の準備記録を見る','이번 주 준비 기록 보기'],'临时交办 ·':['New request ·','臨時の依頼 ·','갑작스러운 부탁 ·'],'继续':['Continue','続ける','계속'],'🎲 校园支线':['🎲 Campus side stories','🎲 キャンパスの小さな物語','🎲 캠퍼스 서브 스토리'],'还有后续':['More to come','続きあり','후속 이야기 있음'],'偶遇与选择':['Encounters and choices','出会いと選択','만남과 선택'],'已核对':['Verified','確認済み','검토 완료'],'段':[' scenes','場面','개 장면'],'人 · 经费余量':[' people · Funding available','人 · 研究費の余裕','명 · 연구비 여유'],'上周结余与本周到账扣去固定支出后，经费余量为':['After incoming funds and fixed expenses, funding available is ','繰越分と今週の入金から固定費を差し引いた研究費の余裕：','이월 잔액과 이번 주 입금에서 고정 지출을 뺀 연구비 여유: '],'🎲 校园支线 ·':['🎲 Campus side stories ·','🎲 キャンパスの小さな物語 ·','🎲 캠퍼스 서브 스토리 ·'],'人':[' people','人','명'],'🏫 本局课题组 ·':['🏫 Your research group ·','🏫 今回の研究室 ·','🏫 이번 연구실 ·'],'📨 临时交办 · 接下不等于交付':['📨 New requests · accepting is not delivery','📨 臨時の依頼・引受と提出は別','📨 갑작스러운 부탁 · 수락과 전달은 다르다'],'查看两侧准备记录':['View preparation records for both disciplines','両分野の準備記録を見る','두 분야의 준비 기록 보기']
  };
  const tutorials={
    zh:['怎么玩','这是一个虚构的研究生生活选择游戏。周一至周四准备，周五参加组会，周末处理反馈或休息。','生活片段由所有安排共用：读文献、帮别人、吃饭、休息只能选一件。接下临时交办不代表完成，要再安排实际处理。','完整回答需要对应学科的真实核对记录。只读摘要得到线索；卡牌、高数值或另一门学科的准备不能替代它。','导师、资深同门和新同门的人数随机；经费余量跨周变化。消息、截止、现场偏好和回应后果都可能改变安排。','交叉学科可以自选两个学科；除了两边各自的问题，还要核对两侧定义、条件和使用场景之间的接口。','正常散会至少10次问答，但状态归零会提前失败。失败后仍能继续生活。存档保存在当前浏览器，换语言不会重置进度。'],
    en:['How to play','A fictional graduate-student life game. Prepare Monday–Thursday, face a lab meeting on Friday, then rest or work on feedback over the weekend.','Every activity uses the same limited time slots. Reading, helping someone, eating and resting compete for time. Accepting a request is not delivery: schedule real work afterward.','A full answer requires verified records in that discipline. Abstracts provide clues. Cards, high scores and preparation in another discipline cannot substitute for those records.','Your group has a random number of supervisors, senior students and junior students. Funding carries over between weeks. New requests, deadlines, preferences and response outcomes may disrupt plans.','For interdisciplinary play, choose two disciplines. Alongside questions from each side, examine the interface between their definitions, assumptions and use cases. Each side needs its own sources.','Normal meetings require at least ten responses before wrap-up. You may fail earlier if morale, patience or time runs out. Life continues after failure. Saves stay in this browser; switching language preserves progress.'],
    ja:['遊び方','架空の大学院生活を体験する選択式ゲームです。月曜から木曜に準備し、金曜の研究室ミーティングで報告。週末はフィードバックへの対応や休息に使います。','すべての行動は限られた同じ時間枠を使います。文献、手伝い、食事、休息は同時にできません。依頼を引き受けても完成ではなく、実際に作業する時間が必要です。','十分な回答には、その分野で確認した記録が必要です。要旨から得られるのは手がかりだけ。カード、高い数値、別分野の準備では代用できません。','指導教員、先輩、後輩の人数はランダムです。研究費の余裕は週をまたいで変動し、依頼、締切、相手の関心、返答の結果が予定を変えることがあります。','学際モードでは二つの分野を選びます。それぞれの問いに加え、定義・前提・利用場面のつながりも確認します。両側の根拠を別々に準備してください。','通常は少なくとも10回回答してから終了できます。ただしメンタル、忍耐、時間が尽きると早く失敗します。失敗後も生活は続きます。保存はこのブラウザー内で行われ、言語を変えても進度は維持されます。'],
    ko:['게임 방법','가상의 대학원 생활 선택 게임입니다. 월요일부터 목요일까지 준비하고, 금요일 연구실 미팅에서 발표합니다. 주말에는 피드백을 처리하거나 쉽니다.','모든 활동은 같은 제한된 시간 구간을 사용합니다. 문헌 읽기, 다른 사람 돕기, 식사, 휴식 중 하나를 골라야 합니다. 부탁을 수락했다고 완료된 것은 아니며 실제 작업 시간을 따로 잡아야 합니다.','완전한 답변에는 해당 분야에서 직접 확인한 기록이 필요합니다. 초록은 단서만 제공합니다. 카드, 높은 수치, 다른 분야의 준비로 대신할 수 없습니다.','지도교수, 선배, 후배의 수는 무작위입니다. 연구비 여유는 다음 주로 이어지며 변동합니다. 새 부탁, 마감, 상대의 관심사, 답변 결과가 계획을 바꿀 수 있습니다.','융합 모드에서는 두 분야를 선택합니다. 각 분야의 질문뿐 아니라 정의, 전제, 활용 상황이 어떻게 연결되는지도 확인합니다. 양쪽 근거를 각각 준비해야 합니다.','보통 미팅을 마치려면 최소 10번 답변해야 합니다. 멘탈, 인내 또는 시간이 소진되면 일찍 실패할 수 있지만 이후 생활은 계속됩니다. 저장은 현재 브라우저에 남으며 언어를 바꿔도 진행 상황이 유지됩니다.']};
  const expandedTutorials={"zh":["共155条路线、1716个专业研究分支；新增专业与医学扩展路线各有12个分支，原路线各有9个。相邻转向显示共同方法、对象或情境的连接点，可搜索目标。确认转向才消耗片段并新建版本；旧资料只留下参考线索，新版完整回答需重新实查。","消息可能不可靠，核实也可能暂时没有回信；预留限时机会后还要实际参加。人物各有安排，选择会改变后续邀请，散会后的回应可能继续带来请求。","七种玩法改变校园节奏。同局挑战从独立生涯开始；复制局号和同周路线报告，朋友可用自己的语言游玩，粘贴报告对比分岔。分享靠局号和报告，没有实时联网房间。"],"en":["There are 155 routes and 1716 research branches: twelve per expanded specialty and nine per original route. Neighboring directions share a method, subject or context; search the listed targets and inspect the connection. Confirming a pivot uses a time slot and starts a new project version. Older work provides clues; full answers require fresh verification.","Messages may be unreliable, and checking may produce no immediate reply. Reserved opportunities still need actual attendance. Characters have their own plans, your choices change later invitations, and meeting follow-ups can lead to more requests.","Seven modes change the campus rhythm. Shared-seed challenges start with an independent career. Share the run code and a report from the same week; friends can play in their own language and paste reports to compare choices. There are no live multiplayer rooms."],"ja":["155ルート、1716の研究方向があります。拡張ルートは各12方向、既存ルートは各9方向です。隣接方向は方法・対象・利用場面のつながりで選ばれ、検索できます。転向を確定すると時間枠を使い、新しい課題版を作ります。以前の資料は手がかりとして残り、十分な回答には新しい確認が必要です。","情報が正しいとは限らず、確認してもすぐ返事が来ない場合があります。機会を予約しただけでは参加したことになりません。登場人物には自分の予定があり、選択が後の誘いを変え、ミーティング後の返事から新しい依頼が来ることもあります。","7つのモードで大学生活の展開が変わります。同じシードのチャレンジは独立した経歴から始まります。局コードと同じ週の報告を共有し、友人は自分の言語でプレイできます。報告を貼り付けて分岐を比較します。リアルタイムのオンライン対戦ではありません。"],"ko":["155개 경로와 1716개 연구 방향이 있습니다. 확장 경로는 각각 12개, 기존 경로는 각각 9개 방향입니다. 인접 방향은 방법, 대상 또는 활용 맥락의 연결에 따라 제시되며 검색할 수 있습니다. 전환을 확정하면 시간 구간을 사용하고 새 연구 버전을 만듭니다. 이전 자료는 단서로 남으며 완전한 답변에는 새 검토가 필요합니다.","메시지가 정확하지 않을 수 있고 확인해도 즉시 답장이 오지 않을 수 있습니다. 기회를 예약한 뒤 실제로 참여해야 합니다. 등장인물에게도 자기 일정이 있으며 선택이 이후의 초대를 바꾸고 미팅 후 답변이 새로운 부탁으로 이어질 수 있습니다.","7개 모드가 캠퍼스의 흐름을 바꿉니다. 같은 시드 도전은 독립된 경력으로 시작합니다. 플레이 코드와 같은 주의 보고서를 공유하면 친구가 자신의 언어로 플레이하고 보고서를 붙여 넣어 선택의 분기를 비교할 수 있습니다. 실시간 온라인 대전 방은 없습니다."]};for(const [lang,items] of Object.entries(expandedTutorials))tutorials[lang].push(...items);

  const academyTutorials={zh:'可选硕士、博士与自由生涯，并选择六种开局。人物自己的投稿、答辩与工作安排会影响帮助。设备、算力、档案与随访窗口要预约和等待，实际核对才产生回执；合作要记录贡献并协商署名。失败可以补救，周末故事与伏笔会跨周继续。存档与安装菜单支持完整JSON备份及恢复；Android和iPhone可安装离线网页应用，Windows可下载应用包。',en:'Choose a master’s, doctoral or open-ended career and one of six starting scenarios. Other students have their own submissions, defenses and job plans. Book resources and wait for their windows; actual verification creates a receipt. Collaborations need contribution records and an authorship agreement. Failures can lead to recovery, and campus stories continue across weeks. Save & install exports a full JSON backup. Android and iPhone support an installable offline web app; Windows has a downloadable app package.',ja:'修士・博士・自由な研究生活と6種類の開始条件を選べます。他の学生にも投稿、発表、就職の予定があります。資源は予約して待ち、実際に確認して記録を残します。共同研究では貢献と著者順を合意します。失敗の後にも立て直しや週をまたぐ物語があります。保存とインストールから完全なJSONバックアップを作れます。AndroidとiPhoneはオフラインWebアプリ、Windowsはダウンロード版に対応します。',ko:'석사·박사·자유 연구 생활과 여섯 가지 시작 조건을 선택합니다. 다른 학생에게도 투고, 발표, 취업 일정이 있습니다. 자원을 예약하고 기다린 뒤 실제 검토 기록을 남깁니다. 협업에서는 기여와 저자 순서를 합의합니다. 실패 후에도 회복과 여러 주에 걸친 이야기가 이어집니다. 저장 및 설치 메뉴에서 전체 JSON 백업을 만듭니다. Android와 iPhone은 오프라인 웹 앱, Windows는 다운로드 앱을 지원합니다.'};for(const [lang,text] of Object.entries(academyTutorials))tutorials[lang].push(text);

  const hierarchyTutorials={zh:'先选14个大类，再展开专业。部分专业可以继续选细分领域，或者直接到导师主页，在导师提供的1–3个方向中选题。日文、韩文的本轮新增专业内容部分使用英文回退，界面会提示。',en:'Choose one of 14 discipline families, then a specialty. Some specialties offer optional subfields; you can also go directly to supervisor profiles and select one of their 1–3 directions. Some newly expanded specialty text uses English in Japanese/Korean views.',ja:'14の大分類から専門を選びます。一部の専門では細分領域を選べます。先に教員ページへ進み、1〜3の方向から選ぶこともできます。今回追加した専門テキストの一部は英語で表示されます。',ko:'14개 대분류에서 전공을 선택합니다. 일부 전공은 세부 분야를 선택할 수 있습니다. 교수 페이지로 바로 이동해 1~3개 방향 중 고를 수도 있습니다. 이번에 추가된 일부 전공 텍스트는 영어로 표시됩니다.'};for(const [lang,text] of Object.entries(hierarchyTutorials))tutorials[lang].push(text);
  const careerTutorials={
    zh:'导师主页展示1–3个子方向和不同职业层级，可选择其方向或保留原题合作。导师跨周申报与评审，晋升可能通过或暂缓。学科长线需三个实际片段，最后交付至少到下一周。当前课题完成三份实查并形成有限结论后可投稿；修稿要留下本稿件回执，修回仍需等复审。稿件保存独立版本，新课题不能继承旧结论。接收成果和关系可能触发博士邀请，接受、暂缓或选择另一条路由你决定。',
    en:'Supervisor profiles show one to three research directions and different career levels. Choose one of their directions or keep your original topic. Supervisors can apply for promotion over several weeks; reviews may pass or be deferred. Discipline storylines take three real time slots, with final delivery in a later week. A project with three verified records and a limited conclusion can become a manuscript. Revisions need manuscript-specific work records; resubmission still awaits review. Each paper keeps its own version while new projects start fresh. Accepted work and your relationship may lead to a PhD invitation, which you can accept, defer or decline.',
    ja:'指導教員のページには1〜3の研究方向と職位が表示されます。その方向を選ぶか、元の課題で協力できます。教員の昇進は週をまたいで申請と審査が進み、通過や延期があります。分野別の物語は実際の時間枠を3回使い、最後の提出は翌週以降です。課題で3件の確認記録と限定的な結論を用意すると投稿できます。修正にはその原稿の作業記録が必要で、再提出後も審査を待ちます。原稿は独立した版を保存し、新しい課題は草稿から始まります。採択された成果と関係によって博士課程への誘いがあり、承諾・保留・辞退を選べます。',
    ko:'지도교수 페이지에는 1~3개의 연구 방향과 직급이 표시됩니다. 교수의 방향을 선택하거나 기존 주제로 협력할 수 있습니다. 교수의 승진 신청과 심사는 여러 주에 걸쳐 진행되며 통과하거나 보류될 수 있습니다. 분야별 이야기는 실제 시간 구간 세 번을 사용하고 최종 제출은 다음 주 이후입니다. 연구에서 검토 기록 세 건과 제한된 결론을 마련하면 투고할 수 있습니다. 수정에는 해당 원고의 작업 기록이 필요하며 재제출 후에도 심사를 기다립니다. 원고는 독립된 버전을 보관하고 새 연구는 초안부터 시작합니다. 게재 승인 성과와 관계에 따라 박사과정 제안을 받을 수 있으며 수락·보류·거절을 선택할 수 있습니다.'
  };for(const [lang,text] of Object.entries(careerTutorials))tutorials[lang].push(text);
  function dictionary(lang){if(dictionaries[lang])return dictionaries[lang];const result={...(window.MEETING_LOCALES?.[lang]||{})},index=['en','ja','ko'].indexOf(lang);for(const [key,values] of Object.entries(glossary))result[key]=values[index];for(const surname of ['周','林','孟','沈','唐','顾','梁','许','陈','叶','宋','韩','方','苏','赵']){const n=glossary[surname]?.[index]||({en:'Zhou',ja:'周',ko:'저우'})[lang];result[surname+'老师']=lang==='en'?`Supervisor ${n}`:lang==='ja'?`${n}先生`:`${n} 교수`;for(const role of ['师兄','师姐','师弟','师妹'])result[surname+role]=lang==='en'?`${['师兄','师姐'].includes(role)?'Senior':'Junior'} ${n}`:lang==='ja'?`${n}${['师兄','师姐'].includes(role)?'先輩':'後輩'}`:`${n} ${['师兄','师姐'].includes(role)?'선배':'후배'}`;}return dictionaries[lang]=result;}
  function trie(lang){if(tries[lang])return tries[lang];const root={};for(const [key,value] of Object.entries(dictionary(lang))){if(window.MEETING_NARRATIVE_WORLD?.longProse(key))continue;if(!value)continue;let n=root;for(const ch of key)n=n[ch]||(n[ch]={});n.value=value;}return tries[lang]=root;}
  function translate(text,lang=language){if(lang==='zh'||!/[\u3400-\u9fff]/u.test(text))return text;const words=dictionary(lang),trimmed=text.trim(),editorial=window.MEETING_NARRATIVE_WORLD?.lookup(trimmed);if(editorial!==null&&editorial!==undefined)return text.slice(0,text.indexOf(trimmed))+editorial+text.slice(text.indexOf(trimmed)+trimmed.length);text=window.MEETING_NARRATIVE_WORLD?.dynamic(text)||text;if(Object.hasOwn(words,trimmed))return text.slice(0,text.indexOf(trimmed))+words[trimmed]+text.slice(text.indexOf(trimmed)+trimmed.length);const protectedTexts=[],hold=value=>{const id=protectedTexts.push(value)-1;return String.fromCharCode(0xE000)+id+String.fromCharCode(0xE001);};text=text.replace(/组里有(\d+)位导师、(\d+)位师兄师姐、(\d+)位师弟师妹。/g,(_,a,b,c)=>hold(lang==='en'?`The group has ${a} supervisors, ${b} senior students and ${c} junior students. `:lang==='ja'?`この研究室には指導教員${a}人、先輩${b}人、後輩${c}人がいます。`:`연구실에는 지도교수 ${a}명, 선배 ${b}명, 후배 ${c}명이 있습니다. `)).replace(/已处理 (\d+)\/(\d+) 份/g,(_,a,b)=>hold(lang==='en'?`Work completed: ${a}/${b} units`:lang==='ja'?`作業済み：${a}/${b}件`:`처리 완료: ${a}/${b}개`)).replace(/第(\d+)周/g,(_,n)=>hold(lang==='en'?`Week ${n}`:lang==='ja'?`第${n}週`:`${n}주차`)).replace(/第(\d+)场/g,(_,n)=>hold(lang==='en'?`Meeting ${n}`:lang==='ja'?`${n}回目`:`${n}번째 미팅`));const root=trie(lang),out=[],chars=Array.from(text);for(let i=0;i<chars.length;){let n=root,match=null,end=i;for(let j=i;j<chars.length&&n[chars[j]];j++){n=n[chars[j]];if(n.value){match=n.value;end=j+1;}}if(match!==null){if(lang==='en'&&out.length&&/[A-Za-z]$/.test(out.at(-1))&&/^[A-Za-z]/.test(match))out.push(' ');out.push(match);if(lang==='en'&&/[A-Za-z]$/.test(match)&&/^[A-Za-z0-9\uE000]$/.test(chars[end]||''))out.push(' ');i=end;}else{out.push(chars[i++]);}}return out.join('').replace(/\uE000(\d+)\uE001/g,(_,id)=>protectedTexts[Number(id)]);}
  function apply(){if(!document.body)return;observer?.disconnect();let note=document.querySelector('.localization-note');if(!note){note=document.createElement('p');note.className='localization-note';note.dataset.noTranslate='true';document.querySelector('#app').before(note);}note.hidden=!['ja','ko'].includes(language);note.textContent=language==='ja'?'今回追加した専門内容の一部は英語表示です。既存の物語と保存データは引き続き利用できます。':language==='ko'?'이번에 추가된 일부 전공 내용은 영어로 표시됩니다. 기존 스토리와 저장 데이터는 계속 사용할 수 있습니다.':'';const hero=document.querySelector('.hero-title');if(hero){hero.dataset.noTranslate='true';const headings={zh:'同学，<br>你能<span>活着散会</span>吗？',en:'Hey, student.<br>Can you survive<br><span>this meeting?</span>',ja:'学生さん、<br>このミーティングを<br><span>乗り切れる？</span>',ko:'학생 여러분,<br>이번 미팅을<br><span>버틸 수 있을까요?</span>'};if(hero.innerHTML!==headings[language])hero.innerHTML=headings[language];}const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('script,style,textarea,[data-no-translate],#language-picker'))continue;const entry=originals.get(node);let source=entry&&node.nodeValue===entry.display?entry.source:node.nodeValue;if(!source.trim())continue;const display=translate(source);originals.set(node,{source,display});if(node.nodeValue!==display)node.nodeValue=display;}
    for(const el of document.querySelectorAll('[aria-label],[title],[placeholder],[alt]')){if(el.closest('[data-no-translate]'))continue;const record=attributes.get(el)||{};for(const name of ['aria-label','title','placeholder','alt']){if(!el.hasAttribute(name))continue;const current=el.getAttribute(name),old=record[name],source=old&&current===old.display?old.source:current,display=translate(source);record[name]={source,display};if(current!==display)el.setAttribute(name,display);}attributes.set(el,record);}document.documentElement.lang=language==='zh'?'zh-CN':language;document.title=translate('组会求生')+' · ROOM 404';observer?.observe(document.body,{subtree:true,childList:true,characterData:true});}
  function set(lang){if(!Object.hasOwn(labels,lang))return false;language=lang;try{localStorage.setItem(KEY,lang);}catch{}const select=document.querySelector('#language-picker');if(select)select.value=lang;apply();return true;}
  function showHelp(){let modal=document.querySelector('#international-help');if(!modal){modal=document.createElement('dialog');modal.id='international-help';modal.dataset.noTranslate='true';document.body.append(modal);}const text=tutorials[language];modal.innerHTML=`<div class="dialog-head"><h2>${text[0]}</h2><button class="close" aria-label="Close">×</button></div>${text.slice(1).map(p=>`<p>${p}</p>`).join('')}<p class="muted">${({zh:'英、日、韩剧情使用机器翻译并校对主要术语；可随时切回中文原文。',en:'English, Japanese and Korean story text is machine-translated with key terms reviewed. Switch to Chinese to view the original.',ja:'英語・日本語・韓国語の物語は機械翻訳を使用し、主要用語を確認しています。いつでも中国語の原文に切り替えられます。',ko:'영어·일본어·한국어 스토리는 기계 번역을 사용하며 주요 용어를 검토했습니다. 언제든 중국어 원문으로 전환할 수 있습니다.'})[language]}</p>`;modal.querySelector('button').onclick=()=>modal.close();modal.showModal();}
  function init(){document.querySelector('.brand-icon')?.setAttribute('data-no-translate','true');const nav=document.querySelector('.topbar nav'),label=document.createElement('label');label.className='language-control';label.dataset.noTranslate='true';label.innerHTML=`<span>🌐</span><select id="language-picker" aria-label="Language / 语言">${Object.entries(labels).map(([id,name])=>`<option value="${id}" ${id===language?'selected':''}>${name}</option>`).join('')}</select>`;nav.append(label);label.querySelector('select').onchange=e=>set(e.target.value);const help=document.createElement('button');help.className='plain';help.dataset.noTranslate='true';help.textContent='?';help.setAttribute('aria-label','How to play / 玩法');help.onclick=showHelp;nav.append(help);observer=new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;apply();});});apply();const params=new URLSearchParams(location.search);if(params.has('lang'))set(params.get('lang'));}
  return {init,set,translate,getLanguage:()=>language,glossary,tutorials,dictionary,showHelp};
})();
window.MEETING_I18N.init();
