/* Disciplinary anchors for composing a distinct case for every fine direction.
   Each anchor states actual objects and a domain-specific distinction. */
window.MEETING_KNOWLEDGE_DOMAINS=(()=>{
 const rows=`
classic;细胞与生命系统|Cells and living systems;细胞状态、组织组成与独立来源|cell states, tissue composition and independent origins;群体读数会受细胞组成和单细胞状态共同影响。|Aggregate readings reflect both composition and individual cell states.
data;计算任务与系统|Computational tasks and systems;任务输入、算法输出与运行条件|task inputs, algorithm outputs and operating conditions;预测性能、运行可靠性和使用效果是不同评价目标。|Prediction, runtime reliability and effects of use are distinct evaluation goals.
theory;数学结构与命题|Mathematical structures and propositions;定义域、命题假设与证明步骤|domains, assumptions and proof steps;命题的有效范围由定义和假设决定，而不是由算例数量决定。|Definitions and assumptions, not example counts, determine a proposition's scope.
field;田野关系与社会实践|Field relationships and social practices;访谈轮次、参与观察与地方关系|interview turns, participant observation and local relationships;访谈叙述发生于具体关系中，不能脱离研究者位置解释。|Interview accounts arise within relationships and require the researcher's position.
clinical;临床比较与患者历程|Clinical comparisons and patient trajectories;入组资格、诊疗记录与结局时间|eligibility, care records and outcome times;临床记录的可得性不等于比较组具有相同的观察机会。|Available clinical records do not ensure equal observation opportunities.
physics;物理系统与观测量|Physical systems and observables;物理量定义、测量响应与近似尺度|quantity definitions, measurement responses and approximation scales;观测量与理论量的对应需要测量模型和适用尺度。|Observables need a measurement model and applicable scale to match theoretical quantities.
chemistry;组成、结构与性质|Composition, structure and properties;成分谱、结构表征与条件依赖性质|composition spectra, structural characterization and condition-dependent properties;组成相同不保证结构、状态及性质相同。|Equal composition does not ensure equal structure, state or properties.
economics;选择、约束与市场|Choice, constraints and markets;预算约束、选择记录与制度条件|budget constraints, choices and institutions;可见选择同时受偏好、约束和可获得方案影响。|Observed choices reflect preferences, constraints and available alternatives.
humanities;文本、叙事与接受|Texts, narration and reception;文本段落、版本变化与读者解释|passages, edition changes and reader interpretations;作者意图、文本发声与读者接受不能直接相互替代。|Authorial intent, textual voice and reception cannot directly replace each other.
art;作品形式与创作过程|Artistic forms and creative processes;创作草稿、媒介痕迹与展示语境|drafts, media traces and exhibition contexts;形式选择需要对应创作问题，作品评价不必借用实验显著性。|Formal choices address creative questions; evaluation need not use experimental significance.
philosophy;概念与论证|Concepts and arguments;论证前提、概念区分与反例|premises, conceptual distinctions and counterexamples;结论是否成立取决于推理与前提，例子直观并不代替论证。|Conclusions depend on inference and premises; intuitive examples do not replace arguments.
law;规范、事实与程序|Norms, facts and procedures;规范版本、争议事实与适用程序|norm versions, disputed facts and applicable procedures;规范存在、事实被证明与规范适用是三个不同问题。|Existing norms, proven facts and norm application are distinct questions.
politics;制度与政治行动|Institutions and political action;制度安排、政治行为与执行记录|institutions, political behavior and implementation records;正式制度与实际政治行动可能有差距，比较需保留组织层次。|Formal institutions can differ from action; comparisons retain organizational levels.
education;学习与教学|Learning and instruction;学习任务、课堂实施与能力评价|learning tasks, instruction and capability assessment;参与活动不等于掌握目标能力，评价任务需要对齐目标。|Participation is not mastery; assessment tasks must align with goals.
sports;运动任务与适应|Movement tasks and adaptation;训练暴露、动作表现与疲劳状态|training exposure, movement performance and fatigue;动作改善可能来自学习、训练适应或测试条件改变。|Movement gains may reflect learning, adaptation or changed testing conditions.
psychology;心理构念与行为任务|Psychological constructs and behavioral tasks;任务反应、量表项目与构念定义|task responses, scale items and construct definitions;单一行为或总分不能完整等同心理构念。|One behavior or total score is not identical to a psychological construct.
languages;语言结构与使用|Language structure and use;语料实例、语言背景与交际任务|corpus examples, language backgrounds and communicative tasks;语法形式、实际使用和交际意图需要分别对应。|Grammar, usage and communicative intention require separate correspondence.
journalism;媒介内容与传播过程|Media content and communication;报道版本、传播路径与受众接触|report versions, circulation paths and audience exposure;内容发布、受众接触和态度变化不是同一结果。|Publication, exposure and attitude change are different outcomes.
history;史料形成与历史解释|Source formation and historical interpretation;同期文书、后出叙事与形成时间|contemporary documents, later narratives and composition dates;史料记录与事件之间的距离本身是解释的一部分。|The distance between source and event is itself part of interpretation.
earth;地球过程与空间时间尺度|Earth processes and spatial-temporal scales;站点观测、地层关系与时间尺度|station observations, stratigraphic relations and temporal scales;局地短时观测不能直接代表区域长期过程。|Local short observations do not directly represent regional long-term processes.
environment;生态过程与环境压力|Ecological processes and environmental pressures;生物群落、环境暴露与空间覆盖|communities, environmental exposure and spatial coverage;环境变化与生态响应可能有滞后并受空间尺度影响。|Ecological responses can lag environmental change and depend on spatial scale.
electrical;电子信号与器件系统|Electronic signals and device systems;电路响应、信号频谱与器件工作状态|circuit responses, spectra and device operating states;器件单项性能不等于完整系统在全部工况下可靠。|A device measure does not ensure whole-system reliability in every condition.
mechanical;载荷、运动与构件|Loads, motion and components;载荷历史、构件变形与运动轨迹|load histories, deformation and motion trajectories;静态性能与动态过程不同，连接及载荷历史会改变表现。|Static and dynamic behavior differ; connections and load history affect performance.
civil;结构、场地与城市设施|Structures, sites and urban infrastructure;荷载路径、场地条件与设施使用|load paths, site conditions and infrastructure use;局部构件满足要求不自动保证体系和使用状态符合目标。|Compliant components do not ensure system or serviceability goals.
energy;能量转换与系统边界|Energy conversion and system boundaries;能量收支、转换效率与负荷时间|energy balances, conversion efficiency and load timing;部件效率与系统净收益不同，边界改变会影响评价。|Component efficiency differs from net system benefit, which depends on boundaries.
aerospace;飞行环境与任务约束|Flight environments and mission constraints;公开载荷模型、轨迹条件与环境假设|public load models, trajectory conditions and environmental assumptions;任务表现依赖环境与资源约束，单一工况成功不代表全部任务。|Mission performance depends on environment and resources; one condition does not cover all missions.
agriculture;作物、土壤与生产环境|Crops, soils and production environments;物候阶段、田块条件与收获记录|phenological stages, field conditions and harvest records;产量形成跨越多个阶段，品种表现会随环境改变。|Yield develops across stages and cultivar performance varies with environment.
veterinary;动物健康与饲养环境|Animal health and husbandry;动物个体、饲养群组与健康历程|animals, husbandry groups and health trajectories;个体观察同时受群养环境影响，群内动物并非完全独立。|Individual observations depend on shared husbandry; group members are not fully independent.
food;食品性质与食用情境|Food properties and consumption contexts;成分、加工变化与感官或膳食记录|composition, processing changes and sensory or dietary records;食品组成、感官体验与长期营养结果是不同评价层次。|Composition, sensory experience and long-term nutrition are different levels.
pharmacy;药物暴露与作用|Drug exposure and effects;作用证据、暴露过程与安全性资料|effect evidence, exposure and safety data;靶点、功能、暴露和临床获益各需相应证据。|Targets, function, exposure and clinical benefit need corresponding evidence.
nursing;照护实施与患者体验|Care delivery and patient experience;照护过程、交接记录与患者自述|care processes, handovers and patient accounts;计划、实施和患者体验不能以登记完成来相互替代。|Plans, delivery and experience cannot be substituted by completed documentation.
management;组织行动与绩效|Organizational action and performance;分工流程、资源使用与绩效口径|workflows, resource use and performance definitions;局部指标改善可能转移负担，需检查整体目标。|Local improvements can shift burdens and must be checked against overall goals.
publicadmin;公共服务与制度执行|Public services and implementation;政策条文、执行层次与受益记录|policy texts, implementation levels and beneficiary records;政策目标不是实施事实，平均表现会掩盖不同人群的可及性。|Policy goals are not implementation facts; averages can hide unequal access.
music;声音、谱面与现场|Sound, notation and live performance;谱本版本、声部关系与演出场次|score editions, part relationships and performance instances;谱面、演奏处理和听觉接受需要分别解释。|Notation, performance choices and auditory reception require separate accounts.
military;公开战略与组织史|Public strategy and organizational history;公开政策、历史叙事与资源制度|public policies, historical narratives and resource institutions;公开表态与能力、意图不同，史料不能覆盖隐秘决策。|Public statements differ from capability and intention and cannot cover private decisions.
interdisciplinary;跨领域共同问题|Shared interdisciplinary questions;两侧研究对象、术语含义与证据接口|objects on both sides, term meanings and evidence interfaces;并列使用方法不是整合，须明确证据怎样回答同一问题。|Parallel methods are not integration; show how evidence addresses one question.
statistics;估计目标与抽样|Estimands and sampling;独立单位、抽样过程与估计不确定性|independent units, sampling and estimation uncertainty;估计含义由目标和设计决定，样本大不能代替正确独立单位。|Targets and design determine estimates; size does not replace correct independent units.
astronomy;天体信号与观测选择|Astronomical signals and observational selection;光谱、亮度时序与望远镜覆盖|spectra, brightness time series and telescope coverage;观测目录会受亮度阈值和观测窗口选择影响。|Catalogs depend on brightness thresholds and observing windows.
sociology;社会位置与互动|Social positions and interaction;社会类别、关系网络与制度情境|social categories, networks and institutions;群体差异并不自动说明个体行为机制。|Group differences do not automatically establish individual behavioral mechanisms.
anthropology;文化实践与研究关系|Cultural practice and research relationships;地方分类、访谈语境与参与关系|local classifications, interview contexts and participation relationships;研究者分类与地方意义可能不一致，需要保留在地语境。|Researchers' categories may differ from local meanings, requiring local context.
archaeology;遗址、层位与形成过程|Sites, strata and formation processes;出土位置、地层堆积与器物组合|find locations, deposits and assemblages;物品年代、堆积时间和发现位置可能不同。|Object age, deposition time and discovery location can differ.
geography;空间单元与地理过程|Spatial units and geographic processes;空间边界、邻接关系与尺度转换|spatial boundaries, adjacency and scale conversion;划分单元改变可能改变统计关系，区域结果不直接代表个人。|Changing spatial units can change associations; area results do not directly describe individuals.
materials;微结构与材料性能|Microstructure and material properties;成分、微结构与载荷环境|composition, microstructure and loading environment;同成分材料可因结构、缺陷与工况具有不同性质。|Equal composition can yield different properties through structure, defects and conditions.
automation;反馈、辨识与系统状态|Feedback, identification and system states;闭环结构、状态观测与扰动响应|feedback structure, state observations and disturbance responses;模型拟合与控制稳定是不同目标，时延会影响闭环。|Model fit and control stability differ; delays affect feedback loops.
communications;信道、编码与资源|Channels, coding and resources;信道时序、编码配置与传输错误|channel sequences, coding configurations and transmission errors;比较性能须保留带宽、功率和时变信道的条件。|Performance comparisons retain bandwidth, power and time-varying channel conditions.
architecture;空间设计与建筑使用|Spatial design and building use;空间图纸、使用路径与环境评价|plans, use paths and environmental assessments;设计意图不等于实际使用，空间体验受人群与时间影响。|Design intention differs from use; experiences depend on people and timing.
design;设计任务与使用反馈|Design tasks and use feedback;原型版本、任务路径与失败反馈|prototype versions, task paths and failure feedback;用户喜欢不等于能够完成任务，失败路径是设计证据。|Liking does not imply task completion; failures are design evidence.
publichealth;群体健康与服务覆盖|Population health and service coverage;群体分母、健康事件与服务可及性|population denominators, health events and service access;病例数量不等于发生率，服务覆盖不等于实际健康获益。|Case counts differ from incidence; coverage differs from health benefit.
cardiology;心脏功能与循环|Cardiac function and circulation;心脏结构、循环负荷与心血管事件|cardiac structure, circulatory loading and cardiovascular events;功能指标受负荷影响，不能独立代表结构及长期结局。|Functional measures depend on loading and do not establish structure or long-term outcomes.
respiratory;通气、交换与气道|Ventilation, gas exchange and airways;肺功能、肺结构与症状活动|lung function, structure and symptom-related activity;通气指标、气体交换和日常症状提供不同信息。|Ventilation, gas exchange and everyday symptoms provide different information.
gastroenterology;消化功能与组织状态|Digestive function and tissue state;动力、黏膜资料与营养症状|motility, mucosal data and nutritional symptoms;症状、动力与黏膜改变不总一致，需对应不同观察层次。|Symptoms, motility and mucosal changes can differ across observation levels.
endocrinology;激素、代谢与反馈|Hormones, metabolism and feedback;激素时序、代谢指标与反馈状态|hormone time courses, metabolic measures and feedback states;单个激素时点不能完整反映反馈系统和代谢状态。|One hormone measurement does not describe the complete feedback or metabolic state.
nephrology;肾滤过、排泄与损伤|Kidney filtration, excretion and injury;滤过估计、尿液标志与容量状态|filtration estimates, urine markers and volume states;功能估计、排泄改变与组织损伤不是同一个结果。|Estimated function, changed excretion and tissue injury are different outcomes.
hematology;血细胞、造血与止血|Blood cells, hematopoiesis and hemostasis;细胞计数、形态与凝血过程|cell counts, morphology and coagulation processes;数量、形态和功能可不同步，不能只用计数概括血液系统。|Counts, morphology and function can diverge; counts do not describe the whole system.
rheumatology;炎症活动与组织损伤|Inflammatory activity and tissue damage;活动度、抗体资料与关节功能|activity measures, antibody data and joint function;活动度、抗体与累积损伤提供不同层次的信息。|Activity, antibodies and cumulative damage provide different levels of information.
neurology;神经网络与功能表现|Neural networks and function;神经结构、电生理与认知运动表现|neural structure, electrophysiology and cognitive-motor performance;结构异常与功能表现不是一一对应关系。|Structural abnormalities do not map one-to-one onto functional performance.
infectious;感染患者历程与宿主反应|Infection trajectories and host responses;公开病例历程、宿主状态与诊断覆盖|public case trajectories, host states and diagnostic coverage;检测阳性、临床症状与宿主反应不能混为同一结果。|Positive tests, symptoms and host responses are not one outcome.
geriatrics;衰弱、功能与照护|Frailty, function and care;多病记录、活动能力与照护支持|multimorbidity, activity capacity and care support;年龄相同不代表功能储备及照护需要相同。|Equal age does not imply equal functional reserve or care needs.
general-surgery;外科患者与恢复过程|Surgical patients and recovery;术前状态、围术期过程与恢复结局|preoperative states, perioperative processes and recovery outcomes;术后结果同时受术前状态与整个恢复过程影响。|Postoperative outcomes depend on preoperative state and recovery processes.
cardiac-surgery;心胸结构与术后恢复|Cardiothoracic structure and recovery;结构病变、术后功能与长期随访|structural disease, postoperative function and long-term follow-up;早期技术结果与长期功能及患者体验不能互代。|Early technical outcomes do not replace long-term function or experience.
neurosurgery;神经外科功能结局|Neurosurgical functional outcomes;病变位置、功能状态与恢复时间|lesion location, functional state and recovery time;影像变化不能单独概括认知、运动或参与结局。|Imaging changes do not alone describe cognition, movement or participation.
orthopedics;骨关节、载荷与运动|Bone, joints, loading and motion;结构影像、载荷反应与步态功能|structural images, loading responses and gait function;结构对齐与疼痛、运动功能可能不一致。|Alignment can differ from pain and movement function.
urology;排尿功能与泌尿结构|Urinary function and structure;排尿日记、解剖资料与随访体验|voiding diaries, anatomy data and follow-up experience;结构、排尿表现与患者困扰提供不同评价维度。|Structure, voiding and patient distress are distinct dimensions.
plastic-surgery;修复、形态与功能|Repair, form and function;创面过程、形态记录与功能体验|wound trajectories, morphology and functional experience;外观、功能和患者满意度不是同一结果。|Appearance, function and satisfaction are different outcomes.
obgyn;生殖与孕产历程|Reproductive and maternity trajectories;生殖阶段、孕产时间与母婴结局|reproductive stages, maternity timing and maternal-infant outcomes;母体与婴儿是关联但不同的观察单位和结局主体。|Mothers and infants are related but distinct units and outcome subjects.
pediatrics;儿童生长与发育|Child growth and development;年龄阶段、生长曲线与儿童功能|developmental stages, growth curves and child function;儿童指标解释依赖阶段，不能直接套用成人含义。|Children's measures depend on development and cannot simply inherit adult meanings.
ophthalmology;眼结构与视觉|Eye structure and vision;眼部影像、视觉任务与屈光资料|eye images, visual tasks and refraction data;视力、视野、屈光和生活中的视觉功能是不同维度。|Acuity, field, refraction and everyday vision are distinct dimensions.
ent;听觉、平衡与言语|Hearing, balance and speech;听觉阈值、前庭任务与沟通表现|hearing thresholds, vestibular tasks and communication performance;听阈改善不自动等同复杂场景沟通改善。|Improved thresholds do not automatically improve communication in complex settings.
dermatology;皮肤屏障与患者症状|Skin barriers and symptoms;皮损形态、屏障资料与瘙痒体验|lesion morphology, barrier data and itch experience;皮损面积、炎症程度与主观困扰并非同一个维度。|Lesion area, inflammation and distress are distinct dimensions.
oncology;肿瘤负担与患者结局|Tumor burden and patient outcomes;分期、病灶变化与生存功能|staging, lesion changes and survival-function outcomes;病灶缩小与长期生存、生活质量需要分别评价。|Lesion reduction, long-term survival and quality of life require separate assessment.
emergency;急诊时间与需求|Emergency timing and demand;分诊时间、就诊流程与需求波动|triage timing, care workflows and demand fluctuations;某环节提速可能转移等待，需保留整段患者时间线。|Faster stages can shift waits; retain the full patient timeline.
critical-care;器官状态与重症恢复|Organ states and critical-care recovery;器官功能、支持过程与长期恢复|organ function, support processes and long-term recovery;短期存活与长期功能恢复是不同结局。|Short-term survival and long-term functional recovery are distinct outcomes.
anesthesiology;围术期状态与疼痛|Perioperative states and pain;监测时序、疼痛报告与恢复活动|monitoring time courses, pain reports and recovery activity;疼痛强度、活动能力和认知恢复不能以一项评分概括。|Pain intensity, activity and cognitive recovery need more than one score.
radiology;影像形成与判读|Image formation and interpretation;成像参数、图像质量与读者判断|acquisition parameters, image quality and reader judgments;可见结构与临床解释之间需要保留采集及判读条件。|Acquisition and interpretation conditions connect visible structure to clinical meaning.
ultrasound;声学窗口与超声定量|Acoustic windows and ultrasound quantification;声窗、切面与运动相关测量|acoustic windows, planes and motion-related measures;切面和声窗改变可影响定量，不应全部归因于对象变化。|Changing planes and windows can affect measurements without subject changes.
pathology;组织形态与病理解释|Tissue morphology and pathology interpretation;组织区域、切片层次与判读分歧|tissue regions, section levels and interpretation disagreements;切片层面的特征不自动代表整个病变或患者。|Section-level features do not automatically describe an entire lesion or patient.
lab-medicine;检验测量与解释|Laboratory measurement and interpretation;平台校准、参考区间与个体结果|platform calibration, reference intervals and individual results;参考区间与疾病诊断阈值不是同一个概念。|Reference intervals differ from diagnostic thresholds.
nuclear-medicine;示踪信号与定量影像|Tracer signals and quantitative imaging;公开影像、重建参数与定量区域|public images, reconstruction parameters and quantified regions;定量值受采集时点和重建影响，信号不直接等同单一机制。|Timing and reconstruction affect quantified signals, which do not imply one mechanism.
rehabilitation;能力、活动与参与|Capacity, activity and participation;功能任务、日常活动与环境支持|functional tasks, daily activities and environmental support;受控场景下的能力不等于真实生活参与。|Controlled-setting capacity differs from real-life participation.
oral-medicine;口腔结构与使用功能|Oral structure and use function;牙周或牙体资料、咀嚼功能与生活体验|periodontal-dental records, mastication and everyday experience;形态评价、咀嚼功能和生活质量提供不同信息。|Morphology, mastication and quality of life provide different information.
traditional-medicine;传统资料与现代评价|Traditional sources and modern assessment;原始文献、证候描述与独立结局|original texts, syndrome descriptions and independent outcomes;传统记载的存在不能替代现代比较及作用证据。|Traditional accounts do not replace modern comparative or effect evidence.
medical-genetics;变异与表型解释|Variants and phenotype interpretation;参考序列、家系关系与表型覆盖|reference sequences, pedigrees and phenotype coverage;变异关联、功能资料与个体临床解释应分层。|Variant associations, functional evidence and clinical interpretation need separate levels.
anatomy-physiology;结构与生理功能|Anatomy and physiology;解剖定位、组织层次与功能状态|anatomical locations, tissue levels and functional states;结构存在不等于某种功能在该状态下已经被证明。|An existing structure does not prove a function in a particular state.
health-policy;健康制度与服务实施|Health institutions and delivery;服务支付、人员配置与患者路径|service payment, staffing and patient pathways;制度覆盖、服务接触与患者获益是不同层次。|Institutional coverage, service contact and patient benefit are distinct levels.
medical-immunology;免疫状态与组织语境|Immune states and tissue contexts;细胞组成、免疫标志与组织背景|cell composition, immune markers and tissue context;免疫标志与细胞比例变化不能直接等同整体免疫功能。|Immune markers or changed proportions do not directly establish overall immune function.
medical-microbiology;微生物群落公开资料|Public microbial-community data;群落组成、测序来源与公开注释|community composition, sequencing origins and public annotations;相对丰度变化不独立证明绝对数量及宿主作用变化。|Relative abundance does not establish absolute counts or host effects.
medical-biochemistry;分子代谢与测量|Molecular metabolism and measurement;分子鉴定、丰度与代谢网络|molecular identification, abundance and metabolic networks;分子丰度变化不直接说明代谢通量和反应方向。|Abundance changes do not directly establish metabolic flux or reaction direction.
epidemiology;人群暴露与健康事件|Population exposures and health events;人群分母、暴露定义与随访起点|population denominators, exposure definitions and follow-up origins;风险比较需要共同资格及时间起点，关联不独立证明因果。|Risk comparisons need aligned eligibility and origins; association alone is not causality.
health-economics;健康价值与资源取舍|Health value and resource tradeoffs;效果来源、效用口径与成本时期|effect sources, utility definitions and cost periods;价值评价依赖比较方案、视角和时间范围。|Value assessment depends on comparator, perspective and time horizon.
clinical-pharmacology;患者暴露与药物结局|Patient exposure and drug outcomes;处方使用、暴露时序与患者结局|prescribing-use records, exposure timing and patient outcomes;处方、配药和真实使用不是同一种暴露记录。|Prescribing, dispensing and actual use are different exposure records.
forensic-medicine;法医学记录与推断|Forensic records and inference;公开鉴定资料、观察条件与推断范围|public assessment records, observation conditions and inference scope;观察相符不等于唯一解释，鉴定需要明确不确定性。|Compatible observations are not a unique explanation; assessment requires uncertainty.
chinese-materia-medica;中药来源与成分|Materia medica origins and composition;来源鉴别、成分差异与作用资料|origin identification, compositional variation and effect data;名称相同不保证来源、批次和成分相同。|Identical names do not ensure identical origins, batches or composition.
integrated-medicine;结合评价与证据层次|Integrated assessment and evidence levels;两类理论术语、比较设计与患者结局|two theoretical vocabularies, comparative designs and patient outcomes;术语对应不是机制等同，需要独立可检查的桥接依据。|Terminological correspondence is not mechanistic equivalence and needs checkable bridges.
special-medicine;特殊环境与适应|Special environments and adaptation;环境负荷、暴露阶段与功能表现|environmental loads, exposure stages and function;特殊环境中的观察不能脱离暴露及适应阶段解释。|Special-environment observations require exposure and adaptation context.
medical-technology;医疗技术与任务可靠性|Medical technology and task reliability;技术版本、测量性能与实际使用|technology versions, measurement performance and use;技术读数可靠与完成临床任务不是同一个目标。|Reliable readings and successful clinical tasks are different goals.
`.trim().split('\n').map(line=>{const a=line.indexOf(';'),id=line.slice(0,a),cells=line.slice(a+1).split(/;(?=[^;|]*\|)/);if(cells.length!==3)throw new Error('Domain fields '+id);return {id,values:cells.map(c=>c.split('|'))};});
 return {rows,add(text){for(const line of text.trim().split('\n')){const a=line.indexOf(';'),id=line.slice(0,a),cells=line.slice(a+1).split(/;(?=[^;|]*\|)/);if(cells.length!==3)throw new Error('Domain fields '+id);rows.push({id,values:cells.map(c=>c.split('|'))});}}};
})();
