/* Topical vocabulary is scoped to its host field. Shared concepts are reusable
   prerequisites; composed cases own their objects, material selection and dispute. */
window.MEETING_KNOWLEDGE_FACETS=(()=>{
 const rows=[];
 function add(text){for(const line of text.trim().split('\n')){const parts=line.split(';'),id=parts.shift(),scope=parts.shift(),pattern=parts.shift(),cells=parts.join(';').split(/;(?=[^;|]*\|)/);if(cells.length!==5)throw new Error('Facet fields '+id);rows.push({id,scope,match:new RegExp(pattern),values:cells.map(c=>c.split('|'))});}}
 add(`
cardiac;medicine,science;心(?!理)|冠|瓣膜|主动脉|循环;心脏负荷与功能的并列记录|paired cardiac-loading and functional records;负荷依赖|Load dependence;功能读数可随前后负荷改变，不独立说明收缩机制。|Functional readings can change with loading without identifying contractile mechanisms.;直接心脏变化|direct cardiac change;循环负荷变化|changed circulatory loading
renal;medicine,science;肾|滤过|尿|透析;滤过估计与尿液标志的不同轨迹|divergent filtration-estimate and urine-marker trajectories;功能与损伤|Function and injury;功能估计与组织损伤标志不同，短期方向也可不一致。|Functional estimates and injury markers differ and can change in opposite directions.;功能状态变化|changed functional state;损伤或容量变化|changed injury or volume
neural;medicine,science;神经|脑|癫痫|认知|头痛;电生理、结构与任务表现的对应|correspondence among electrophysiology, structure and task performance;结构与功能对应|Structure-function correspondence;相同结构表现可对应不同功能，任务和观察时点影响解释。|Similar structural findings can accompany different function depending on tasks and timing.;结构相关信号|structure-related signals;任务或功能状态|task or functional state
respiration;medicine,science;呼吸|肺|气道|通气|氧疗;通气、交换与活动症状的分项资料|separate ventilation, exchange and activity-symptom data;通气与气体交换|Ventilation and gas exchange;通气表现不能独立概括交换效率及日常功能。|Ventilation alone does not establish exchange efficiency or everyday function.;气道与通气变化|airway and ventilation changes;交换或活动限制|exchange or activity constraints
metabolism;medicine,science;代谢|糖尿|肥胖|内分泌|甲状腺|激素|垂体|肾上腺;激素或代谢时序与状态分层|hormonal or metabolic series with state strata;反馈与时序|Feedback and timing;反馈系统中的单一时点可错过相位变化，不能完整代表动态状态。|One time point can miss feedback phases and does not describe dynamic state.;持续代谢状态|sustained metabolic state;测量相位或反馈改变|measurement phase or altered feedback
digestive;medicine,science;消化|胃|肠|胰|胆|肝|内镜;动力、组织评价与消化症状的对照|motility, tissue assessment and digestive-symptom comparisons;症状与组织过程|Symptoms and tissue processes;症状可受多个过程影响，症状变化不独立定位组织机制。|Symptoms reflect multiple processes and do not independently locate a tissue mechanism.;组织或动力改变|tissue or motility changes;感觉、摄入或观察差异|sensory, intake or observation differences
hematology;medicine,science;血液|造血|贫血|血细胞|输血;细胞计数、形态与功能分开登记|separate cell counts, morphology and function;数量与功能|Quantity and function;数量正常不保证形态和功能相同，比例变化也不同于绝对数量。|Normal counts do not ensure equal morphology or function; proportions differ from absolute counts.;数量或组成变化|quantity or composition changes;单细胞功能变化|single-cell functional changes
hemostasis;medicine,science;血栓|凝血|止血|血小板;血小板、凝血及出血资料的分别评价|separate platelet, coagulation and bleeding assessments;止血的多个环节|Multiple hemostatic processes;不同环节的指标不能混成一个完整止血或风险结论。|Measures of distinct processes do not establish one complete hemostatic or risk conclusion.;血小板环节变化|platelet-process changes;凝血或出血背景|coagulation or bleeding context
immunity;medicine,science;免疫|抗体|自身|风湿|炎性|炎症;细胞组成、活化标志与组织状态|cell composition, activation markers and tissue states;标志与功能|Markers and function;标志强度、细胞比例和功能响应不同，单项不能概括整个系统。|Marker intensity, proportions and function differ; one measure does not describe the whole system.;活化或功能改变|activation or functional change;细胞组成改变|changed cell composition
oncology;medicine,science;肿瘤|癌|瘤;病灶变化、分期与患者功能的对照|lesion changes, staging and patient-function comparisons;病灶与患者结局|Lesions and patient outcomes;病灶指标变化与生存或生活功能是不同层次。|Lesion changes and survival or everyday function are distinct levels.;病灶负担变化|changed lesion burden;观察选择或患者功能|observation selection or patient function
musculoskeletal;medicine,science;骨|关节|肌|脊柱|运动障碍;结构、负荷及动作功能的联合描述|joint descriptions of structure, loading and motion function;结构与使用表现|Structure and use performance;形态修复不自动恢复真实运动功能，环境和负荷需要保留。|Morphological repair does not automatically restore movement; environment and loading matter.;组织结构变化|structural change;载荷或活动策略变化|changed loading or activity strategy
vision;medicine,science;眼|视网膜|青光|角膜|白内|视力|屈光|近视;视野、视力及视觉任务的分别登记|separate fields, acuity and visual-task records;视觉的多维功能|Multidimensional vision;视力读数不能完整代表视野、对比及复杂任务能力。|Acuity does not fully describe fields, contrast or complex tasks.;光学或结构变化|optical or structural change;任务及知觉条件|task and perceptual conditions
auditory;medicine,science;耳|听|嗅|前庭|咽喉|吞咽|言语;感知阈值、沟通任务及平衡表现|sensory thresholds, communication tasks and balance performance;阈值与日常任务|Thresholds and everyday tasks;受控阈值改善不自动转为复杂环境中的沟通或活动改善。|Improved controlled thresholds need not improve complex-environment communication or activity.;感知能力变化|changed sensory capacity;任务负荷与环境差异|task-load and environment differences
skin;medicine,science;皮肤|皮损|创面|瘢痕|毛发|屏障;形态、屏障与患者困扰的对照|morphology, barrier function and distress comparisons;可见变化与体验|Visible change and experience;外观、屏障功能和主观困扰可不同步。|Appearance, barrier function and distress can change differently.;形态或组织变化|morphological or tissue change;患者感受与功能差异|experience and functional differences
reproduction;medicine,science;生殖|妊娠|围产|妇|孕|新生;生命阶段与母婴或生殖结局的对应|life-stage and reproductive or maternal-infant outcome correspondence;关联主体与观察单位|Linked subjects and observation units;母婴或家庭成员相关但不是同一独立单位，阶段还影响解释。|Linked family or maternal-infant subjects are not one independent unit, and stage matters.;阶段相关差异|stage-related differences;主体间关联或选择|linked subjects or selection
aging;medicine,science;老年|衰老|衰弱|寿命;功能储备、年龄及照护需要|functional reserve, age and care needs;年龄与功能储备|Age and functional reserve;同年龄的人可具有不同功能及适应能力，年龄不是完整机制解释。|Same-age people can differ in function and adaptation; age is not a complete mechanism.;功能储备差异|functional-reserve differences;年龄标签或照护背景|age labels or care context
development;medicine,science;儿童|儿科|发育|生长;发育分期、成长轨迹与功能任务|developmental staging, growth trajectories and functional tasks;年龄与阶段|Age and stage;相同日龄或年龄不保证相同发育状态。|Equal chronological age does not ensure equal developmental state.;真实阶段差异|developmental-stage differences;分期错位|stage misalignment
genetics;medicine,science,agriculture;遗传|家系|变异|罕见|种质|育种;参考版本、来源关系与变异表型对应|reference versions, relatedness and variant-phenotype correspondence;关联与功能解释|Association and functional interpretation;共同变化或共分离提供线索，但不能独立证明因果及个体结局。|Covariation or segregation is informative but does not establish causality or individual outcomes.;遗传相关信号|genetic associations;来源结构或环境差异|population structure or environment differences
microbial;medicine,science,agriculture;微生物|微生态|群落|宿主;公开组成表、注释版本与绝对量边界|public composition tables, annotation versions and absolute-count limits;相对与绝对数量|Relative and absolute quantities;相对丰度会上下联动，一个类别比例升高不证明绝对数量升高。|Relative abundances co-vary; a higher proportion does not establish a higher absolute count.;组成变化|compositional change;总量或注释变化|total-count or annotation change
anatomy;medicine,science;解剖|组织|生理|病理|切片;结构定位、组织层次与判读条件|structural locations, tissue levels and interpretation conditions;局部与整体|Parts and wholes;局部组织或切片不能无条件代表整个个体或器官。|Local tissue or sections do not unconditionally represent an organ or person.;局部真实差异|local differences;取样位置或判读差异|sampling-site or reader differences
molecular;medicine,science;分子|细胞|蛋白|生化|代谢组|组学|受体;鉴定可靠性、分子丰度与功能资料|identification reliability, molecular abundance and function data;丰度与过程|Abundance and process;丰度变化不自动代表功能、流量或作用方向变化。|Abundance changes do not automatically establish function, flux or effect direction.;分子状态变化|molecular-state changes;鉴定、组成或测量差异|identification, composition or measurement differences
rehabilitation;medicine,education;康复|参与|作业|步态|远程康复;测试能力、生活活动与环境支持|tested capacity, everyday activity and environmental support;能力与参与|Capacity and participation;受控任务中的能力与真实环境中的参与不同。|Controlled-task capacity differs from real-environment participation.;能力改善|capacity gains;环境或支持变化|environment or support changes
nutrition;medicine,science,agriculture,engineering;营养|膳食|饲料|食物|食品;组成、摄入及整体模式的分别记录|separate composition, intake and overall-pattern records;组成与实际摄入|Composition and actual intake;成分丰富不代表摄入足够，实际摄入又不等于长期健康结果。|Rich composition is not adequate intake, and intake is not a long-term health outcome.;摄入或组成变化|intake or composition changes;总模式与报告差异|overall patterns or reporting differences
care;medicine;照护|护理|交接|交班|患者体验|家属|家庭照护;计划、实施与患者本人或代理报告|plans, delivery and patient or proxy reports;交付与体验|Delivery and experience;安排好的措施不等于实施，代理报告不等于患者本人体验。|Planned care is not delivery, and proxy reports differ from patient experience.;照护实际改变|changed delivered care;登记或报告者差异|documentation or reporter differences
pharmaco;medicine;药物|药代|药理|药学|用药|针灸|中药;来源、暴露及作用层次的分别资料|separate origins, exposure and effect levels;暴露与作用|Exposure and effects;记录暴露或传统使用不自动证明药效或临床获益。|Exposure or traditional use does not establish efficacy or clinical benefit.;作用相关变化|effect-related changes;暴露、选择或背景差异|exposure, selection or context differences
`);
 return {rows,add};
})();
