/* 连续世界：所有抽签只在推进时间或选择时发生，读取和翻译不消耗随机数。 */
window.MEETING_WORLD=(()=>{
  'use strict';
  const C=window.MEETING_CONTENT,P=window.MEETING_PREPARATION,copy=x=>JSON.parse(JSON.stringify(x)),clamp=x=>Math.max(0,Math.min(100,x));
  const modes=[
    ['normal','普通校园','各种路线交错，消息与后果慢慢接上。'],
    ['lucky','幸运的一周','机会更常出现，求助与核实更容易收到回应。'],
    ['cascade','连环事故','突发更密，休息和留余量会更重要。'],
    ['social','社交风暴','人物请求、误会和传播更频繁，拒绝也有后续。'],
    ['poor','穷组求生','低经费起步，补充资源和控制范围影响课题。'],
    ['absurd','学术荒诞季','校猫、食堂和奇怪活动轮番占用你的时间。'],
    ['blind','盲盒课题组','开局随机两个学科；人物、经费和各类事件随后揭晓。']
  ].map(([id,name,desc])=>({id,name,desc}));
  const goals=[['paper','赶自己的论文','detail'],['grant','准备项目申请','direct'],['teach','备课与助教工作','brief'],['family','处理家里的事情','cautious'],['relationship','安排重要的约会','cooperate'],['job','寻找下一份工作','direct'],['rest','想守住休息时间','brief'],['collaborate','寻找新的合作伙伴','cooperate']].map(([id,title,focus])=>({id,title,focus}));
  const messages=[
    ['cancel','有人说本周组会取消了','聊天截图说老师临时外出，日历上却还是原来的时间。','群聊截图'],
    ['deadline','截止日期好像延后了','转发消息说材料可以下周交，正式系统还显示本周截止。','二手转发'],
    ['method','这个办法据说可以省一半时间','同门发来一个简短教程，但没有写限制条件。','熟人经验'],
    ['room','会议室似乎临时换了','朋友看见门口贴了纸条，却没有拍到完整日期。','走廊目击'],
    ['fund','听说可以申请一笔补助','群里有人转述一个申请入口，资格条件还不明确。','群聊线索'],
    ['dataset','新的资料入口能直接使用吗','共享盘出现一份整理好的材料，来源说明只写了一行。','共享文件'],
    ['visit','大拿好像会旁听这次组会','师弟说听到了邀请，导师还没有确认。','口头消息'],
    ['authorship','对方说合作贡献以后再谈','一段热情的聊天提出共同做事，却没写交付范围。','合作邀约']
  ].map(([id,title,scene,source])=>({id,title,scene,source}));
  const opportunities=[
    ['workshop','临时空出的研讨席位','一场小型研讨会有人退出，席位只保留一小段时间。','literature'],
    ['archive','限时开放的档案室','资料室临时开放，但预约窗口很短。','record'],
    ['mentor','一位访客愿意听五分钟','对方马上离开校园，你能带一个具体问题去聊。','boundary'],
    ['collab','跨组合作的试做窗口','另一组愿意提供一份材料，但需要你先说清交换范围。','method'],
    ['poster','海报展示的临时名额','空出来的展示名额可以用，也可能挤掉自己的原定安排。','rehearsal'],
    ['friend','朋友约你去看展','朋友只在这两天有空。这次机会也可以留给生活。','rest']
  ].map(([id,title,scene,kind])=>({id,title,scene,kind}));
  const seasons=[
    ['cat','校猫拿走了会议室钥匙','猫把钥匙拖到了沙发下面。现在整个组站在门口。'],
    ['canteen','组会改在食堂角落','会议室被征用，导师提议边吃边讲。隔壁正在叫号。'],
    ['files','七个文件都叫最终版','共享盘里有七份最终版，谁也不敢肯定最后改的是哪份。'],
    ['drill','消防演练撞上汇报','警报响起时，你刚打开最复杂的一页。队伍里还在讨论。'],
    ['beauty','实验室门面评选','学院要拍展示照，老师希望桌面看起来像会出成果。'],
    ['meal','食堂推出导师同款套餐','套餐附带一张写着“再补一个”的小纸条，同门想拍短视频。'],
    ['festival','周年活动借走所有插线板','展览需要插线板，你的电脑电量却已经开始报警。'],
    ['robot','自动纪要把疑问写成了结论','软件把“是否成立”识别成了“已经成立”，群里开始祝贺。']
  ].map(([id,title,scene])=>({id,title,scene}));
  const channels=[
    ['careful','更多人带着原始记录来找你','大家记得你会追来源，这次请求你一起查一处不一致。'],
    ['social','邀请又多了一张','上次交流的人带来新朋友，希望你再讲一遍自己的课题。'],
    ['rest','朋友替你留了一个安静下午','你前几次守住了休息安排，朋友知道可以不用聊进度。'],
    ['show','热闹的故事又被转发','有人记得你上次的妙语，想让你替一个不熟悉的说法站台。'],
    ['boundary','有人来问你怎样拒绝临时加活','你之前明确过范围，现在同门想请你一起商量边界。']
  ].map(([id,title,scene])=>({id,title,scene}));
  const repercussions={support:['严厉的追问后，导师私下发来资料','上次被追得很紧，但导师后来发了一份更合适的来源，并问你愿不愿意缩小问题。'],praise:['表扬带来了一个新请求','组会里的一句肯定被别人听见，现在多了一份希望你帮忙处理的材料。'],rumor:['你的话少了后半句','有人转述了组会回答，保留了结论，却漏掉了你说明的限制。'],repair:['散会后，同门想重新谈谈','上次现场的回应让对方不太舒服。现在有机会把原意和实际记录摆在一起。'],pivot:['导师建议换一个更小的问题','上次发现的漏洞没有消失，对方愿意让你重新界定下一步。']};
  const statuses={draft:'初步草稿',checked:'有本版核对记录',flaw:'发现待处理漏洞',narrowed:'问题已缩小',pivot:'方向已调整',ready:'可作有限结论'};
  const tick=w=>(w.number-1)*14+w.day*2+w.slot;
  const derive=(root,n,kind=0)=>{let x=(root^Math.imul(n+1,0x9e3779b9)^Math.imul(kind+1,0x85ebca6b))>>>0;x=Math.imul(x^(x>>>16),0x7feb352d);x=Math.imul(x^(x>>>15),0x846ca68b);return (x^(x>>>16))>>>0;};
  const pick=(w,a,rand)=>a[Math.floor(rand(w)*a.length)];
  function config(config,root){const c={...config,rulesVersion:config.rulesVersion||(window.MEETING_ACADEMY?'10':'09'),playMode:modes.some(m=>m.id===config.playMode)?config.playMode:'normal'};if(c.playMode==='blind'){const a=C.projects.filter(p=>p.id!=='interdisciplinary').map(p=>p.id),i=derive(root,0)%a.length,first=a.splice(i,1)[0];c.project='interdisciplinary';c.mixProjects=[first,a[derive(root,1)%a.length]];}if(window.MEETING_DIRECTIONS){const list=window.MEETING_DIRECTIONS.list(c);if(!list.some(d=>d.id===c.direction))c.direction=list[0].id;}return c;}
  function init(w,previous,rand){if(w.config.uncertainty===false)return;const old=previous?.world?.challenge===!!w.config.challenge?previous.world:null,mode=w.config.playMode||'normal';
    w.world=old?copy(old):{version:1,root:w.config.challengeSeed??w.seed,challenge:!!w.config.challenge,runCareer:{relations:{boss:50,stats:50,senior:50},bag:{},experience:0,meetings:0,debt:0,coins:0},paths:{careful:0,social:0,rest:0,show:0,boundary:0},messages:[],opportunities:[],queue:[],npcs:{},artifact:{version:1,route:window.MEETING_MIX?.route(w)||w.config.project,scope:3,status:'draft',checks:[],history:[],claimed:0},history:[],seasons:[],report:[],plan:null,focus:null};
    const a=w.world;a.mode=mode;a.plan=null;a.focus=null;a.schedule={};a.weekEvents=0;
    if(!old&&mode==='poor'&&w.group){w.group.balance=8;w.group.income=2;w.group.funding='靠省着用维持';w.group.news.after=8;}
    if(!old){const life=C.roles.find(r=>r.id===w.config.role)?.life||{};for(const [k,v] of Object.entries(life))w.resources[k]=clamp(w.resources[k]+v);}
    if(!old&&mode==='lucky'){w.resources.energy=85;w.resources.stress=12;}
    if(old&&previous.config.mentorId!==w.config.mentorId)delete a.npcs['mentor-0'];
    if(old&&(previous.config.project!==w.config.project||w.config.direction&&previous.config.direction!==w.config.direction)){const prior=a.artifact,d=window.MEETING_DIRECTIONS.find(w.config.direction);a.artifact={version:prior.version+1,route:d?.route||w.config.project,direction:d?.id,scope:2,status:'draft',checks:[],history:[...prior.history,{week:w.number,version:prior.version+1,status:'draft',action:'开局选择了新的研究方向，旧成果继续归档，新题从草稿开始。'}].slice(-24),references:[],claimed:0};}
    for(const m of w.group?.members||[]){if(m.rank==='mentor'&&!m.mentorStyle)m.mentorStyle=m.id==='mentor-0'&&C.personas.some(p=>p.id===w.config.persona)?w.config.persona:pick(w,C.personas,rand).id;let n=a.npcs[m.id];if(!n)n=a.npcs[m.id]={goal:pick(w,goals,rand).id,memory:[],mood:0};n.mood=Math.floor(rand(w)*5)-2;if(rand(w)<.22)n.goal=pick(w,goals,rand).id;}
    window.MEETING_DIRECTIONS?.init(w,old);expire(w);a.artifact.history=a.artifact.history.slice(-24);a.history=a.history.slice(-80);a.report=a.report.slice(-52);
  }
  function expire(w){const a=w.world;if(!a)return;for(const o of a.opportunities)if(['offered','reserved'].includes(o.status)&&tick(w)>o.deadline){o.status='expired';a.history.push({week:w.number,type:'expired',id:o.id,text:'机会窗口关闭了，预留不等于实际参加。'});}a.opportunities=a.opportunities.slice(-16);a.messages=a.messages.slice(-16);}
  function choice(text,action,effects={},traits={},extra={}){return {text,worldAction:action,effects,traits,career:{},work:{progress:0,quality:0},preparationGains:{},continueOriginal:false,flavor:'具体后果会在选择后揭晓。',...extra};}
  function event(w,type,id,rand){const a=w.world,p=a.artifact;let title='',scene='',choices=[];
    if(type==='message'){const d=messages.find(x=>x.id===id),m={id:derive(a.root,tick(w),7)+'-'+id,kind:id,truth:rand(w)<.52,status:'unseen',source:d.source,week:w.number};a.messages.push(m);title=d.title;scene=d.scene+' 消息来自：'+d.source+'。现在还没有确认。';choices=[choice('用这半天联系正式来源，等一份能追溯的答复。','check',{energy:-7,stress:2},{study:1}),choice('先按这条消息安排，节省核实时间。','believe',{energy:4,stress:-3}),choice('保留原定边界，明确告诉转发者自己还没确认。','hold',{energy:-2,stress:1},{})];id=m.id;}
    else if(type==='opportunity'){const d=opportunities.find(x=>x.id===id),o={id:derive(a.root,tick(w),8)+'-'+id,kind:id,prepKind:d.kind,deadline:tick(w)+2,status:'unseen',route:window.MEETING_MIX?.route(w)||w.config.project};a.opportunities.push(o);title=d.title;scene=d.scene+' 留位不算完成，窗口结束前还要实际投入一个生活片段。';choices=[choice('先预留机会，稍后安排一个片段真正参加。','reserve',{stress:2}),choice('说明现有安排，把这个机会转给需要的人。','pass',{stress:-2},{collaboration:1}),choice('当场用这半天参加，原定安排让到后面。','attend',{energy:-10,stress:4},{})];id=o.id;}
    else if(type==='npc'){const m=w.group.members.find(x=>x.id===id),n=a.npcs[id],g=goals.find(x=>x.id===n.goal);title=m.name+'也有自己的安排';scene=m.name+'最近在'+g.title+'。'+(n.memory.length?'对方还记得你之前怎样回应过请求。':'')+'对方想请你帮一小段，也提到自己这周的余量有限。';scene=window.MEETING_STORY_EDITORIAL?.npc(w,id,scene)||scene;choices=[choice('说清能帮的范围，用这半天陪对方处理一段。','help',{energy:-9,stress:3},{collaboration:1}),choice('承认自己接不住，提出一个明确的交接办法。','handoff',{energy:-3,stress:1}),choice('先答应全部，具体怎样挤出时间以后再想。','promise',{energy:2,stress:-2},{promise:1})];}
    else if(type==='project'){title='课题还在同一个故事里';scene='当前版本：'+p.version+'。正在研究「'+(window.MEETING_DIRECTIONS?.topic(p)||P.topic(p.route,'boundary'))+'」。状态：'+statuses[p.status]+'。这半天决定怎样推进本版课题。';choices=[choice('打开本版来源，实查一个条件并留下版本记录。','verify',{energy:-11,notes:7,stress:3},{study:1}),choice('缩小到一个能解释的小问题，整理已有依据的边界。','narrow',{energy:-6,slides:4,stress:-2}),choice(window.MEETING_DIRECTIONS?'沿相邻联系转向「'+window.MEETING_DIRECTIONS.target(w).name+'」，建立新的草稿。':'保留旧稿，转向一个新问题，从新的草稿开始。','pivot',{energy:-5,stress:4},{pivot:1},{directionTarget:window.MEETING_DIRECTIONS?.target(w)?.id})];}
    else if(type==='season'){const d=seasons.find(x=>x.id===id);title=d.title;scene=d.scene;choices=[choice('认真处理这个现实障碍，留一份能交接的记录。','fix',{energy:-8,stress:3}),choice('顺着现场整一段活，接受事情可能传播出去。','joke',{energy:-3,stress:-4},{chaos:1}),choice('划清自己的安排，请大家共同分担处理。','share',{energy:-3,stress:2},{collaboration:1})];}
    else if(type==='channel'){const d=channels.find(x=>x.id===id);title=d.title;scene=d.scene+' 这次邀请来自你此前的选择。';choices=[choice('用这半天查清一处具体材料，讲清能确认的部分。','check',{energy:-9,notes:5,stress:2},{study:1}),choice('聊聊各自的经验，明确说交流还不算核对。','talk',{energy:-3,stress:-4},{collaboration:1}),choice('把安排停在这里，给自己留出休息。','stop',{energy:9,stress:-6},{rest:1})];}
    else if(type==='echo'){const q=a.queue.find(x=>x.id===id),d=repercussions[q.kind];title=d[0];scene=d[1]+' 来源：第'+q.week+'周的组会与回答记录。';choices=[choice('打开当时的记录，把原话、条件和后续范围核对清楚。','clarify',{energy:-8,notes:3,stress:2}),choice('先与对方交流，再决定接下来的投入。','talk',{energy:-4,stress:-2}),choice('先接住所有期待，不急着解释原来的限制。','overclaim',{energy:1,stress:2},{promise:1})];}
    else if(type==='settle'){const q=a.queue.find(x=>x.id===id);title='前几天的安排，有了回信';scene=q.text;choices=[choice('对照真实情况，改掉已经不成立的安排。','repair',{energy:-7,stress:4}),choice('联系当事人一起找补，接受需要更多时间。','help',{energy:-5,stress:2},{collaboration:1}),choice('继续沿用原来的说法，等下一次再解释。','delay',{energy:2,stress:-1},{promise:1})];}
    for(let i=choices.length-1;i>0;i--){const j=Math.floor(rand(w)*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}
    return {id:'world-'+type+'-'+id,day:w.day,slot:w.slot,project:window.MEETING_MIX?.route(w)||w.config.project,worldType:type,worldId:id,title,scene,choices};
  }
  function prepare(w,rand){const a=w.world;if(!a)return;expire(w);a.plan=null;if(w.day===4)return;const due=a.queue.find(q=>!q.done&&q.due<=tick(w));if(due){a.plan=event(w,due.type,due.id,rand);return;}if(w.day===0&&w.slot===0)return;
    const rate={normal:.33,lucky:.4,cascade:.62,social:.6,poor:.43,absurd:.72,blind:.48}[a.mode];if(rand(w)>rate)return;
    const weights=[['message',3],['opportunity',a.mode==='lucky'?6:2],['npc',a.mode==='social'?8:2],['project',3],['season',a.mode==='absurd'?12:1],['channel',Math.min(6,Object.values(a.paths).reduce((x,y)=>x+y,0)/3)]];let total=weights.reduce((x,[,y])=>x+y,0),r=rand(w)*total,type='project';for(const [k,weight] of weights){r-=weight;if(r<0){type=k;break;}}
    let id=type==='message'?pick(w,messages,rand).id:type==='opportunity'?pick(w,opportunities,rand).id:type==='season'?pick(w,seasons.filter(d=>!a.seasons.some(s=>s.id===d.id&&s.week===w.number)).length?seasons.filter(d=>!a.seasons.some(s=>s.id===d.id&&s.week===w.number)):seasons,rand).id:type==='npc'&&w.group?.members.length?pick(w,w.group.members,rand).id:type==='channel'?pick(w,channels.filter(d=>a.paths[d.id]===Math.max(...Object.values(a.paths))),rand).id:'artifact';
    if(type==='npc'&&!w.group)type='project';a.plan=event(w,type,id,rand);
  }
  function current(w,raw){if(!w.world)return raw;if(w.world.focus){const o=w.world.opportunities.find(x=>x.id===w.world.focus);if(!o||!['offered','reserved'].includes(o.status))return raw;const d=opportunities.find(x=>x.id===o.kind);return {id:'world-opportunity-work-'+o.id,day:w.day,slot:w.slot,project:o.route,worldType:'opportunity-work',worldId:o.id,title:'实际参加 · '+d.title,scene:'这个片段用于已经预留的机会，原定准备不会同时完成。',choices:[choice('把这半天真正投入进去，核对具体内容与来源。','attend',{energy:-10,stress:3}),choice('与当事人说明缩短安排，只交换入口与线索。','partial',{energy:-4,stress:-1}),choice('取消预留，把机会让给别人。','pass',{energy:5,stress:-2})]};}
    if(w.campus?.plan?.location==='world-project')return copy(w.world.plan);
    if(!w.world.plan||w.campus?.plan||raw?.choices?.some(c=>c.assignmentAction||c.groupAction||c.storyAction!==undefined)||raw?.joint)return raw;return copy(w.world.plan);
  }
  function dispatch(w,id){const o=w.world?.opportunities.find(x=>x.id===id);if(w.status!=='life'||w.pending||w.campus?.plan||window.MEETING_ASSIGNMENTS?.offer(w)||!o||!['offered','reserved'].includes(o.status)||tick(w)>o.deadline)return false;w.world.focus=id;w.campus.plan={day:w.day,slot:w.slot,location:'world',original:w.eventId};return true;}
  function projectDispatch(w){if(!w.world||w.status!=='life'||w.pending||w.campus?.plan||window.MEETING_ASSIGNMENTS?.offer(w))return false;w.world.plan=event(w,'project','artifact',s=>{s.rng=derive(s.rng,1);return s.rng/4294967296;});w.campus.plan={day:w.day,slot:w.slot,location:'world-project',original:w.eventId};return true;}
  function queue(w,type,kind,text,delay=2){const a=w.world;a.queue.push({id:'q-'+w.number+'-'+tick(w)+'-'+a.queue.length,type,kind,text,due:tick(w)+delay,week:w.number,done:false});a.queue=a.queue.slice(-24);}
  function resolve(w,e,c,effects,rand){const a=w.world;if(!a)return null;const add=o=>{for(const [k,v] of Object.entries(o))effects[k]=(effects[k]||0)+v;};
    if(a.mode==='cascade'&&rand(w)<.38)add({energy:-4,stress:5});if(a.mode==='lucky'&&rand(w)<.3)add({energy:4,stress:-3});let text='',status='';const type=e.worldType,id=e.worldId,action=c.worldAction;
    if(type==='message'){const m=a.messages.find(x=>x.id===id);if(action==='check'){const reply=rand(w)<(a.mode==='lucky'?.92:.78);m.status=reply?(m.truth?'confirmed':'refuted'):'unresolved';a.paths.careful++;text=reply?(m.truth?'正式来源证实了这条消息，你留下了回复。':'正式来源否定了这条消息，原来的截图缺了条件。'):'来源暂未答复。你有联系记录，但还没有确认消息真假。';}else if(action==='believe'){m.status='believed';a.paths.show++;queue(w,'settle',m.truth?'message-true':'message-false',m.truth?'先前的消息确实成立，但没有核实的习惯仍可能在别的消息上出问题。':'先前的消息被正式通知否定了，你已经按错误信息排了时间。',2+Math.floor(rand(w)*3));text='你先按消息改变了安排。是否可靠，要等正式信息或后续回信。';}else {m.status='held';a.paths.boundary++;text='你留下了未确认的标记，维持原来的安排。机会可能擦肩而过，至少没有把转发当作确认。';}status=m.status;}
    else if(type==='opportunity'||type==='opportunity-work'){const o=a.opportunities.find(x=>x.id===id),d=opportunities.find(x=>x.id===o.kind);if(o.status==='unseen')o.deadline=tick(w)+2;if(action==='reserve'){o.status='reserved';text='机会已预留。还需要在窗口结束前点击参加，并真正用掉一个片段。';}else if(action==='pass'){o.status='passed';a.paths.boundary++;text='你让出了机会。没有获得这次活动的材料或休息回执。';}else if(action==='partial'){o.status='partial';a.paths.social++;text='你只交换了入口，没有把活动完成。';}else{const success=rand(w)<(a.mode==='lucky'?.88:.65);o.status=success?'completed':'interrupted';if(d.kind==='rest'){add({energy:success?24:9,stress:success?-17:-4});a.paths.rest++;text=success?'你和朋友一起看了展，把这段时间留给生活。':'活动临时改变，你们还是一起走了一段路。';}else{c.preparationGains=success?{[d.kind]:2}:{[d.kind]:1};c.preparationRoute=o.route;a.paths.careful++;text=success?'你实际参加并核对了具体内容，留下这次来源记录。':'现场临时缩短，只有入口和线索，完整核对没有完成。';}o.receipt={week:w.number,day:w.day,eventId:e.id,action:c.text,complete:success};}status=o.status;}
    else if(type==='npc'){const m=w.group.members.find(x=>x.id===id),n=a.npcs[id],yes=rand(w)<.65+(n.mood*.04);if(action==='help'){window.MEETING_GROUP.trust(w,id,yes?4:1);a.paths.social++;text=yes?'你帮到了对方的一段具体工作，对方记住了这次范围。':'对方自己的安排又变了，你投入了时间，却没能把这件事顺利接上。';}else if(action==='handoff'){window.MEETING_GROUP.trust(w,id,n.mood<0?-2:1);a.paths.boundary++;text=n.mood<0?'对方正忙得焦躁，暂时没接住这个边界。之后仍可以解释。':'对方接受了交接办法，记住你没有含糊答应。';}else {window.MEETING_GROUP.trust(w,id,2);queue(w,'settle','npc-promise',m.name+'记得你答应过帮忙，现在来问实际交付在哪里。',3);text='口头承诺留下了。任务尚未完成，后面还会来问。';}n.memory.push({week:w.number,action,goal:n.goal});n.memory=n.memory.slice(-8);}
    else if(type==='project'){const p=a.artifact;if(action==='verify'){const kind=p.status==='flaw'?'boundary':p.checks.length===0&&window.MEETING_DIRECTIONS?window.MEETING_DIRECTIONS.active(w).kind:P.kinds[p.checks.length%4],success=rand(w)<(a.mode==='poor'&&w.group?.balance<20?.46:.78);c.preparationRoute=p.route;c.preparationGains={[kind]:success?2:1};if(success){if(p.checks.length>=100)p.checks.shift();p.checks.push({version:p.version,route:p.route,kind,week:w.number,eventId:e.id,action:c.text,level:2});p.status=p.checks.length>=3?'ready':'checked';text='本版实际核对了一段条件，记录带着版本号，能用于对应课题回答。';}else{p.status='flaw';add({stress:6});text='核对发现一个不成立的条件。本版留下了漏洞，完整核对记录没有增加。';}}else if(action==='narrow'){p.scope=Math.max(1,p.scope-1);p.status=p.checks.length?'narrowed':'draft';a.paths.boundary++;text=p.checks.length?'你把问题范围缩小，保留了本版已经核对的依据。':'范围缩小了，但还没有本版核对记录，暂时仍是草稿。';}else if(window.MEETING_DIRECTIONS?.pivot(w,c.directionTarget)){const d=window.MEETING_DIRECTIONS.active(w);c.preparationRoute=d.route;c.preparationGains={boundary:1};text='课题沿已有联系转向「'+d.name+'」。旧资料只留下参考线索，新版本还需要实际核对。';}else{p.version++;p.checks=[];p.status='pivot';p.scope=2;const routes=window.MEETING_MIX?.routes(w)||[w.config.project];p.route=pick(w,routes,rand);text='旧稿进入历史，新版本从草稿开始。过去的阅读仍是知识，但不能替新版本的核对背书。';}p.history.push({week:w.number,version:p.version,status:p.status,action:c.text});p.history=p.history.slice(-24);status=p.status;}
    else if(type==='season'){a.seasons.push({id,week:w.number,action});a.seasons=a.seasons.slice(-24);if(action==='fix'){a.paths.careful++;text=id==='files'||id==='robot'?'你核对了版本和原话，留下能追回去的记录，花掉的时间不会回来。':'障碍被处理了一段，大家得以继续安排，原定准备仍需另找时间。';}else if(action==='joke'){a.paths.show+=2;const spread=rand(w)<.6;add(spread?{stress:5}:{stress:-3});text=spread?'名场面传到别的群，有人只记得热闹，后续可能还会让你解释。':'大家笑了一阵，这次没有传远，但半天已经过去。';if(spread)queue(w,'echo','rumor','',2);}else{a.paths.boundary++;text='工作分给了几个人，协调并不免费，但你没有一人接下全部。';}}
    else if(type==='channel'){if(action==='check'){a.paths.careful++;text='你留下了这一处的来路，但没有把别人的说法全盘接住。';}else if(action==='talk'){a.paths.social++;text='交流扩大了下一次邀请的可能，也留下更多需要区分的说法。';}else{a.paths.rest++;text='这次你给生活留出了位置。未来更容易收到不以工作为目的的邀请。';}}
    else if(type==='echo'||type==='settle'){const q=a.queue.find(x=>x.id===id);q.done=true;status='resolved';if(type==='settle'){if(q.kind==='message-false'||q.kind==='npc-promise'){add({energy:action==='delay'?-2:-5,stress:action==='delay'?12:6});if(action==='delay'){queue(w,'echo','repair','',3);a.paths.show++;}text=action==='delay'?'你把解释继续往后放，误差与期待没有消失。':'你开始修正过去的安排，付出了当时省下的时间。';}else {add({stress:-3});text='回信接上了之前的消息，这次安排没有落空。';}}else{if(action==='clarify'){a.paths.careful++;a.paths.boundary++;if(q.kind==='support'){c.preparationGains={literature:1};text='你收到适合继续核对的来源，严厉追问变成了一个小的入口。';}else if(q.kind==='pivot'){a.artifact.status='flaw';text='漏洞被写进本版课题，下一步需要实际核对或缩小范围。';}else text='原话与条件被摆回一起，一部分误解得以澄清，期待也有了范围。';}else if(action==='talk'){a.paths.social++;text='你们谈清了各自的期待，但具体材料还要另找时间处理。';}else{a.paths.show++;queue(w,'settle','npc-promise','散会后增加的期待又来询问交付。',3);text='你接下了更多期待，承诺暂时没有变成实际工作。';}}}
    if(!type)return null;a.weekEvents++;a.history.push({week:w.number,day:w.day,type,id,action,text});a.history=a.history.slice(-80);return {type,id,action,status,text};
  }
  function afterLife(w,e,c,record){const a=w.world;if(!a)return;for(const [k,v] of Object.entries(record.traits||{})){if(k==='study')a.paths.careful+=v;if(k==='rest')a.paths.rest+=v;if(k==='chaos')a.paths.show+=v;if(k==='collaboration')a.paths.social+=v;}a.report.push({week:w.number,day:w.day,slot:w.slot,eventId:e.id,answer:record.answer,type:e.worldType||'life',action:c.worldAction??null,deltas:copy(record.deltas)});a.report=a.report.slice(-52);
    if(record.assignment){const task=w.assignments?.items?.find(t=>t.id===record.assignment.id),n=a.npcs[task?.giverId];if(n){n.memory.push({week:w.number,action:['delivered','partial','withdrawn'].includes(record.assignment.status)?record.assignment.status:record.assignment.action,task:task.title});n.memory=n.memory.slice(-8);}}
  }
  function context(w,ctx){if(!w.world)return ctx;ctx.world=copy(w.world);const a=w.world;if(a.mode==='cascade')ctx.deltas.mood-=4;if(a.mode==='poor'&&w.group.balance<20)ctx.deltas.evidence-=3;return ctx;}
  function meetingInit(s){const a=s.weekContext?.world;if(!a||!s.live)return;s.worldAsked=false;for(const id of ['boss','stats','senior']){const m=window.MEETING_GROUP.person(s,id),n=a.npcs[m?.id],g=goals.find(g=>g.id===n?.goal),p=s.live.profiles[id];if(n&&p){const style=C.personas.find(x=>x.id===m.mentorStyle);if(style?.focus)p.preference=style.focus;if(n.mood<0)p.preference=g.focus;const memory=n.memory.at(-1);p.temper+=n.mood+(memory?.action==='help'||memory?.action==='delivered'?1:0);p.severity=Math.max(1,Math.min(5,p.severity+(n.mood<0?1:0)+(a.mode==='social'?1:0)+(memory?.action==='promise'?1:0)));}}}
  function scheduled(s){return s.weekContext?.world&&s.live&&!s.wrapUp&&!s.worldAsked&&s.choicesMade>=7?{id:'world-research-question',phase:6}:null;}
  function question(s){if(s.eventId!=='world-research-question')return null;const a=s.weekContext.world,p=a.artifact,source=p.checks.findLast(x=>x.version===p.version),full=!!source;return {id:s.eventId,phase:6,who:'boss',project:p.route,title:'“这几周还是同一个课题，具体改到了哪一步？”',scene:'课题版本 '+p.version+' · '+(window.MEETING_DIRECTIONS?.topic(p)||'')+' · '+statuses[p.status]+'。只接受当前版本实际留下的记录；旧版本的阅读不能替新版本完成核对。',quote:'“把草稿、发现的漏洞和现在能讲的范围放在一起。”',choices:[{text:'拿出当前版本的实查记录，说明它支持的那一小段。',approach:'detail',effects:{evidence:4,patience:2,time:-3},flags:{rigor:1},prepared:{kind:source?.kind||'record',route:p.route,minimum:2,level:full?2:0,available:full,source:copy(source||null),reason:'当前课题版本还没有实查记录，需要用生活片段推进课题。'},worldAnswer:'receipt',result:'本版课题的来路被摆在台面上。',flavor:'你没有把旧版本的核对直接搬成新结论。'}, {text:'按时间线说明改过的范围，承认本版还没查完的地方。',approach:'cautious',effects:{evidence:-2,patience:1,time:-2},flags:{honest:1},worldAnswer:'boundary',result:'现在能回答的范围被说明了。',flavor:'下一步仍需要真实核对，讲清计划不会自动生成回执。'}, {text:'把几周的所有进度一起讲成成熟结论。',approach:'direct',effects:{mood:3,patience:-3,time:-2},flags:{chaos:1},worldAnswer:'claim',risk:{chance:p.status==='ready'?.25:.78,effects:{evidence:-12,patience:-8},flavor:'老师追到当前版本的条件，旧稿的熟悉不能替代本版核对。'},result:'你把故事讲得超过了本版记录。',flavor:'课题被讲得很大，具体条件仍会继续追问。'}]};}
  function afterAnswer(s,e,c,record){if(e.id==='world-research-question'){s.worldAsked=true;record.worldAnswer=c.worldAnswer;if(c.worldAnswer==='claim')s.weekContext.world.artifact.claimed++;}}
  function afterMeeting(w,s){const a=w.world;if(!a)return;if(s.weekContext?.world)a.artifact.claimed=s.weekContext.world.artifact.claimed;const log=s.log.filter(r=>r.type==='choice'),bad=log.filter(r=>r.unlucky).length,score=window.MEETING_ENGINE.score(s);const kind=s.flags.chaos>=3?'rumor':s.flags.debt>=3?'repair':bad>=3?'support':score>=65?'praise':'pivot';queue(w,'echo',kind,'',1);if(s.live?.flaw||bad>=4){a.artifact.status='flaw';a.artifact.history.push({week:w.number,version:a.artifact.version,status:'flaw',action:'组会指出了本版仍需补查的条件。'});}a.runCareer.relations=copy(s.relations);a.runCareer.meetings++;a.runCareer.experience+=10+s.choicesMade;a.runCareer.debt=s.flags.debt;
    a.lastMeeting={week:w.number,ending:s.ending,score,rounds:s.choicesMade,answers:log.map(r=>({eventId:r.eventId,answer:r.answer,unlucky:r.unlucky}))};a.queue=a.queue.slice(-24);
  }
  function ending(s){if(s.wrapUp!==2||!s.weekContext?.world)return null;const a=s.weekContext.world,p=a.artifact;if(p.claimed>0&&!p.checks.length&&s.flags.chaos>=2)return 'world-old-draft';if(a.messages.some(m=>m.status==='believed'&&!m.truth)&&s.flags.chaos>=3)return 'world-message';if(a.opportunities.filter(o=>o.status==='expired').length>=2)return 'world-window';if(a.paths.show>=6&&s.flags.chaos>=3)return 'world-famous';const season=a.seasons.findLast(x=>x.week===s.weekContext.number&&x.action==='joke');if(season)return 'world-season-'+season.id;if(p.status==='ready'&&s.flags.rigor>=2)return 'world-artifact';if(p.scope===1&&p.checks.length&&s.flags.honest>=2)return 'world-small';if(a.paths.boundary>=5&&s.flags.honest>=3)return 'world-boundary';if(a.paths.rest>=6&&s.stats.mood>=30)return 'world-weekend';return null;}
  const ends=[['world-old-draft','failure','📄','旧稿替新稿背了锅','你把旧版本的熟悉当作本版已经核对，追问却落在新条件上。'],['world-message','failure','📱','转发消息成为了时间表','你反复把未经确认的消息带进安排，正式回信终于追上了你的汇报。'],['world-window','open','⌛','预留席位收藏家','你预留过很多机会，却没有在窗口里投入时间。有些故事留给了别人。'],['world-famous','funny','📣','校园传说本人待核实','大家都听过你的故事，但传播里的你比实际记录更能干。'],['world-artifact','open','📚','课题终于长出了一页','几周的实际核对留下了同一版本的记录，有限结论终于能独立站住。'],['world-small','open','🔍','把大题做成一个小问题','你缩小了范围，拿出了能解释的材料。故事还可以继续。'],['world-boundary','open','🧭','不接全部，也能继续合作','你留下具体边界，有些人暂时不理解，愿意合作的人仍会再来。'],['world-weekend','open','🌿','课题之外也过了一周','你没有把所有机会变成进度，生活有了自己的回执。'],...seasons.map(d=>['world-season-'+d.id,'funny',{cat:'🐈',canteen:'🍜',files:'🗂️',drill:'🚨',beauty:'📸',meal:'🍱',festival:'🔌',robot:'🤖'}[d.id],{cat:'校猫获得了会议召集权',canteen:'在叫号声中完成了理论突破',files:'最终版终于有了第八个版本',drill:'唯一准时散会的是消防演练',beauty:'桌面比论文先通过评审',meal:'再补一个套餐成为了代表作',festival:'课题暂时断电，校园照常热闹',robot:'纪要已经毕业，你还在解释'}[d.id],'这周的奇怪插曲成了名场面。热闹占用了时间，也留下了需要继续说明的故事。'])];
  for(const [id,kind,icon,title,desc] of ends)C.endings.push({id,kind,icon,title,subtitle:'前几周的决定，这一周还在。',desc,hint:id.startsWith('world-season-')?'在对应荒诞事件中整活并抵达收尾。':'让课题、消息、机会或生活路线留下对应记录，并抵达收尾。'});
  function valid(w){const a=w.world;return !a||(a.version===1&&modes.some(m=>m.id===a.mode)&&Number.isInteger(a.root)&&a.root>=0&&a.root<=4294967295&&a.artifact&&C.projects.some(p=>p.id===a.artifact.route)&&Number.isInteger(a.artifact.version)&&a.artifact.version>=1&&[1,2,3].includes(a.artifact.scope)&&Object.hasOwn(statuses,a.artifact.status)&&Array.isArray(a.artifact.checks)&&a.artifact.checks.length<=100&&a.artifact.checks.every(x=>x.version===a.artifact.version&&P.kinds.includes(x.kind)&&x.level===2)&&['messages','opportunities','queue','history','report','seasons'].every(k=>Array.isArray(a[k]))&&a.queue.length<=24&&a.history.length<=80&&a.report.length<=52&&(window.MEETING_DIRECTIONS?.valid(w)??true)&&Object.values(a.paths).every(x=>Number.isInteger(x)&&x>=0));}
  function code(w){const c=w.config,a=w.world;return [!c.rulesVersion||c.rulesVersion==='08'?'LM08':c.rulesVersion==='10'?'LM10':'LM09',a.root,a.mode,c.project,(c.mixProjects||[]).join('+')||'-',c.role||'newbie',c.difficulty||'normal',c.persona||'random',...(!c.rulesVersion||c.rulesVersion==='08'?(c.direction?[c.direction]:[]):[c.direction||'-',c.mentorId||'-',...(c.rulesVersion==='10'?[c.studyStage||'master',c.scenario||'regular']:[])])].join(':');}
  function parse(text){const p=String(text).trim().split(':');const legacy=p[0]==='LM08';if(!(legacy?[8,9].includes(p.length):(p[0]==='LM09'&&p.length===10||p[0]==='LM10'&&p.length===12))||!/^\d{1,10}$/.test(p[1])||Number(p[1])>4294967295||!modes.some(m=>m.id===p[2])||!C.projects.some(d=>d.id===p[3])||!C.roles.some(d=>d.id===p[5])||!['normal','friday','surprise'].includes(p[6])||!(p[7]==='random'||C.personas.some(d=>d.id===p[7])))return null;if(p.length>=9&&p[8]!=='-'&&(!window.MEETING_DIRECTIONS?.find(p[8])))return null;const mix=p[4]==='-'?null:window.MEETING_MIX.sanitize(p[4].split('+'));if(p[4]!=='-'&&(!mix||p[3]!=='interdisciplinary'))return null;if(p.length>=9&&p[8]!=='-'&&!window.MEETING_DIRECTIONS.list({project:p[3],mixProjects:mix}).some(d=>d.id===p[8]))return null;if(p[0]==='LM10'&&(!window.MEETING_ACADEMY?.stages.some(d=>d.id===p[10])||!window.MEETING_ACADEMY?.scenarios.some(d=>d.id===p[11])))return null;const mentor=!legacy&&p[9]!=='-'?window.MEETING_MENTORS?.find(p[9]):null;if(!legacy&&p[9]!=='-'&&(!mentor||mentor.style!==p[7]))return null;return {...(p.length>=9&&p[8]!=='-'?{direction:p[8]}:{}),...(p[0]==='LM10'?{studyStage:p[10],scenario:p[11]}:{}),rulesVersion:legacy?'08':p[0]==='LM10'?'10':'09',mentorId:mentor?.id||null,challenge:true,challengeSeed:Number(p[1]),playMode:p[2],project:p[3],...(mix?{mixProjects:mix}:{}),role:p[5],difficulty:p[6],persona:p[7],relations:{boss:50,stats:50,senior:50}};}
  function report(w){return {format:w.config.rulesVersion==='10'?'LM10-route':'LM09-route',code:code(w),week:w.number,name:w.config.name,challenge:aChallenge(w),mode:w.world.mode,project:w.config.project,mixProjects:w.config.mixProjects||null,meeting:copy(w.world.lastMeeting?.week===w.number?w.world.lastMeeting:null),choices:copy(w.world.report),mentorId:w.config.mentorId||null,routeStories:copy(w.routeStories?.history||[]),publication:(w.publication?.history||[]).map(t=>({id:t.id,title:t.title,route:t.route,journal:t.journal,status:t.status,version:t.projectVersion,round:t.round,finished:t.finished})),artifact:{version:w.world.artifact.version,status:w.world.artifact.status,checks:w.world.artifact.checks.length,direction:w.world.artifact.direction||null,route:w.world.artifact.route,references:w.world.artifact.references?.length||0},academic:w.academy?{stage:w.academy.term.stage,scenario:w.academy.scenario,milestones:copy(w.academy.term.milestones),yearbook:copy(w.academy.yearbook)}:null,paths:copy(w.world.paths)};}
  const aChallenge=w=>!!w.world?.challenge;
  function compare(left,right){if(!right||!['LM08-route','LM09-route','LM10-route'].includes(right.format)||!left.challenge||!right.challenge||right.code!==left.code||right.week!==left.week||!Array.isArray(right.choices)||right.choices.length>52||right.choices.some(x=>typeof x.eventId!=='string'||x.eventId.length>200||typeof x.answer!=='string'||x.answer.length>2000))return null;const n=Math.max(left.choices.length,right.choices.length),differences=[];for(let i=0;i<n;i++){const l=left.choices[i],r=right.choices[i];if(!l||!r||l.eventId!==r.eventId||l.answer!==r.answer)differences.push({index:i,left:l||null,right:r||null});}return {same:n-differences.length,total:n,differences,first:differences[0]||null,leftScore:left.meeting?.score??null,rightScore:Number.isFinite(right.meeting?.score)?right.meeting.score:null};}
  return {modes,goals,messages,opportunities,seasons,channels,repercussions,statuses,tick,derive,config,init,prepare,current,dispatch,projectDispatch,resolve,afterLife,context,meetingInit,scheduled,question,afterAnswer,afterMeeting,ending,valid,code,parse,report,compare,expire,event};
})();
