/* A wholly fictional academic setting. Names are invented, not aliases for real entities.
   Career dates and publication bands are narrative metadata, never gameplay evidence. */
window.MEETING_NARRATIVE_WORLD=(()=>{
 'use strict';
 const lex=new Map(),live=new Map(),fragments=new Map();let compiled=false;
 const pair=(zh,en)=>{lex.set(zh,en);if(compiled)live.set(zh,en);return zh;},hash=s=>{let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;},pick=(a,n)=>a[n%a.length];
 const cities=[['澄汀','Clearhaven','河口旧城与新建大学城隔着一条通勤线','a river-mouth old town linked to a new university district'],['岚浦','Mistport','港区厂房逐渐改成工作室，海风常让室外活动改期','a former dock district with converted studios and unreliable coastal weather'],['栖原','Nestplain','山麓校园离市中心很远，周末末班车决定聚会什么时候结束','a foothill campus where the last bus decides when weekend gatherings end'],['雾岬','Fogcape','两个校区分在海湾两侧，设备和档案不能靠一张通行证通用','two campuses across a bay, with separate equipment and archive access'],['槐川','Ashbrook','老校区的街巷很热闹，新校区的共享平台却要提前预约','a lively old campus and a new campus whose shared facilities require bookings'],['砾庭','Flintcourt','工业园与大学相邻，合作方的季度验收常撞上考试周','an industrial district where quarterly partner reviews collide with exam weeks'],['霜汀','Frosthaven','冬季日照短，跨境合作要同时照顾时差与假期','short winter days and international work shaped by time zones and holidays'],['遥屿','Far Isle','岛上研究站规模很小，一次运输延误会改掉整周计划','a small island research station where delayed deliveries reshape the week'],['西芜','Westmere','旧城档案馆分散，访问学者常带着地图和多张预约单','scattered old-town archives that visiting researchers navigate with maps and bookings'],['星栈','Starwharf','研究园区开放工位多，但短期合同和搬家也很频繁','an open-workspace research district with frequent short contracts and moves']].map(([name,en,desc,eng],i)=>({id:'city-'+i,name:pair(name,en),desc:pair(desc,eng),overseas:i>=6}));
 const schools=[['澄汀知衡大学','Clearhaven University of Inquiry',0,'综合大学'],['岚浦潮序理工学院','Mistport Institute of Tidal Systems',1,'理工学院'],['栖原见微大学','Nestplain University of Close Inquiry',2,'综合大学'],['雾岬循证医学院','Fogcape College of Health Inquiry',3,'医学院'],['槐川文境大学','Ashbrook University of Cultural Contexts',4,'人文社会研究型大学'],['砾庭构源大学','Flintcourt University of Making',5,'综合大学'],['霜汀折光大学','Frosthaven University of Refractions',6,'海外研究型大学'],['遥屿远岸研究院','Far Isle Institute of Distant Shores',7,'海外研究院'],['西芜镜河大学','Westmere Mirror-River University',8,'海外综合大学'],['星栈序桥理工大学','Starwharf Orderbridge Institute',9,'海外理工大学']].map(([name,en,city,type],i)=>({id:'school-'+i,name:pair(name,en),city:cities[city],type,overseas:i>=6}));
 const modes={
 compute:['计算与开放系统','Computing and Open Systems','可复算系统研究室','Recomputable Systems Lab','算力配额、环境镜像和输入清单','compute quotas, environment images and input inventories','《栈桥计算札记》','Stackbridge Computing Notes','《可复算研究》','Recomputable Inquiry','《序桥系统前沿》','Orderbridge Systems Frontiers'],
 proof:['形式推理与基础问题','Formal Reasoning and Foundations','条件与反例研究室','Conditions and Counterexamples Group','定义谱系、命题草稿和反例讨论','definitions, draft propositions and counterexample seminars','《界限推理通讯》','Bounded Reasoning Letters','《命题与结构》','Propositions and Structures','《折光基础论丛》','Refraction Foundations Review'],
 bench:['测量与材料研究','Measurement and Materials','测量与材料过程研究室','Measurement and Materials Processes Lab','共享平台预约、批次说明和原始记录','shared-platform bookings, batch context and original records','《微庭材料札记》','Microcourt Materials Notes','《测量与过程研究》','Measurement and Process Inquiry','《构源物质前沿》','Making Matter Frontiers'],
 clinical:['健康与服务研究','Health and Care Research','健康过程与情境研究室','Health Processes and Contexts Lab','合作场景、授权材料和观察时点','partner settings, authorized materials and observation windows','《照护情境简报》','Care Context Briefs','《循境健康研究》','Contextual Health Inquiry','《生命历程与健康前沿》','Life-Course and Health Frontiers'],
 field:['田野与社会经验','Fieldwork and Social Experience','社会经验与现场研究室','Social Experience and Field Settings Group','联系窗口、记录许可和现场语境','contact windows, permission to record and field context','《现场经验札记》','Situated Experience Notes','《社会情境研究》','Social Context Inquiry','《群体与经验论丛》','Groups and Experience Review'],
 archive:['文本与历史解释','Texts and Historical Interpretation','文本与版本研究室','Texts and Versions Group','原件预约、版本索引和引用许可','original-document bookings, version indexes and quotation permissions','《镜河文献札记》','Mirror-River Documentary Notes','《版本与解释》','Versions and Interpretations','《文境思想论丛》','Cultural Contexts Review'],
 survey:['组织与公共问题','Organizations and Public Questions','组织与公共问题研究室','Organizations and Public Questions Group','合作约定、口径版本和贡献记录','partner agreements, reporting definitions and contribution records','《公共问题简报》','Public Questions Briefs','《组织与口径研究》','Organizations and Definitions Inquiry','《知衡公共研究》','Inquiry in Public Affairs'],
 environment:['环境与空间观察','Environmental and Spatial Observation','空间过程与观察研究室','Spatial Processes and Observation Lab','场地开放、季节窗口和缺测说明','site access, seasonal windows and missing-observation notes','《岸线观察札记》','Shoreline Observation Notes','《尺度与环境研究》','Scale and Environment Inquiry','《远岸地景前沿》','Distant Shores Landscape Frontiers'],
 engineer:['系统与工程验证','Systems and Engineering Validation','接口与工况研究室','Interfaces and Operating Conditions Lab','共享台架、接口版本和验收范围','shared test rigs, interface versions and acceptance scope','《构源工程简报》','Making Engineering Briefs','《工况与系统研究》','Operating Conditions and Systems Inquiry','《潮序工程前沿》','Tidal Systems Engineering Frontiers'],
 design:['设计与公共体验','Design and Public Experience','原型与公共体验工作室','Prototypes and Public Experience Studio','展示排期、原型版本和参与者反馈','exhibition slots, prototype versions and participant feedback','《栖原设计札记》','Nestplain Design Notes','《原型与情境》','Prototypes and Contexts','《文境设计论丛》','Cultural Design Review']
 };
 const journals={},meetings={};for(const [kind,row] of Object.entries(modes)){const [area,en,lab,labEn,resource,resourceEn,...titles]=row;modes[kind]={area:pair(area,en),lab:pair(lab,labEn),resources:pair(resource,resourceEn)};journals[kind]=['brief','methods','frontier'].map((id,i)=>({id,kind,name:pair(titles[i*2],titles[i*2+1]),band:i===0?'3—4区':i===1?'2区':'1区',tier:i===0?4:i===1?2:1,scope:pair(['重视范围明确的短篇工作，栏目容量有限，编辑可能因主题不合退回。','关注方法、过程与解释的可追溯性，评审通常要求回应替代解释。','关注问题的重要性与跨场景联系；新颖的标题不能替代实际支持。'][i],['Publishes tightly scoped short work; limited space and theme mismatch may cause rejection.','Examines traceable methods, processes and interpretation, usually including alternative explanations.','Examines the significance of a question and links across settings; an ambitious title cannot replace support.'][i])}));meetings[kind]={name:pair('雾湾'+area+'年会','Fogbay Annual Meeting on '+en),venue:schools[hash(kind)%6],format:pair('短报告、专题讨论与海报交流分开评议；摘要入选不等于全文成果被接收。','Short talks, focused discussions and posters are assessed separately; abstract selection is not paper acceptance.')};}
 for(const [z,e] of [['指导习惯如何形成','How supervision habits developed'],['研究之外的生活','Life beyond research'],['游戏内1区','Game band 1'],['游戏内2区','Game band 2'],['游戏内3—4区','Game bands 3–4'],['1区','Band 1'],['2区','Band 2'],['3—4区','Bands 3–4'],['地点：','Setting: '],['本轮问题围绕','The question concerns '],['与组内其他安排共用。',' are shared with the group’s other commitments.'],['的团队在这里参与合作，人物主页中的经历提供理解线索，但不保证这次求助成功。',' works with partners here; the biography offers clues rather than guaranteeing help.']])pair(z,e);
 const note=pair('本页学校、城市、实验室、会议与期刊均为独立虚构；“区”是游戏内难度分档，不对应真实JCR、中科院分区或学校评价。','Every institution, city, lab, meeting and journal on this page is invented. Publication bands are game difficulty labels, not JCR, CAS rankings or university assessments.');
 function resource(route){return window.MEETING_ROUTE_STORIES?.forRoute(route)?.id||[...(window.MEETING_MEDICAL?.routes||[]),...(window.MEETING_SPECIALTIES?.routes||[])].find(r=>r.id===route)?.resource||({data:'compute',statistics:'compute',theory:'proof',clinical:'clinical',classic:'bench',humanities:'archive',law:'archive',design:'design'})[route]||'survey';}
 function setting(route,mentorId){const n=hash(mentorId||route),kind=resource(route),family=window.MEETING_CONTENT.projects.find(p=>p.id===route)?.family,eligible=family==='medicine'?[schools[0],schools[2],schools[3],schools[5]]:kind==='archive'||kind==='field'||kind==='design'?[schools[0],schools[2],schools[4],schools[5]]:schools.slice(0,6),existing=window.MEETING_MENTORS?.find(mentorId)?.biography?.institution,school=schools.find(s=>s.name===existing)||pick(eligible,n),mode=modes[kind];return {kind,school,city:school.city,mode,meeting:meetings[kind],journals:journals[kind]};}
 function journal(id,route){return journals[resource(route)]?.find(j=>j.id===id)||journals.survey.find(j=>j.id===id);}
 function english(s){const value=lex.get(s);return value!==undefined?(typeof value==='function'?value():value):(window.MEETING_LOCALES?.en?.[s]||s);}
 function lookup(s){return lex.has(s)?english(s):null;}
 function dictionary(){const result=Object.fromEntries([...lex].map(([z,e])=>[z,typeof e==='function'?e():e]));compiled=true;return result;}
 function fragment(z,e){fragments.set(z,e);return pair(z,e);}
 function dynamic(text){for(const source of [fragments,live])for(const [z,e] of source)if(text.includes(z))text=text.split(z).join(typeof e==='function'?e():e);return text;}
 function longProse(text){return text.length>120&&lex.has(text);}
 return {version:1,year:2026,cities,schools,modes,journals,meetings,note,hash,pick,pair,fragment,setting,journal,resource,english,lookup,dictionary,dynamic,longProse};
})();
