/* Read existing receipts only. Dialogue and the notebook grant no game rewards. */
window.MEETING_PEOPLE_MEMORY=(()=>{
  'use strict';
  const N=window.MEETING_NARRATIVE_WORLD,pair=(zh,en)=>N?.pair(zh,en)||zh,en=s=>N?.english(s)||s;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  for(const [zh,english]of [['相处记录','Shared history'],['一起处理过的事留在这里，下次见面时，还能接着聊。','Shared work and encounters stay here, ready to pick up at your next meeting.'],['目前没有保留的具体相处记录。以后实际帮助、交接和合作会留下痕迹。','No specific encounters are retained yet. Actual help, handoffs and collaboration will leave records.'],['已离组','Has left the group'],['记录只包含当前存档保留的片段，不是完整人生履历。','Only encounters retained in this save appear here; this is not a complete biography.']])pair(zh,english);
  function timeline(w,id){
    const rows=[],a=w.academy,add=(key,r,label,text,reaction,englishReaction)=>{if(!Number.isInteger(r.week)||r.week<1||r.week>w.number)return;rows.push({key,order:rows.length,week:r.week,day:Number.isInteger(r.day)&&r.day>=0&&r.day<=6?r.day:-1,slot:r.slot===0||r.slot===1?r.slot:-1,label,text,reaction:pair(reaction,englishReaction)});};
    const arr=x=>Array.isArray(x)?x:[],n=a?.people?.[id];
    for(const [i,r]of arr(n?.relationships).entries()){if(!r||typeof r!=='object')continue;
      const table={train:['一起准备材料','You prepared material together','你们一起核对过一个小问题，留下了带教记录。','You checked a small question together and kept a training record.','对方翻出上次一起练过的记录，先问这次是不是同一份材料。','They reopen the earlier practice notes and ask whether this is the same material.'],
        'person-talk':['聊过近况','You caught up','那半天没聊进度，你们坐下来，说了说各自的近况。','You set progress aside for the slot, sat down and caught up.','对方记得上次你们聊了近况，这次先问你最近睡得怎么样。','They remember catching up and first ask how you have been sleeping.'],
        'person-help':['你曾向对方求助','You asked for help',r.success===true?'对方给过一条待核对的线索。':r.success===false?'那次没有拿到线索，半天用于说清问题和各自的安排。':'存档保留了求助这件事，未记录是否获得了线索。',r.success===true?'They offered a lead to check.':r.success===false?'No lead was obtained; the slot went into clarifying the question and both schedules.':'The request is retained, but its outcome was not recorded.',r.success===true?'对方先问，上次给你的那条线索后来有没有追到来源。':r.success===false?'上次没能接住你的求助，对方这次先翻了翻日历。':'对方记得你之前来问过问题，先确认这次的范围。',r.success===true?'They ask whether you traced the previous lead to its source.':r.success===false?'Unable to help last time, they check their calendar first.':'They remember the earlier request and first clarify its scope.']};
      const t=table[r.action];if(t)add('person-'+i,r,pair(t[0],t[1]),pair(t[2],t[3]),t[4],t[5]);
    }
    for(const [i,r]of arr(w.world?.npcs?.[id]?.memory).entries()){if(!r||typeof r!=='object')continue;
      let t;
      if(r.task){const labels={delivered:'完整交付',partial:'有限交付',withdrawn:'交回未完成部分',decline:'说明无法接下',accept:'接下交办',negotiate:'协商交办范围',extend:'申请延期',thorough:'实际核对了一份',overdue:'交办超过期限'};const label=labels[r.action]||'回应过交办';t=[label,'An assignment response','交办是「'+r.task+'」。'+(r.action==='delivered'?'约定范围有完整交付记录。':'接单、部分处理与完整交付分别记录。'),'The task was '+en(r.task)+'. Acceptance, partial work and complete delivery remain distinct.','对方提起上次那份「'+r.task+'」，先把这次要交什么、什么时候用说清楚。','They recall '+en(r.task)+' and clarify this task’s scope and deadline.'];}
      else if(r.action==='help')t=['腾出时间帮忙','You made time to help',r.success===false?'投入了时间，但那次安排没有顺利接上。':'你曾把半天留给对方的一段安排。',r.success===false?'Time was spent, but the arrangement did not come together.':'You made a slot available for part of their work.','对方记得你曾腾出半天，这次也先问你能接住多大范围。','They remember the slot you made available and ask how much you can take on now.'];
      else if(r.action==='handoff'&&r.success===false)t=['交接当时没谈妥','Handoff was not agreed','你提出了交接办法，对方当时没能接受，双方尚未谈妥。','You proposed a handoff, but it was not accepted at the time.','上次的交接没谈拢，对方这次先问哪一段还等着处理。','The earlier handoff was not agreed; they first ask what is still waiting.'];
      else if(r.action==='handoff'||r.action==='promise-revised')t=['交接与范围重新说清','Scope and handoff clarified','你说清了自己能帮到哪一步，并提出如何交接。','You explained how far you could help and proposed a handoff.','对方记得你上次把边界说清了，这次先把分工写下来。','Remembering the earlier boundary, they put the division of work in writing first.'];
      else if(r.action==='promise')t=['口头答应过帮忙','You made a verbal promise','当时先口头答应了，帮忙还没真正落到日程里。','You agreed verbally, before fitting the help into your schedule.','对方没有马上讲新的请求，先问起你上次答应的那一段。','Before making a new request, they ask about the earlier promise.'];
      else if(r.action==='promise-helped')t=['回应过先前承诺','You acted on the earlier promise','你处理了约定中的一段，剩下的事情重新排了时间。','You addressed part of the arrangement and rescheduled the rest.','对方把上次的交接记录放到一旁，问这次怎样安排才不会挤在一起。','They set aside the previous handoff record and ask how to avoid overlapping commitments this time.'];
      if(t)add('world-'+i,r,pair(t[0],t[1]),pair(t[2],t[3]),t[4],t[5]);
    }
    for(const l of arr(a?.loans))if(l?.personId===id){const returned=l.status==='returned',overdue=!returned&&Number.isInteger(l.penaltyAt),r={week:returned?l.returnedWeek||l.from:l.lastInteractionWeek||l.penaltyAt||l.from,day:returned?l.returnedDay:l.lastInteractionDay,slot:returned?l.returnedSlot:l.lastInteractionSlot};
      add('loan-'+l.id,r,pair(returned?'借用已经归还':overdue?'借用曾超过约定时间':'借用仍有交接约定',returned?'Borrowed access returned':overdue?'Borrowing passed its deadline':'Borrowed access awaits handoff'),pair('借用源自第'+l.from+'周。'+(returned?'归还已经记录。':'当前约定第'+l.dueWeek+'周交接。')+(l.penaltyAt?'此前有超期记录，归还不会抹掉它。':''),()=> 'Borrowing began in week '+l.from+'. '+(returned?'Return is recorded.':'Handoff is due in week '+l.dueWeek+'.')+(l.penaltyAt?' Earlier lateness remains on record.':'')),returned?'对方记得你把借来的东西还了，这次仍先确认自己的使用时间。':overdue?'对方提起上次没按时交接的事，这次先把归还日期说清楚。':'对方先提醒你还有借用要交接，自己的安排也等着用。',returned?'They remember the return, but first check their own schedule.':overdue?'Recalling the late handoff, they clarify the return date first.':'They remind you that the borrowed access still needs returning.');}
    for(const co of [...arr(a?.collab?.history),...(a?.collab?.active?[a.collab.active]:[])])if(co?.partnerId===id){const state=co.status,week=co.lastInteractionWeek||co.agreement?.week||co.from;
      add('collab-'+co.id,{week,day:co.lastInteractionDay,slot:co.lastInteractionSlot},pair(state==='agreed'?'共同范围与署名已确认':state==='disputed'?'署名分歧仍有记录':state==='ended'?'合作已经交接结束':'合作仍在推进',state==='agreed'?'Shared scope and authorship agreed':state==='disputed'?'Authorship dispute retained':state==='ended'?'Collaboration handed over and ended':'Collaboration in progress'),pair('课题版本 '+co.version+' · 已记录 '+arr(co.contributions).length+' 段贡献。',()=> 'Project version '+co.version+' · '+arr(co.contributions).length+' contributions recorded.'),state==='disputed'?'对方先把贡献清单放在桌上，问上次没谈清的署名这次怎么算。':state==='agreed'?'对方记得你们确认过共同署名，这次先问是否仍用原来的范围。':state==='ended'?'对方记得上轮已经交接结束，新合作得重新约定。':'对方提醒还有共同材料要交接，先核对双方各做到哪一步。',state==='disputed'?'They reopen the contribution list and the unresolved authorship question.':state==='agreed'?'They recall the agreed authorship and ask whether the scope is unchanged.':state==='ended'?'The previous collaboration ended; new work needs a fresh agreement.':'They check each person’s progress before the pending handoff.');}
    return rows.sort((a,b)=>b.week-a.week||b.day-a.day||b.slot-a.slot||b.order-a.order).slice(0,24);
  }
  function line(w,id){const r=timeline(w,id)[0];return r?pair('第'+r.week+'周的相处还留在记录里。'+r.reaction,()=> 'The encounter from week '+r.week+' is still on record. '+en(r.reaction)):'';}
  function show(w,id){const person=w.group?.members.find(m=>m.id===id)||w.academy?.people[id];if(!person)return false;let d=document.querySelector('#people-memory');if(d?.open){d.querySelector('.close').focus();return true;}if(!d){d=document.createElement('dialog');d.id='people-memory';d.className='faculty-dossier';document.body.append(d);}const trigger=document.activeElement,rows=timeline(w,id),title=pair('相处记录 · '+person.name,()=> 'Shared history · '+en(person.name));d.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button class="close" aria-label="关闭">×</button></div><p>${esc(person.role)}${person.status==='alumni'?' · 已离组':''}</p><p>一起处理过的事留在这里，下次见面时，还能接着聊。</p>${rows.map((r,i)=>`<details class="faculty-about" ${i===0?'open':''}><summary>第 ${r.week} 周 · ${esc(r.label)}</summary><p>${esc(r.text)}</p></details>`).join('')||'<p class="dossier-empty">目前没有保留的具体相处记录。以后实际帮助、交接和合作会留下痕迹。</p>'}<small>记录只包含当前存档保留的片段，不是完整人生履历。</small>`;d.querySelector('.close').onclick=()=>d.close();d.onclose=()=>{if(trigger?.isConnected)trigger.focus({preventScroll:true});};d.showModal();return true;}
  return {timeline,line,show};
})();
