/* English counterparts of the authored Chinese cases; other locales use English fallback. */
window.MEETING_PHARMACOLOGY_ENGLISH=(()=>{
 if(!window.MEETING_NARRATIVE_WORLD||!window.MEETING_PHARMACOLOGY)return null;
 const P=window.MEETING_NARRATIVE_WORLD.pair,R=window.MEETING_PHARMACOLOGY;
 const rows=`
pharmacy-10;Cardiovascular pharmacology;Cardiac contraction, vascular tone and drug action;Cardiac and vascular function records, receptor evidence and exposure information;Separate direct cardiac action, vascular action and loading changes;Lower blood pressure was described as improved myocardial function;Hemodynamic change alone establishes neither myocardial protection nor long-term benefit;Is the action in the heart, the vessels or an indirect loading effect?;Can cellular and organ-level evidence explain different functional responses at similar exposure?
pharmacy-11;Renal pharmacology;Renal transport, function and drug disposition;Renal-function timelines, transporter evidence and exposure records;Separate renal-function change, drug clearance and pharmacodynamic response;Higher exposure was interpreted as greater target sensitivity;Reduced clearance is not a changed target, and short-term indicators do not establish renal protection;Is a stronger response due to reduced clearance or a changed response system?;Can joint transport and renal-function information separate exposure differences from response differences?
pharmacy-12;Neuropharmacology;Central action, behavior and brain exposure;Brain-exposure data, receptor evidence and behavioral-task records;Separate the target behavior, motor ability and sedation;Reduced movement was interpreted as improvement in the target symptom;Behavior alone cannot locate a receptor mechanism or equate sedation with benefit;Could the task change simply reflect altered movement or alertness?;Can brain exposure and receptor-participation evidence explain responses across tasks?
pharmacy-13;Endocrine and metabolic pharmacology;Hormonal feedback, metabolic state and response;Hormone timelines, metabolic measures, food intake and body weight;Compare metabolic change with intake, weight and feedback state;Improvement after reduced intake was attributed entirely to direct metabolic action;One metabolic measure establishes neither complete metabolic improvement nor long-term safety;Is the change direct, or mediated by intake and body weight?;Can observations over time separate short-term responses from sustained metabolic regulation?
pharmacy-14;Cancer pharmacology;Drug response, cell state and model extrapolation;Model provenance, exposure and growth-response evidence;Separate general toxicity, target participation and model sensitivity;All reductions in cell growth were called tumor-selective action;Growth inhibition alone establishes neither targeting nor patient efficacy;Does inhibition depend on the target and the model?;Can target participation and exposure jointly explain responses across models?
pharmacy-15;Immunopharmacology;Immune state, cell composition and drug action;Immune-cell composition, functional measures and action evidence;Separate changes in cell number from changes in per-cell function;A composition-driven signal decrease was called per-cell functional suppression;An aggregate signal cannot directly represent every cell type's function;Does the signal decrease reflect composition or altered function?;Can state and cell-type stratification explain responses in different immune backgrounds?
pharmacy-16;Inflammation and analgesic pharmacology;Inflammation, pain behavior and movement;Pain behavior, inflammatory measures and movement records;Evaluate pain, inflammation and motor ability separately;Lower task response caused by reduced activity was called analgesia;Pain behavior, inflammatory change and functional recovery are different outcomes;Does lower pain-task response accompany impaired movement?;Can action location and functional state explain responses across pain conditions?
pharmacy-17;Respiratory pharmacology;Airway response, inflammation and respiratory function;Airway-function records, inflammatory evidence and observation conditions;Separate bronchodilation, inflammation and structural change;Short-term bronchodilation was described as restored lung structure;Short-term airway change establishes neither structural restoration nor long-term outcome;Does improved airway function reflect relaxation or altered inflammation?;Can inflammatory background and airway responsiveness explain heterogeneous responses?
pharmacy-18;Gastrointestinal pharmacology;Motility, secretion and symptoms;Motility and secretion measures, intake and symptom records;Align observation periods and distinguish motility, secretion and symptoms;Intake-driven symptom differences were attributed to direct motility action;Symptom improvement alone cannot establish a motility or secretion mechanism;Why do symptoms and motility measures disagree?;Can joint motility, secretion and sensory observations explain discordant responses?
pharmacy-19;Autonomic pharmacology;Receptor selectivity, efficacy and organ response;Receptor evidence, organ function and background-tone records;Separate affinity, efficacy and tissue context;A stronger tissue response was called higher receptor affinity;Tissue-effect size cannot substitute for affinity or selectivity;Does the response difference arise from receptor action or tissue context?;Can expression and functional coupling explain organ-dependent responses?
pharmacy-20;Thrombosis and hemostasis pharmacology;Platelets, coagulation and bleeding risk;Platelet function, coagulation evidence and safety observations;Explain platelet action, coagulation and bleeding separately;One coagulation change was treated as proof of every antithrombotic action;Antithrombotic signals and bleeding risk require separate evaluation;Do platelet and coagulation data support the same action pathway?;Can multidimensional functional evidence explain disagreement between stronger action and safety change?
pharmacy-21;Molecular and receptor pharmacology;Affinity, efficacy and signaling;Binding evidence, functional responses and receptor expression;Separate binding, function and downstream signaling;Stronger binding was called greater functional efficacy;Binding alone does not establish agonism, antagonism or in-vivo effectiveness;Why does binding strength not directly establish functional strength?;Do signaling differences reflect biased action or expression and measurement context?
pharmacy-22;Pharmacokinetic and pharmacodynamic relationships;Exposure time courses and functional response;Concentration-time data, response timelines and model assumptions;Align exposure and response times and separate delays from baseline change;One concentration measurement was used to explain the entire response;Good fit does not establish an identified mechanism;Does delayed response reflect the process or misaligned observations?;Can a model predicting unseen periods distinguish competing delay explanations?
pharmacy-23;Drug toxicology and safety pharmacology;Target action and non-target functional risk;Target-action evidence, non-target function and exposure ranges;Record useful target signals and functional harm separately;A better target measure obscured impaired function in another organ;One normal safety measure cannot establish overall safety;Do useful action and functional harm occur within the same exposure range?;Can multiple organ-function records explain risk without treating absent records as absent risk?
pharmacy-24;Developmental and aging pharmacology;Life stage, response systems and disposition;Stage information, functional state and exposure evidence;Separate disposition changes from stage-dependent response systems;All age-related response differences were attributed to receptors;Age labels cannot replace developmental state, exposure or functional context;Does the stage difference reflect disposition or the response system?;Can continuous-stage information explain nonlinear change hidden by age groups?
pharmacy-25;Reproductive and sex-related pharmacology;Hormonal state, sex variables and drug response;Hormonal state, sex variables and exposure-response records;Check hormonal and exposure differences while retaining individual variation;Group-average differences were generalized to every individual;Sex categories cannot replace hormonal, exposure or individual context;Which observable conditions explain the group difference?;Can state and exposure stratification explain within-group differences without binary extrapolation?
pharmacy-1;Basic pharmacology and mechanisms;Drug action, efficacy and evidence levels;Target evidence, functional response and exposure information;Separate target participation, functional change and clinical benefit;One functional signal was treated as proof of both the target and therapeutic benefit;Targets, function and clinical outcomes require different evidence;Does the evidence support target participation or only functional change?;Can evidence across levels separate direct action from secondary change?
pharmacy-2;Pharmaceutical analysis;Reliable quantification in complex matrices;Calibration, matrix effects, stability and quantification records;Check matrix effects and measurement range rather than peak area alone;Matrix-dependent responses were interpreted as concentration differences;A signal without reliable quantification cannot directly establish exposure;Is the difference true content or a matrix effect?;How does quantification across matrices compare with a simpler method?
pharmacy-3;Medication-use and policy research;Medication processes, rules and implementation;Prescribing processes, medicine access and service records;Separate policy requirements, implementation and actual use;A published rule was described as changed patient use;A rule's existence proves neither implementation nor benefit;Where does the process change actual medicine use?;Can policy and service information explain implementation across settings?
pharmacy-4;Pharmaceutics and drug delivery;Release, stability and accessible exposure;Formulation properties, release data and exposure information;Separate release, disposition and target-site access;Slower release was described as longer in-vivo action;In-vitro release cannot replace in-vivo exposure and effectiveness;Does the release difference actually change accessible exposure?;Can properties and biological context predict performance under unseen conditions?
pharmacy-5;Natural-product research;Provenance, mixtures and attribution of action;Source batches, composition profiles and functional evidence;Separate mixture-level response from single-component explanations;Batch differences were attributed to the same unchecked component;Provenance or traditional use cannot establish an active component or effect;Do batch responses change with composition?;Can composition and function distinguish correlated variation from a contribution to action?
pharmacy-6;Computational pharmacy;Computational assumptions and action evidence;Model inputs, scoring baselines and independent validation;Compare predictions with independent evidence and check leakage;Higher docking scores were described as greater efficacy;Predicted poses and scores prove neither binding, selectivity nor efficacy;What does the prediction add beyond a simple baseline?;Does the model retain checkable value for unseen objects and different sources?
pharmacy-7;Drug safety research;Safety signals and risk evaluation;Exposed populations, event definitions and reporting sources;Separate reporting signals, incidence and confounding;More reports were called higher incidence;Reporting proportions are not incidence and signals need verification;Could exposure and reporting practices explain the difference?;Can multiple sources strengthen risk evaluation while retaining their denominators and selection limits?
pharmacy-8;Pharmacoeconomics;Value, perspective and uncertainty;Cost definitions, utility sources and time horizons;Specify the perspective and verify the comparator;Prices from different years and perspectives were merged;Cost-effectiveness depends on the comparator, perspective and assumptions;Whose costs and which comparator does the conclusion concern?;Can a long-term model explain decision uncertainty rather than give only one ratio?
pharmacy-9;Pharmaceutical care;Communication, implementation and patient experience;Communication, understanding and actual-use records;Separate explanation, understanding and implementation;A completed education form was treated as patient understanding;Form completion cannot replace understanding, implementation or outcomes;At which step does care improve understanding or actual use?;Can continuous care improve implementation while explaining nonparticipants' missing information?
clinical-pharmacology-1;Drug-outcome research;Medication comparisons and patient outcomes;Comparison populations, treatment starts and outcome follow-up;Align eligibility and time zero;Only people surviving until treatment entered the treated group;Observational association does not directly establish drug causation;Do comparison groups really share eligibility and observation starts?;Can a more explicit design reduce time-related and selection bias?
clinical-pharmacology-2;Real-world medication data;Use records, indication and confounding;Prescriptions, dispensing, actual use and indication data;Separate prescribing from exposure and check indication;A prescription was treated as continuous medicine use;Available records do not establish accurate exposure;What information is missing between prescription and actual use?;Can linked sources improve exposure assessment while retaining source differences?
clinical-pharmacology-3;Medication safety data;Event timing and risk signals;Event definitions, exposure windows and reporting sources;Separate temporal association, reporting practices and comparative risk;An event after treatment was directly attributed to the medicine;Temporal order alone does not establish causation;What is the sequence of events, exposure and other changes?;Can independent sources verify a signal without recounting the same person?
clinical-pharmacology-4;Medication-use evaluation;Evaluation standards and actual use;Indications, use processes and standard versions;Record standard compliance separately from observed outcomes;Old records were judged using a newly revised standard;Standard compliance is not individual efficacy;Does the difference reflect actual use or the standard version?;Can contextual evaluation distinguish process problems from missing information?
clinical-pharmacology-5;Clinical pharmacokinetics;Individual exposure and disposition;Sampling times, exposure data and covariates;Check times and assumptions while retaining individual variation;Concentrations from different times were compared directly;Concentration differences cannot establish clearance differences without timing;Could different sampling times explain the concentration difference?;Can the model explain exposure in unseen individuals while retaining parameter uncertainty?
clinical-pharmacology-6;Pharmacogenomics;Genetic variation and drug response;Genotypes, ancestry, exposure and response data;Separate genetic association from exposure and population composition;Ancestry and treatment changed together but only genetics was credited;Genetic association cannot directly determine an individual's medication;How can response differences be separated from exposure and population background?;Does cross-population validation preserve meaning rather than simply transfer predictions?
clinical-pharmacology-7;Drug-interaction research;Combined use, exposure and response;Combined-use timing, disposition and response data;Separate pharmacokinetic from pharmacodynamic interaction;Worse disease in combined-use patients was attributed entirely to interaction;Combined-use association is not a demonstrated interaction mechanism;Does the difference concern exposure or response?;Can timelines separate interactions from changing disease state?
clinical-pharmacology-8;Clinical pharmacology in special populations;Population state and extrapolation;Population state, exposure and observable outcomes;Specify the population and conditions outside the scope;A few follow-up completers represented the entire special population;A category cannot replace individual function or information limits;Which states and unobserved people are actually covered?;Can stratified models improve explanation while retaining uncertainty in sparse groups?
clinical-pharmacology-9;Medication economic evaluation;From clinical evidence to economic models;Clinical-effect sources, costs and utility assumptions;Separate observed effects from extrapolation;Short follow-up was silently extrapolated into long-term effects;Long-term economics depends partly on extrapolation rather than observed outcomes;Which long-term results are observed and which are assumed?;Do alternative extrapolations change conclusions and applicability?
clinical-pharmacology-10;Patient medication experience;Treatment burden, understanding and use;Patient accounts, reporters and medication processes;Separate experience, adherence behavior and outcomes;A caregiver's response was treated as the patient's own account;Experience scores cannot substitute for behavior or efficacy;Who reported which experience and how does it relate to use?;Can continuous reports explain discontinuation without observing only persistent users?
clinical-pharmacology-11;Clinical pharmacology study design;Questions, comparators and identifiable effects;Study populations, comparators and endpoint definitions;Specify the target question and competing explanations;An exploratory comparison was called a prespecified primary conclusion;The design's scope determines the interpretation's scope;What does the design compare and what does it rule out?;What identifiable information does a new design add?
clinical-pharmacology-12;Medication data quality;Record meanings and usable exposure data;Source dictionaries, timelines and missingness reasons;Check field meanings and trace missing information;Same-named fields were treated as identical exposures;Matching field names do not establish matching clinical meaning;Does the field represent the same behavior across sources?;Can linkage reduce gaps without introducing mismatches or duplicate people?
`.trim().split('\n');
 for(const line of rows){const[id,...english]=line.split(';'),r=R.get(id);if(!r)throw Error(id);['name','topic','material','check','snag','limit','foundation','frontier'].forEach((key,i)=>P(r[key],english[i]));}
 const syllables=Object.fromEntries('顾:Gu 林:Lin 周:Zhou 陈:Chen 许:Xu 陆:Lu 沈:Shen 江:Jiang 唐:Tang 叶:Ye 季:Ji 黎:Li 邵:Shao 温:Wen 白:Bai 罗:Luo 程:Cheng 蓝:Lan 简:Jian 钟:Zhong 余:Yu 苏:Su 孟:Meng 贺:He 明:Ming 清:Qing 书:Shu 景:Jing 予:Yu 知:Zhi 星:Xing 若:Ruo 沐:Mu 云:Yun 怀:Huai 时:Shi 言:Yan 望:Wang 听:Ting 修:Xiu 安:An 亦:Yi 远:Yuan 南:Nan 映:Ying 初:Chu 向:Xiang 念:Nian 川:Chuan 宁:Ning 遥:Yao 禾:He 澜:Lan 舟:Zhou 齐:Qi 夏:Xia 秋:Qiu 雪:Xue 辰:Chen 微:Wei 和:He 月:Yue 溪:Xi 竹:Zhu 阳:Yang 归:Gui 行:Xing 舒:Shu 恒:Heng 岚:Lan'.split(' ').map(x=>x.split(':')));for(const m of window.MEETING_MENTORS.profiles.filter(m=>m.directionIds.some(id=>window.MEETING_DIRECTIONS.find(id)?.catalogAddition))){const chars=[...m.name];P(m.name,(syllables[chars[0]]||chars[0])+' '+chars.slice(1).map(c=>syllables[c]||c).join(''));}
 for(const m of window.MEETING_MENTORS.profiles.filter(m=>m.directionIds.some(id=>R.get(id)))){P(m.research,m.directionIds.map(id=>window.MEETING_NARRATIVE_WORLD.english(window.MEETING_DIRECTIONS.find(id).name)).join(', '));}
 return {rows:rows.length};
})();
