window.MEETING_PREPARATION_UI=(() => {
 const P=window.MEETING_PREPARATION,C=window.MEETING_CONTENT,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const status=n=>n>=2?'已核对，可据此回答':n===1?'只有线索，完整回答未解锁':'尚未准备';
 const origin=a=>a?`第${a.week}周 · ${C.weekDays[a.day]}「${a.action}」`:'还没有相应的行动记录';
 function ledger(book,route,w=null){return `<div class="preparation-ledger">${P.kinds.map(kind=>{const n=P.level(book,route,kind),a=P.source(book,route,kind,n);return `<article class="${n>=2?'ready':n===1?'partial':'missing'}"><strong>${P.icons[kind]} ${P.names[kind]}</strong><span>${esc(w&&window.MEETING_DIRECTION_REVIEW?.topic(w,kind)||P.topic(route,kind))}</span><b>${status(n)}</b><small>${esc(origin(a))}</small></article>`;}).join('')}</div>`;}
 function lifeHint(w,e,index){if(!P.enabled(w))return '';const c=e.choices[index];if(e.worldType&&c.worldAction==='pivot'&&window.MEETING_DIRECTIONS)return '<span class="preparation-life-hint">旧资料只留下参考线索，新版本还需要实际核对。</span>';if(e.worldType&&['verify','attend'].includes(c.worldAction))return '<span class="preparation-life-hint">实际核对可能完成，也可能发现漏洞或中断；选择后才揭晓是否留下完整依据。</span>';const p=P.lifePreview(w,e,index);return `<span class="preparation-life-hint">${Object.entries(p.gains).map(([kind,n])=>`${P.icons[kind]} ${P.names[kind]} → ${n===2?'已核对，解锁完整回答':'线索，尚不能完整回答'}`).join(' · ')||'这项行动不增加回答依据'}${!p.available?'<br>🔒 先获得结果与原始材料的线索，才能核对解释边界。':''}</span>`;}
 function choiceHint(s,c){if(!P.active(s)||!c.prepared)return '';const p=c.prepared;return `<span class="preparation-choice-hint ${p.available?'ready':'missing'}">${p.available?'✓ 可回答，依据来自 '+esc(origin(p.source)):p.reason?`🔒 ${esc(p.reason)}`:`🔒 需要${esc(P.names[p.kind])}：${p.minimum===2?'完成核对':'至少掌握线索'}。目前${p.level?'只有线索':'没有对应准备'}。`}</span>`;}
 function review(meeting,tasks=[]){const p=meeting?.preparation;if(!p)return '';return `<div class="preparation-review"><h3>这一周的准备，接住了哪些问题？</h3><p>四类准备检查中，完整回答了 ${p.attempts.filter(a=>a.eventId.startsWith('prepared-question-')&&a.status==='answered').length} 类；留下 ${p.gaps.length} 类具体补查任务。</p>${p.attempts.map(a=>`<div><strong>${esc(a.title)}</strong><span>${a.status==='answered'?'✓ 根据准备回答':a.status==='bluff'?'⚡ 冒险硬答':'△ 说明目前的准备范围'} · ${esc(origin(a.source))}${a.gap?(tasks.some(t=>t.prepKind===a.kind&&t.done)?' · ✓ 周末已核对补好':' · → 仍待补查'):''}</span></div>`).join('')}</div>`;}
 function decorateWeek(w,render,save){if(!P.enabled(w))return;const board=$('.week-board'),panel=document.createElement('section');panel.className='preparation-board';
  panel.innerHTML=`<div class="section-line"><h3>做过的准备，才是周五的回答依据</h3><span>可追溯笔记 / ${w.preparation.sources.filter(a=>a.week===w.number).length} 条本周记录</span></div><p>精读与核对能解锁完整回答；只看摘要或听同门讲留下线索。手牌、道具和高底气不能替代准备。</p>${(window.MEETING_MIX?.routes(w)?'<details class="mixed-ledgers"><summary>查看两侧准备记录</summary>'+window.MEETING_MIX.routes(w).map(id=>`<h4>${C.projects.find(p=>p.id===id).name}这一侧</h4>`+ledger(w.preparation,id)).join('')+'</details>':'<details class="mixed-ledgers"><summary>查看本周准备记录</summary>'+ledger(window.MEETING_DIRECTION_REVIEW?.book(w)||w.preparation,w.config.project,w)+'</details>')}${w.status==='life'?`<div class="preparation-plans"><h4>这段时间可以专门补一项</h4><p>占用一个生活片段，与校园地点二选一；也可以直接处理原定日常。</p><div>${P.kinds.map(kind=>`<button data-preparation="${kind}" ${w.pending||w.campus.plan?'disabled':''}><strong>${P.icons[kind]} ${{literature:'精读文献',method:'核对方法',record:'检查原始材料',boundary:'梳理边界',rehearsal:'预演汇报'}[kind]}</strong><small>${esc(window.MEETING_DIRECTION_REVIEW?.topic(w,kind)||P.topic(window.MEETING_MIX?.route(w)||w.config.project,kind))}</small></button>`).join('')}</div></div>`:''}`;
  const map=$('.campus-map');if(map)map.parentElement.before(panel);else board.before(panel);
  panel.querySelectorAll('[data-preparation]').forEach(b=>b.onclick=()=>{if(P.dispatch(w,b.dataset.preparation)){save();render();$('.life-scene')?.scrollIntoView({block:'start',behavior:'smooth'});}else window.MEETING_APP.toast(window.MEETING_WEEK.actionReason(w)||'当前条件还不满足，请查看准备要求。');});
  if(w.status==='life'&&!w.pending){const e=window.MEETING_WEEK.current(w);document.querySelectorAll('[data-life]').forEach((b,i)=>{const hint=document.createElement('div');hint.innerHTML=lifeHint(w,e,i);b.append(hint);if(!P.lifePreview(w,e,i).available)b.disabled=true;});}
  if(w.pending?.preparation){const p=w.pending.preparation,n=document.createElement('div');n.className='preparation-feedback';n.innerHTML=p.sources.map(a=>`<p>${P.icons[a.kind]} ${P.names[a.kind]}：${a.level===2?'完成核对，完整回答已解锁':'记下线索，仍需核对'}。</p>`).join('')+(p.repaired.length?`<p>✓ 已补好对应问题：${p.repaired.map(esc).join('；')}</p>`:'');$('.life-effects')?.after(n);}
  if(w.meeting?.preparation&&(w.day===5||w.status==='report')){const n=document.createElement('section');n.className='preparation-review';n.innerHTML=review(w.meeting,w.tasks);board.after(n);}
 }
 function decorateMeeting(s){if(!P.active(s)||$('.preparation-meeting'))return;const panel=document.createElement('details');panel.className='preparation-meeting';panel.innerHTML='<summary>查看回答依据 · 这周实际准备过什么</summary>'+(window.MEETING_MIX?.routes(s)?window.MEETING_MIX.routes(s).map(id=>`<h4>${C.projects.find(p=>p.id===id).name}这一侧</h4>`+ledger(s.weekContext.preparation,id)).join(''):ledger(window.MEETING_DIRECTION_REVIEW?.book(s.weekContext)||s.weekContext.preparation,s.project,s.weekContext));$('.meeting-week-link').after(panel);
  if(s.pending?.preparation){const p=s.pending.preparation,n=document.createElement('p');n.className='preparation-answer-source';n.innerHTML=p.status==='answered'?`✓ 回答依据：${esc(origin(p.source))}`:p.gap?`△ ${P.names[p.kind]}仍有缺口，散会后会成为一项具体补查任务。`:'这次回应说明了目前的准备范围。';$('.feedback h3')?.after(n);}
 }
 return {lifeHint,choiceHint,decorateWeek,decorateMeeting};
})();
