/* 虚构期刊；投稿、审稿与博士选择均为游戏流程，不连接任何真实投稿系统。 */
window.MEETING_PUBLICATION=(()=>{
  'use strict';
  const C=window.MEETING_CONTENT,copy=x=>JSON.parse(JSON.stringify(x)),tick=w=>(w.number-1)*14+w.day*2+w.slot;
  const journals=[{id:'brief',name:'《专题研究简报》',fit:'小范围材料与有限发现',strictness:.1,delay:14},{id:'methods',name:'《方法与记录》',fit:'来源清楚、过程可追溯的工作',strictness:.23,delay:21},{id:'frontier',name:'《跨域前沿》',fit:'希望看到更广的联系，评审取舍更严',strictness:.4,delay:28}];
  function journal(id,route){const j=journals.find(j=>j.id===id),n=window.MEETING_NARRATIVE_WORLD?.journal(id,route);return n?{...j,...n}:j;}
  function label(id,route){const j=journal(id,route);return j.name+(j.band?'（游戏内'+j.band+'）':'');}
  const statuses={submitted:'已投稿，等待评审',mail:'评审回信待处理',revising:'修稿进行中',resubmitted:'已经修回，等待复审',accepted:'已接收',rejected:'被拒稿',desk:'编辑初筛退稿',withdrawn:'主动撤稿'};
  const decisions={major:'大修',minor:'小修',accepted:'接收',rejected:'拒稿',desk:'编辑初筛退稿'};
  const issues=['要求把扩大了的结论缩回实际材料范围。','要求补清来源与版本，解释两份记录为何不同。','要求明确另一种解释，以及当前工作没有覆盖的条件。'];
  function ensure(w){if(window.MEETING_EXPERIENCE?.enabled(w,'publication')===false||!w.world||(w.config.rulesVersion==='08'||w.config.challenge&&!w.config.rulesVersion))return null;return w.publication||(w.publication={version:1,active:null,history:[],submittedKeys:[],serial:0,plan:null,doctorate:null});}
  function init(w,previous){if(window.MEETING_EXPERIENCE?.enabled(w,'publication')===false||!w.world||(w.config.rulesVersion==='08'||w.config.challenge&&!w.config.rulesVersion))return;w.publication=previous?.publication?copy(previous.publication):{version:1,active:null,history:[],submittedKeys:[],serial:0,plan:null,doctorate:null};w.publication.plan=null;}
  function eligible(w){const p=w.world?.artifact,a=w.publication,key=p?p.route+':'+p.direction+':'+p.version:'';return !!a&&!a.active&&p?.status==='ready'&&p.checks.length>=3&&(window.MEETING_ACADEMY?.publicationAllowed(w)??true)&&!a.submittedKeys.includes(key);}
  function can(w){return !!w.world&&w.status==='life'&&w.day!==4&&!w.pending&&!w.campus?.plan&&(w.day!==0||w.slot!==0||!!w.group?.news.handled)&&!window.MEETING_ASSIGNMENTS?.offer(w)&&w.config.rulesVersion!=='08';}
  function option(text,action,effects={},extra={}){return {text,publicationAction:action,effects,traits:{},career:{},work:{},preparationGains:{},continueOriginal:false,flavor:'具体结果会在处理后揭晓。',...extra};}
  function build(w,kind){const a=w.publication,t=a.active,p=w.world.artifact;let title='',scene='',choices=[];
    if(kind==='submit'){title='成果投稿 · 给这份课题选一个去处';scene='当前课题版本 '+p.version+' 已有三份实际核对记录，可以整理成有限范围的稿件。这里的期刊全部是虚构的游戏期刊，审稿结果不会被资源或信任保证。';choices=journals.map(base=>{const j=journal(base.id,p.route);return option('整理稿件并投到'+label(j.id,p.route)+'：'+j.fit+'。','submit-'+j.id,{energy:-12,slides:4,stress:6});});scene+=' '+(window.MEETING_NARRATIVE_WORLD?.note||'');}
    else if(kind==='mail'){title='期刊回信 · '+decisions[t.decision];scene='稿件：'+t.title+' · '+label(t.journal,t.route)+'。'+(t.decision==='accepted'?'编辑同意接收这份范围有限的工作。':t.decision==='desk'?'编辑认为稿件与刊物当前安排不匹配，未进入外审。':t.decision==='rejected'?'评审意见没有达到本刊的接收要求，现版本被拒。':issues[t.issue]+' 修回需要实际处理对应意见。');choices=[option(['major','minor'].includes(t.decision)?'读完意见，把需要做的修改拆成实际任务。':'读完回信，记录结果与仍需说明的范围。','read',{energy:-5,stress:3}),option(t.decision==='accepted'?'低调告诉同门，整理后续材料。':'不急着争辩，保留意见并撤回这轮安排。','withdraw',{energy:4,stress:-3}),option('先在群里宣布已经接收，具体回信以后再说。','announce',{energy:2,stress:-2},{traits:{chaos:1}})];}
    else if(kind==='revision'){title='修稿工作台 · '+t.title;scene=issues[t.issue]+' 实际完成 '+t.revisions.length+'/'+t.required+' 份修稿核对。修改必须留下本稿件的回执；其他课题的准备不能代替。';choices=[option('用这半天处理一项评审意见，打开投稿时的记录核对。','revise',{energy:-11,notes:4,stress:4}),option('整理逐条回复，正式修回当前稿件。','resubmit',{energy:-7,slides:3,stress:5},{publicationAvailable:t.revisions.length>=t.required}),option('判断这轮投入已超过自己的安排，撤回稿件。','withdraw',{energy:6,stress:-5})];}
    else if(kind==='new'){title='下一课题 · 让新问题从草稿开始';scene='投稿稿件保留自己的版本和修稿记录。新的课题不会继承旧题已经核对的结论。';choices=[option('在当前方向提出一个新的小问题，建立下一版草稿。','new',{energy:-7,stress:3}),option('先整理旧稿归档和生活安排，下次再开新题。','pause',{energy:8,stress:-6}),option('把旧稿扩大包装成下一份成熟课题。','inflate',{energy:3,slides:6,stress:-2},{traits:{chaos:1}})];}
    else if(kind==='doctorate'){title='导师找你聊了聊 · 要不要继续读博？';scene='已有 '+a.history.filter(t=>t.status==='accepted').length+' 份接收成果。导师想听你是否愿意把一个问题继续做下去，同时提醒经费、时间与课题要求还会变化。';choices=[option('了解后续安排后，接受转博邀请。','phd-yes',{energy:-3,stress:7}),option('约定以后再谈，先完成现在的阶段与生活安排。','phd-later',{energy:3,stress:-2}),option('感谢认可，明确选择完成当前学位后走另一条路。','phd-no',{energy:6,stress:-6})];}
    if(window.MEETING_NARRATIVE_WORLD){const N=window.MEETING_NARRATIVE_WORLD;if(kind==='submit')scene+='\n\n'+journals.map(j=>label(j.id,p.route)+'：'+journal(j.id,p.route).scope).join('\n');if(kind==='mail')scene+='\n\n'+N.pair('编辑要兼顾栏目范围与有限版面，评审也可能有不同偏好。拒稿不等于材料全部无效，大修也不是接收承诺；需要按这封回信决定下一步。','Editors balance topic scope and limited space; reviewers can disagree. Rejection does not invalidate all the work, and major revision is not a promise of acceptance. The actual letter guides the next step.');if(kind==='revision')scene+='\n\n'+N.pair('共同作者需要看过修改范围，不能只替换正文却保留原来的回应。现在处理的是投稿时的材料快照，新的课题不会自动补齐旧稿。','Coauthors need to review the changed scope; replacing the main text without updating the response is insufficient. Revision concerns the submitted snapshot, not automatically the newer project.');if(kind==='doctorate')scene+='\n\n'+N.pair('导师欣赏这轮工作，也可能需要有人延续长期问题。你可以问清资助、年限、培养安排与可退出的节点；认可是一项邀请，选择仍然属于你。','The supervisor values the work and may want continuity for a longer question. Funding, duration, supervision and exit points can be discussed; recognition is an invitation and the choice remains yours.');}return {id:'publication-'+kind+'-'+(t?.id||p.version),day:w.day,slot:w.slot,project:t?.route||p.route,publicationType:kind,title,scene,choices};
  }
  function dispatch(w,kind){if(!can(w))return false;const a=ensure(w);if(!a)return false;if(kind==='submit'&&!eligible(w)||kind==='revision'&&a.active?.status!=='revising'||kind==='mail'&&a.active?.status!=='mail'||kind==='doctorate'&&a.doctorate?.status!=='offered'||kind==='new'&&!a.submittedKeys.includes(w.world.artifact.route+':'+w.world.artifact.direction+':'+w.world.artifact.version))return false;if(!['submit','revision','mail','doctorate','new'].includes(kind))return false;a.plan=build(w,kind);w.campus.plan={day:w.day,slot:w.slot,location:'publication',original:w.eventId};return true;}
  function prepare(w,rand){const a=ensure(w);if(!a)return;a.plan=null;const t=a.active;if(t&&['submitted','resubmitted'].includes(t.status)&&tick(w)>=t.due){const j=journals.find(j=>j.id===t.journal),r=rand(w);t.decision=t.round===0?(r<j.strictness*.65?'desk':r<j.strictness+.08?'rejected':r<.64?'major':r<.92?'minor':'accepted'):(r<j.strictness*.7?'rejected':r<.25&&t.round<3?'minor':'accepted');t.issue=Math.floor(rand(w)*issues.length);t.status='mail';}if(w.day!==4&&t?.status==='mail')a.plan=build(w,'mail');else if(w.day!==4&&a.doctorate?.status==='offered')a.plan=build(w,'doctorate');}
  function current(w,raw){if(w.campus?.plan?.location==='publication')return copy(w.publication.plan);const plan=w.publication?.plan;if(!plan||w.campus?.plan||w.world?.focus||raw?.joint||raw?.choices?.some(c=>c.assignmentAction||c.groupAction)||raw?.publicationType)return raw;return copy(plan);}
  function close(w,t,status,rand){const a=w.publication;t.status=status;t.finished=w.number;a.history.push(copy(t));a.history=a.history.slice(-16);a.active=null;a.plan=null;if(status==='accepted'){const m=w.group.members.find(m=>m.rank==='mentor');window.MEETING_GROUP.trust(w,m.id,4);if(m.promotion)m.promotion.points+=3;if(!a.doctorate&&m.trust>=48&&rand(w)<.65)a.doctorate={status:'offered',week:w.number,mentorId:m.id,paperId:t.id};}}
  function resolve(w,e,c,effects,rand){if(!e.publicationType)return null;const a=w.publication,p=w.world.artifact,t=a.active,action=c.publicationAction;let text='';const add=o=>{for(const [k,v] of Object.entries(o))effects[k]=(effects[k]||0)+v;};
    if(action.startsWith('submit-')){if(!eligible(w))return null;const selected=action.slice(7),j=journal(selected,p.route),id='paper-'+(++a.serial);a.active={id,title:window.MEETING_DIRECTIONS.topic(p),route:p.route,direction:p.direction,projectVersion:p.version,journal:selected,status:'submitted',submitted:w.number,due:tick(w)+j.delay+Math.floor(rand(w)*7),round:0,required:0,revisions:[],source:copy(p.checks),issue:0,decision:null,announced:false};window.MEETING_ACADEMY?.publicationSnapshot(w,a.active);a.submittedKeys.push(p.route+':'+p.direction+':'+p.version);a.submittedKeys=a.submittedKeys.slice(-100);text='稿件已整理并提交到'+j.name+'。评审至少跨一周，等待期间可以开始下一课题。';}
    else if(e.publicationType==='retarget'){if(action==='retarget-stop')text='你保留原稿与退稿记录，停止这次转投。';else{const previous=a.history.at(-1),selected=action.slice(9),j=journal(selected,previous?.route);if(!previous||!j||a.active)return null;a.active={...copy(previous),id:'paper-'+(++a.serial),journal:selected,status:'submitted',submitted:w.number,due:tick(w)+j.delay+Math.floor(rand(w)*7),round:0,required:0,revisions:[],decision:null,announced:false};delete a.active.finished;delete a.active.celebrated;text='你用本片段整理原稿与意见，投往'+j.name+'。这是新的等待过程，原刊退稿仍保留。';}}
    else if(e.publicationType==='mail'){if(action==='announce'&&t.decision!=='accepted'){t.announced=true;add({stress:9});text='群里开始祝贺，但真实回信没有接收；状态按回信保留，组会还会追问。';}else if(t.decision==='accepted'){text='回信确认接收，成果进入记录；这是这一份稿件的结果，新课题仍需从草稿开始。';close(w,t,'accepted',rand);}else if(action==='withdraw'){text='你保留意见并撤下这轮稿件，没有得到接收成果。';close(w,t,['desk','rejected'].includes(t.decision)?t.decision:'withdrawn',rand);}else if(['major','minor'].includes(t.decision)){t.status='revising';t.required=t.decision==='major'?2:1;t.revisions=[];text='意见已读，进入'+decisions[t.decision]+'。需要 '+t.required+' 个实际修稿核对回执后才能修回。';}else{ text='稿件这轮被退回，意见和记录仍保留。你可以换期刊重新整理投出，也可以开始下一课题。';t.status=t.decision;t.finished=w.number;a.history.push(copy(t));a.history=a.history.slice(-16);a.active=null;}}
    else if(action==='revise'){const success=rand(w)<.82;if(success&&t.revisions.length<t.required){t.revisions.push({week:w.number,day:w.day,eventId:e.id,action:c.text,paperId:t.id,round:t.round});text='你实际处理了一项评审意见，留下属于本稿件这一轮的核对回执。';}else{text='这一项意见又遇到不一致，投入了时间，但暂时没有完整修稿回执。';add({stress:5});}}
    else if(action==='resubmit'){if(t.revisions.length<t.required)return null;t.round++;t.status='resubmitted';t.due=tick(w)+7+Math.floor(rand(w)*8);text='逐条回复与修稿实际提交，开始等待复审；修回不保证被接收。';}
    else if(action==='withdraw'){text='你主动撤回这份稿件，已有工作和评审意见保留。';close(w,t,'withdrawn',rand);}
    else if(action==='new'||action==='inflate'){p.version++;p.checks=[];p.references=[];p.status='draft';p.scope=action==='new'?1:3;p.claimed=0;p.history.push({week:w.number,version:p.version,status:'draft',action:c.text});p.history=p.history.slice(-24);text=action==='new'?'下一课题建立了新草稿。上一稿的投稿和修稿继续使用旧版快照，不能替新问题完成核对。':'新草稿的范围被放大了，但实查记录仍为空，旧成果没有自动变成新课题结论。';}
    else if(action==='pause')text='你把这半天留给归档和生活，没有新建课题。';
    else if(action.startsWith('phd-')){a.doctorate.status={ 'phd-yes':'accepted','phd-later':'later','phd-no':'declined'}[action];a.doctorate.decided=w.number;if(action==='phd-yes'&&w.academy){const cycle=w.academy.term.cycle+1;w.academy.term=window.MEETING_ACADEMY.term('doctor',w.number+1,'regular');w.academy.term.cycle=cycle;w.config.studyStage='doctor';}text={'phd-yes':'你接受了继续读博的邀请。新的阶段保留已有关系，课题与生活也还会继续。','phd-later':'你把决定留到以后，当前成果被保留，后续不会替你自动转博。','phd-no':'你选择了另一条人生路线，成果与认可仍是这段经历的一部分。'}[action];}
    return {action,paperId:t?.id||a.active?.id||null,text,status:t?.status||a.active?.status||null};
  }
  function retarget(w,id){const a=w.publication,last=a?.history.at(-1);if(!can(w)||a.active||!last||!['rejected','desk','withdrawn'].includes(last.status)||!journals.some(j=>j.id===id))return false;a.plan={...build(w,'submit'),id:'publication-retarget-'+last.id,publicationType:'retarget',scene:'上一稿被退回，实际材料与评审意见仍在。重新整理投往另一期刊也会占一个生活片段。',choices:[option('整理原稿与意见，投往'+label(id,last.route)+'。','retarget-'+id,{energy:-10,stress:5}),option('停止转投，保留这份工作的记录。','retarget-stop',{energy:5,stress:-4})]};w.campus.plan={day:w.day,slot:w.slot,location:'publication',original:w.eventId};return true;}
  function context(w,ctx){if(w.publication)ctx.publication=copy(w.publication);return ctx;}
  function scheduled(s){const a=s.weekContext?.publication;return s.live&&!s.wrapUp&&!s.publicationAsked&&s.choicesMade>=6&&(a?.active||a?.history.length||a?.doctorate)?{id:'publication-question',phase:6}:null;}
  function question(s){if(s.eventId!=='publication-question')return null;const a=s.weekContext.publication,t=a.active||a.history.at(-1),actual=t?.status==='accepted',has=t?.source?.length>=3;return {id:s.eventId,phase:6,who:'boss',project:t?.route||s.project,title:'“投稿、修回和接收，实际走到了哪一步？”',scene:t?'稿件：'+t.title+' · '+statuses[t.status]+'。稿件版本 '+t.projectVersion+'，与当前新课题分别保留记录。':'导师还想听你怎样安排成果之后的道路。',quote:'“把真实回信和做过的修稿摆在一起。”',choices:[{text:'打开投稿材料、回信与本轮修稿回执，按实际状态说明。',publicationAnswer:'receipt',approach:'detail',effects:{evidence:4,patience:1,time:-3},flags:{rigor:1},prepared:{kind:'record',route:t?.route||s.project,minimum:2,level:has?2:0,available:has,source:has?copy(t.source.at(-1)):null,reason:'尚未整理可追溯的稿件材料。'},result:'投稿经历与实际状态对上了。',flavor:'修回是修回，接收以真实回信为准。'},{text:'说明正在等待或尚未处理的意见，把后续任务缩小。',publicationAnswer:'boundary',approach:'cautious',effects:{evidence:-2,patience:1,time:-2},flags:{honest:1},result:'尚未完成的部分被说明了。',flavor:'等待本身不会产生接收成果。'},{text:'把这份稿件讲成已经接收，用成果撑住场面。',publicationAnswer:'claim',approach:'direct',effects:{mood:3,patience:-2,time:-2},flags:{chaos:1},risk:{chance:actual?.18:1,effects:{evidence:-13,patience:-8},flavor:'真实回信与宣布的状态不同，导师当场追到这一处。'},result:'成果被讲得超过了回信。',flavor:'实际记录仍按期刊回信保留。'}]};}
  function afterAnswer(s,e,c,record){if(e.id==='publication-question'){s.publicationAsked=true;record.publicationAnswer=c.publicationAnswer;if(c.publicationAnswer==='claim'){const a=s.weekContext.publication,t=a.active||a.history.at(-1);s.publicationFalseClaim=t?.status!=='accepted';}}}
  function ending(s){if(s.wrapUp!==2)return null;const a=s.weekContext?.publication;if(!a)return null;if(s.publicationFalseClaim)return 'publication-false';if(a.doctorate?.decided&&!a.doctorate.celebrated)return {accepted:'publication-phd',later:'publication-phd-later',declined:'publication-other-road'}[a.doctorate.status]||null;const t=a.history.findLast(t=>!t.celebrated&&t.finished>=s.weekContext.number-1);if(t?.status==='accepted')return 'publication-accepted';if(t?.status==='desk')return 'publication-desk';if(t?.status==='rejected')return 'publication-rejected';if(a.active?.status==='resubmitted')return 'publication-return';return null;}
  function afterMeeting(w,s){const a=w.publication;if(!a)return;if(['publication-phd','publication-phd-later','publication-other-road'].includes(s.ending)&&a.doctorate)a.doctorate.celebrated=true;if(['publication-accepted','publication-desk','publication-rejected'].includes(s.ending)){const t=a.history.at(-1);if(t)t.celebrated=true;}}
  for(const [id,kind,icon,title,desc] of [['publication-false','failure','📬','群里接收，邮箱拒稿','你把等待或退稿说成了接收，导师打开回信，成果的外观没能替代事实。'],['publication-phd','open','🎓','成果之后，决定再读几年','导师基于已有成果提出邀请，你了解安排后选择继续读博；新的问题还在后面。'],['publication-phd-later','open','🧭','博士邀请先放在抽屉里','成果带来了邀请，你选择先过完当前阶段，不把认可变成必须立刻决定的人生。'],['publication-other-road','open','🌿','有成果，也可以选择离开','你感谢邀请并选择另一条路，完成过的工作没有因此失去意义。'],['publication-accepted','open','📄','邮箱终于出现了接收','一份范围有限的工作走过投稿与评审，接收回信留下记录，新课题从新草稿开始。'],['publication-desk','funny','🚪','编辑比导师更快散会','稿件在初筛被退回，先前材料和意见仍在，故事可以从另一个入口继续。'],['publication-rejected','open','📮','被拒的一稿仍有记录','评审没有接收这次稿件，实际工作仍能帮助你缩小范围或重新整理。'],['publication-return','open','🛠️','修回已经发出，人生继续等待','你实际处理了评审意见，完成修回；复审结果还有不确定性。']])C.endings.push({id,kind,icon,title,desc,subtitle:'成果有自己的时间线，生活还在继续。',hint:'按真实投稿、修稿回执、回信或博士选择抵达本周收尾。'});
  function valid(w){const a=w.publication;if(!a)return true;const ok=t=>t&&typeof t.id==='string'&&Object.hasOwn(statuses,t.status)&&journals.some(j=>j.id===t.journal)&&Number.isInteger(t.projectVersion)&&t.projectVersion>=1&&C.projects.some(p=>p.id===t.route)&&Array.isArray(t.source)&&t.source.length>=3&&t.source.length<=100&&Array.isArray(t.revisions)&&t.revisions.length<=2&&[0,1,2].includes(t.required)&&Number.isInteger(t.round)&&t.round>=0&&Number.isInteger(t.due);return a.version===1&&Array.isArray(a.history)&&a.history.length<=16&&a.history.every(ok)&&(!a.active||ok(a.active))&&Number.isInteger(a.serial)&&Array.isArray(a.submittedKeys)&&a.submittedKeys.length<=100&&(!a.doctorate||['offered','accepted','later','declined'].includes(a.doctorate.status));}
  return {journals,journal,label,statuses,decisions,issues,init,ensure,eligible,can,build,dispatch,prepare,current,resolve,retarget,context,scheduled,question,afterAnswer,afterMeeting,ending,valid};
})();
