/* Basic and frontier research emphases; deterministic, version-scoped, no score bonus. */
window.MEETING_RESEARCH_AGENDA=(()=>{
 'use strict';const N=window.MEETING_NARRATIVE_WORLD,A=window.MEETING_RESEARCH_AGENDA_CONTENT,L=window.MEETING_DIRECTION_LIBRARY,D=window.MEETING_DIRECTIONS;
 if(!N||!A||!L||!D)return null;const P=N.pair,E=N.english;
 const labels={foundation:P('基础研究','Foundational research'),frontier:P('前沿探索','Frontier exploration')};
 // These summaries cover only the stated examples, never an entire field.
 const sourceRows=[
 ['af3','Accurate structure prediction of biomolecular interactions with AlphaFold 3',2024,'https://www.nature.com/articles/s41586-024-07487-w','原始方法研究 · 正文相关段落','Primary method study · relevant main-text passages','报道了多类分子复合物的结构预测评估。','Reports structure-prediction evaluations for several molecular complex types.','预测准确度不独立证明结合、药效或机制；原文附有 2024 年增补。','Prediction accuracy alone does not establish binding, efficacy or mechanism; a 2024 addendum exists.'],
 ['ensemble','Experiment-guided AlphaFold3 resolves measurement-consistent protein ensembles',2026,'https://www.nature.com/articles/s41587-026-03166-5','原始方法研究 · 正文相关段落','Primary method study · relevant main-text passages','将实验测量纳入构象集合的建模，并检查与测量的一致性。','Incorporates experimental measurements into ensemble modeling and checks measurement agreement.','测量一致性不是任意体系动力学与热力学都已验证；本卡只讨论方法层级。','Measurement agreement is not validated dynamics or thermodynamics for every system; this card concerns methods.'],
 ['sc-eval','Zero-shot evaluation reveals limitations of single-cell foundation models',2025,'https://doi.org/10.1186/s13059-025-03574-x','原始评估研究 · 正文相关段落','Primary evaluation study · relevant main-text passages','比较了 Geneformer、scGPT 与基线在所选单细胞任务中的零样本表现。','Compares Geneformer, scGPT and baselines on selected zero-shot single-cell tasks.','评价限于这些模型、版本和任务，不能写成所有模型在所有任务上都无用。','Evaluation concerns these models, versions and tasks, not all models or all tasks.'],
 ['hf-trial','Semaglutide in Patients with Obesity-Related Heart Failure and Type 2 Diabetes',2024,'https://doi.org/10.1056/NEJMoa2313917','原始随机试验 · 摘要与索引节选','Primary randomized trial · abstract and indexed excerpts','研究肥胖、射血分数保留型心衰合并二型糖尿病人群的症状、身体限制等结局。','Studies symptoms, physical limitations and other outcomes in obesity-related HFpEF with type 2 diabetes.','适用人群、观察窗口和结局有限，未完成全文审查；不是用药建议。','Population, window and outcomes are bounded; full-text review is incomplete; this is not prescribing advice.'],
 ['pathology','Towards a general-purpose foundation model for computational pathology',2024,'https://www.nature.com/articles/s41591-024-02857-3','原始方法研究 · 摘要与索引节选','Primary method study · abstract and indexed excerpts','提出 UNI 并评估所选计算病理任务。','Introduces UNI and evaluates selected computational-pathology tasks.','预训练切片和任务评估不等于前瞻性临床获益，未完成补充材料审查。','Pretraining slides and task evaluations do not establish prospective benefit; supplements were not reviewed.'],
 ['connectome','Neuronal wiring diagram of an adult brain',2024,'https://www.nature.com/articles/s41586-024-07558-y','原始资源研究 · 摘要与索引节选','Primary resource study · abstract and indexed excerpts','提供成年雌性果蝇脑的突触层面连接资源。','Provides a synapse-level connectivity resource for an adult female fly brain.','一只果蝇的结构连接不是人的动态功能或疾病证据，资源条目不是独立动物重复。','One fly connectome is not human functional or disease evidence; resource entries are not independent animals.'],
 ['proof','Olympiad-level formal mathematical reasoning with reinforcement learning',2025,'https://www.nature.com/articles/s41586-025-09833-y','原始方法研究 · 正文相关段落','Primary method study · relevant main-text passages','研究形式环境中的证明搜索与竞赛问题评价。','Studies proof search in a formal environment and evaluations on competition problems.','报道的求解成绩不表示任意数学问题已解决；形式陈述与原题之间仍要核对。','Reported results do not solve arbitrary mathematics; check formal statements against original problems.'],
 ['quantum','Quantum error correction below the surface code threshold',2024,'https://www.nature.com/articles/s41586-024-08449-y','原始器件研究 · 摘要与索引节选','Primary device study · abstract and indexed excerpts','报道特定超导架构中低于阈值的表面码存储实验。','Reports below-threshold surface-code memories in a particular superconducting architecture.','存储实验不等于普遍实用算法已可运行；2024 年在线发表，卷期为 2025 年。','Memory experiments do not establish general practical algorithms; online publication was 2024, issue year 2025.'],
 ['gencast','Probabilistic weather forecasting with machine learning',2024,'https://www.nature.com/articles/s41586-024-08252-9','原始方法研究 · 正文相关段落','Primary method study · relevant main-text passages','研究概率性天气预测和指定评估窗口中的比较。','Studies probabilistic weather forecasting and comparisons in specified evaluation windows.','天气预测技巧不证明生态因果或长期气候预测，时间和基准设置不能省略。','Weather skill does not establish ecological causation or long-term climate prediction; retain time and benchmarks.'],
 ['earth-model','A foundation model for the Earth system',2025,'https://www.nature.com/articles/s41586-025-09005-y','原始方法研究 · 摘要与索引节选','Primary method study · abstract and indexed excerpts','研究多来源地球系统资料中的预训练与下游预测。','Studies pretraining and downstream prediction using Earth-system data.','预测能力取决于任务、资料和微调条件，不能自动外推到所有地区或生态过程。','Prediction depends on task, data and adaptation, not every region or ecological process.'],
 ['pangenome','Pan-genome bridges wheat structural variations with habitat and breeding',2024,'https://www.nature.com/articles/s41586-024-08277-0','原始资源研究 · 摘要与索引节选','Primary resource study · abstract and indexed excerpts','研究小麦泛基因组结构变异及其与生境、育种资料的联系。','Studies wheat pangenome structural variation and links with habitat and breeding records.','基因组资源不独立证明所有作物的育种成效；2024 年在线，卷期为 2025 年。','A genomic resource does not establish breeding success for all crops; online 2024, issue 2025.'],
 ['carbon-date','Tracing ancient solar cycles with tree rings and radiocarbon in the first millennium BCE',2024,'https://www.nature.com/articles/s41467-024-55757-y','原始测量研究 · 正文相关段落','Primary measurement study · relevant main-text passages','利用年轮和放射性碳资料研究古代太阳变化与年代精度。','Uses tree rings and radiocarbon to study past solar variation and dating precision.','精度潜力取决于年代、材料与校准；测量本身不能替代考古层位。','Precision depends on period, material and calibration; measurement does not replace stratigraphy.'],
 ['ancient-text','Contextualizing ancient texts with generative neural networks',2025,'https://www.nature.com/articles/s41586-025-09292-5','原始方法研究 · 正文相关段落','Primary method study · relevant main-text passages','研究拉丁铭文的语境检索、复原与人机协作评价。','Studies contextual retrieval, restoration and human-AI evaluation of Latin inscriptions.','生成复原是候选解释，拉丁铭文表现不能直接代表所有语言和历史材料。','Restorations are candidate interpretations; Latin results do not establish every language or source type.'],
 ['learn-guard','Generative AI without guardrails can harm learning: Evidence from high school mathematics',2025,'https://doi.org/10.1073/pnas.2422633122','原始课堂研究 · 正文相关段落','Primary classroom study · relevant main-text passages','比较高中数学中不同工具安排及撤去工具后的表现。','Compares tool arrangements in high-school mathematics and performance after tool removal.','该情境不能代表全部课程或工具；2025 年有作者单位更正。','This setting does not represent all courses or tools; a 2025 affiliation correction exists.'],
 ['learn-tutor','AI tutoring outperforms in-class active learning: an RCT introducing a novel research-based design in an authentic educational setting',2025,'https://www.nature.com/articles/s41598-025-97652-6','原始课堂试验 · 摘要与索引节选','Primary classroom trial · abstract and indexed excerpts','比较特定大学物理课程中设计过的助教与课堂活动。','Compares a designed tutor with classroom activities in a particular university physics course.','特定课次评价不能独立证明长期学习，也不与其他设计的试验形成简单矛盾。','Lesson-specific evaluations do not establish long-term learning or simply contradict differently designed trials.'],
 ['work','Generative AI at Work',2025,'https://doi.org/10.1093/qje/qjae044','原始工作场景研究 · 摘要与索引节选','Primary workplace study · abstract and indexed excerpts','研究客服工作中引入生成工具后的生产率与人员差异。','Studies productivity and worker differences after tool introduction in customer support.','一个工作场景不代表全经济的就业、工资或长期技能效果。','One workplace does not establish economy-wide employment, wages or long-term skills.'],
 ['creativity','Generative AI enhances individual creativity but reduces the collective diversity of novel content',2024,'https://doi.org/10.1126/sciadv.adn5290','原始创作实验 · 摘要与索引节选','Primary creative-task experiment · abstract and indexed excerpts','研究短篇故事任务中的辅助创作、评价与内容多样性。','Studies assisted short-story creation, ratings and content diversity.','短篇任务不代表全部艺术和媒介；个人评分与作品集合多样性不同。','Short stories do not represent all arts and media; individual ratings differ from collection diversity.'],
 ['pqc','NIST FIPS 203, 204 and 205 approval',2024,'https://www.nist.gov/news-events/news/2024/08/announcing-approval-three-federal-information-processing-standards-fips','官方标准发布 · 方法背景','Official standard announcement · methodological background','美国官方发布后量子密钥封装与数字签名标准。','Official US standards cover post-quantum key encapsulation and signatures.','标准发布不是每个系统实现已安全；此入口不是实验论文。','Publication does not secure every implementation; this is not an experimental paper.'],
 ['legal-tools','Hallucination-Free? Assessing the Reliability of Leading AI Legal Research Tools',2024,'https://arxiv.org/abs/2405.20362','作者预印本入口 · 索引节选','Author preprint entrance · indexed excerpts','对特定美国法律检索工具进行预注册评价。','Reports a preregistered evaluation of specific US legal-research tools.','本入口按预印本处理；版本、工具和司法制度有限，不提供法律建议。','This entrance is treated as a preprint; versions, tools and jurisdiction are bounded; no legal advice.'],
 ['catalysis','Polymeric ionic liquid promotes acidic electrocatalytic CO2 conversion to multicarbon products with ampere level current on Cu',2025,'https://www.nature.com/articles/s41467-025-57095-z','原始材料研究 · 正文相关段落','Primary materials study · relevant main-text passages','研究特定材料和条件下的电催化转化评价。','Studies electrocatalytic conversion under specific materials and conditions.','本例不证明工业全寿命净减排；游戏只讨论材料评价边界，不复述实验操作。','This example does not establish industrial lifecycle emissions benefits; the game covers assessment boundaries, not procedures.'],
 ['path-eval','A benchmark study of vision and pathology foundation models for computational pathology',2026,'https://www.nature.com/articles/s41467-026-76004-6','原始评估研究 · 正文相关段落','Primary evaluation study · relevant main-text passages','比较视觉和病理基础模型在所选病理任务中的表现。','Compares vision and pathology foundation models on selected pathology tasks.','来源暴露、任务与组织差异影响比较，不能据此宣称所有机构中的临床获益。','Source exposure, tasks and tissues affect comparisons; this does not establish clinical benefit in every site.']
 ];
 const sources=Object.freeze(Object.fromEntries(sourceRows.map(([id,title,year,url,scope,se,f,fe,l,le])=>[id,Object.freeze({id,title,year,url,scope:P(scope,se),finding:P(f,fe),limit:P(l,le),checkedAt:'2026-10-04'})])));
 // Fine directions override the shared packet question without altering taxonomy.
 const refinementRows=`
biomedical;单细胞|空间;一个供体里的多种细胞状态，怎样与个体间差异区分？|How do within-donor cell states differ from between-person variation?;以供体为独立单位，保留区域、批次与注释不确定性。|Use donors as independent units, retaining regions, batches and annotation uncertainty.;细胞基础模型能否在未见供体和平台上优于简单基线？|Can cell foundation models outperform simple baselines in unseen donors and platforms?;零样本、微调与机制解释不同，需要分别比较；图谱不是独立重复。|Zero-shot use, fine-tuning and mechanisms differ, atlases are not independent replicates.
biomedical,pharma;蛋白|结构|分子模拟;一个结构模型怎样与实际测量和环境对应？|How does a structural model correspond to measurements and environment?;区分静态构象、测量平均与功能，保留来源和条件。|Separate static conformations, measurement averages and function, retaining provenance and conditions.;实验约束下的构象集合能否解释多种测量？|Can experiment-constrained ensembles explain several measurement types?;测量一致性不独立证明热力学分布、结合或药效。|Measurement agreement does not establish thermodynamic distributions, binding or efficacy.
chemistry;分析;检出限、定量限与测量不确定性如何影响报告？|How do detection, quantification limits and uncertainty affect reporting?;低于报告阈值不能直接写成不存在，校准与样品背景要对应。|Below-threshold values are not absent, align calibration and sample backgrounds.;跨平台非靶向测量能否在未知样品中保持鉴定可靠？|Can cross-platform untargeted measurements retain identification reliability in unknown samples?;信号匹配不等于结构已确认，候选鉴定与确证层级不同。|Signal matching is not confirmed structure, candidate and confirmed identifications differ.
chemistry;催化|电化学;反应选择性、速率与能耗如何在相同边界下比较？|How can selectivity, rate and energy be compared under matched boundaries?;对齐催化材料、反应状态与评价窗口，避免只选最好时点。|Align materials, states and windows rather than selecting the best moment.;低碳转化怎样同时保留长期稳定性与全流程评价？|How can low-carbon conversion retain durability and whole-process assessment?;短时高性能不代表规模化可靠或净减排。|Short-term performance does not establish scale reliability or net emissions reductions.
chemistry;高分子|聚合物;分子量分布与材料性质如何对应？|How do molecular-weight distributions relate to material properties?;区分分布、链结构与测量状态，核对批次和使用条件。|Separate distributions, chain structure and measurement states, checking batches and use.;可回收聚合物如何在循环后保留结构与使用表现？|How can recyclable polymers retain structure and performance after cycling?;单次循环的性质保留不能代表长期循环和环境优势。|One cycle does not establish long-term circularity or environmental advantage.
physics;量子|凝聚;观测量与多体模型的近似条件怎样对应？|How do observables correspond to approximations in many-body models?;区分有限尺寸、噪声与理论极限，比较可辨别预测。|Separate finite size, noise and limits, comparing distinguishable predictions.;量子多体模拟怎样验证局部观测与整体解释？|How can quantum many-body simulations validate local observations and collective interpretations?;局部符合不保证全局状态已确定，器件纠错仅是相邻方法背景。|Local agreement does not fix global states, device error correction is related-method background only.
physics;天文|天体|宇宙|恒星|星系;观测选择和距离估计怎样影响天体样本比较？|How do selection and distance estimates affect astronomical comparisons?;保留巡天覆盖、亮度限制与观测窗口，区分模型和观测。|Retain survey coverage, magnitude limits and windows, separating models and observations.;多信使与时域资料如何检验不同天体过程的解释？|How can multimessenger and time-domain data test explanations of astronomical processes?;时间相关与空间对应都需要不确定性，不能仅凭巧合认定来源。|Temporal and spatial matches require uncertainty, not source attribution by coincidence.
physics;光学|光子|激光;光学响应怎样与材料、几何和测量条件对应？|How does optical response relate to materials, geometry and measurement?;区分本征响应、器件结构与仪器背景。|Separate intrinsic response, device structure and instrument background.;可重构光子器件怎样兼顾带宽、损耗与长期稳定？|How can reconfigurable photonics balance bandwidth, loss and durability?;一项响应曲线不证明全部器件性能，条件变化需要复测。|One response curve does not establish all device performance, recheck changed conditions.
math;代数|几何|拓扑;一个结构在何种映射下保持哪些不变量？|Which invariants survive which maps of a structure?;先说明对象和映射类别，再核对分类或存在命题的条件。|Specify objects and map categories before checking classification or existence assumptions.;计算辅助的猜想如何转成可核验的结构性论证？|How can computational conjectures become checkable structural arguments?;有限实例和图形直觉不能代替一般证明。|Finite examples and visual intuition do not replace general proof.
math;概率|随机;概率模型中的独立性与极限条件如何说明？|How should independence and limiting assumptions be stated?;区分样本路径、分布收敛与期望，逐项检查假设。|Separate paths, distributional convergence and expectations, checking assumptions.;非平稳或相关过程怎样建立可用的极限与误差结果？|How can nonstationary or dependent processes yield useful limits and error results?;经验频率稳定不能独立证明模型条件或极限成立。|Stable frequencies do not establish model assumptions or limits.
statistics;因果|计量;目标比较为何需要设计与识别条件，而不只是拟合？|Why does a target comparison need design and identification rather than fit alone?;明确估计目标、处理分配、比较组和未测混杂假设。|Specify estimand, assignment, comparisons and unmeasured-confounding assumptions.;机器学习辅助估计怎样保留识别、重叠与有效不确定性？|How can ML-assisted estimation retain identification, overlap and valid uncertainty?;算法复杂不能修复没有比较支持的因果问题。|Complex algorithms do not repair causal questions without comparison support.
statistics;纵向|缺失|重复;同一对象多次观察怎样进入独立单位和缺失解释？|How do repeated observations relate to independent units and missingness?;保留对象索引、相关结构和谁更容易失访。|Retain subject indexes, dependence and differential attrition.;不规则常规记录能否支持可解释的动态风险研究？|Can irregular routine records support interpretable dynamic risk research?;访视频率和缺失可能有信息，预测轨迹不自动是自然病程。|Visit frequency and missingness may be informative, predicted trajectories are not necessarily natural history.
imaging;病理;一位患者的多个切片怎样参与评价？|How do multiple slides from one patient enter evaluation?;按个体和机构分组，保留染色、扫描与判读差异。|Group by people and sites, retaining staining, scanning and reader differences.;病理基础模型怎样在未见机构和少见类型上检验迁移？|How can pathology foundation models test transfer to unseen sites and rare types?;预训练暴露与样本重叠会影响评价，切片多不代表患者多。|Pretraining exposure and overlap affect evaluations, more slides do not mean more patients.
imaging;检验;两个平台的数值变化是对象变化还是测量口径变化？|Do changed values across platforms reflect subjects or measurement definitions?;核对测量单位、平台版本、校准和来源个体。|Check units, platform versions, calibration and subjects.;多指标联合解释怎样面对跨平台漂移和参考范围变化？|How can joint biomarker interpretation face platform drift and changing reference ranges?;组合分数需独立评价，平台升级不能直接写成对象改善。|Evaluate composite scores independently, upgrades do not establish subject improvement.
nursing;老年|社区|家庭;家庭支持与本人照护体验如何区分？|How do family support and personal care experience differ?;保留实际实施和本人或代理报告，说明生活环境。|Retain delivered care and patient or proxy reports, stating living contexts.;混合照护如何兼顾数字接入、家庭负担与连续支持？|How can hybrid care balance digital access, family burden and continuity?;联络更频繁不等于体验更好，未接入的人不能从分母消失。|More contact is not better experience, do not omit people without access.
nursing;重症|急危|交班;交班文件完整能否证明信息真正被接住？|Do complete handover documents establish received information?;区分记录、沟通和后续落实，保留班次与工作负担。|Separate records, communication and follow-through, retaining shifts and workload.;数字交接工具怎样保留关键信息又避免告警疲劳？|How can digital handovers retain key information without alert fatigue?;文书完整、工作效率和患者结局需要分别评价。|Assess documentation, efficiency and patient outcomes separately.
pharma;药剂|制剂|递送;一项制剂表征怎样与同批次的其他评价对应？|How does a formulation measurement correspond to other evaluations of its batch?;保留批次、状态与评价条件，区分材料性质和使用效果。|Retain batch, state and assessment conditions, separating properties and effects.;递送平台怎样兼顾跨批次稳定、暴露与安全性评价？|How can delivery platforms balance batch stability, exposure and safety assessment?;表征改善不证明有效性，平台概念不是可用于患者的产品。|Characterization gains are not efficacy, a platform concept is not a patient-ready product.
pharma;药代|药动|暴露;暴露曲线怎样与时间窗和效应评价对应？|How do exposure profiles relate to windows and effect assessments?;把暴露、作用信号、有效性与安全性分开。|Separate exposure, activity, efficacy and safety.;模型辅助暴露研究怎样面对人群差异与外部校准？|How can model-assisted exposure research face population differences and external calibration?;暴露预测不代替效应评价，模型外推需要独立依据。|Exposure prediction does not replace effects, extrapolation needs independent evidence.
biomedical;免疫;细胞表型、活性信号与功能解释如何区分？|How do cell phenotypes, activity signals and function differ?;保留来源个体与状态，区分相关差异和功能证据。|Retain subjects and states, separating associated differences from function.;组织环境与纵向状态资料怎样刻画免疫异质性？|How can tissue environments and longitudinal states characterize immune heterogeneity?;静态分群不独立证明功能过程，关联接口仍需验证。|Static clusters do not establish functional processes, validate association interfaces.
software;编译|程序语言;程序语义与优化假设怎样保证相互一致？|How can program semantics and optimization assumptions stay consistent?;区分定义行为、优化前提和测试覆盖。|Separate defined behavior, optimization premises and test coverage.;生成与优化工具怎样提供可核验的语义保持证据？|How can generation and optimization tools provide checkable semantics preservation?;通过基准测试不证明所有程序或输入都保持语义。|Benchmarks do not prove semantics preservation for all programs or inputs.
software;分布|云|存储;故障期间的可用性与一致性承诺如何对应？|How do availability and consistency guarantees relate during failures?;区分正常运行、网络分隔与恢复后的行为。|Separate normal operation, partitions and recovery behavior.;自适应分布式系统怎样在故障与负载变化中保留承诺？|How can adaptive distributed systems retain guarantees amid faults and changing load?;自适应策略需要退化条件与可复核日志，正常高分不代表故障可靠。|Adaptive policies need degradation conditions and logs, normal scores do not establish fault reliability.
law;民|合同|商|公司;约定文本的解释、效力与实际履行如何分开？|How do interpretation, validity and performance of agreements differ?;保留关系类型、争议事实和适用时期。|Retain relationship types, disputed facts and periods.;平台化交易中的自动约定如何面对解释、责任和救济？|How can automated platform agreements address interpretation, responsibility and remedies?;自动执行不等于法律有效或争议已解决，制度条件仍需明确。|Automatic execution is not legal validity or resolved disputes, state institutions.
law;诉讼|证据;证据可提交、可使用和证明力怎样区分？|How do submission, admissibility and probative force differ?;回到取得方式、程序阶段和证明对象。|Check acquisition, procedure and facts to be proved.;算法材料如何接受来源审查与程序中的质疑？|How can algorithmic material face provenance scrutiny and procedural challenge?;模型分数不能独立替代事实认定，适用规则需要对应具体制度。|Scores do not replace fact-finding, applicable rules depend on institutions.
history;口述|记忆;亲历、转述与后来的解释怎样共同进入历史叙述？|How do firsthand accounts, retellings and later interpretations enter history?;区分事件时间和叙述时间，保留访谈形成的情境。|Separate event and narrative times, retaining interview contexts.;多来源记忆档案怎样保留不同声音与相互矛盾？|How can multisource memory archives retain different voices and contradictions?;自动整合不能把矛盾改成统一事实，沉默和缺失也是材料边界。|Automatic integration must not turn contradictions into one fact, silence and gaps limit evidence.
arts;设计;原型形式、使用目标与审美判断怎样对应？|How do prototype form, use goals and aesthetic judgments correspond?;保留委托条件、版本和目标用户反馈。|Retain requirements, versions and target-user feedback.;可持续与生成辅助设计怎样兼顾可用性和作品差异？|How can sustainable, generation-assisted design balance usability and distinctiveness?;方案新颖不独立证明可用或环境优势，需实际情境评价。|Novelty does not establish usability or environmental advantage, assess real contexts.
organization;供应|物流|运营;局部周转变快，为什么全链交付仍可能不变？|Why can faster local turnover leave whole-chain delivery unchanged?;区分库存、排队、责任接口与交付边界。|Separate inventory, queues, interfaces and delivery boundaries.;韧性供应链怎样在预测误差与冲击下平衡库存和交付？|How can resilient supply chains balance stocks and delivery under forecast error and shocks?;局部仿真改善不代表真实全链稳健，约束与扰动范围要可比。|Local simulation gains do not establish chain robustness, match constraints and disturbances.
ecology;气候|气象;天气波动、气候统计与模型误差如何区分？|How do weather variability, climate statistics and model errors differ?;明确时空尺度、初始条件和参照资料。|State scales, initial conditions and reference data.;概率天气模型如何在极端事件与新时期检验校准？|How can probabilistic weather models test calibration on extremes and new periods?;天气基准胜出不等于长期气候规律被解决。|Winning a weather benchmark does not resolve long-term climate laws.
ecology;土壤|水文;局部水土记录怎样与流域和季节过程连接？|How do local soil-water records connect to watershed and seasonal processes?;保留采样深度、位置与时间，区分缺测和没有变化。|Retain depth, location and time, separating missingness from no change.;多源观测如何解释干旱与恢复过程中的尺度差异？|How can multisource observations explain scale differences in drought and recovery?;遥感信号不独立代表地下过程，外部参照需要保留。|Remote signals do not establish subsurface processes, retain external reference.
education;教学|课堂|课程;一个教学目标怎样转成能检验掌握的任务？|How can a teaching goal become a task that tests mastery?;把目标、实施和评价对齐，保留撤去辅助后的表现。|Align goals, implementation and assessment, retaining unaided performance.;智能助教的提示设计能否改善延迟迁移而非只提高即时答题？|Can tutor prompts improve delayed transfer rather than just immediate answers?;课次、知识范围和工具安排不同会改变结果，不用单一分数概括。|Lessons, content and tool arrangements change outcomes, avoid one-score summaries.
`.trim().split('\n').map(line=>{const[ids,pattern,...cells]=line.split(';');if(cells.length!==4)throw Error('Agenda refinement '+ids);return {ids:ids.split(','),match:new RegExp(pattern),values:cells.map(c=>P(...c.split('|')))};});
 const packetSources={ 'heart-failure':['hf-trial'],math:['proof'],logic:['proof'],physics:['quantum'],chemistry:[],computing:['proof'],nlp:['legal-tools'],cryptography:['pqc'],labor:['work'],economics:['work'],organization:['work'],education:['learn-guard','learn-tutor'],languageLearning:[],imaging:['pathology'],neuro:['connectome'],anatomy:['connectome'],biomedical:['sc-eval'],pharma:['af3'],cropBreeding:[], 'crop-breeding':['pangenome'],crop:['pangenome'],archaeometry:['carbon-date'],'digital-humanities':['ancient-text'],history:['ancient-text'],arts:['creativity'],literature:['creativity'],media:['creativity'],ecology:['gencast','earth-model'],'remote-sensing':['earth-model'] };
 function get(id){const b=L.get(id),d=D.find(id);if(!b||!d)return null;const base=A.byPacket[b.packet];if(!base)return null;const fine=refinementRows.find(r=>r.ids.includes(b.packet)&&r.match.test(d.name)),v=fine?.values;let item={...base,...(v?Object.fromEntries(['foundationQuestion','foundationAnchor','frontierQuestion','frontierBoundary'].map((k,i)=>[k,v[i]])):{}),id,direction:d.name,topic:d.topic,packet:b.packet,refined:!!v};let ids=packetSources[b.packet]||[];
  if(['biomedical','pharma'].includes(b.packet)&&/蛋白|结构|分子模拟/.test(d.name))ids=['af3','ensemble'];
  if(b.packet==='pharma'&&!/蛋白|结构|分子模拟/.test(d.name))ids=[];
  if(b.packet==='biomedical'&&/免疫/.test(d.name))ids=[];
  if(b.packet==='chemistry'&&/催化|电化学/.test(d.name))ids=['catalysis'];
  if(b.packet==='imaging'&&!/病理/.test(d.name))ids=[];
  if(b.packet==='imaging'&&/病理/.test(d.name))ids=['pathology','path-eval'];
  if(b.packet==='law'&&/数据|智能|算法|信息|数字/.test(d.name))ids=['legal-tools'];
  if(b.packet==='history'&&!/数字|计算|古代|铭文/.test(d.name))ids=[];
  if(b.packet==='physics'&&!/量子|凝聚/.test(d.name))ids=[];
  if(b.packet==='anatomy'&&!/神经|脑/.test(d.name))ids=[];
  if(b.packet==='ecology'&&/土壤|水文|地质/.test(d.name))ids=[];
  item.references=ids.map(k=>sources[k]);item=window.MEETING_DIRECTION_DOSSIERS?.agenda(item)||item;return Object.freeze(item);
 }
 function active(holder){const b=L.active(holder);return b?get(b.id):null;}
 function mode(holder){const p=holder?.world?.artifact||holder?.weekContext?.world?.artifact,t=p?.researchTheme,b=L.active(holder);return t&&t.direction===b?.id&&t.version===p.version&&Object.hasOwn(labels,t.mode)?t.mode:'foundation';}
 function reason(w){const p=w?.world?.artifact;if(w?.config?.challenge)return P('同局挑战使用固定内容，不更换研究侧重。','Seeded challenges keep their fixed content.');if(!p||!active(w))return P('本局尚未建立可安排的课题。','No project is available to schedule yet.');if(w.status!=='life'||w.pending)return P('先完成当前片段，再安排课题。','Finish the current slot before scheduling.');const t=p.researchTheme;if(t?.version===p.version&&t?.direction===p.direction&&t.locked||p.checks.length||(!t&&p.history.length)||(!t&&w.log.length))return P('本版课题已经开始。侧重随存档保留，新课题或转向后可以重新选择。','This project version has started. Its emphasis stays in the save; a new project or pivot can choose again.');return '';}
 function select(w,value){if(!Object.hasOwn(labels,value)||reason(w))return false;const p=w.world.artifact;p.researchTheme={mode:value,direction:p.direction,version:p.version,locked:false};return true;}
 function snapshot(w){const p=w.world?.artifact;return p?{version:p.version,direction:p.direction}:null;}
 function init(w,previous){if(w.config.challenge||!w.world||!active(w))return;const p=w.world.artifact,t=p.researchTheme,old=previous?.world?.artifact;if(t&&t.version===p.version&&t.direction===p.direction)return;p.researchTheme={mode:'foundation',version:p.version,direction:p.direction,locked:!!old&&old.version===p.version&&old.direction===p.direction};}
 function afterLife(w,before){if(w.config.challenge||!w.world||!active(w))return;const p=w.world.artifact,isNew=before&&(before.version!==p.version||before.direction!==p.direction);p.researchTheme={mode:mode(w),direction:p.direction,version:p.version,locked:!isNew};}
 function valid(w){const t=w.world?.artifact?.researchTheme;return !t||Object.hasOwn(labels,t.mode)&&Number.isInteger(t.version)&&t.version>0&&!!D.find(t.direction)&&typeof t.locked==='boolean';}
 function focusText(a,m){return m==='frontier'?a.frontierQuestion:a.foundationQuestion;}
 function contextText(a,m){return m==='frontier'?a.frontierBoundary:a.foundationAnchor;}
 function question(a,m,kind){const q=focusText(a,m),b=L.get(a.id);return ({method:q,literature:P(q+' 两篇文献若答案不同，先比较哪些前提？',()=>`${E(q)} If two papers disagree, which premises do you compare?`),record:P(q+' 只看汇总页能判断吗？请说明'+b.material+'怎样支持核对。',()=>`${E(q)} Can summaries decide this? Explain how ${E(b.material)} supports checking.`),boundary:P(q+' 如果'+b.snag+'，哪些解释必须暂缓？',()=>`${E(q)} If ${E(b.snag)}, which interpretations must wait?`),rehearsal:P(q+' 请向非本专业的人说明核心思路和未决部分。',()=>`${E(q)} Explain the core reasoning and unresolved parts to a non-specialist.`)})[kind]||q;}
 function life(w,raw){const a=active(w);if(!a||w.config.challenge||!raw?.bankId)return raw;const m=mode(w);return {...raw,researchMode:m,researchAgendaId:a.id,scene:P('本版侧重：'+labels[m]+'。这一段围绕「'+a.direction+'」的一个研究提案：'+focusText(a,m),()=>`Emphasis: ${E(labels[m])}. This slot addresses a proposal in ${E(a.direction)}: ${E(focusText(a,m))}`)+'\n\n'+contextText(a,m)+'\n\n'+raw.scene};}
 function meeting(s,raw){const a=active(s);if(!a||s.config?.challenge||s.weekContext?.world?.challenge||!raw?.bankId||raw.bankId!==a.id)return raw;const m=mode(s),q=question(a,m,raw.bankKind||raw.prepKind);const e={...raw,researchMode:m,researchAgendaId:a.id};if(!raw.flaw&&raw.id!=='live-followup'&&!raw.academicTalk&&!raw.id?.includes('story-question')){e.title=P('「'+a.direction+'」· '+labels[m]+'：'+q,()=>`${E(a.direction)} · ${E(labels[m])}: ${E(q)}`);e.quote=e.title;}
  e.scene=P('研究提案：'+focusText(a,m),()=>`Research proposal: ${E(focusText(a,m))}`)+'\n'+contextText(a,m)+'\n\n'+raw.scene;
  const actual=raw.choices.find(c=>c.prepared?.available&&c.prepared.source?.researchDossier===a.id)?.prepared.source;if(actual)e.scene+='\n\n'+P('你的实际记录：第 '+actual.week+' 周，你选择了「'+actual.action+'」。这条准备属于当前方向与课题版本；这轮要解释它怎样支持问题，记录存在并不代表疑点已经排除。',()=>`Your actual record: in week ${actual.week}, you chose ${E(actual.action)}. This preparation belongs to the current direction and version; explain how it supports the question. A record does not mean the concern is ruled out.`);
  // Preserve promises, source availability, RNG and explicit failure choices.
  e.choices=raw.choices.map(c=>c.hardStop||c.semantic==='joint'||c.semantic==='promise'||c.semantic==='complete'||raw.flaw||raw.academicTalk?c:c.prepared||c.semantic==='bounded'||c.flags?.honest?{...c,text:c.text+' '+P('这项提案先按这个条件讨论：'+contextText(a,m),()=>`Discuss this proposal under the condition that ${E(contextText(a,m))}`)}:c);return e;
 }
 function lesson(s,e,c,r){const a=get(e.researchAgendaId);if(!a||!r.learning)return;const m=e.researchMode;r.learning.researchMode=m;r.learning.text+='\n\n'+P('研究侧重解析：','Research-emphasis explanation:')+' '+contextText(a,m)+' '+P('研究问题是待验证的提案，本局做过的准备才决定你能拿出什么；看过资料没有自动产生发现。','A research question is a proposal; actual preparation determines what you can present. Reading does not automatically create findings.');}
 return {get,active,mode,select,reason,init,snapshot,afterLife,valid,life,meeting,lesson,labels,sources,refinementRows,focusText,contextText,question};
})();
