/* 校园支线：同一个承诺跨片段推进，只有实际核对才留下可用依据。 */
window.MEETING_SIDE_STORIES=(()=>{
  'use strict';
  const C=window.MEETING_CONTENT,P=window.MEETING_PREPARATION,copy=x=>JSON.parse(JSON.stringify(x));
  const stories=[
    ['poster','海报上的陌生箭头','boundary','走廊展览的海报用了一个你很熟悉的词，但箭头连接的含义不太一样。','作者回了消息：那条箭头是示意，不是已经证明的关系。','作者想听你介绍两种说法的差别，地点从走廊变成了周末的小讨论。'],
    ['archive','旧书里夹着一页笔记','literature','借来的旧书夹着一页没有署名的笔记。看上去很有用，出处却不清楚。','图书管理员找到了借阅线索，原来的摘录与后来流传的版本并不完全相同。','一位同学也在找这份材料，愿意交换出处，顺便听听你发现了什么。'],
    ['club','兴趣社团找你当一次解释员','rehearsal','朋友的社团想知道你研究的东西到底是什么。听众没有你的学科背景。','活动改成了五分钟短讲；有人提前发来一个非常直接的问题。','现场有人拍照，还有人想转述你的说法。你的例子可能比结论传播得更远。'],
    ['rumor','群里那个神奇办法','method','群里传来一个号称能省掉很多工作的办法。截图没有写适用条件。','发截图的人补充：自己只在一个很窄的条件下试过，别的情况不确定。','同门准备把这个办法带到讨论里，问你能不能替它作一个推荐。'],
    ['festival','校园节的小摊位','boundary','校园节邀请研究生摆一个展示摊。你可以试着用日常物品解释一个概念。','主办方想把标题写得更吸引人，提出了一句有点超过材料范围的话。','一位路过的老师停下来问：这个展示能说明什么，又说明不了什么？'],
    ['backup','被翻出来的旧版本','record','整理共享盘时，你发现了一份被忘记的旧版本。它与现在的总结差了一句话。','原来的编辑者说那句话后来改过，但记录还散在两个文件夹里。','有人想省事直接合并两份文件；也有人愿意与你把变动的来路重新对一遍。'],
    ['walk','散步时遇见另一个学科的人','method','朋友带来一个完全不同学科的人。散步时聊起的方法听起来与你的研究很像。','对方发来一个例子：同名的方法使用了不同的输入，也有不同的限制。','对方提出继续交流。你得决定是认真对照条件，还是先把这个想法当作谈资。'],
    ['lost-and-found','失物招领里的无名资料夹','record','你在失物招领处看到一个无名资料夹。里面有手写索引，却没有完整的版本说明。','资料夹的主人找到了，但有几页是别人后来补进去的，需要分开确认。','主人邀请你分享如何整理记录，也允许你保留一份已确认出处的索引。']
  ].map(([id,title,kind,...scenes])=>({id,title,kind,scenes}));
  const statuses={open:'支线进行中',verified:'支线核对完成',shared:'只做了交流，依据未核对',abandoned:'支线已放下'};
  const tick=w=>(w.number-1)*14+w.day*2+w.slot;
  function init(w,previous){if(window.MEETING_EXPERIENCE?.enabled(w,'sideStories')===false||w.config.uncertainty===false)return;const old=previous?.sideStories;w.sideStories={version:1,active:copy(old?.active||null),history:copy(old?.history||[]).slice(-16),seen:[...(old?.seen||[])].slice(-8),plan:null};}
  function build(w,t,rand){const d=stories.find(e=>e.id===t.id),topic=window.MEETING_DIRECTION_REVIEW?.topic(w,d.kind)||P.topic(t.route,d.kind),step=t.step,proof=t.checked===2;
    const texts=step===0?['用这半天寻找原始材料，先记下能核对的出处。','先和当事人聊聊，交换线索，暂时不作确定判断。','说清自己的安排，放下这条支线，留出一点休息时间。']:step===1?['打开两边的材料对照，把不一致的条件写进记录。','找另一位同学一起讨论，收集不同解释，但暂不替它背书。','说明自己暂时接不住后续，到这里停止。']:['打开此前留下的原始材料，逐项核对范围，再说明能确认的部分。','把它当作一段有趣经历分享，明确说自己还没核对完。','停止继续扩展，交回线索，不把故事讲成已经验证的发现。'];
    const choices=texts.map((text,action)=>({text,storyAction:action,storyId:t.id,storyStep:step,effects:action===0?{energy:-9,notes:4,stress:3}:action===1?{energy:-4,stress:-2}:{energy:8,stress:-4},traits:action===0?{study:1}:action===1?{collaboration:1}:{rest:1},career:{},work:{progress:0,quality:0},preparationGains:action===0?{[d.kind]:step===2&&proof?2:1}:{},flavor:'后续和具体后果将在选择后揭晓。',continueOriginal:false}));
    for(let i=choices.length-1;i>0;i--){const j=Math.floor(rand(w)*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}
    return {id:`side-story-${t.id}-${step}`,day:w.day,slot:w.slot,project:t.route,title:`校园支线 · ${d.title} · ${step+1}/3`,scene:d.scenes[step]+` 这次需要弄清的是「${topic}」。`,choices};
  }
  function prepare(w,rand){const a=w.sideStories;if(!a)return;a.plan=null;let t=a.active;const now=tick(w);if(t&&now>=t.next){a.plan=build(w,t,rand);return;}if(t||w.day===4||rand(w)>.19)return;const pool=stories.filter(e=>!a.seen.includes(e.id)),d=(pool.length?pool:stories)[Math.floor(rand(w)*(pool.length||stories.length))],route=window.MEETING_MIX?.route(w)||w.config.project;t={id:d.id,route,step:0,checked:0,started:w.number,next:now,status:'open',source:null};a.active=t;a.seen.push(t.id);a.seen=a.seen.slice(-8);a.plan=build(w,t,rand);}
  function event(w,raw){const plan=w.sideStories?.plan;if(!plan||!raw||(w.pending&&!w.pending.sideStory)||raw.choices?.some(c=>c.assignmentAction||c.groupAction)||raw.joint)return raw;return copy(plan);}
  function resolve(w,e,c,effects,rand){if(c.storyAction===undefined)return null;const a=w.sideStories,t=a?.active;if(!t||t.id!==c.storyId||t.step!==c.storyStep)return null;const action=c.storyAction,d=stories.find(e=>e.id===t.id);let text='';if(action===2){t.status='abandoned';text='你明确停下了这条支线，留下已有线索。没有获得完整核对记录。';}
    else {if(action===0)t.checked++;if(t.step===2){t.status=t.checked===3?'verified':'shared';if(t.status==='verified'){text='三次实际核对接上了：出处、条件和使用范围都有记录，可以在对应问题中据此说明。';t.source={route:t.route,kind:d.kind,week:w.number,day:w.day,eventId:e.id,action:c.text,level:2};}else text='这段经历留下了交流和线索，但没有完成三次核对。它不能充当完整答案的依据。';}
      else {t.step++;t.next=tick(w)+2+Math.floor(rand(w)*3);text=action===0?'这一段的出处或条件已核对，后续仍需真正处理，不能直接跳到完整结论。':'你收到了新线索，也认识了新的解释。是否成立，要等后续打开材料核对。';}}
    if(action!==2&&rand(w)<.25){effects.stress=(effects.stress||0)+5;text+=' 对方临时又发来一个追问，这次比预计更费心。';}
    const result={id:t.id,step:c.storyStep,action,status:t.status,text,checked:t.checked,route:t.route};if(t.status!=='open'){a.history.push(copy(t));a.history=a.history.slice(-16);a.active=null;}return result;
  }
  function context(w,ctx){if(w.sideStories)ctx.sideStories={active:copy(w.sideStories.active),history:copy(w.sideStories.history)};return ctx;}
  function scheduled(s){if(!s.live||s.wrapUp||s.storyAsked||s.choicesMade<6)return null;const a=s.weekContext?.sideStories;if(!a?.active&&!a?.history?.length)return null;return {id:'side-story-question',phase:6};}
  function question(s){if(s.eventId!=='side-story-question')return null;const a=s.weekContext.sideStories,t=a.active||a.history.at(-1),d=stories.find(e=>e.id===t.id),full=t.status==='verified';return {id:'side-story-question',phase:6,who:'senior',project:t.route,title:`“你最近遇到的「${d.title}」，哪些部分真的核对过？”`,scene:`这段经历的实际记录：${statuses[t.status]}。听到线索、参与交流和完成核对是不同的事。`,quote:'“故事很好听，依据在哪里？”',choices:[{text:'拿出这条支线的完整记录，说明出处、条件和适用范围。',approach:'detail',effects:{evidence:5,patience:1,time:-3},flags:{rigor:1},prepared:{kind:d.kind,minimum:2,level:full?2:0,available:full,source:copy(t.source),reason:full?null:'这条支线还没有三段核对的完整记录。别处的准备不能替代这次经历。'},result:'经历有了可以追溯的依据。',flavor:'你说明的是实际做过的核对。'}, {text:'按实际经历讲进度，把线索和已经确认的部分分开。',approach:'cautious',effects:{evidence:full?0:-2,patience:1,time:-2},flags:{honest:1},result:'这段经历的范围被讲清了。',flavor:'说清不知道的部分，不会自动补齐缺少的核对。'}, {text:'把这个经历讲成新发现，先用热闹的故事撑住场面。',approach:'direct',effects:{mood:3,patience:-3,time:-2},flags:{chaos:1},risk:{chance:full?.18:.75,effects:{evidence:-11,patience:-7},flavor:'对方追到具体条件，故事的热闹没能代替来源。'},result:'你把经历讲得比记录更大了。',flavor:'场面活跃，实际材料仍要经得起追问。'}]};}
  function afterAnswer(s,e,record){if(e.id==='side-story-question'){s.storyAsked=true;record.sideStory=true;}}
  function ending(s){if(s.wrapUp!==2)return null;const h=s.weekContext?.sideStories?.history||[],current=h.filter(t=>t.started===s.weekContext.number);if(current.some(t=>t.status==='shared'&&t.id==='rumor')&&s.flags.chaos>=3)return 'story-rumor';if(current.some(t=>['club','festival'].includes(t.id)&&t.status==='shared')&&s.flags.chaos>=3)return 'story-celebrity';if(current.some(t=>t.status==='verified')&&s.flags.rigor>=2)return 'story-small-proof';if(current.some(t=>t.status==='abandoned')&&s.flags.honest>=3)return 'story-stop';return null;}
  for(const [id,kind,icon,title,desc,hint] of [['story-rumor','failure','📣','传闻跑得比依据快','那条神奇办法从群聊走进了组会。你讲得太确定，追问却发现适用条件还没有核对。','未经完整核对的传闻支线，反复扩大说法。'],['story-celebrity','funny','🎤','校园名人，材料待补','大家记住了你的五分钟故事，还想邀请你再讲一次。现在需要先回答：哪句话有材料支持？','展示或社团支线只做交流，多次整活。'],['story-small-proof','open','📎','偶遇最后变成了一份小依据','三次认真处理让一个偶然线索有了出处、条件和边界。它很小，但下一次追问时可以打开给人看。','实际完成三段核对，并严谨回应。'],['story-stop','open','🍃','有些支线可以不做完','你保留了线索，也清楚说出了自己的范围。校园很大，这一周的时间仍然有限。','明确放下支线，并诚实说明范围。']])C.endings.push({id,kind,icon,title,subtitle:'偶然碰见的事，也会留下后续。',desc,hint});
  function valid(w){const a=w.sideStories;if(!a)return true;const ok=t=>stories.some(d=>d.id===t.id)&&C.projects.some(p=>p.id===t.route)&&[0,1,2].includes(t.step)&&Number.isInteger(t.checked)&&t.checked>=0&&t.checked<=3&&Object.hasOwn(statuses,t.status)&&Number.isInteger(t.next);return a.version===1&&Array.isArray(a.history)&&a.history.length<=16&&a.history.every(ok)&&(!a.active||ok(a.active)&&a.active.status==='open')&&Array.isArray(a.seen)&&(!a.plan||a.plan.choices.length===3);}
  function decorate(w){const a=w.sideStories;if(!a)return;const items=[...(a.active?[a.active]:[]),...a.history.slice(-2)],el=document.createElement('details');el.className='group-board story-board';el.innerHTML=`<summary>🎲 校园支线 · ${a.active?'还有后续':'偶遇与选择'}</summary><p>随机出现的支线会记住选择，隔几段时间带来后续。选项顺序每段随机；切换页面不会重新抽取。本片段与准备、吃饭、交办共用时间。</p>${items.length?items.map(t=>`<p><strong>${stories.find(d=>d.id===t.id).title}</strong> · ${statuses[t.status]} · 已核对 ${t.checked}/3 段</p>`).join(''):'<p>校园里暂时安静，新的偶遇可能在途中发生。</p>'}`;document.querySelector('.assignment-board')?.after(el);}
  return {stories,statuses,init,prepare,event,resolve,context,scheduled,question,afterAnswer,ending,valid,decorate};
})();
