(() => {
  'use strict';
  const C=window.MEETING_CONTENT,W=window.MEETING_WEEK,A=window.MEETING_APP,$=s=>document.querySelector(s),app=$('#app'),KEY='meeting-survival-v3-week';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={energy:'精力',notes:'资料',slides:'幻灯片',stress:'压力'},kinds={failure:'翻车结局',funny:'滑稽结局',open:'开放结局'};
  let week=null;try{const old=JSON.parse(localStorage.getItem(KEY));if(W.isValid(old))week=window.MEETING_PREPARATION?.upgrade(old)||old;}catch{}
  if(week){window.MEETING_ACADEMY?.calendar(week);window.MEETING_TIMELINE?.init(week,{timeline:week.timeline});}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(week));window.MEETING_SAVES?.schedule();}catch{A.toast('浏览器没有保存这次进度，请暂时不要关闭页面。');}}
  function seed(){const x=new Uint32Array(1);crypto.getRandomValues(x);return x[0];}
  function calendar(){return `<div class="week-calendar" aria-label="本周时间线">${C.weekDays.map((d,i)=>`<div class="${i===week.day?'today':i<week.day?'past':''}"><small>${d}</small><strong>${i===4?'组会':i<4?'准备 · 生活':'反馈 · 休息'}</strong><span>${i===week.day?'● 当前':i<week.day?'✓ 已过':'· 待续'}</span></div>`).join('')}</div>`;}
  function resources(){return `<div class="week-resources">${Object.entries(labels).map(([k,l])=>`<div><span>${l}</span><strong>${week.resources[k]}</strong><i><b style="width:${week.resources[k]}%"></b></i></div>`).join('')}</div>`;}
  const effects=e=>Object.entries(e).filter(([,v])=>v).map(([k,v])=>`${labels[k]} ${v>0?'+':''}${v}`).join(' · ');
  function tasks(){return `<div class="week-tasks"><h3>组会留下的事</h3>${week.tasks.length?week.tasks.map(t=>`<p class="${t.done?'done':''}">${t.done?'✓':'○'} ${esc(t.title)} <small>第${t.from}周</small></p>`).join(''):'<p>周五还没有开会。上周的未完成事项会带到这里。</p>'}</div>`;}
  function careerEffects(record){const c=week.world?.challenge?week.world.runCareer:A.getCareer();for(const [k,v] of Object.entries(record.career)){if(k==='taskDone')continue;if(['boss','stats','senior'].includes(k))c.relations[k]=window.MEETING_UNCERTAINTY&&week.config.uncertainty!==false?window.MEETING_UNCERTAINTY.changeTrust(c.relations[k],v):Math.max(0,Math.min(100,c.relations[k]+v));else if(k==='debt')c.debt=Math.max(0,c.debt+v);else if(k==='coins')c.coins=(c.coins||0)+v;}if(!week.world?.challenge)A.persistCareer();}
  function arrangeLife(){
    if(!['life','meeting','report'].includes(week.status))return;
    const board=$('.week-board'),resources=$('.week-resources'),bottom=$('.week-tasks');
    board.id='daily-scene';resources.after(board);board.classList.add('daily-focus');
    const choices=[...board.querySelectorAll('.life-choice')],shared=document.createElement('div');shared.className='life-shared-hints';
    if(choices.length>1){for(const selector of [':scope > span',':scope > .work-preview',':scope > div']){const nodes=choices.map(c=>c.querySelector(selector));if(nodes.every(n=>n&&n.textContent.trim()===nodes[0].textContent.trim())){shared.append(nodes[0]);nodes.slice(1).forEach(n=>n.remove());}}if(shared.childNodes.length)board.querySelector('.week-hint').before(shared);}
    const nav=document.createElement('nav');nav.className='life-section-nav';nav.setAttribute('aria-label','生活页面导航');
    nav.innerHTML='<a href="#daily-scene">☀️ 当天事件</a><a href="#life-planning">📖 准备与去处</a><a href="#life-research">🔎 课题与成果</a><a href="#life-community">🏫 课题组与本周动态</a>';board.before(nav);
    const planning=document.createElement('div');planning.id='life-planning';planning.className='life-planning';bottom.before(planning);
    const mix=$('.mix-board');if(mix)planning.append(mix);
    const tools=document.createElement('div');tools.className='life-tool-grid';planning.append(tools);
    const preparation=$('.preparation-board'),map=$('.campus-map');if(preparation)tools.append(preparation);if(map)tools.append(map.parentElement);
    const leisure=[...app.querySelectorAll('.week-world .friend-plan')];if(leisure.length){const tray=document.createElement('div');tray.className='life-leisure';planning.append(tray);leisure.forEach(n=>tray.append(n));}
    for(const selector of ['.assignment-board','.story-board']){const node=$(selector);if(node)planning.append(node);}
    const research=document.createElement('div');research.id='life-research';bottom.before(research);
    const world=$('.world-board');if(world)research.append(world);
    const direction=$('.direction-board');if(direction){const drawer=document.createElement('details');drawer.className='direction-drawer';const summary=document.createElement('summary');summary.textContent='🧭 当前研究方向 · 相邻转向目标';direction.before(drawer);drawer.append(summary,direction);}
    const stories=document.createElement('div');stories.className='life-research-grid';research.append(stories);for(const selector of ['.route-story-board:not(.publication-board)','.publication-board']){const node=$(selector);if(node)stories.append(node);}
    const community=document.createElement('div');community.id='life-community';community.className='life-community';bottom.before(community);
    const news=$('.week-world');if(news){community.append(news);const social=news.querySelector('.social-week');if(social&&social.parentElement===news){const drawer=document.createElement('details');drawer.className='world-news';const summary=document.createElement('summary');summary.textContent='🏫 这周，大家也在过自己的生活';social.before(drawer);drawer.append(summary,social);}}
    const group=$('.group-board:not(.story-board)');if(group){group.open=false;community.append(group);}
    const review=$('.preparation-review');if(review)community.append(review);
    const campus=$('.planning-drawer');if(campus)community.append(campus.parentElement);
    const report=$('.campus-report');if(report)planning.append(report);
    nav.querySelectorAll('a').forEach(a=>a.onclick=e=>{e.preventDefault();app.querySelector(a.getAttribute('href'))?.scrollIntoView({block:'start',behavior:'smooth'});});
  }
  function render(){if(!week)return;window.MEETING_DASHBOARD_UI?.clear();A.clearView();const p=C.projects.find(p=>p.id===week.config.project);
    let body='';
    if(week.status==='life'){
      const e=W.current(week),q=week.pending;
      body=`<section class="life-scene"><p class="eyebrow">${week.day<4?'BEFORE FRIDAY':'LIFE AFTER THE MEETING'} / ${C.weekDays[week.day]} · ${week.slot?'下半天':'上半天'}</p><span class="life-icon">${week.day<4?'☕':week.day===4?'🎒':'🌿'}</span><h1>${esc(e.title)}</h1><p>${esc(e.scene)}</p>${week.day===5&&week.meeting?`<div class="week-context">昨天的组会：「${esc(week.meeting.title)}」<br>底气 ${week.meeting.stats.evidence} · 撑过 ${week.meeting.rounds} 回合。反馈已经进入待办。</div>`:''}</section><section class="life-options">${q?`<div class="feedback"><p class="eyebrow">这件事留下了后果</p><h3>${esc(q.answer)}</h3><p>${esc(q.flavor)}</p><p class="life-effects">${effects(q.deltas)}</p>${q.taskDone?`<p>✓ 已处理：${esc(q.taskDone)}</p>`:''}<button class="primary" id="life-next">${week.day===4?'准备进入组会':week.day===6&&week.slot===1?'看看这一周':'时间往前走'} →</button></div>`:e.choices.map((c,i)=>`<button class="life-choice" data-life="${i}"><small>0${i+1}</small><strong>${esc(c.text)}</strong><span>${window.MEETING_LIFE_SURPRISES?.active(week)?esc(window.MEETING_LIFE_SURPRISES.hint(week,c)):effects(window.MEETING_CAMPUS?.preview(week,c)||c.effects)}</span></button>`).join('')}<p class="week-hint">精力与压力影响心态；资料与幻灯片影响底气。迟到缩短组会时间，承诺和未完成事项变成解释债。</p></section>`;
    }else if(week.status==='meeting'){
      const ctx=W.meetingContext(week);body=`<section class="life-scene"><p class="eyebrow">FRIDAY / 准备进入会议室</p><span class="life-icon">🎤</span><h1>这一周，现在轮到你讲了。</h1><p>你的准备、熬夜、合作和承诺，会一起走上讲台。</p><div class="week-context">本周最终入场修正：心态 ${ctx.deltas.mood>=0?'+':''}${ctx.deltas.mood} · 底气 ${ctx.deltas.evidence>=0?'+':''}${ctx.deltas.evidence} · 时间 ${ctx.deltas.time} min<br>额外解释债 ${ctx.debt} 笔。${ctx.deltas.patience?`耐心修正 ${ctx.deltas.patience>0?'+':''}${ctx.deltas.patience}。`:''}角色、难度、导师风格也会影响初始状态。</div></section><section class="life-options"><button class="primary" id="enter-friday">进入周五组会 ↗</button><p class="week-hint">组会仍然不限十回合。失败后也继续过周末，下一周还能再来。</p><details class="week-history"><summary>回看本周入场前的选择</summary>${week.log.map(r=>`<p>${C.weekDays[r.day]} · ${esc(r.answer)}</p>`).join('')}</details></section>`;
    }else{
      body=`<section class="life-scene"><p class="eyebrow">SUNDAY / 本周生活报告</p><span class="life-icon">📒</span><h1>一周结束，故事还开着。</h1><p>${esc(week.config.name)}，这周你做了 ${week.log.filter(r=>!r.timeSkipped).length} 次日常选择。${week.meeting?`周五解锁「${esc(week.meeting.title)}」。`:'组会记录暂未生成。'}</p><div class="week-context">${week.meeting?kinds[week.meeting.kind]+' · 本场评分 '+week.meeting.score+'/100':''}<br>未完成 ${week.tasks.filter(t=>!t.done).length} 件事，会进入下一周；处理过的任务保持完成。</div></section><section class="life-options"><button class="primary" id="next-week">继续第 ${week.number+1} 周 ↗</button><button class="secondary" id="week-config">回门口换个学科 / 人设</button><details class="week-history"><summary>这一周的生活轨迹</summary>${week.log.map(r=>`<p><small>${C.weekDays[r.day]}</small> ${esc(r.answer)}${r.taskDone?' ✓ 已处理一项遗留':''}</p>`).join('')}</details></section>`;
    }
    app.innerHTML=`<div class="run-head"><div><p class="eyebrow">WEEK ${week.number} / ${p.icon} ${p.name}</p><h2>${esc(week.config.name)}的一周</h2></div><button class="plain" id="week-door">回到门口 · 自动保存</button></div>${calendar()}${resources()}<div class="week-board">${body}</div>${tasks()}<div class="week-bottom"><button class="secondary" id="life-shop">逛逛补给站</button><small>游戏中的一周不跟随现实时间。随时停下，下次接着过。</small></div>`;
    if(!window.MEETING_CAMPUS?.enabled(week)){const notice=document.createElement('p');notice.className='week-hint';notice.textContent='当前旧周历会保留进度；从下一周开始，开放校园探索、课题养成与手牌。';app.querySelector('.week-board').before(notice);}
    window.MEETING_CAMPUS_UI?.decorate(week,render,save);window.MEETING_PREPARATION_UI?.decorateWeek(week,render,save);window.MEETING_LIFE_SURPRISES?.decorate(week,render,save);window.MEETING_GROUP?.decorate(week);window.MEETING_MIX?.decorate(week,render,save);window.MEETING_ASSIGNMENTS?.decorate(week,render,save);window.MEETING_SIDE_STORIES?.decorate(week);window.MEETING_WORLD_UI?.decorate(week,render,save);window.MEETING_ROUTE_STORIES_UI?.decorate(week,render,save);window.MEETING_PUBLICATION_UI?.decorate(week,render,save);
    arrangeLife();window.MEETING_ACADEMY_UI?.decorate(week,render,save);window.MEETING_DIRECTION_LIBRARY_UI?.decorate(week);window.MEETING_HUB_UI?.life(week);app.querySelectorAll('[data-life]').forEach(b=>b.onclick=()=>{const r=W.choose(week,Number(b.dataset.life));if(!r){A.toast('当前选项需要先完成对应准备，请选择可用回应。');return;}careerEffects(r);save();render();});
    if($('#life-next'))$('#life-next').onclick=()=>{if(W.advance(week)){careerEffects({career:window.MEETING_ASSIGNMENTS?.drain(week)||{}});save();render();if(week.campus){const target=week.status==='life'?$('.life-section-nav'):week.status==='meeting'?$('.deck-board'):$('.campus-report');target?.scrollIntoView({block:'start',behavior:'smooth'});}}};
    if($('#enter-friday'))$('#enter-friday').onclick=()=>{if(!A.restoreMeeting(week.id)){if(week.campus)week.campus.deckLocked=true;save();A.startWith(week.config,W.meetingContext(week));}};
    const nextWeek=()=>{if(!week.reportApplied){const career=week.world?.challenge?week.world.runCareer:A.getCareer();career.weeks=Math.max(career.weeks||0,week.number);week.reportApplied=true;if(!week.world?.challenge)A.persistCareer();save();}const run=week.world?.challenge?week.world.runCareer:A.getCareer();week=W.create({...week.config,campus:true,preparation:true,peer:run.peer,relations:{...run.relations}},window.MEETING_WORLD?.derive(week.world?.root||week.seed,week.number+1)||seed(),week,week.number+1);save();render();window.scrollTo(0,0);};if($('#next-week'))$('#next-week').onclick=nextWeek;
    window.MEETING_TIMELINE_UI?.decorate(week,render,save,w=>{week=w;},nextWeek);
    if(week.status==='life'&&!week.pending){const e=W.current(week),blocked=e.choices?.find(c=>c.academyAvailable===false&&c.worldAction==='verify');if(blocked){const hint=document.createElement('div');hint.className='progress-prerequisite';hint.innerHTML='<p>本版实查需要先预约并复核资源窗口。等待时仍可选择缩小范围或其他安排。</p><button class="secondary" id="daily-resource">🗓️ 去处理资源排期</button>';document.querySelector('.life-options')?.append(hint);hint.querySelector('button').onclick=()=>{const job=week.academy?.resource.active,type=job&&['available','blocked'].includes(job.status)?'resource-work':'resource';if(job&&type==='resource'){A.toast('已有排期正在等待。可收起事件，到课题入口查看开放时间。');return;}if(window.MEETING_ACADEMY.resourceDispatch(week)){save();render();}else A.toast('当前片段还有正在处理的安排，先完成或交回后再预约。');};}}
    if($('#week-config'))$('#week-config').onclick=A.landing;$('#week-door').onclick=A.landing;$('#life-shop').onclick=A.showShop;window.MEETING_EXPERIENCE_UI?.decorate(week);window.MEETING_DASHBOARD_UI?.decorate(week);
  }
  function resume(id){if(!week||(id&&id!==week.id))return false;if(week.status==='meeting'&&A.restoreMeeting(week.id))return true;render();window.scrollTo(0,0);return true;}
  function enhanceLanding(){window.MEETING_ACADEMY_UI?.landing();const start=$('#start');if(!start)return;
    const copy=$('.hero-copy');copy.innerHTML='这周怎么准备，周五就怎么回答。<br>准备决定你能讲什么，现场决定对方买不买账。漏洞、连续追问和关系波动，每场重新面对。';
    document.querySelector('.family-filter')?.remove();document.querySelector('#discipline-search')?.remove();document.querySelector('.taxonomy-path')?.remove();
    const T=window.MEETING_TAXONOMY,t=T.state(),head=$('.discipline-head'),filters=document.createElement('div');filters.className='family-filter taxonomy-families';filters.setAttribute('aria-label','第一步：选择学科大类');filters.innerHTML=C.families.map(f=>`<button data-family="${f.id}" aria-pressed="${t.family===f.id}" class="${t.family===f.id?'active':''}"><span aria-hidden="true">${T.icons[f.id]}</span><strong>${f.name}</strong><small>${C.projects.filter(p=>p.family===f.id).length} 条专业路线</small></button>`).join('');head.after(filters);
    head.innerHTML='<h2>① 从一个学科大类开始</h2><span>先看门类，再展开专业</span>';
    const path=document.createElement('nav');path.className='taxonomy-path';path.setAttribute('aria-label','当前选择路径');path.innerHTML=`<button id="taxonomy-root">学科大类</button>${t.family?`<span>›</span><button id="taxonomy-family">${C.families.find(f=>f.id===t.family).name}</button><span>›</span><span>${t.route?C.projects.find(p=>p.id===t.route).name:'② 选择专业路线'}</span>`:'<span>选择后展开专业与细分领域</span>'}`;filters.after(path);path.querySelector('#taxonomy-root').onclick=()=>{T.back();A.landing();};if(t.family)path.querySelector('#taxonomy-family').onclick=()=>{T.backToFamily();A.landing();};
    const search=document.createElement('input');search.id='discipline-search';search.type='search';search.placeholder='搜索当前门类的专业或研究分支';search.setAttribute('aria-label','搜索当前门类');search.hidden=!t.family;path.after(search);
    const grid=$('.discipline-grid'),MT=t.family==='medicine'?window.MEETING_MEDICAL_TAXONOMY:window.MEETING_DISCIPLINE_TREE;grid.hidden=!t.family||!MT.branch()||MT.routes().length===1;const filter=()=>{const q=search.value.trim().toLocaleLowerCase(),tr=s=>window.MEETING_I18N?.translate(s)||s;app.querySelectorAll('[data-project]').forEach(b=>{const p=C.projects.find(p=>p.id===b.dataset.project),terms=[p.name,...window.MEETING_DIRECTIONS.all.filter(d=>d.route===p.id).map(d=>d.name)].map(tr).join(' ').toLocaleLowerCase();b.hidden=p.family!==t.family||!MT.routes().includes(p.id)||(q&&!terms.includes(q));b.classList.toggle('selected',t.route===p.id);b.setAttribute('aria-pressed',String(t.route===p.id));});};
    filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{T.chooseFamily(b.dataset.family);A.landing();$('.taxonomy-path')?.scrollIntoView({block:'start',behavior:'smooth'});});search.oninput=filter;filter();
    app.querySelectorAll('[data-project]').forEach(b=>{const original=b.onclick;b.onclick=()=>{if(T.chooseRoute(b.dataset.project)){MT.routeSelected();original();$('.direction-setup')?.scrollIntoView({block:'start',behavior:'smooth'});}};});
    start.disabled=!T.ready();
    start.textContent='下一步：了解与选择导师 ↗';start.onclick=()=>{const number=Math.max(A.getCareer().weeks||0,week?.number||0)+1,root=seed(),config=window.MEETING_WORLD?.config({...A.getMenuConfig(),playMode:window.MEETING_WORLD_UI?.mode()},root)||A.getMenuConfig();const enter=chosen=>{if(!window.MEETING_MENTORS.find(chosen.mentorId)||!window.MEETING_DIRECTIONS.find(chosen.direction)){A.toast('先选导师及具体研究方向，再开始入组。');return;}if(week){if(!window.MEETING_SAVES.archive(C.projects.find(p=>p.id===week.config.project).name+' · 第'+week.number+'周')){A.toast('未能保存暂停生涯，当前进度仍保留。请先导出完整存档。');return;}A.clearSavedMeeting();week=null;save();}if(chosen.experienceMode==='meeting'){A.startWith(chosen);return;}week=W.create({...chosen,campus:true,preparation:true,peer:A.getCareer().peer,relations:{...A.getCareer().relations}},root,null,number);save();render();window.scrollTo(0,0);};window.MEETING_MENTORS_UI.choose(config,enter);};
    const quick=document.createElement('button');quick.className='secondary';quick.id='quick-meeting';quick.textContent='只玩一场组会';quick.disabled=!T.ready();quick.onclick=()=>{window.MEETING_MENTORS_UI.choose(A.getMenuConfig(),config=>{if(window.MEETING_MENTORS.find(config.mentorId)&&window.MEETING_DIRECTIONS.find(config.direction)){if(week){if(!window.MEETING_SAVES.archive(C.projects.find(p=>p.id===week.config.project).name+' · 第'+week.number+'周')){A.toast('未能保存暂停生涯，请先导出完整存档。');return;}A.clearSavedMeeting();week=null;save();}A.startWith(config);}});};start.before(quick);
    if(week){const btn=document.createElement('button');btn.className='primary';btn.id='resume-week';btn.textContent=`继续第${week.number}周 · ${C.weekDays[week.day]}`;btn.onclick=()=>resume();start.before(btn);}
    if($('#resume')&&week&&week.status!=='report')$('#resume').onclick=()=>resume();window.MEETING_WORLD_UI?.landing(config=>{if(config.challengeImported)return startChallenge(config);if(week&&week.status!=='report'){A.toast('先完成当前一周，再开始新的挑战。');return resume();}window.MEETING_MENTORS_UI.choose(config,startChallenge);});window.MEETING_MEDICAL_TAXONOMY_UI?.landing();window.MEETING_DISCIPLINE_TREE_UI?.landing();window.MEETING_DIRECTIONS_UI?.landing();window.MEETING_HUB_UI?.landing();window.MEETING_TIMELINE_UI?.landing();window.MEETING_EXPERIENCE_UI?.landing();
  }
  function startChallenge(config){if(week&&week.status!=='report'){A.toast('先完成当前一周，再开始同局挑战；当前进度继续保留。');resume();return;}A.clearSavedMeeting();week=W.create({...config,name:A.getMenuConfig().name,campus:true,preparation:true},config.challengeSeed,null,1);save();render();window.scrollTo(0,0);}
  function decorateMeeting(s){const ctx=s.weekContext;if(!ctx||$('.meeting-week-link'))return;const strip=document.createElement('div');strip.className='meeting-week-link';strip.innerHTML=`📅 第${ctx.number}周 · 周五组会 <span>生活与准备带来的心态 ${ctx.deltas.mood>=0?'+':''}${ctx.deltas.mood} / 底气 ${ctx.deltas.evidence>=0?'+':''}${ctx.deltas.evidence} / 时间 ${ctx.deltas.time} min</span><details><summary>这些修正来自我的哪些选择？</summary>${ctx.sourceActions.map(r=>`<p>${C.weekDays[r.day]} · ${esc(r.answer)}</p>`).join('')}</details>`;if(ctx.campus){const info=document.createElement('div');info.className='campus-meeting-cards';info.innerHTML=ctx.campus.deck.map(id=>{const c=C.workCards.find(c=>c.id===id);return `<span>${c.icon} ${c.name}</span>`;}).join('')+ctx.campus.combos.map(x=>`<span>✦ ${x}</span>`).join('');strip.append(info);}$('.run-head').after(strip);}
  window.MEETING_WEEK_UI={setResearchEmphasis:value=>{if(!week)return false;const candidate=JSON.parse(JSON.stringify(week));if(!window.MEETING_RESEARCH_AGENDA?.select(candidate,value))return false;try{localStorage.setItem(KEY,JSON.stringify(candidate));}catch{A.toast('浏览器没有保存研究侧重，选择未生效。');return false;}week.world.artifact.researchTheme=candidate.world.artifact.researchTheme;try{window.MEETING_SAVES?.schedule();}catch{}return true;},getWeek:()=>week,resume,enhanceLanding,decorateMeeting,startChallenge,onMeetingEnded:s=>{if(week&&W.completeMeeting(week,s))save();}};
  const showAlbum=$('#collection').onclick;$('#collection').onclick=()=>{showAlbum();let bar=$('#ending-filters');if(bar)bar.remove();bar=document.createElement('div');bar.id='ending-filters';bar.className='family-filter';bar.innerHTML=[['all','全部'],...Object.entries(kinds)].map(([id,name])=>`<button data-kind="${id}">${name} · ${C.endings.filter(e=>id==='all'||e.kind===id).length}</button>`).join('');$('#album-grid').before(bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#album-grid').querySelectorAll('.album-card').forEach((card,i)=>card.hidden=b.dataset.kind!=='all'&&C.endings[i].kind!==b.dataset.kind);bar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));});bar.querySelector('button').classList.add('active');};
  $('#calendar').onclick=()=>{if(!resume())A.toast('在门口选好学科，开始新的一周。');};
  document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.altKey||e.metaKey||['INPUT','TEXTAREA','BUTTON','SELECT','SUMMARY'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]')||A.getState()||!week)return;if(['1','2','3'].includes(e.key))app.querySelector(`[data-life="${Number(e.key)-1}"]`)?.click();if(e.key==='Enter')$('#life-next')?.click();});
  enhanceLanding();
})();
