window.MEETING_WEEK=(() => {
  'use strict';
  const C=window.MEETING_CONTENT,clamp=x=>Math.max(0,Math.min(100,x));
  function random(w){if(window.MEETING_LIFE_SURPRISES&&w.config.uncertainty!==false){w.rng=(w.rng+0x6D2B79F5)>>>0;let t=w.rng;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;}w.rng=(Math.imul(w.rng,1664525)+1013904223)>>>0;return w.rng/4294967296;}
  function select(w){
    window.MEETING_MIX?.select(w,random);const activeRoute=window.MEETING_MIX?.route(w)||w.config.project;
    const specific=C.lifeEvents.filter(e=>e.day===w.day&&e.slot===w.slot&&e.project===activeRoute);
    const generic=C.lifeEvents.filter(e=>e.day===w.day&&!e.project);
    let pool=window.MEETING_EXPANSION&&w.config.uncertainty!==false&&random(w)<.32?generic.filter(e=>!w.seen.includes(e.id)):specific.length?specific:generic.filter(e=>!w.seen.includes(e.id));if(!pool.length)pool=generic;
    w.eventId=pool[Math.floor(random(w)*pool.length)].id;w.seen.push(w.eventId);window.MEETING_LIFE_SURPRISES?.prepare(w,random);window.MEETING_SIDE_STORIES?.prepare(w,random);window.MEETING_WORLD?.prepare(w,random);window.MEETING_ROUTE_STORIES?.prepare(w,random);window.MEETING_PUBLICATION?.prepare(w,random);window.MEETING_ACADEMY?.prepare(w,random);
  }
  function create(config,seed=1,previous=null,number=1){
    config=window.MEETING_EXPERIENCE?.config(config)||config;config={...config,rulesVersion:config.rulesVersion||(previous?.world?.challenge&&previous?.config.challenge&&!previous?.config.rulesVersion?'08':window.MEETING_ACADEMY?'10':'09')};config=window.MEETING_MENTORS?.config(config)||config;if(window.MEETING_ACADEMY&&(!config.challenge||config.rulesVersion==='10'))config=window.MEETING_ACADEMY.config(config);const tasks=(previous?.tasks||[]).filter(t=>!t.done).map(t=>({...t}));
    const resources=previous?{energy:clamp(Math.round(previous.resources.energy*.45+40)),notes:clamp(Math.round(previous.resources.notes*.35+25)),slides:25,stress:clamp(Math.round(previous.resources.stress*.4+tasks.length*4))}:{energy:75,notes:30,slides:25,stress:20};
    const w={version:1,id:`week-${number}-${seed>>>0}`,number,seed:seed>>>0,rng:seed>>>0,config:{...config},day:0,slot:0,status:'life',resources,traits:{unfinished:tasks.length},tasks,seen:[],log:[],pending:null,eventId:'',meeting:null,reportApplied:false};window.MEETING_CAMPUS?.init(w,previous);window.MEETING_MIX?.init(w);window.MEETING_PREPARATION?.init(w,previous);window.MEETING_LIFE_SURPRISES?.init(w,previous,random);window.MEETING_MIX?.init(w);window.MEETING_GROUP?.init(w,previous,random);window.MEETING_ASSIGNMENTS?.init(w,previous,random);window.MEETING_SIDE_STORIES?.init(w,previous);window.MEETING_WORLD?.init(w,previous,random);window.MEETING_MENTORS?.advance(w,previous,random);window.MEETING_ROUTE_STORIES?.init(w,previous);window.MEETING_PUBLICATION?.init(w,previous);window.MEETING_ACADEMY?.init(w,previous,random);window.MEETING_TIMELINE?.init(w,previous);select(w);return w;
  }
  function current(w){if(w.pending&&w.presentation)return JSON.parse(JSON.stringify(w.presentation));const assignment=window.MEETING_ASSIGNMENTS?.workEvent(w),joint=window.MEETING_MIX?.jointEvent(w);if(assignment||joint)return assignment||joint;const raw=C.lifeEvents.find(e=>e.id===w.eventId)||C.campusEvents?.find(e=>e.id===w.eventId)||C.preparationEvents?.find(e=>e.id===w.eventId)||window.MEETING_LIFE_SURPRISES?.locations.find(e=>e.id===w.eventId),focused=window.MEETING_PREPARATION?.lifeEvent(w,raw)||raw;const directed=window.MEETING_DIRECTION_REVIEW?.life(w,focused)||focused;const surprised=window.MEETING_LIFE_SURPRISES?.event(w,directed)||directed,grouped=window.MEETING_GROUP?.event(w,surprised)||surprised,assigned=window.MEETING_ASSIGNMENTS?.event(w,grouped)||grouped;const story=window.MEETING_SIDE_STORIES?.event(w,assigned)||assigned;const living=window.MEETING_WORLD?.current(w,story)||story;const routed=window.MEETING_ROUTE_STORIES?.current(w,living)||living;const published=window.MEETING_PUBLICATION?.current(w,routed)||routed;const academic=window.MEETING_ACADEMY?.current(w,published)||published;return window.MEETING_MIX?.annotate(w,academic)||academic;}
  function choose(w,index){if(w.status!=='life'||w.pending)return null;const e=current(w),c=e?.choices[index];if(!c||c.academyAvailable===false||(window.MEETING_PREPARATION?.enabled(w)&&!window.MEETING_PREPARATION.lifePreview(w,e,index).available))return null;
    const effects=window.MEETING_CAMPUS?.preview(w,c)||c.effects,unlucky=c.risk?random(w)<c.risk.chance:false;
    if(unlucky)for(const [k,v] of Object.entries(c.risk.effects))effects[k]=(effects[k]||0)+v;
    const surprise=window.MEETING_LIFE_SURPRISES?.roll(w,e,c,effects,random),assignment=window.MEETING_ASSIGNMENTS?.resolve(w,e,c,effects,random),group=window.MEETING_GROUP?.resolve(w,e,c,effects,random),story=window.MEETING_SIDE_STORIES?.resolve(w,e,c,effects,random);
    const living=window.MEETING_WORLD?.resolve(w,e,c,effects,random);const routed=window.MEETING_ROUTE_STORIES?.resolve(w,e,c,effects,random);const published=window.MEETING_PUBLICATION?.resolve(w,e,c,effects,random);const academic=window.MEETING_ACADEMY?.resolve(w,e,c,effects,random);const deltas={};for(const [k,v] of Object.entries(effects)){const old=w.resources[k];w.resources[k]=clamp(old+v);deltas[k]=w.resources[k]-old;}
    for(const [k,v] of Object.entries(c.traits))w.traits[k]=(w.traits[k]||0)+v;
    const task=c.career.taskDone?w.tasks.find(t=>!t.done&&!t.prepKind):null;if(task)task.done=true;
    const record={day:w.day,slot:w.slot,eventId:e.id,title:e.title,answer:c.text,flavor:academic?.text||published?.text||routed?.text||living?.text||story?.text||assignment?.text||group?.text||surprise?.flavor||(unlucky?c.risk.flavor:c.flavor),deltas,traits:{...c.traits},career:{...c.career},taskDone:task?.title||null,unlucky:unlucky||!!surprise?.failed};record.project=c.preparationRoute||e.project||window.MEETING_MIX?.route(w)||w.config.project;if(academic)record.academy=academic;if(published)record.publication=published;if(routed)record.routeStory=routed;if(living)record.world=living;if(story)record.sideStory=story;if(assignment)record.assignment=assignment;if(group)record.group=group;if(surprise)record.liveLife=surprise;if(surprise?.id)record.surprise=surprise;window.MEETING_CAMPUS?.afterChoice(w,e,c,record);window.MEETING_PREPARATION?.afterLife(w,e,index,record);window.MEETING_WORLD?.afterLife(w,e,c,record);window.MEETING_ACADEMY?.afterLife(w,e,c,record);w.log.push(record);w.presentation=JSON.parse(JSON.stringify(e));w.pending=record;return record;
  }
  function advance(w){if(!w.pending||w.status!=='life')return false;w.pending=null;w.presentation=null;w.taskFocus=null;w.jointPlan=false;if(w.academy)w.academy.plan=null;if(w.world)w.world.focus=null;window.MEETING_CAMPUS?.nextFragment(w);
    if(w.day===4){w.status='meeting';w.surprise=null;window.MEETING_ASSIGNMENTS?.advance(w);return true;}
    if(w.slot===0){w.slot=1;}else{w.slot=0;w.day++;}
    if(w.day===7){w.day=6;w.status='report';w.surprise=null;window.MEETING_ASSIGNMENTS?.advance(w);window.MEETING_CAMPUS?.settleReport(w);return true;}window.MEETING_ASSIGNMENTS?.advance(w);select(w);return true;
  }
  function meetingContext(w){const r=w.resources,t=w.traits;
    const ctx={weekId:w.id,number:w.number,resources:{...r},traits:{...t},sourceActions:w.log.map(r=>({day:r.day,answer:r.answer,traits:{...r.traits}})),carryTasks:w.tasks.filter(t=>!t.done).map(t=>t.title),unresolvedFlaws:w.tasks.filter(t=>!t.done&&t.liveFlaw&&(window.MEETING_MIX?.routes(w)||[w.config.project]).includes(t.route)).map(t=>({...t})),deltas:{mood:Math.round((r.energy-65)*.3-(r.stress-25)*.25),evidence:Math.round((r.notes+r.slides-100)*.18),time:-Math.min(8,(t.late||0)*2)},debt:Math.min(3,Math.floor((t.promise||0)/2)+w.tasks.filter(t=>!t.done).length)};window.MEETING_CAMPUS?.context(w,ctx);window.MEETING_LIFE_SURPRISES?.context(w,ctx);window.MEETING_GROUP?.context(w,ctx);window.MEETING_ASSIGNMENTS?.context(w,ctx);window.MEETING_SIDE_STORIES?.context(w,ctx);window.MEETING_WORLD?.context(w,ctx);window.MEETING_ROUTE_STORIES?.context(w,ctx);window.MEETING_PUBLICATION?.context(w,ctx);window.MEETING_ACADEMY?.context(w,ctx);if(window.MEETING_MIX?.routes(w)){ctx.mixProjects=[...w.config.mixProjects];ctx.jointKind=w.jointKind;}return window.MEETING_PREPARATION?.context(w,ctx)||ctx;
  }
  function completeMeeting(w,s){if(s.weekContext?.weekId!==w.id||!s.ended||w.meeting)return false;
    const ending=C.endings.find(e=>e.id===s.ending);w.meeting={seed:s.seed,ending:s.ending,title:ending.title,kind:ending.kind,stats:{...s.stats},rounds:s.choicesMade,score:window.MEETING_ENGINE.score(s)};
    const titles=[];if(s.flags.debt>0)titles.push('兑现组会上答应补充的内容');if(s.stats.evidence<55)titles.push(`重新梳理${C.projects.find(p=>p.id===s.project).topics[2]}`);if(ending.kind==='failure')titles.push('复盘一个卡住的问题，把下周目标缩小');if(!titles.length)titles.push('整理这次反馈，保留下一步最想研究的问题');
    for(const title of titles)if(!w.tasks.some(t=>!t.done&&t.title===title))w.tasks.push({title,done:false,from:w.number});
    window.MEETING_CAMPUS?.afterMeeting(w,s);window.MEETING_PREPARATION?.afterMeeting(w,s);window.MEETING_UNCERTAINTY?.afterMeeting(w,s);window.MEETING_GROUP?.afterMeeting(w,s);window.MEETING_WORLD?.afterMeeting(w,s);window.MEETING_ROUTE_STORIES?.afterMeeting(w,s);window.MEETING_PUBLICATION?.afterMeeting(w,s);window.MEETING_ACADEMY?.afterMeeting(w,s);w.resources.energy=clamp(w.resources.energy-15);w.resources.stress=clamp(w.resources.stress+(ending.kind==='failure'?15:5));w.day=5;w.slot=0;w.status='life';w.pending=null;select(w);return true;
  }
  function passTime(w){if(w.status!=='life'||w.pending)return false;const record={day:w.day,slot:w.slot,eventId:w.eventId,title:'平静时段',answer:'略过这个片段，没有新增准备记录。',flavor:'时间继续，已有约定保持。',deltas:{},traits:{},career:{},timeSkipped:true};w.log.push(record);w.pending=record;return advance(w);}
  function isValid(w){return !!w&&w.version===1&&typeof w.id==='string'&&Number.isInteger(w.number)&&w.number>0&&Number.isInteger(w.rng)&&C.projects.some(p=>p.id===w.config?.project)&&Number.isInteger(w.day)&&w.day>=0&&w.day<7&&[0,1].includes(w.slot)&&['life','meeting','report'].includes(w.status)&&['energy','notes','slides','stress'].every(k=>Number.isFinite(w.resources?.[k])&&w.resources[k]>=0&&w.resources[k]<=100)&&w.traits&&Object.values(w.traits).every(v=>Number.isInteger(v)&&v>=0)&&Array.isArray(w.tasks)&&Array.isArray(w.log)&&w.log.length<=13&&Array.isArray(w.seen)&&(!w.pending||w.log.at(-1)?.eventId===w.pending.eventId)&&(!w.config.campus||window.MEETING_CAMPUS?.isValid(w.campus))&&(!w.config.preparation||window.MEETING_PREPARATION?.bookValid(w.preparation))&&(w.status!=='life'||current(w)?.day===w.day||(current(w)?.location===w.campus?.plan?.location&&w.campus.plan.day===w.day&&w.campus.plan.slot===w.slot))&&(window.MEETING_LIFE_SURPRISES?.valid(w)??true)&&(window.MEETING_MIX?.valid(w)??true)&&(window.MEETING_ASSIGNMENTS?.valid(w)??true)&&(window.MEETING_GROUP?.valid(w)??true)&&(window.MEETING_SIDE_STORIES?.valid(w)??true)&&(window.MEETING_WORLD?.valid(w)??true)&&(window.MEETING_ROUTE_STORIES?.valid(w)??true)&&(window.MEETING_MENTORS?.valid(w)??true)&&(window.MEETING_PUBLICATION?.valid(w)??true)&&(window.MEETING_ACADEMY?.valid(w)??true)&&(window.MEETING_TIMELINE?.valid(w)??true)&&(window.MEETING_EXPERIENCE?.valid(w)??true);}
  const dispatch=(w,location)=>location==='food'?window.MEETING_LIFE_SURPRISES?.food(w,random)||null:location==='friends'?window.MEETING_LIFE_SURPRISES?.friends(w,random)||null:window.MEETING_CAMPUS?.dispatch(w,location,random)||null;
  return {passTime,random,create,current,choose,advance,useLocation:dispatch,meetingContext,completeMeeting,isValid};
})();
