(() => {
  'use strict';
  const C=window.MEETING_CONTENT,W=window.MEETING_WEEK,A=window.MEETING_APP,$=s=>document.querySelector(s),app=$('#app'),KEY='meeting-survival-v3-week';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={energy:'精力',notes:'资料',slides:'幻灯片',stress:'压力'},kinds={failure:'翻车结局',funny:'滑稽结局',open:'开放结局'};
  let week=null,family='all';try{const old=JSON.parse(localStorage.getItem(KEY));if(W.isValid(old))week=old;}catch{}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(week));}catch{A.toast('浏览器没有保存这次进度，请暂时不要关闭页面。');}}
  function seed(){const x=new Uint32Array(1);crypto.getRandomValues(x);return x[0];}
  function calendar(){return `<div class="week-calendar" aria-label="本周时间线">${C.weekDays.map((d,i)=>`<div class="${i===week.day?'today':i<week.day?'past':''}"><small>${d}</small><strong>${i===4?'组会':i<4?'准备 · 生活':'反馈 · 休息'}</strong><span>${i===week.day?'● 当前':i<week.day?'✓ 已过':'· 待续'}</span></div>`).join('')}</div>`;}
  function resources(){return `<div class="week-resources">${Object.entries(labels).map(([k,l])=>`<div><span>${l}</span><strong>${week.resources[k]}</strong><i><b style="width:${week.resources[k]}%"></b></i></div>`).join('')}</div>`;}
  const effects=e=>Object.entries(e).filter(([,v])=>v).map(([k,v])=>`${labels[k]} ${v>0?'+':''}${v}`).join(' · ');
  function tasks(){return `<div class="week-tasks"><h3>组会留下的事</h3>${week.tasks.length?week.tasks.map(t=>`<p class="${t.done?'done':''}">${t.done?'✓':'○'} ${esc(t.title)} <small>第${t.from}周</small></p>`).join(''):'<p>周五还没有开会。上周的未完成事项会带到这里。</p>'}</div>`;}
  function careerEffects(record){const c=A.getCareer();for(const [k,v] of Object.entries(record.career)){if(k==='taskDone')continue;if(['boss','stats','senior'].includes(k))c.relations[k]=Math.max(0,Math.min(100,c.relations[k]+v));else if(k==='debt')c.debt=Math.max(0,c.debt+v);else if(k==='coins')c.coins+=v;}A.persistCareer();}
  function render(){if(!week)return;A.clearView();const p=C.projects.find(p=>p.id===week.config.project);
    let body='';
    if(week.status==='life'){
      const e=W.current(week),q=week.pending;
      body=`<section class="life-scene"><p class="eyebrow">${week.day<4?'BEFORE FRIDAY':'LIFE AFTER THE MEETING'} / ${C.weekDays[week.day]} · ${week.slot?'下半天':'上半天'}</p><span class="life-icon">${week.day<4?'☕':week.day===4?'🎒':'🌿'}</span><h1>${esc(e.title)}</h1><p>${esc(e.scene)}</p>${week.day===5&&week.meeting?`<div class="week-context">昨天的组会：「${esc(week.meeting.title)}」<br>底气 ${week.meeting.stats.evidence} · 撑过 ${week.meeting.rounds} 回合。反馈已经进入待办。</div>`:''}</section><section class="life-options">${q?`<div class="feedback"><p class="eyebrow">这件事留下了后果</p><h3>${esc(q.answer)}</h3><p>${esc(q.flavor)}</p><p class="life-effects">${effects(q.deltas)}</p>${q.taskDone?`<p>✓ 已处理：${esc(q.taskDone)}</p>`:''}<button class="primary" id="life-next">${week.day===4?'准备进入组会':week.day===6&&week.slot===1?'看看这一周':'时间往前走'} →</button></div>`:e.choices.map((c,i)=>`<button class="life-choice" data-life="${i}"><small>0${i+1}</small><strong>${esc(c.text)}</strong><span>${effects(c.effects)}</span></button>`).join('')}<p class="week-hint">精力与压力影响心态；资料与幻灯片影响底气。迟到缩短组会时间，承诺和未完成事项变成解释债。</p></section>`;
    }else if(week.status==='meeting'){
      const ctx=W.meetingContext(week);body=`<section class="life-scene"><p class="eyebrow">FRIDAY / 准备进入会议室</p><span class="life-icon">🎤</span><h1>这一周，现在轮到你讲了。</h1><p>你的准备、熬夜、合作和承诺，会一起走上讲台。</p><div class="week-context">本周入场修正：心态 ${ctx.deltas.mood>=0?'+':''}${ctx.deltas.mood} · 底气 ${ctx.deltas.evidence>=0?'+':''}${ctx.deltas.evidence} · 时间 ${ctx.deltas.time} min<br>额外解释债 ${ctx.debt} 笔。角色、难度、导师风格也会影响初始状态。</div></section><section class="life-options"><button class="primary" id="enter-friday">进入周五组会 ↗</button><p class="week-hint">组会仍然不限十回合。失败后也继续过周末，下一周还能再来。</p><details class="week-history"><summary>回看本周入场前的选择</summary>${week.log.map(r=>`<p>${C.weekDays[r.day]} · ${esc(r.answer)}</p>`).join('')}</details></section>`;
    }else{
      body=`<section class="life-scene"><p class="eyebrow">SUNDAY / 本周生活报告</p><span class="life-icon">📒</span><h1>一周结束，故事还开着。</h1><p>${esc(week.config.name)}，这周你做了 ${week.log.length} 次日常选择。${week.meeting?`周五解锁「${esc(week.meeting.title)}」。`:'组会记录暂未生成。'}</p><div class="week-context">${week.meeting?kinds[week.meeting.kind]+' · 本场评分 '+week.meeting.score+'/100':''}<br>未完成 ${week.tasks.filter(t=>!t.done).length} 件事，会进入下一周；处理过的任务保持完成。</div></section><section class="life-options"><button class="primary" id="next-week">继续第 ${week.number+1} 周 ↗</button><button class="secondary" id="week-config">回门口换个学科 / 人设</button><details class="week-history" open><summary>这一周的生活轨迹</summary>${week.log.map(r=>`<p><small>${C.weekDays[r.day]}</small> ${esc(r.answer)}${r.taskDone?' ✓ 已处理一项遗留':''}</p>`).join('')}</details></section>`;
    }
    app.innerHTML=`<div class="run-head"><div><p class="eyebrow">WEEK ${week.number} / ${p.icon} ${p.name}</p><h2>${esc(week.config.name)}的一周</h2></div><button class="plain" id="week-door">回到门口 · 自动保存</button></div>${calendar()}${resources()}<div class="week-board">${body}</div>${tasks()}<div class="week-bottom"><button class="secondary" id="life-shop">逛逛补给站</button><small>游戏中的一周不跟随现实时间。随时停下，下次接着过。</small></div>`;
    app.querySelectorAll('[data-life]').forEach(b=>b.onclick=()=>{const r=W.choose(week,Number(b.dataset.life));if(!r)return;careerEffects(r);save();render();});
    if($('#life-next'))$('#life-next').onclick=()=>{if(W.advance(week)){save();render();}};
    if($('#enter-friday'))$('#enter-friday').onclick=()=>{if(!A.restoreMeeting(week.id))A.startWith(week.config,W.meetingContext(week));};
    if($('#next-week'))$('#next-week').onclick=()=>{if(!week.reportApplied){const career=A.getCareer();career.weeks=Math.max(career.weeks||0,week.number);week.reportApplied=true;A.persistCareer();save();}week=W.create(week.config,seed(),week,week.number+1);save();render();window.scrollTo(0,0);};
    if($('#week-config'))$('#week-config').onclick=A.landing;$('#week-door').onclick=A.landing;$('#life-shop').onclick=A.showShop;
  }
  function resume(id){if(!week||(id&&id!==week.id))return false;if(week.status==='meeting'&&A.restoreMeeting(week.id))return true;render();window.scrollTo(0,0);return true;}
  function enhanceLanding(){const start=$('#start');if(!start)return;
    const copy=$('.hero-copy');copy.innerHTML='先过完一周，再去活着散会。<br>周一到周日都有故事，周五会记得你前几天的选择。';
    const head=$('.discipline-head');const filters=document.createElement('div');filters.className='family-filter';filters.setAttribute('aria-label','按学科门类筛选');filters.innerHTML=[{id:'all',name:'全部 · 36条路线'},...C.families].map(f=>`<button data-family="${f.id}" class="${family===f.id?'active':''}">${f.name}</button>`).join('');head.after(filters);
    const filter=()=>{app.querySelectorAll('[data-project]').forEach(b=>b.hidden=family!=='all'&&C.projects.find(p=>p.id===b.dataset.project).family!==family);filters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.family===family));};filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{family=b.dataset.family;filter();});filter();
    start.textContent='开始新的一周 ↗';start.onclick=()=>{if(week&&week.status!=='report'){A.toast('这一周还没过完，先继续当前一周；结束后可以换配置。');resume();return;}const number=Math.max(A.getCareer().weeks||0,week?.number||0)+1;week=W.create(A.getMenuConfig(),seed(),week,number);save();render();window.scrollTo(0,0);};
    const quick=document.createElement('button');quick.className='secondary';quick.id='quick-meeting';quick.textContent='只玩一场组会';quick.onclick=()=>{if(week&&week.status!=='report'){A.toast('请先完成当前一周，避免覆盖周五的组会记录。');return;}A.startWith(A.getMenuConfig());};start.before(quick);
    if(week){const btn=document.createElement('button');btn.className='primary';btn.id='resume-week';btn.textContent=`继续第${week.number}周 · ${C.weekDays[week.day]}`;btn.onclick=()=>resume();start.before(btn);}
    if($('#resume')&&week&&week.status!=='report')$('#resume').onclick=()=>resume();
  }
  function decorateMeeting(s){const ctx=s.weekContext;if(!ctx||$('.meeting-week-link'))return;const strip=document.createElement('div');strip.className='meeting-week-link';strip.innerHTML=`📅 第${ctx.number}周 · 周五组会 <span>前四天带来的心态 ${ctx.deltas.mood>=0?'+':''}${ctx.deltas.mood} / 底气 ${ctx.deltas.evidence>=0?'+':''}${ctx.deltas.evidence} / 时间 ${ctx.deltas.time} min</span><details><summary>这些修正来自我的哪些选择？</summary>${ctx.sourceActions.map(r=>`<p>${C.weekDays[r.day]} · ${esc(r.answer)}</p>`).join('')}</details>`;$('.run-head').after(strip);}
  window.MEETING_WEEK_UI={resume,enhanceLanding,decorateMeeting,onMeetingEnded:s=>{if(week&&W.completeMeeting(week,s))save();}};
  const showAlbum=$('#collection').onclick;$('#collection').onclick=()=>{showAlbum();let bar=$('#ending-filters');if(bar)bar.remove();bar=document.createElement('div');bar.id='ending-filters';bar.className='family-filter';bar.innerHTML=[['all','全部'],...Object.entries(kinds)].map(([id,name])=>`<button data-kind="${id}">${name} · ${C.endings.filter(e=>id==='all'||e.kind===id).length}</button>`).join('');$('#album-grid').before(bar);bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#album-grid').querySelectorAll('.album-card').forEach((card,i)=>card.hidden=b.dataset.kind!=='all'&&C.endings[i].kind!==b.dataset.kind);bar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));});bar.querySelector('button').classList.add('active');};
  $('#calendar').onclick=()=>{if(!resume())A.toast('在门口选好学科，开始新的一周。');};
  document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.altKey||e.metaKey||['INPUT','TEXTAREA','BUTTON','SELECT','SUMMARY'].includes(document.activeElement?.tagName)||document.querySelector('dialog[open]')||A.getState()||!week)return;if(['1','2','3'].includes(e.key))app.querySelector(`[data-life="${Number(e.key)-1}"]`)?.click();if(e.key==='Enter')$('#life-next')?.click();});
  enhanceLanding();
})();
