/* Canonical fictional geography and institutions; reading this material creates no gameplay state. */
window.MEETING_WORLD_SETTING=(()=>{
 const N=window.MEETING_NARRATIVE_WORLD,P=N.pair;
 const institutions=[
 ['东澜省',1906,'东滨大学城与老城校区','综合研究型大学。医学院、理学院、人文学院与工学院并存，共享平台集中在新校区。','Donglan Province','A comprehensive university with medical, science, humanities and engineering schools; shared facilities are on the new campus.'],
 ['岭北省',1952,'岭州旧港校区与工业园校区','由工科院校发展而来，计算、材料、装备与环境研究较强；企业合作多，验收与课程安排常冲突。','Lingbei Province','A technology university with computing, materials, equipment and environmental research; partner reviews often collide with teaching.'],
 ['岭北省',1918,'北原南山校区与市区资料中心','综合大学。基础理论、历史文献、法学与生命研究各有团队，跨院借阅便利，跨院经费仍要分别申请。','Lingbei Province','A comprehensive university spanning foundations, historical sources, law and life sciences; cross-school access does not merge budgets.'],
 ['东澜省',1957,'海临医学校区与湾东合作院区','医科大学，设临床、基础、药学、公共卫生、护理、口腔与康复相关学院；附属医院的诊疗排班优先。','Donglan Province','A medical university with clinical, basic, pharmacy, public health, nursing, dental and rehabilitation schools; clinical shifts take priority.'],
 ['江沅省',1931,'江沅老校区与西城教学基地','师范大学。教育、心理、语言、历史、艺术及基础理科并存，学校合作、档案借阅与公开展演有不同的窗口。','Jiangyuan Province','A normal university combining education, psychology, languages, history, arts and basic sciences, each with distinct partner windows.'],
 ['江沅省',1946,'广临河西校区与科教园','综合大学。工农医与经济管理发展较快，也保留人文团队；不同学院的设备预算差异明显。','Jiangyuan Province','A comprehensive university with engineering, agriculture, medicine, management and humanities; equipment budgets differ by school.'],
 ['诺文',1889,'诺德林主校区与北港研究园','海外综合研究型大学。冬季短日照与暑期休假影响排期，来访人员往往只参与一个项目阶段。','Norven','An overseas comprehensive research university; winter light and summer leave shape visiting projects.'],
 ['卡文',1948,'北卡文滨海研究站与市区办公室','独立研究院，以跨机构项目与专题访问为主。研究院访问经历不等于获得研究院学位。','Caven','An independent research institute focused on interinstitutional projects and visits; a visit is not a degree.'],
 ['维斯',1894,'维斯登市区校区与中央资料馆','海外综合大学，文献、社会研究与定量方法交流活跃；资料预约与访问期限各自管理。','Wis','An overseas comprehensive university with source studies, social research and quantitative methods; access and visit terms are managed separately.'],
 ['洛恩',1912,'洛斯顿大学园与创新园','海外理工大学，计算与工程团队常使用开放工位和项目合同。项目结束后，账号、设备和工位需要交回。','Lorn','An overseas technology university with project contracts and open workspaces; access and equipment return when projects end.']
 ];
 institutions.forEach(([region,founded,campus,desc,enRegion,enDesc],i)=>Object.assign(N.schools[i],{region:P(region,enRegion),founded,campus:P(campus,`${N.english(N.cities[i].name)} campuses and research facilities`),profile:P(desc,enDesc)}));
 const departments={philosophy:['哲学系','Department of Philosophy'],economics:['经济学院','School of Economics'],law:['法学院','School of Law'],education:['教育学院','School of Education'],literature:['语言文学学院','School of Language and Literature'],history:['历史学院','School of History'],science:['理学院','School of Science'],engineering:['工学院','School of Engineering'],agriculture:['农学院','School of Agriculture'],management:['管理学院','School of Management'],military:['国防与公共安全研究中心','Centre for Defence and Public Safety Studies'],arts:['艺术学院','School of Arts'],interdisciplinary:['交叉学科研究院','Institute of Interdisciplinary Studies'],clinical:['临床医学院','School of Clinical Medicine'],pharmacy:['药学院','School of Pharmacy'],publichealth:['公共卫生学院','School of Public Health'],nursing:['护理学院','School of Nursing'],dental:['口腔医学院','School of Dentistry'],rehabilitation:['康复医学院','School of Rehabilitation Medicine'],basicmedicine:['基础医学院','School of Basic Medical Sciences']};
 Object.values(departments).forEach(x=>P(...x));
 function department(route){const p=window.MEETING_CONTENT.projects.find(p=>p.id===route),key=p?.family==='medicine'?N.journalKey(route):p?.family;return (departments[key]||departments.interdisciplinary)[0];}
 const sections=[
 ['这是什么地方？','Where are we?','故事发生在2026年前后的虚构现代大学世界。国内地区称宁华，分为东澜、岭北和江沅三个主要大学区；海外交流通向诺文、卡文、维斯和洛恩。人物都在这套环境中工作，但公开简介与当周实际余量并不相同。','A fictional modern university world around 2026. Ninghua has three main university regions, with exchanges to Norven, Caven, Wis and Lorn. Public biographies do not guarantee weekly availability.'],
 ['学校与学科怎么对应？','How do universities and disciplines connect?','大学提供组织背景，学院承接招生，导师负责1—3个具体子方向，课题组再与医院、平台、资料馆或企业合作。你选择的是研究方向和导师，不是学校排名。各校的院系并不完全相同，相同学科也可能落在不同学院。','Universities provide institutional context, schools admit students, supervisors cover one to three directions, and groups work with external partners. Choices concern research and supervision rather than rankings.'],
 ['一个组的日常','Life inside a group','导师有课程、申请、会议和评审；高年级同门有修稿、答辩和求职，新生会逐步学会独立做事。临时帮忙、借用和合作可能留下下一周的约定。毕业的人会离组并留下年鉴，新人再听到他们的故事。','Supervisors teach and apply for support; seniors revise, defend and seek jobs; newcomers learn independence. Loans and collaborations persist, graduates leave, and newcomers hear their stories.'],
 ['资源与经费','Resources and funding','宁华研究资助署管理基础研究项目，社会与教育研究基金理事会支持人文社科，各大学另设青年项目和小额种子基金。平台、医院与企业还有自己的流程。游戏里的资源余量是抽象指标，不等于银行余额；项目多也不保证设备当天可用。','Fictional national, social-science and university funds coexist with platform and partner procedures. The resource score is abstract, not a bank balance; more projects do not guarantee same-day equipment.'],
 ['一周与一个学位','A week and a degree','周一到周四准备，周五汇报，周末处理反馈或生活。普通一周包含13个生活片段与一场组会。硕士与博士的游戏时间线约为156与208周；一周、一个月或一年体验只是结算节点，开题、中期和毕业另有要求。','Monday to Thursday are for preparation, Friday for a meeting, and weekends for life and follow-up. A normal week has thirteen life slots and one meeting; degree stages span about 156 or 208 weeks, independently of short play sessions.'],
 ['成果如何流动？','How does work become a paper?','实际准备留下线索与核对记录，当前方向和课题版本决定它们能回答什么。达到要求后整理成稿，选择相应领域的期刊，经历初筛、外审、修改、修回和可能的接收。旧稿保留自己的材料快照，新课题从草稿开始。','Preparation creates clues and checked records tied to a direction and version. Eligible work becomes a manuscript with screening, review, revision and possible acceptance. Old papers retain their snapshot; new projects begin fresh.'],
 ['期刊和会议','Journals and conferences','校级学报、领域研究刊物和国际交流刊物采用不同范围；各专业会显示适合本领域的名称。分区为游戏内难度标签，评审等待在玩法中经过压缩。会议有专题报告、海报和讨论，摘要入选与全文接收分别处理。','University journals, specialist journals and international venues have distinct scopes. Names follow the subject. Bands are fictional difficulty labels, review times are compressed, and conference abstract selection is separate from paper acceptance.'],
 ['合作与署名','Collaboration and authorship','合作先说清分工，再记录实际贡献，最后讨论文章主线和署名。介绍材料、提供资源、实际分析和写作是不同贡献。对方退出或不同意结论时，可能拆稿、交回任务或继续小范围合作。','Agree on roles, record actual contributions and then discuss the argument and authorship. Introductions, resources, analysis and writing differ; disagreement can lead to divided papers or narrower collaboration.'],
 ['失败以后','After a setback','退稿、检查没通过和资源中断都会保留记录。可以转投、补救、延期、缩小问题或换方向，也可以选择结束这一段。失败不自动变成成功，新的结果要靠后续行动；滑稽结局会留下传说，却不会补出研究证据。','Rejection, failed reviews and lost resources remain recorded. Retarget, repair, delay, narrow, pivot or stop. New outcomes require action; funny legends create no research evidence.'],
 ['校园之外','Beyond research','食堂、图书馆、周末桌游、乐队与校猫属于同一个生活世界。朋友有自己的下班时间，志愿者有轮值，团体活动会错过或延期。休息可以只是休息，不需要每次都转化成合作灵感。','Dining halls, libraries, games, bands and campus cats share the same world. Friends have work hours and volunteers have shifts. Rest can simply be rest.'],
 ['去海外的一段经历','A period abroad','联合培养、访问研究、项目聘用与完整学位是不同经历。学期、假期、合同和时差影响沟通，返回以后旧合作也可能继续。导师主页分别写出学位学校、合作地点与任职单位，不能把几个月访问算成海外学位。','Joint training, visits, project employment and full degrees differ. Terms, holidays, contracts and time zones shape work, and collaborations may continue after return. Profiles separate degree, visit and appointment institutions.'],
 ['阅读与实际玩法','Reading and actual play','手册描述世界的组织和来历。具体开局仍由所选导师、方向、剧本和随机事件决定。阅读不会推进日期、提高信任、生成准备记录或改写存档；更长的编辑设定与期刊目录随离线包一起提供。','The handbook explains the setting. Actual runs depend on supervision, direction, scenario and events. Reading advances no time and creates no trust, records or save changes. The full setting and journal catalog are included in the source package.']
 ].map(([title,enTitle,text,enText])=>({title:P(title,enTitle),text:P(text,enText)}));
 const organizations=[['宁华研究资助署','Ninghua Research Funding Agency'],['社会与教育研究基金理事会','Council for Social and Educational Research Funding'],['诺德林学术出版集团','Nordlin Academic Publishing Group'],['宁华学术交流联合会','Ninghua Academic Exchange Association']].map(x=>P(...x));
 for(const [kind,list]of Object.entries(N.journals))for(const [i,j]of list.entries()){const host=N.schools.find(s=>j.name.includes(s.name));j.publisher=i===2?organizations[2]:host?host.name+'学报编辑部':organizations[3]+' · 专业编辑委员会';j.frequency=P(i===0?'双月刊':i===1?'季刊':'月刊',i===0?'Bimonthly':i===1?'Quarterly':'Monthly');}
 return {version:1,sections,department,organizations,institutions:N.schools};
})();
