const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..'),box={window:{}};vm.createContext(box);
for(const f of ['content.js','content-expand.js','content-disciplines.js','content-v03.js','content-cast-v08.js','content-week.js','campus-content.js','campus-engine.js','preparation.js','uncertainty.js','life-surprise-content.js','cast-surprises-v08.js','life-surprises.js','content-expansion-v06.js','cross-discipline.js','group-dynamics.js','assignments.js','side-stories.js','living-world.js','research-directions.js', 'research-directions-extra.js','engine.js','week-engine.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),box);
const {MEETING_CONTENT:C,MEETING_WORLD:X,MEETING_WEEK:W,MEETING_ENGINE:E,MEETING_PREPARATION:P,MEETING_ASSIGNMENTS:A}=box.window,copy=x=>JSON.parse(JSON.stringify(x)),base={project:'data',role:'newbie',difficulty:'normal',persona:'random',preparation:true,campus:true,challenge:true,challengeSeed:7654},types=new Set(),modeDigests=new Set();let actions=0,questions=0,weeks=0;
function isolated(seed=5){const w=W.create({...base,playMode:'normal'},seed);w.group.news.handled=true;w.assignments.offers=[];w.sideStories.plan=null;w.sideStories.active=null;w.surprise=null;w.world.plan=null;return w;}
function select(w,type,id,action,rand=()=>.2){w.sideStories.plan=null;w.world.plan=X.event(w,type,id,rand);const e=W.current(w),i=e.choices.findIndex(c=>c.worldAction===action);assert(i>=0,e.id+' missing '+action);return W.choose(w,i);}
// Unconfirmed messages carry delayed costs; checking can yield an unresolved answer and never guarantees truth.
for(const truth of [true,false]){const w=isolated();select(w,'message','cancel','believe',()=>truth?.2:.8);const m=w.world.messages.at(-1);assert.equal(m.truth,truth);assert.equal(m.status,'believed');assert.equal(w.world.queue.length,1);assert(!W.choose(w,0));W.advance(w);w.sideStories.plan=null;w.world.queue[0].due=X.tick(w);X.prepare(w,()=>.2);const e=W.current(w);assert.equal(e.worldType,'settle');const r=W.choose(w,e.choices.findIndex(c=>c.worldAction==='repair'));assert(r);assert(w.world.queue[0].done);if(!truth)assert(r.deltas.stress>0);}
{const w=isolated();w.world.plan=X.event(w,'message','deadline',()=>.2);const e=W.current(w),c=e.choices.find(c=>c.worldAction==='check');const r=X.resolve(w,e,c,{...c.effects},()=>.99);assert.equal(w.world.messages.at(-1).status,'unresolved');assert(!r.text.includes('证实'));}
// Booking creates no reading source; actually attending consumes a later fragment; expiry applies without pressing a button.
{const w=isolated();const before=w.preparation.sources.length;select(w,'opportunity','archive','reserve');assert.equal(w.preparation.sources.length,before);const o=w.world.opportunities.at(-1);assert.equal(o.status,'reserved');W.advance(w);assert(X.dispatch(w,o.id));const e=W.current(w);assert.equal(e.worldType,'opportunity-work');W.choose(w,e.choices.findIndex(c=>c.worldAction==='attend'));assert(['completed','interrupted'].includes(o.status));assert.equal(w.log.length,2);assert.equal(w.log[1].eventId,e.id);assert(o.receipt);}
{const w=isolated();select(w,'opportunity','workshop','reserve');const o=w.world.opportunities.at(-1);o.deadline=-1;X.expire(w);assert.equal(o.status,'expired');assert.equal(X.dispatch(w,o.id),false);}
// An unshown prepared event leaves no visible or actionable opportunity. Current and reload never reroll choices.
{const w=isolated();w.world.plan=X.event(w,'opportunity','mentor',()=>.2);assert.equal(w.world.opportunities.at(-1).status,'unseen');assert.equal(X.dispatch(w,w.world.opportunities.at(-1).id),false);const before=JSON.stringify(w);for(let i=0;i<12;i++){assert.deepEqual(copy(W.current(w)),copy(W.current(copy(w))));}assert.equal(JSON.stringify(w),before);}
// Project work is version-bound; old general reading does not unlock a fresh artifact after pivot.
{const w=isolated();select(w,'project','artifact','verify');const p=w.world.artifact;W.advance(w);p.checks=[{version:p.version,route:p.route,kind:'record',level:2,week:1,eventId:'real-current',action:'checked'}];p.status='checked';let s=E.create({...base,seed:1,weekContext:W.meetingContext(w)});s.eventId='world-research-question';assert(X.question(s).choices[0].prepared.available);select(w,'project','artifact','pivot');assert.equal(p.version,2);assert.equal(p.checks.length,0);s=E.create({...base,seed:1,weekContext:W.meetingContext(w)});s.eventId='world-research-question';assert.equal(E.current(s).choices.find(c=>c.worldAnswer==='receipt').prepared.available,false);assert(w.preparation.sources.length>0);W.advance(w);assert(X.projectDispatch(w));assert.equal(W.current(w).worldType,'project');}
// Exact group members remember concrete helping and handoff, and their own goal changes the corresponding examiner.
{const w=isolated(),id=w.group.members[0].id;select(w,'npc',id,'handoff');assert.equal(w.world.npcs[id].memory[0].action,'handoff');w.world.npcs[id].goal='teach';w.world.npcs[id].mood=-1;const s=E.create({...base,seed:1,weekContext:W.meetingContext(w)});assert.equal(s.live.profiles.boss.preference,'brief');}
// Choices change the future event pool, with the same scheduler draw and a different learned route.
{const a=isolated(),b=copy(a);a.world.paths.careful=30;b.world.paths.rest=30;const rand=()=>.98;a.world.mode=b.world.mode='absurd';// choose channel with independent fixed draws
const ea=X.event(a,'channel','careful',rand),eb=X.event(b,'channel','rest',rand);assert.notEqual(ea.title,eb.title);a.world.mode=b.world.mode='normal';function sequence(){const v=[.01,.99,.2,.3,.4,.5,.6,.7];let i=0;return ()=>v[i++%v.length];}a.day=b.day=1;X.prepare(a,sequence());X.prepare(b,sequence());assert.equal(a.world.plan.worldType,'channel');assert.equal(b.world.plan.worldType,'channel');assert.notEqual(a.world.plan.worldId,b.world.plan.worldId);}
// Codes validate all config fields. Reports compare only matching independent challenge runs and reject oversized/unrelated input.
{const w=isolated(),code=X.code(w),c=X.parse(code);assert(c);assert.equal(c.challengeSeed,w.world.root);assert.equal(X.parse(code.replace('LM08','LM07')),null);assert.equal(X.parse(code.replace(String(w.world.root),'4294967296')),null);const l=X.report(w),r=copy(l);assert.equal(X.compare(l,r).differences.length,0);r.choices=[{eventId:'different',answer:'different'}];assert.equal(X.compare(l,r).first.index,0);r.code+='x';assert.equal(X.compare(l,r),null);r.code=l.code;r.challenge=false;assert.equal(X.compare(l,r),null);}
// All seven modes run through actual life/meeting/weekend, carrying their own project, debts and delayed consequences.
for(const mode of X.modes)for(let seed=1;seed<=12;seed++){
 let previous=null;const config=X.config({...base,playMode:mode.id,challengeSeed:seed},seed);
 for(let number=1;number<=3;number++){
  const w=W.create(config,number===1?seed:X.derive(seed,number),previous,number);if(number===1&&mode.id==='poor')assert.equal(w.group.balance,8);
  for(let safety=0;w.status!=='report'&&safety<220;safety++){
   assert(W.isValid(w),mode.id+' '+number+' '+w.status+' '+W.current(w)?.id);if(w.pending){W.advance(w);A.drain(w);continue;}
   if(w.status==='meeting'){
    const ctx=W.meetingContext(w),s=E.create({...config,seed:X.derive(seed,number,1),career:w.world.runCareer,weekContext:ctx}),cloned=copy(s);
    for(let i=0;!s.ended&&i<180;i++){assert(E.isValid(s));if(s.pending){assert(E.advance(s));assert(E.advance(cloned));assert.equal(JSON.stringify(s),JSON.stringify(cloned));continue;}const e=E.current(s);if(e.id==='world-research-question')questions++;const choices=e.choices.map((c,i)=>({c,i})).filter(x=>x.c.prepared?.available!==false&&!x.c.hardStop),pick=choices[(seed+i)%choices.length].i;const r=E.choose(s,pick),r2=E.choose(cloned,pick);assert.deepEqual(copy(r),copy(r2));assert.equal(JSON.stringify(s),JSON.stringify(cloned));}
    assert(s.ended);assert(W.completeMeeting(w,s));assert(w.world.queue.some(q=>q.type==='echo'));continue;
   }
   const e=W.current(w);if(e.worldType)types.add(e.worldType);const available=e.choices.map((c,i)=>({c,i})).filter(x=>P.lifePreview(w,e,x.i).available),pick=available[(seed+safety)%available.length].i,clone=copy(w),snapshot=JSON.stringify(w);assert.deepEqual(copy(e),copy(W.current(w)));assert.equal(JSON.stringify(w),snapshot);const r=W.choose(w,pick),r2=W.choose(clone,pick);assert(r);assert.deepEqual(copy(r),copy(r2));assert.equal(JSON.stringify(w),JSON.stringify(clone));actions++;
  }
  assert.equal(w.status,'report');assert.equal(w.log.length,13);assert(X.valid(w));assert.equal(X.report(w).choices.length,number*13);modeDigests.add(mode.id+':'+w.log.map(r=>r.eventId).join(','));previous=w;weeks++;
 }
}
assert(types.size>=7);assert(questions>0);assert.equal(C.endings.length,352);const result={passed:true,modes:X.modes.length,weeks,lifeActions:actions,meetingProjectQuestions:questions,eventTypes:[...types],endingCount:C.endings.length,deterministicLifeAndMeetings:true,versionBoundProject:true,delayedConsequences:true,expiry:true,independentChallenge:true};fs.writeFileSync(path.join(root,'.qa/world-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
