/* Real browser interactions on an isolated test origin; no existing player profile is opened. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=path.resolve(__dirname,'..'),out=path.join(root,'.qa/'+(process.env.BROWSER_FAMILIES?'browser-'+process.env.BROWSER_FAMILIES.split(',')[0]:'browser'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(e,bytes)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(bytes);});});
let browser;const errors=[],checks=[];let clicks=0;
async function click(page,selector){await page.locator(selector).first().click({timeout:6000});clicks++;}
async function closeDaily(page){if(await page.locator('#daily-event-dialog[open]').count())await click(page,'#daily-event-dialog .close');}
async function lifeStep(page){
 if(!await page.locator('dialog[open]').count()&&await page.locator('#open-daily-event').count())await click(page,'#open-daily-event');
 if(await page.locator('#life-next:visible').count()){const before=await page.evaluate(()=>{const w=window.MEETING_WEEK_UI.getWeek();return w.day+':'+w.slot+':'+w.status+':'+w.clock?.minute;});await click(page,'#life-next');const after=await page.evaluate(()=>{const w=window.MEETING_WEEK_UI.getWeek();return w.day+':'+w.slot+':'+w.status+':'+w.clock?.minute;});assert.notEqual(after,before,'time advances');return 'advance';}
 if(await page.locator('[data-life]:visible:enabled').count()){await click(page,'[data-life]:visible:enabled');assert(await page.locator('#life-next:visible').count(),'choice reveals a consequence');return 'choice';}
 if(await page.locator('#enter-friday:visible').count()){await click(page,'#enter-friday');return 'meeting';}
 if(await page.locator('[data-choice]:enabled').count()){await click(page,'[data-choice]:enabled');return 'answer';}
 if(await page.locator('#next').count()){await click(page,'#next');return 'question';}
 if(await page.locator('#continue-career').count()){await click(page,'#continue-career');return 'weekend';}
 if(await page.locator('#next-week:visible').count())return 'report';
 throw Error('No usable next step: '+await page.locator('button:visible').allTextContents());
}
async function context(viewport={width:1365,height:900}){const ctx=await browser.newContext({viewport,serviceWorkers:'block',acceptDownloads:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.stack));await p.goto(base,{waitUntil:'load'});if(await p.locator('#guide-skip').count())await click(p,'#guide-skip');return {ctx,p};}
let base;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 // Tutorial, keyboard controls and repeatable close/reopen.
 {const ctx=await browser.newContext(),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.stack));await p.goto(base);for(let i=0;i<7;i++)await click(p,'#guide-next');assert(!await p.locator('#beginner-guide[open]').count());await click(p,'#guide-replay');await click(p,'#guide-close');await ctx.close();checks.push('seven tutorial steps and replay');}
 {const {ctx,p}=await context({width:390,height:844});const before=await p.evaluate(()=>JSON.stringify({...localStorage}));await click(p,'#world-handbook-open');for(let i=0;i<14;i++){await click(p,'[data-world-page="'+i+'"]');assert(await p.locator('.world-handbook-reading').innerText());assert(await p.evaluate(()=>document.querySelector('#world-handbook').scrollWidth<=document.querySelector('#world-handbook').clientWidth+2));}await click(p,'#world-handbook .close');assert.equal(await p.evaluate(()=>JSON.stringify({...localStorage})),before);checks.push('14 world handbook pages, responsive and no save changes');await ctx.close();}
 const families=['philosophy','economics','law','education','literature','history','science','engineering','agriculture','medicine','military','management','arts','interdisciplinary'];
 const chosenFamilies=process.env.BROWSER_FAMILIES?process.env.BROWSER_FAMILIES.split(','):families;
 for(const [unused,family]of (process.env.BROWSER_ACTIONS_ONLY?[]:chosenFamilies).entries()){const i=families.indexOf(family);assert(i>=0);
  const {ctx,p}=await context(i%2?{width:390,height:844}:{width:1365,height:900});await click(p,'[data-feature-set="'+(['simple','medium','full'][i%3])+'"]');await p.locator('#meeting-cadence').selectOption('1');await click(p,'[data-family="'+family+'"]');
  await click(p,family==='medicine'?'[data-medical-primary]':'[data-primary]');await click(p,family==='medicine'?'[data-medical-secondary]':'[data-secondary]');await click(p,family==='medicine'?'#medical-to-mentor':'#discipline-mentor');
  assert(await p.locator('[data-faculty]').count(),'faculty available for '+family);await click(p,'#faculty-random');assert(!await p.locator('#faculty-confirm').isDisabled(),'random selection gives a confirmable direction');
  assert(await p.locator('.faculty-identity').textContent());assert(await p.locator('.faculty-timeline li').count()>=5);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'no page overflow '+family);
  if(['medicine','literature','engineering'].includes(family)){await p.screenshot({path:path.join(out,'faculty-'+family+'.png'),fullPage:true});if(family==='medicine'){await p.locator('#toast.visible').waitFor({state:'hidden',timeout:8000});await p.locator('.faculty-detail').evaluate(el=>el.scrollIntoView({behavior:'instant',block:'start'}));await p.screenshot({path:path.join(root,'docs/mentor-mobile-v147.png')});}}
  await click(p,'#faculty-confirm');assert(await p.locator('#open-daily-event').count());await p.reload();await click(p,'#calendar');assert(await p.locator('#open-daily-event').count(),'saved week reopens');
  await closeDaily(p);await click(p,'[data-hub-entry="planning"]');assert(await p.locator('#life-planning').isVisible());await click(p,'[data-life-hub="home"]');
  await click(p,'#checkpoint-now');await click(p,'[data-timeline-action="0"]');await click(p,'#save-center');const downloadPromise=p.waitForEvent('download');await click(p,'#backup-export');const download=await downloadPromise;await download.saveAs(path.join(out,'save-'+family+'.json'));await click(p,'#save-close');
  let done=false;for(let n=0;n<500;n++){if(await lifeStep(p)==='report'){done=true;break;}}assert(done,'complete week '+family);assert(await p.evaluate(()=>window.MEETING_WEEK_UI.getWeek().log.length>30));assert(await p.evaluate(()=>window.MEETING_WEEK.isValid(window.MEETING_WEEK_UI.getWeek())));checks.push('natural week, random mentor, save and resume: '+family);
  if(family==='medicine')await p.screenshot({path:path.join(out,'week-report-mobile.png'),fullPage:true});await ctx.close();console.log('browser family passed',family);
 }
 // Reproduce the empty candidate bug in the custom two-discipline branch.
 {const {ctx,p}=await context();await click(p,'[data-family="interdisciplinary"]');await click(p,'[data-primary="catalog-custom"]');await click(p,'[data-secondary]');await click(p,'#discipline-mentor');await click(p,'#faculty-random');assert(!await p.locator('#faculty-confirm').isDisabled());await click(p,'#faculty-confirm');const config=await p.evaluate(()=>window.MEETING_WEEK_UI.getWeek().config);assert.equal(config.project,'interdisciplinary');assert.equal(config.mixProjects.length,2);checks.push('custom interdisciplinary random mentor');await ctx.close();}
 // Search, rank filters, pagination and manual application; random recommendation never bypasses confirmation.
 {const {ctx,p}=await context();await click(p,'[data-family="medicine"]');await click(p,'[data-medical-primary]');await click(p,'[data-medical-secondary]');await click(p,'#medical-to-mentor');await p.locator('#faculty-search').fill('没有这个名字xyz');await click(p,'#faculty-random');assert(await p.locator('#toast.visible').count());assert(!await p.locator('#open-daily-event').count());await p.locator('#faculty-search').fill('');await p.locator('#faculty-level').selectOption('senior');await click(p,'#faculty-random');assert(await p.locator('#faculty-confirm').count());assert(/教授|研究员/.test(await p.locator('.faculty-rank').innerText()));assert(await p.evaluate(()=>window.MEETING_MENTORS.profiles.filter(x=>x.level==='senior').some(x=>document.querySelector('.faculty-detail').textContent.includes(x.name))));await p.locator('#faculty-level').selectOption('all');if(!await p.locator('#faculty-next').isDisabled()){await click(p,'#faculty-next');await click(p,'#faculty-prev');}await click(p,'[data-faculty]');if(await p.locator('#faculty-confirm').isDisabled())await click(p,'[data-faculty-direction]:enabled');assert(!await p.locator('#faculty-confirm').isDisabled());await click(p,'#faculty-confirm');await closeDaily(p);await click(p,'#checkpoint-now');await click(p,'[data-timeline-action="1"]');await click(p,'#calendar');await closeDaily(p);await click(p,'#save-center');const downloadPromise=p.waitForEvent('download');await click(p,'#backup-export');const dl=await downloadPromise,savePath=path.join(out,'save-import.json');await dl.saveAs(savePath);await p.locator('#backup-file').setInputFiles(savePath);await p.getByRole('button',{name:'确认用这份存档恢复进度',exact:true}).click();clicks++;await p.waitForLoadState('load');await click(p,'#calendar');assert(await p.locator('#open-daily-event').count());checks.push('search, rank, pagination, manual direction, pause and JSON import');await ctx.close();}
 // Each enabled time-consuming entrance must display its own action or an explicit rejection.
 {const {ctx,p}=await context();await click(p,'[data-feature-set="full"]');await click(p,'[data-family="engineering"]');await click(p,'[data-primary]');await click(p,'[data-secondary]');await click(p,'#discipline-mentor');await click(p,'#faculty-random');await click(p,'#faculty-confirm');
  await closeDaily(p);await click(p,'[data-hub-entry="planning"]');assert(await p.locator('[data-preparation="literature"]').isDisabled(),'mandatory budget not overwritten');assert(await p.locator('#life-planning .action-availability').isVisible());await click(p,'#life-planning .action-availability button');await click(p,'[data-life]:enabled');await p.keyboard.press('Enter');assert(!await p.locator('#life-next:visible').count(),'Enter advances modal consequence');
  for(let n=0;n<30&&await p.evaluate(()=>!!window.MEETING_WEEK.actionReason(window.MEETING_WEEK_UI.getWeek()));n++)await lifeStep(p);await closeDaily(p);
  const snap=await p.evaluate(()=>({...localStorage}));const selectors=['[data-preparation="literature"]','[data-preparation="method"]','[data-preparation="record"]','[data-preparation="boundary"]','[data-preparation="rehearsal"]','[data-location="library"]','[data-location="lab"]','[data-location="cafe"]','[data-location="mentor"]','[data-location="home"]','[data-location="wander"]','#week-food','#world-project','#route-story-dispatch','[data-academic="resource"]','[data-academic="collab"]','[data-academic="stage-prep"]','#direction-pivot'];
  for(const selector of selectors){await p.evaluate(s=>{localStorage.clear();for(const[k,v]of Object.entries(s))localStorage.setItem(k,v);},snap);await p.reload();await click(p,'#calendar');await closeDaily(p);const t=p.locator(selector).first();if(!await t.count()){checks.push('not offered: '+selector);continue;}const hub=await t.evaluate(el=>el.closest('#life-planning')?'planning':el.closest('#life-research')?'research':'community');await click(p,'[data-hub-entry="'+hub+'"]');await t.evaluate(el=>{for(let n=el.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});if(await t.isDisabled()){assert(await t.getAttribute('title'),'disabled reason '+selector);checks.push('explicit prerequisite: '+selector);continue;}
   await click(p,selector);assert(await p.locator('#daily-event-dialog[open]').count()||await p.locator('#toast.visible').count(),'entrance feedback '+selector);await lifeStep(p);checks.push('action entrance: '+selector);
  }await ctx.close();}
 assert.deepEqual(errors,[],'no browser exceptions');const result={passed:true,browser:'Chromium'+(process.env.BROWSER_CHANNEL?' / '+process.env.BROWSER_CHANNEL:''),families:process.env.BROWSER_ACTIONS_ONLY?0:chosenFamilies.length,clicks,checks,errors,screenshots:fs.readdirSync(out).filter(f=>f.endsWith('.png'))};fs.writeFileSync(path.join(out,process.env.BROWSER_ACTIONS_ONLY?'actions-results.json':'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
