const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..'),box={window:{}};vm.createContext(box);
const modules=[...fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script src="([^?]+)\?/g)].map(m=>m[1]).slice(0, -1);for(const f of modules){if(f==='save-manager.js')break;vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),box,{filename:f});}
const {MEETING_CONTENT:C,MEETING_WEEK:W,MEETING_ENGINE:E,MEETING_ACADEMY:A,MEETING_WORLD:X,MEETING_PREPARATION:B,MEETING_DIRECTIONS:D,MEETING_PUBLICATION:P,MEETING_DIALOGUE:T,MEETING_PROFESSIONAL:F}=box.window,copy=x=>JSON.parse(JSON.stringify(x));
const base={project:'data',role:'newbie',difficulty:'normal',persona:'warm',campus:true,preparation:true,rulesVersion:'10',studyStage:'master',scenario:'regular'};
const isolated=(opts={})=>{const w=W.create({...base,...opts},9);w.group.news.handled=true;w.assignments.offers=[];w.surprise=null;w.world.plan=null;w.routeStories.plan=null;w.publication.plan=null;w.academy.plan=null;w.sideStories.plan=null;return w;};
const clear=w=>{w.pending=null;w.presentation=null;w.campus.plan=null;w.academy.plan=null;};
function drive(w,type,action,target=null){clear(w);assert(A.dispatch(w,type,target),type);const e=W.current(w),i=e.choices.findIndex(c=>c.academyAction===action);assert(i>=0);const saved=JSON.stringify(w);for(let n=0;n<4;n++)W.current(w);assert.equal(JSON.stringify(w),saved);const clone=copy(w),r=W.choose(w,i),r2=W.choose(clone,i);assert(r);assert.deepEqual(copy(r),copy(r2));assert.equal(JSON.stringify(w),JSON.stringify(clone));assert(W.isValid(w));return r;}
assert.equal(C.projects.length,90);assert.equal(D.all.length,936);assert.equal(C.endings.length,508);assert.equal(Object.keys(F.reviewed).length,90);for(const p of C.projects){assert(F.reviewed[p.id]);assert(C.events.some(e=>e.id==='reviewed-'+p.id));assert(D.all.filter(d=>d.route===p.id).length>=9);}
// Current-version resource evidence, actual delays, blocked alternatives and stale versions.
for(const route of ['classic','data','field','history','design','clinical','theory','economics','environment','mechanical','cardiology','radiology']){const w=isolated({project:route}),e=A.build(w,'resource');w.group.balance=90;let got=A.resolve(w,e,e.choices[0],{},()=>.01);assert(got.success);assert(!A.resourceReady(w));const j=w.academy.resource.active;w.day=3;w.slot=1;j.due=A.tick(w);j.obstacle=false;w.academy.lastTick=-1;A.prepare(w,()=>.99);assert.equal(j.status,'available');drive(w,'resource-work','resource-check');assert(A.resourceReady(w));assert.equal(w.world.artifact.checks.at(-1).direction,w.world.artifact.direction);const old=copy(w);w.world.artifact.version++;assert(!A.resourceReady(w));assert(A.resourceReady(old));}
{const w=isolated(),e=A.build(w,'resource');w.group.balance=0;assert(!A.resolve(w,e,e.choices[0],{},()=>.01).success);assert.equal(w.academy.resource.active,null);}
// A claimed shared contribution blocks publication until actual contribution and agreement.
{const w=isolated();drive(w,'collab','collab-external');const co=w.academy.collab.active;assert(!A.publicationAllowed(w));drive(w,'collab-work','collab-work');assert.equal(co.step,1);w.number++;drive(w,'collab-work','collab-work');assert.equal(co.step,2);drive(w,'collab-work','collab-claim');assert.equal(co.status,'disputed');assert(!A.publicationAllowed(w));drive(w,'collab-work','collab-work');assert.equal(co.status,'agreed');assert(A.publicationAllowed(w));const paper={};A.publicationSnapshot(w,paper);const before=JSON.stringify(paper);co.agreement.authors.push('later');assert.equal(JSON.stringify(paper),before);drive(w,'collab-work','collab-stop');assert.equal(w.academy.collab.active,null);}
// Borrowing changes a real relationship when overdue and can be returned.
{const w=isolated(),peer=w.group.members.find(m=>m.rank!=='mentor');assert(peer);A.addLoan(w,peer.id,'loan-test');const l=w.academy.loans[0],trust=peer.trust;w.number=4;w.academy.lastTick=-1;A.prepare(w,()=>.99);assert(peer.trust<trust);drive(w,'loan','loan-return',l.id);assert.equal(l.status,'returned');}
// A deadline failure is recoverable. Stage preparation and real current evidence are separate.
{const w=isolated(),m=A.milestone(w);w.number=m.due;drive(w,'stage-check','stage-submit');assert.equal(m.extension,1);assert(w.academy.recovery.active);drive(w,'stage-prep','stage-work');const p=w.world.artifact;p.checks=[{version:p.version,route:p.route,direction:p.direction,kind:'record',level:2}];w.number=m.due;drive(w,'stage-check','stage-submit');assert.equal(m.status,'passed');assert(w.academy.lastResults.some(r=>r.id==='stage-recovered'));}
// Alumni leave the actual group; juniors grow; new entrants are stable across a save reload.
{let w=isolated();for(let n=2;n<=25;n++)w=W.create(w.config,X.derive(9,n),w,n);assert(w.academy.yearbook.some(t=>t.type==='graduate'));assert(Object.values(w.academy.people).some(n=>n.status==='alumni'));assert(W.isValid(w));assert(w.group.members.every(m=>!w.academy.people[m.id]||w.academy.people[m.id].status==='active'));}
// All four leisure goals cross real weeks, retain their ending and yearbook.
for(const d of box.window.MEETING_ACADEMIC_CONTENT.campus){const w=isolated();w.day=5;for(let n=0;n<d.steps;n++){drive(w,'campus','campus-do',d.id);clear(w);assert(!A.dispatch(w,'campus',d.id));w.number++;}assert(w.academy.campus[d.id].finished);assert(w.academy.lastResults.some(r=>r.id==='campus-'+d.id));assert(w.academy.yearbook.some(r=>r.type==='campus'));}
// Foreshadows retain originating choice; recovery is a later-week action.
{const w=isolated();A.addShadow(w,'email','源自已完成的交接');w.number+=2;w.academy.lastTick=-1;A.prepare(w,()=>.99);const f=w.academy.foreshadows[0];drive(w,'foreshadow','foreshadow-do',f.id);assert.equal(f.status,'resolved');assert.equal(f.origin,'源自已完成的交接');A.startRecovery(w,'failure','失败','缺口');drive(w,'recovery','recover-teach');clear(w);assert.equal(B.lifePreview(w,A.build(w,'recovery'),0).available,false);w.number++;drive(w,'recovery','recover-finish');assert(w.academy.lastResults.some(r=>r.id==='recovery-teaching'));}
// Continuous answers cite prior turns, require current records, and expose contradictions.
{const w=isolated(),s=E.create({...base,weekContext:W.meetingContext(w),seed:3});s.eventId='academic-talk-format';s.phase=6;box.window.MEETING_UNCERTAINTY.prepareRound(s,()=>.1);let e=E.current(s);assert.equal(e.choices.find(c=>c.semantic==='checked')?.prepared.available,false);const c=e.choices.find(c=>c.semantic==='bounded'||c.semantic==='promise');T.after(s,e,c,{flavor:''});s.choicesMade=5;s.eventId='academic-talk-followup';e=T.question(s);assert(e.scene.includes(c.text));const claim=e.choices.find(c=>c.semantic==='complete'),effects={};T.before(s,e,claim,effects);assert.equal(s.academicDialogue.contradictions,1);assert(effects.evidence<0);}
for(const scenario of A.scenarios){const w=isolated({scenario:scenario.id}),code=X.code(w),parsed=X.parse(code);assert(parsed);assert.equal(parsed.scenario,scenario.id);assert.equal(X.code(W.create(parsed,parsed.challengeSeed)),code);if(scenario.id==='tiny-lab')assert.equal(w.group.members.length,1);if(scenario.id==='dual')assert.equal(w.group.members.filter(m=>m.rank==='mentor').length,2);}
assert(X.parse('LM08:42:normal:data:-:newbie:normal:random:data-1'));assert(X.parse('LM09:42:normal:data:-:newbie:normal:random:data-1:-'));assert.equal(X.parse('LM10:42:normal:data:-:newbie:normal:random:data-1:-:garbage:regular'),null);
let weeks=0,actions=0,dialogues=0;for(const route of C.projects){let old=null;for(let number=1;number<=3;number++){let w=W.create({...base,project:route.id,...(route.id==='interdisciplinary'?{mixProjects:['radiology','data']}:{}),scenario:number===1?'regular':old.config.scenario},X.derive(24,number),old,number);for(let n=0;w.status!=='report'&&n<260;n++){assert(W.isValid(w),route.id+' week '+number+' '+W.current(w)?.id);if(w.pending){W.advance(w);continue;}if(w.status==='meeting'){const s=E.create({...w.config,weekContext:W.meetingContext(w),seed:X.derive(24,number,1)});for(let k=0;!s.ended&&k<150;k++){assert(E.isValid(s),route.id+' '+s.eventId);if(s.pending){E.advance(s);continue;}const e=E.current(s);if(e.academicTalk)dialogues++;const options=e.choices.map((c,i)=>({c,i})).filter(x=>x.c.prepared?.available!==false&&!x.c.hardStop);assert(E.choose(s,options[k%options.length].i));}assert(s.ended);assert(W.completeMeeting(w,s));continue;}const e=W.current(w),opts=e.choices.map((c,i)=>({c,i})).filter(x=>B.lifePreview(w,e,x.i).available);assert(W.choose(w,opts[n%opts.length].i));actions++;}assert.equal(w.status,'report');assert.equal(w.log.length,13);old=w;weeks++;}}
const result={passed:true,routes:C.projects.length,medicalRoutes:box.window.MEETING_MEDICAL.routes.length,reviewedRoutes:Object.keys(F.reviewed).length,directions:D.all.length,endings:C.endings.length,weeks,actions,dialogues,resourceGate:true,authorshipGate:true,crossWeekCampus:true,realAlumni:true,legacyCodes:true};fs.mkdirSync(path.join(root,'.qa'),{recursive:true});fs.writeFileSync(path.join(root,'.qa/academy-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));

