const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..'),box={window:{}};vm.createContext(box);
for(const f of ['content.js','content-expand.js','content-disciplines.js','content-v03.js','content-cast-v08.js','content-week.js','campus-content.js','campus-engine.js','preparation.js','uncertainty.js','life-surprise-content.js','cast-surprises-v08.js','life-surprises.js','content-expansion-v06.js','cross-discipline.js','group-dynamics.js','assignments.js','side-stories.js','living-world.js','research-directions.js', 'research-directions-extra.js','engine.js','week-engine.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),box);
const {MEETING_CONTENT:C,MEETING_CAST:K,MEETING_ENGINE:E,MEETING_WEEK:W,MEETING_MIX:M,MEETING_WORLD:X,MEETING_LIFE_SURPRISES:L}=box.window;let pairs=0,skills=0;
assert.equal(C.projects.length,48);assert.equal(C.roles.length,12);assert.equal(C.personas.length,12);for(const collection of [C.projects,C.roles,C.personas,C.events,C.lifeEvents,C.endings,L.incidents])assert.equal(new Set(collection.map(x=>x.id)).size,collection.length,'unique ids');
for(const d of K.routes){assert.equal(C.events.filter(e=>e.project===d.id).length,7);assert.equal(C.lifeEvents.filter(e=>e.project===d.id).length,4);assert.equal(C.preparationEvents.filter(e=>e.project===d.id).length,5);assert.equal(C.preparationQuestions.filter(e=>e.project===d.id).length,4);assert.equal(L.incidents.filter(e=>e.project===d.id).length,3);assert(C.endings.find(e=>e.id==='failure-'+d.id));for(let seed=1;seed<=6;seed++){const w=W.create({project:d.id,role:'newbie',campus:true,preparation:true},seed);assert(W.isValid(w));const s=E.create({project:d.id,seed,weekContext:W.meetingContext(w)});assert(E.isValid(s));}}
for(const role of C.roles){const s=E.create({role:role.id,project:'data',seed:2,persona:'warm'});const r=E.useItem(s,'skill');assert(r);assert.equal(E.useItem(s,'skill'),null);assert.equal(s.preparation,undefined);skills++;}
const profiles=new Set();for(const persona of K.mentors){const s=E.create({project:'data',persona:persona.id,seed:3});assert.equal(s.live.profiles.boss.preference,persona.focus);assert(E.isValid(s));profiles.add(JSON.stringify(s.live.profiles.boss));}
assert(profiles.size>=5);const ids=C.projects.filter(p=>p.id!=='interdisciplinary').map(p=>p.id);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const cfg={project:'interdisciplinary',mixProjects:[ids[i],ids[j]],role:'newbie',campus:true,preparation:true},w=W.create(cfg,i*100+j);assert(W.isValid(w));assert(M.bridge(w).title);assert(X.parse(X.code(w)));pairs++;}
assert.equal(pairs,1081);const result={passed:true,routes:48,newRoutes:12,roles:12,newRoles:8,mentorStyles:12,newMentorStyles:8,validPairs:pairs,oneUseSkills:skills,uniqueContentIds:true,allNewRoutesHavePreparationLifeIncidentsFailures:true};fs.writeFileSync(path.join(root,'.qa/cast-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
