const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..'),box={window:{}};vm.createContext(box);
const files=['content.js','content-expand.js','content-disciplines.js','content-v03.js','content-cast-v08.js','content-week.js','campus-content.js','campus-engine.js','preparation.js','uncertainty.js','life-surprise-content.js','cast-surprises-v08.js','life-surprises.js','content-expansion-v06.js','cross-discipline.js','group-dynamics.js','assignments.js','side-stories.js','living-world.js','research-directions.js','research-directions-extra.js','mentor-profiles.js','route-stories.js','publication.js','engine.js','week-engine.js'];for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),box,{filename:f});
const {MEETING_CONTENT:C,MEETING_WEEK:W,MEETING_ENGINE:E,MEETING_WORLD:X,MEETING_ROUTE_STORIES:R,MEETING_PUBLICATION:P,MEETING_MENTORS:M,MEETING_DIRECTIONS:D,MEETING_PREPARATION:B}=box.window,copy=x=>JSON.parse(JSON.stringify(x)),base={project:'data',role:'newbie',persona:'random',difficulty:'normal',preparation:true,campus:true,playMode:'normal',rulesVersion:'09'};
let weeks=0,actions=0,routeQuestions=0,paperQuestions=0;const stages=new Set(),ends=new Set(),promotion=new Set();
assert.equal(C.endings.length,400);assert.equal(M.profiles.filter(m=>!m.id.startsWith('faculty-')).length,16);assert.equal(M.profiles.length,16+C.projects.filter(p=>p.id!=='interdisciplinary').reduce((n,p)=>n+Math.ceil(D.all.filter(d=>d.route===p.id).length/3),0));assert.equal(R.stories.length,10);for(const route of C.projects.filter(p=>p.id!=='interdisciplinary'))assert(R.forRoute(route.id),route.id);for(const m of M.profiles){assert(m.directionIds.length>=1&&m.directionIds.length<=3);m.directionIds.forEach(id=>assert(D.find(id),id));const w=W.create({...base,mentorId:m.id},3);assert.equal(w.config.persona,m.style);assert.equal(w.group.members[0].name,m.name+'老师');assert.equal(w.group.members[0].level,m.level);assert(W.isValid(w));const code=X.code(w),parsed=X.parse(code);assert.equal(parsed.mentorId,m.id);assert.equal(X.code(W.create(parsed,parsed.challengeSeed)),code);}
function isolated(route='data',seed=3){const w=W.create({...base,project:route},seed);w.group.news.handled=true;w.assignments.offers=[];w.surprise=null;w.sideStories.plan=null;w.sideStories.active=null;w.world.plan=null;w.routeStories.plan=null;return w;}
function drive(w,e,action,key='routeAction',draw=.01){w.campus.plan=null;w.routeStories.plan=null;w.publication.plan=null;if(e.routeStory){w.routeStories.plan=e;w.campus.plan={day:w.day,slot:w.slot,location:'route-story',original:w.eventId};}else{w.publication.plan=e;w.campus.plan={day:w.day,slot:w.slot,location:'publication',original:w.eventId};}const index=e.choices.findIndex(c=>c[key]===action);assert(index>=0,action);const clone=copy(w),r=W.choose(w,index),r2=W.choose(clone,index);assert(r);assert.deepEqual(copy(r),copy(r2));assert.equal(JSON.stringify(w),JSON.stringify(clone));assert.equal(W.choose(w,index),null);assert.deepEqual(copy(W.current(w)),copy(e));return r;}
// Each discipline chain has three real choices, final work crosses into a later week.
for(const d of R.stories)for(const branch of ['resource','peer','mentor']){const w=isolated(d.routes[0]);const t=R.start(w,()=>.01);assert.equal(t.id,d.id);assert(R.valid(w));const e=R.build(w,t,()=>.01);const snapshot=JSON.stringify(w);for(let i=0;i<4;i++)R.build(w,t,()=>.01);assert.equal(JSON.stringify(w),snapshot);drive(w,e,branch);assert.equal(w.log.length,1);assert.equal(t.step,1);W.advance(w);w.day=2;w.slot=0;w.assignments.offers=[];drive(w,R.build(w,t,()=>.01),'rebuild');assert.equal(t.step,2);assert(t.next>=14);assert.equal(R.canDispatch(w),false);const old=copy(w),next=W.create(w.config,8,old,2);next.group.news.handled=true;next.assignments.offers=[];next.sideStories.plan=null;next.world.plan=null;next.surprise=null;assert.equal(next.routeStories.active.branch,branch);assert.equal(next.routeStories.active.projectVersion,t.projectVersion);next.routeStories.active.checked=true;next.routeStories.active.scope='small';const e2=R.build(next,next.routeStories.active,()=>.01);drive(next,e2,'verify');const done=next.routeStories.history.at(-1);assert(['verified','withdrawn'].includes(done.status));assert.equal(done.log.length,3);assert.equal(done.loan,false);const s=E.create({...base,project:d.routes[0],seed:3,weekContext:W.meetingContext(next)});s.eventId='route-story-question';s.phase=6;const q=E.current(s),full=q.choices.find(c=>c.routeAnswer==='receipt');assert.equal(full.prepared.available,done.status==='verified');assert.equal(full.prepared.source?.instance||null,done.source?.instance||null);s.weekContext.world.artifact.version++;assert.equal(E.current(s).choices.find(c=>c.routeAnswer==='receipt').prepared.available,false);}
// Resources, absent peers and mentor timing are distinct routes with fixed hidden outcomes.
for(const budget of [0,90]){const w=isolated(),t=R.start(w,()=>.2);w.group.balance=budget;const e=R.build(w,t,()=>.2),c=e.choices.find(c=>c.routeAction==='resource'),effects={};const result=R.resolve(w,e,c,effects,()=>.5);assert.equal(result.success,budget===90);assert.equal(result.spend,budget===0?0:10);}
{const w=isolated();w.group.members=w.group.members.filter(m=>m.rank==='mentor');const t=R.start(w,()=>.01),e=R.build(w,t,()=>.01),c=e.choices.find(c=>c.routeAction==='peer');assert.equal(R.resolve(w,e,c,{},()=>.01).success,false);}
{const w=isolated(),t=R.start(w,()=>.01);t.deadline=-1;R.expire(w);assert.equal(w.routeStories.active,null);assert.equal(w.routeStories.history.at(-1).status,'expired');}
// Generic reading cannot manufacture a chain or manuscript receipt.
{const w=isolated(),t=R.start(w,()=>.01);w.preparation.sources.push({kind:'record',route:'data',week:1,day:0,eventId:'other',action:'other',level:2});const s=E.create({...base,weekContext:W.meetingContext(w)});s.eventId='route-story-question';s.phase=6;assert.equal(E.current(s).choices.find(c=>c.routeAnswer==='receipt').prepared.available,false);assert.equal(P.eligible(w),false);}
function ready(w){const p=w.world.artifact;p.status='ready';p.checks=[0,1,2].map(i=>({version:p.version,route:p.route,kind:'record',week:w.number,day:w.day,eventId:'checked-'+i,action:'real-'+i,level:2}));}
// Submission snapshots are immutable when a fresh project starts. Revision claims cannot replace actual work.
{const w=isolated();ready(w);drive(w,P.build(w,'submit'),'submit-brief','publicationAction');const paper=copy(w.publication.active);assert.equal(paper.source.length,3);W.advance(w);w.assignments.offers=[];w.sideStories.plan=null;w.world.plan=null;w.surprise=null;drive(w,P.build(w,'new'),'new','publicationAction');assert.equal(w.world.artifact.version,2);assert.equal(w.world.artifact.checks.length,0);assert.deepEqual(copy(w.publication.active.source),paper.source);assert.equal(P.eligible(w),false);const t=w.publication.active;t.status='mail';t.decision='major';w.pending=null;w.presentation=null;w.campus.plan=null;drive(w,P.build(w,'mail'),'read','publicationAction');assert.equal(t.status,'revising');assert.equal(t.required,2);w.pending=null;w.presentation=null;w.campus.plan=null;const e=P.build(w,'revision');assert.equal(B.lifePreview(w,e,e.choices.findIndex(c=>c.publicationAction==='resubmit')).available,false);assert.equal(P.resolve(w,e,e.choices.find(c=>c.publicationAction==='resubmit'),{},()=>.01),null);for(let i=0;i<2;i++){const e=P.build(w,'revision');P.resolve(w,e,e.choices.find(c=>c.publicationAction==='revise'),{},()=>.01);}assert.equal(t.revisions.length,2);assert(t.revisions.every(r=>r.paperId===t.id));P.resolve(w,e,e.choices.find(c=>c.publicationAction==='resubmit'),{},()=>.01);assert.equal(t.status,'resubmitted');assert.equal(t.round,1);assert(t.due> X.tick(w));assert(P.valid(w));}
// Editor decisions include desk rejection, external rejection, both revisions and acceptance.
for(const [draw,expected] of [[.01,'desk'],[.13,'rejected'],[.3,'major'],[.8,'minor'],[.98,'accepted']]){const w=isolated();ready(w);const e=P.build(w,'submit');P.resolve(w,e,e.choices[0],{},()=>.01);w.publication.active.due=0;P.prepare(w,()=>draw);assert.equal(w.publication.active.decision,expected);w.group.members[0].trust=70;const mail=P.build(w,'mail');P.resolve(w,mail,mail.choices[0],{},()=>.01);if(expected==='accepted'){assert.equal(w.publication.history.at(-1).status,'accepted');assert.equal(w.publication.doctorate.status,'offered');for(const action of ['phd-yes','phd-later','phd-no']){const clone=copy(w),offer=P.build(clone,'doctorate');P.resolve(clone,offer,offer.choices.find(c=>c.publicationAction===action),{},()=>.01);const s=E.create({...base,weekContext:W.meetingContext(clone)});s.wrapUp=2;assert(P.ending(s));ends.add(P.ending(s));}}if(['desk','rejected'].includes(expected)){w.campus.plan=null;w.pending=null;assert(P.retarget(w,'methods'));const event=W.current(w);assert.equal(event.publicationType,'retarget');const result=W.choose(w,0);assert(result);assert.equal(w.publication.active.journal,'methods');assert.equal(w.publication.history.at(-1).status,expected);}}
// Promotions may pass or defer, keep the same teacher, and persist rather than resetting next week.
for(const draw of [.01,.99]){const w=isolated();const m=w.group.members[0];m.level='young';m.promotion={points:10,since:1,stage:'review',reviewAt:2,history:[]};w.number=2;const before=m.name;M.advance(w,{meeting:{score:70}},()=>draw);assert.equal(m.name,before);assert.equal(m.promotion.stage,draw===.01?'promoted':'deferred');promotion.add(m.promotion.stage);if(draw===.01){assert.equal(m.level,'associate');const next=W.create(w.config,4,w,3);assert.equal(next.group.members[0].level,'associate');}}
// Imported LM08 challenges keep the old systems, new codes bind an exact mentor profile.
{const cfg=X.parse('LM08:42:normal:data:-:newbie:normal:random:data-1');assert(cfg);const w=W.create(cfg,42);assert.equal(w.routeStories,undefined);assert.equal(w.publication,undefined);assert.equal(w.group.members[0].promotion,undefined);assert.equal(X.code(w),'LM08:42:normal:data:-:newbie:normal:random:data-1');}
// Full actual weeks with all hooks enabled, not isolated hand-crafted states.
for(const route of C.projects.filter(p=>p.id!=='interdisciplinary')){let prev=null;for(let number=1;number<=4;number++){const w=W.create({...base,project:route.id,mentorId:M.profiles[(weeks+number)%M.profiles.length].id},X.derive(19,number),prev,number);for(let safety=0;w.status!=='report'&&safety<280;safety++){assert(W.isValid(w),route.id+' '+number+' '+w.status+' '+W.current(w)?.id);if(w.pending){W.advance(w);continue;}if(w.status==='meeting'){const s=E.create({...w.config,seed:X.derive(19,number,1),weekContext:W.meetingContext(w),career:w.world.runCareer});for(let k=0;!s.ended&&k<180;k++){assert(E.isValid(s));if(s.pending){E.advance(s);continue;}const e=E.current(s);if(e.id==='route-story-question')routeQuestions++;if(e.id==='publication-question')paperQuestions++;const opts=e.choices.map((c,i)=>({c,i})).filter(x=>x.c.prepared?.available!==false&&!x.c.hardStop);E.choose(s,opts[(k+number)%opts.length].i);}assert(s.ended);assert(W.completeMeeting(w,s));continue;}const e=W.current(w);if(e.routeStory)stages.add(e.choices[0].routeStep);const options=e.choices.map((c,i)=>({c,i})).filter(x=>B.lifePreview(w,e,x.i).available),chosen=options[(number+safety)%options.length].i,clone=copy(w),r=W.choose(w,chosen),r2=W.choose(clone,chosen);assert(r);assert.deepEqual(copy(r),copy(r2));assert.equal(JSON.stringify(w),JSON.stringify(clone));actions++;}assert.equal(w.status,'report');assert.equal(w.log.length,13);prev=w;weeks++;}}
assert(routeQuestions>0);assert.equal(stages.size,3);const result={passed:true,mentors:M.profiles.length,authoredMentors:16,levels:3,mentorDirectionCounts:[1,2,3],routeFamilies:10,coveredRoutes:47,lifeWeeks:weeks,lifeActions:actions,routeMeetingQuestions:routeQuestions,promotionResults:[...promotion],doctorateEndings:[...ends],snapshotIsolation:true,realRevisionGate:true,legacyChallengeCompatible:true,endings:C.endings.length};fs.writeFileSync(path.join(root,'.qa/routes-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
